### ISSUE TITLE
[Request] Autocomplete and Chips Input

### ISSUE THREAD

**Issue by MoacirSchmidt** [quasarframework/quasar#1432] opened 2018-01-16 12:30 UTC
I would like to have autocomplete to work with the chips input.

**Comment by realcarbonneau** [comment] 2018-01-21 22:42
It's a good idea, I have been thinking of combining chips and search/autocomplete also.  This is quite common.

**Comment by rstoenescu** [comment] 2018-01-23 10:03
Duplicate of https://github.com/quasarframework/quasar/issues/400 so closing.

**Closed by rstoenescu** 2018-01-23 10:03 UTC
