### ISSUE TITLE
[Request] Make double-click on dates in QDatetime picker trigger `set()`

### ISSUE THREAD

**Issue by dsl101** [quasarframework/quasar#798] opened 2017-08-11 17:06 UTC
Pretty much that is all :).

**Comment by NothingWeAre** [comment] 2017-09-05 18:35
Or maybe option to accept click on bottom level as `set()`. Some users are lazy, and complaining about having to press another button (

**Comment by rstoenescu** [comment] 2017-11-03 17:45
Closing as duplicate of https://github.com/quasarframework/quasar/issues/798

**Closed by rstoenescu** 2017-11-03 17:45 UTC

**Comment by dsl101** [comment] 2017-11-03 18:12
Duplicate of itself?

**Comment by rstoenescu** [comment] 2017-11-03 18:36
Damn. Duplicate of this: https://github.com/quasarframework/quasar/issues/718
