### ISSUE TITLE
Typescript Errors are not printed during dev or build when using Vite + Typescript 

### ISSUE THREAD

**Issue by boid-com** [quasarframework/quasar#15679] opened 2023-04-05 06:53 UTC
### What happened?

From a fresh quasar project using Vite and Typescript make a change which would cause a typescript build error. Run `quasar dev` or `quasar build` and no error is presented, the build will succeed.

### What did you expect to happen?

Any typescript error which would normally cause the typescript compiler to throw an error and refuse to compile should also be caught and handled during dev and build stage of quasar.

### Reproduction URL

https://github.com/jdheeter/quasar-ts-vite-no-errors

### How to reproduce?

1. Easiest repro is just use `yarn create quasar` and choose Typescript and Vite during project creation
2. create a type error, like in IndexPage.vue, you can see my repo link for example. vscode will report an error, normally typescript would refuse to compile in this case.
3. run `yarn dev` or `yarn build` and you will see no errors are reported.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite), TypeScript Support

### Quasar info output

```Shell
Operating System - Darwin(22.3.0) - darwin/arm64
NodeJs - 18.12.1

Global packages
  NPM - 8.19.2
  yarn - 1.22.19
  @quasar/cli - undefined
  @quasar/icongenie - 2.5.4
  cordova - Not installed

Important local packages
  quasar - 2.11.10 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.2.1 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.16.2 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.47 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.1.6
  pinia - 2.0.33 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 2.9.15 -- Native-ESM powered web dev build tool
  eslint - 8.37.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*
```

**Comment by pdanpdan** [comment] 2023-04-05 07:04
duplicate of #15448

**Closed as completed by pdanpdan** 2023-04-05 07:04 UTC
Labels: kind/bug 🐞, area/typescript, Qv2 🔝, bug/1-hard-to-reproduce, bug/1-repro-available, area/cli, flavour/quasar-cli-vite

**Comment by boid-com** [comment] 2023-04-05 07:40
For anyone still confused, you need another dependency to handle typechecking.
`vue-tsc --no-emit`
https://github.com/vuejs/language-tools/tree/master/packages/vue-tsc
