### ISSUE TITLE
QEditor buttons affect wrong text on ios

### ISSUE THREAD

**Issue by dsl101** [quasarframework/quasar#5388] opened 2019-10-24 09:45 UTC
**Describe the bug**
When using QEditor toolbar buttons (e.g. to create bullet lists), the wrong text is targeted.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/dsl101/pen/vYYmLvr

**To Reproduce**
1. Open the codepen on ios safari.
2. Click on the second line in the editor
3. Click the toolbar bullet icon
4. The _first_ line is turned into a bullet point, not the second line

**Expected behavior**
One desktop browsers, the second line is correctly turned into a bullet list.

**Platform (please complete the following information):**
Browsers: Mobile Safari
iOS: 13.1.3

**Additional context**
It seems none of the toolbar buttons work as expected—try selecting a word and then using the 'bold' button. The caret is immediately placed at the start of the editable region, and it looks like that's happening before the toolbar button action takes place.

**Comment by rstoenescu** [comment] 2019-10-25 18:46
Duplicate of #5277

**Closed by rstoenescu** 2019-10-25 18:46 UTC
Labels: bug
