### ISSUE TITLE
[Request] Material Design Icons

### ISSUE THREAD

**Issue by dexif** [quasarframework/quasar#1073] opened 2017-10-30 21:00 UTC
It would be nice if you add support https://materialdesignicons.com
npm: https://www.npmjs.com/package/mdi

**Comment by rstoenescu** [comment] 2017-10-30 21:20
Closing as it's duplicate of https://github.com/quasarframework/quasar/issues/980
Also, there's a PR waiting for me to merge it just for this.

**Closed by rstoenescu** 2017-10-30 21:20 UTC
