### ISSUE TITLE
Q-tooltip inside Q-Icon does not appear if custom icon is used.

### ISSUE THREAD

**Issue by DelaneDiamon** [quasarframework/quasar#7289] opened 2020-06-24 01:01 UTC
**Describe the bug**
Using custom q-icon (name="img:...") with inner q-tooltip disables q-tooltip. 
Using q-icon with name from icon library and inner tooltip works fine

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/Diamon33/xg841e0L/50/

**To Reproduce**
See Fiddle

**Expected behavior**
q-tooltip inside q-icon expected to work with custom icons

**Comment by pdanpdan** [comment] 2020-06-24 04:21
Duplicate of https://github.com/quasarframework/quasar/issues/6618

**Closed by pdanpdan** 2020-06-24 04:21 UTC
Labels: bug
