### ISSUE TITLE
[v1] QSelect not selectable on QDialog

### ISSUE THREAD

**Issue by carlesar** [quasarframework/quasar#3835] opened 2019-04-09 11:30 UTC
### Software version

Quasar: 1.0.0-beta.15
@quasar/app (v1+ only): 1.0.0-beta.15
OS: Debian 4.9.144-3 x86_64 GNU/Linux
Node: 9.11.2
NPM: 5.6.0
Browsers: Chrome and Firefox

### Codepen
https://codepen.io/anon/pen/QPdbez

### What were you expecting?
I was expecting that the user could select an option from the select object. But select options are "not" available, just a few of them are visible, the other items of the list are hiden.

Should QDialog(.q-dialog__inner > div) not have overflow:auto?

Thanks in advance!

**Comment by rstoenescu** [comment] 2019-04-09 11:50
Duplicate of https://github.com/quasarframework/quasar/issues/3242

Will get fixed in beta.16.

**Closed by rstoenescu** 2019-04-09 11:50 UTC
