### ISSUE TITLE
Please allow dynamic styles/classes for q-table

### ISSUE THREAD

**Issue by Daemach** [quasarframework/quasar#9251] opened 2021-05-12 14:11 UTC
I would like for the `styles`/`classes` properties in the column definition to work the same as `format`, rather than having to add a template cell style.  It would be more readable, maintainable and elegant.

```
        {
          name: "bSuccess",
          required: true,
          label: "Success",
          align: "left",
          field: "bSuccess",
          format: (val, row) => (val) ? "True" : "False",
          classes: (val, row) => (val) ? "text-positive" : "text-negative",
          sortable: true,
        },
        {
          name: "bTraded",
          required: true,
          label: "Already Traded",
          align: "left",
          field: "bTraded",
          classes: (val, row) => (val) ? "text-strike" : "",
          sortable: true,
        },
```

**Comment by Daemach** [comment] 2021-05-12 14:13
It would also be great if this could be rolled back to v1...

**Comment by rstoenescu** [comment] 2021-05-15 16:29
The following format will be available in 2.0.0-beta.17:
`style: row => ...`
`classes: row => ...`

For perf reasons, "val" will not be supplied.

PS: trying to port this over to v1 as well (and will post here when done), but closing ticket for now.

**Closed by rstoenescu** 2021-05-15 16:29 UTC
Labels: feature request

**Comment by rstoenescu** [comment] 2021-05-15 16:51
So updated availability: Quasar 2.0.0-beta.17 & v1.15.15

**Comment by Daemach** [comment] 2021-05-15 21:30
Thank you!

**Comment by Daemach** [comment] 2021-05-20 15:33
Please forgive the dumb question, but which of the quasar packages does
this fall into?  I would guess @quasar/extras but it appears I'm way
behind.  Below are the results of running "yarn upgrade" - not sure I'm
doing it right as js development is relatively new for me.

├─ @***@***.***
├─ @***@***.***
├─ @***@***.***
├─ @***@***.***

**Comment by stlsmiths** [comment] 2021-05-20 18:42
Unless I am doing this wrong - I noticed that the column `headerClasses` property seems to be overridden by the `align` property.  This seems to be how it worked in QTable v1.x also.

If I set a column.headerClass it seems to be appended to prior classes inherited from the column.align setting.

Is this the intended behavior ?

[https://codepen.io/stlsmiths/pen/KKWammV](https://codepen.io/stlsmiths/pen/KKWammV)

In the above codepen I try to set the TH alignment to "center" while the data TD alignment should be "text-right", we often use this functionality.

Any thoughts ?   Open a new ticket ?

**Comment by rstoenescu** [comment] 2021-05-21 10:31
@stlsmiths This is because the "align" prop already adds a text aligning CSS class. A better way would be to use the "align" prop for the header and then "classes" for body td align. Example:

```js
{
    name: 'name',
    required: true,
    label: 'Dessert (100g serving)',
    align: 'center', // <<<<<<<<<<
    classes: 'text-right', // <<<<<<<<<<
    field: row => row.name,
    format: val => `${val}`,
    sortable: true
  }
```

**Comment by rstoenescu** [comment] 2021-05-21 10:35
@Daemach Already pointed it out. It's the "quasar" package (UI) -- v1.15.15 or v2.0.0-beta.17. On a Quasar CLI project you can use "quasar upgrade --install" (which upgrades all Quasar related packages, but does not touches the non-Quasar ones). Alternatively, simply use the yarn/npm commands to upgrade to the newer packages -- mastering this is essential for modern webdev.

**Comment by Daemach** [comment] 2021-05-21 12:03
Yes, sorry - not sure why the yarn output ended up with *** in my previous post.  I was asking which of the packages (UI, extras, app etc.) had the new code.

**Comment by rstoenescu** [comment] 2021-05-21 12:44
@Daemach For completeness:
* "quasar" -> the UI package
* "@quasar/app" -> the Quasar App CLI
* "@quasar/extras" -> helper package; contains icon libs, fonts etc

This change is a UI change affecting QTable, so "quasar" is the package.

**Comment by stlsmiths** [comment] 2021-05-21 12:45
Thanks for the clarification Razvan.  It just doesn't seem super intuitive to me as a user of many other grid packages.  Not sure if a doc change on [Defining the columns](https://next.quasar.dev/vue-components/table#defining-the-columns) might help to clarify this.

As a note - on my [codepen](https://codepen.io/stlsmiths/pen/KKWammV) I changed it to remove the `align` property and (let it use defaults), in that case it STILL overrides the alignment defined in `headerClasses: text-left`, for example.    

IMHO the `align` logic might be a little over-agressive but I don't have the chops to recommend code changes.

**Comment by rstoenescu** [comment] 2021-05-21 12:49
@stlsmiths Like I mentioned above, all you need is:

```
align: 'center', // <<<<<<<<<<
classes: 'text-right', // <<<<<<<<<<
```

Notice that I've removed "headerClasses". It might seem counterintuitive, but it allowed us not to make breaking changes.

**Comment by stlsmiths** [comment] 2021-05-21 13:14
Thanks @rstoenescu ... here's to "not make breaking changes" !

I am really loving Quasar and the great components !
