### ISSUE TITLE
QDate new selection mode

### ISSUE THREAD

**Issue by apavelm** [quasarframework/quasar#4304] opened 2019-06-04 21:34 UTC
It would be very nice if you'll add the possibility to select a whole week by clicking a date in the week.
And optionally, select date range/multiple dates, like "v-calendar" does.

Thanks

**Comment by hawkeye64** [comment] 2019-06-04 21:37
You may be interested in this: https://quasarframework.github.io/app-extension-qscroller/demo

**Comment by rstoenescu** [comment] 2019-06-04 21:48
Duplicate of https://github.com/quasarframework/quasar/issues/640

**Closed by rstoenescu** 2019-06-04 21:48 UTC

**Comment by apavelm** [comment] 2019-06-04 21:59
@hawkeye64 Thank you, but it is not exactly what I suggested (UX is poor: functional but not convenient to use). Please have a look: https://github.com/nathanreyes/v-calendar#date-picker

@rstoenescu Ranges and multiple date selection modes are not mentioned in the issue you've referred.

P.S. Whole week selection by making one click would be really very nice.

Thank you for a great job, guys!

**Comment by pdanpdan** [comment] 2019-09-09 09:07
Please follow up in unified #5052
