### ISSUE TITLE
v-ripple throw error after upgrade quasar

### ISSUE THREAD

**Issue by goforu** [quasarframework/quasar#13213] opened 2022-04-19 02:55 UTC
### What happened?

v-ripple throw unhandled error as follow after upgrade Quasar:
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/5236864/163910754-0c52f27f-e4c0-4518-8a45-2622e026798d.png">

### What did you expect to happen?

no error

### Reproduction URL

[Reproduction URL](https://codesandbox.io/s/nifty-northcutt-352vkf?file=/src/pages/Index.vue)

### How to reproduce?

upgrade quasar 
 quasar: 2.2.2 → 2.6.6
 @quasar/app: 3.1.8 → 3.3.3

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Directives (quasar)

### Platforms/Browsers

Chrome

### Quasar info output

```Shell
Operating System - Darwin(21.4.0) - darwin/x64
NodeJs - 16.6.1

Global packages
  NPM - 7.20.3
  yarn - 1.22.11
  @quasar/cli - 1.0.5
  @quasar/icongenie - 2.4.0
  cordova - Not installed

Important local packages
  quasar - 2.6.6 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 3.3.3 -- Quasar Framework local CLI
  @quasar/extras - 1.13.5 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - 1.1.0 -- Official ESLint plugin for Quasar
  vue - 3.2.33 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.0.14
  vuex - 4.0.2 -- state management for Vue.js
  electron - 16.2.1 -- Build cross platform desktop apps with JavaScript, HTML, and CSS
  electron-packager - 15.4.0 -- Customize and package your Electron app with OS-specific bundles (.app, .exe, etc.) via JS or CLI
  electron-builder - 23.0.2 -- A complete solution to package and build a ready for distribution Electron app for MacOS, Windows and Linux with “auto update” support out of the box
  @babel/core - 7.17.8 -- Babel compiler core.
  webpack - 5.71.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 4.7.4 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 6.5.2 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  typescript - 4.5.5 -- TypeScript is a language for application scale JavaScript development
  @capacitor/core - 3.4.3 -- Capacitor: Cross-platform apps with JavaScript and the web
  @capacitor/cli - Not installed
  @capacitor/android - 3.4.3 -- Capacitor: Cross-platform apps with JavaScript and the web
  @capacitor/ios - 3.4.3 -- Capacitor: Cross-platform apps with JavaScript and the web

Quasar App Extensions
  @quasar/quasar-app-extension-testing - 1.0.5 -- A Quasar App Extension for managing Test Harnesses
  @quasar/quasar-app-extension-testing-e2e-cypress - 1.0.0-beta.13 -- A Quasar App Extension for Cypress e2e
  @quasar/quasar-app-extension-testing-unit-jest - 3.0.0-alpha.10 -- A Quasar App Extension for running Jest tests

Networking
  Host - Joeys-MacBook-Pro.local
  en0 - 192.168.102.6
```

**Comment by therealcoder1337** [comment] 2022-04-19 03:32
possible duplicate of: https://github.com/quasarframework/quasar/issues/13154

**Comment by goforu** [comment] 2022-04-19 03:46
I found some clues. It seems if a v-ripple comes along with a dialog, the page will throw error!
[Reproduction URL](https://codesandbox.io/s/nifty-northcutt-352vkf?file=/src/pages/Index.vue)

**Comment by goforu** [comment] 2022-04-19 03:50
> possible duplicate of: #13154

seems not

**Comment by heriisei** [comment] 2022-04-19 05:15
I have those same error messages when I use the `v-ripple` directive.
I am using quasar as a vite plugin flavour.

"quasar": "^2.6.6",
"@quasar/extras": "^1.13.5"
"@quasar/vite-plugin": "^1.0.9"

![image](https://user-images.githubusercontent.com/18598759/163924841-2d6daa25-2a18-48fd-8429-d8f21d6af22a.png)

**Comment by goforu** [comment] 2022-04-19 06:42
> I have those same error messages when I use the `v-ripple` directive. I am using quasar as a vite plugin flavour.
> 
> "quasar": "^2.6.6", "@quasar/extras": "^1.13.5" "@quasar/vite-plugin": "^1.0.9"
> 
> ![image](https://user-images.githubusercontent.com/18598759/163924841-2d6daa25-2a18-48fd-8429-d8f21d6af22a.png)

I guess if you get rid of menu, the page will be fine. Quasar has v-ripple bug when it comes with Popups such as Dialog/Menu ...

If anyone knows how to fix it

**Comment by rstoenescu** [comment] 2022-04-19 06:57
Duplicate with the pinned Vie bug ticket.
Downgrade Vue to .31 until the regression is solved.

**Comment by rstoenescu** [comment] 2022-04-19 06:58
Vue 3.2.31 to be exact

**Closed** 2022-04-19 06:57 UTC
Labels: kind/bug 🐞, :outbox_tray: external lib issue, Qv2 🔝, area/ui, area/directives
