### ISSUE TITLE
Round ripple not showing properly on iOS safari

### ISSUE THREAD

**Issue by rooneyl** [quasarframework/quasar#4891] opened 2019-08-13 19:17 UTC
**Describe the bug**
Button with round style should have rounded ripple effect, but on iOS safari it shows as regular square ripple when I press button quickly multiple times. It seems like its happening only for the buttons in toolbar

**To Reproduce**
1. Go to 'https://quasar.dev/vue-components/toolbar#Example--With-Avatar' on *iPhone safari*
2. Click on 'any button on toolbar multiple time quickly'

**Expected behavior**
It should always show round ripple effect with round option

**Screenshots**
Expected:
<img width="236" alt="Screen Shot 2019-08-13 at 11 46 10 AM" src="https://user-images.githubusercontent.com/23136511/62970319-12504180-bdc4-11e9-9378-b8ff2ed9f765.png">
Actual:
![ezgif com-crop](https://user-images.githubusercontent.com/23136511/62970324-17ad8c00-bdc4-11e9-9eac-a0ec41f5d522.gif)

**Platform (please complete the following information):**
iOS: 12.3.1

**Comment by smakinson** [comment] 2019-10-26 14:39
Noticing a possibly related issue on flat round buttons and the Ripple. You can see the bottom left corner breaks out of the button when clicked on the docs here: https://quasar.dev/vue-components/button#Design

Click either one of the round buttons in the first 2 rows there and watch the bottom left corner.

**Comment by pdanpdan** [comment] 2019-11-08 09:10
I suppose this was fixed by Safari in the newer releases, because i cannot be reproduced on iOS 13+.
If it is present only on iOS 12 Safari then it's a bug in the browser and we cannot fix it, sorry.

**Comment by soccer99** [comment] 2020-03-05 18:15
Seeing the same issue as @smakinson on the latest version of google chrome on Mac OSX.  The bottom left of the round ripple shows through the circle.

**Comment by rstoenescu** [comment] 2020-06-11 12:23
Cannot reproduce with latest Quasar on MacOS or iOS (v13+). Probably Apple fixed this bug.

**Closed by rstoenescu** 2020-06-11 12:23 UTC
Labels: bug, team-pick
