### ISSUE TITLE
Qtree getNodeByKey could return parents as well

### ISSUE THREAD

**Issue by pintaf** [quasarframework/quasar#6960] opened 2020-05-05 11:10 UTC
@pdanpdan For you to track in #6959 

**Describe the solution you'd like**
Enhance the Qtree `getNodeByKey (key)`  function but adding a parameter to return the node with its parents

**Describe alternatives you've considered**
Customs built code at the moment, but knowing hierarchy of a node is important.

**Example code**

This code is a function returning (if requested) the parents of a node.
In that case it's a structure like the tree structure that is retained: object with childen array.
In that case children alway contain one element, until we reach the requested node.
Not sure it's the best structure, but for me it is needed as I use this to display on the side a summary about where we are in the tree (important on vastly expanded trees)

```
function findNodeById (treeArray, id, withParents) {
  for (let i = 0; i < array.length; i++) {
    const node = JSON.parse(JSON.stringify(array[i]));
    if (node.id === id) {
      node.children = [];
      return node;
    } else {
      const result = findNodeById(node.children, id, withParents);
      if (result !== undefined) {
        if (withParents) {
          const rtn = node;
          rtn.children = [result];
          return rtn;
        } else {
          return result;
        }
      }
    }
  }
}
```

**Comment by pdanpdan** [comment] 2020-05-05 11:19
duplicate of #5642 5642

**Closed by pdanpdan** 2020-05-05 11:19 UTC
Labels: feature request
