### ISSUE TITLE
[Request] UMD HREF support

### ISSUE THREAD

**Issue by nicholaszuccarelli** [quasarframework/quasar#2471] opened 2018-08-26 04:25 UTC
Hiya,

I've been playing around with the UMD version of Quasar (which may I add, is super cool), however I'm having problems with creating HREF items.

For example, I have created a layout-drawer with some 
`<q-item to="http://google.com"></q-item>`

However, the `<q-item>` is rendered as a `<router-link>`, rather than an `<a href="http://google.com">`.

This also goes with <q-btn> (and any other elements which support the 'to' attribute)

So I'm wondering if there is any way to create a href on these elements naturally through the UMD version of Quasar?

Cheers!

**Comment by smolinari** [comment] 2018-08-26 08:03
Hi Nicholas,

In general, we'd rather have only bugs and suggestions as issues in the repos. So, please use either the [forum](http://forum.quasar-framework.org/) or the [discord channel](https://discord.gg/5TDhbDg) for questions. You'll get answers there for sure. Please just have some patience. 

Thanks. 😄 

Scott

**Comment by nicholaszuccarelli** [comment] 2018-08-26 08:09
Hi Scott,
Thanks for the reply. I'll do so in the future :)

In regards to this request though, I'd possibly even classify this as a bug as I am literally unable to create hrefs for links at all unless I use a normal `<a>`, unless this was expected behaviour for the components.

Thanks.

**Comment by nicholaszuccarelli** [comment] 2018-08-26 11:05
Hey again Scott

For buttons, I used type="" (`<q-btn type="a" href="blah.com" />`)
For Qitems, I used `<q-item tag="a" href="blah.com" />`)

I've only come across one small problem with the Qitem solution: 
https://i.gyazo.com/dee7e4050d0ce5fc26b017a1b8456d3d.png

So if you don't mind, I'm going to reopen this thread - could the text possibly be fixed? :D

**Comment by smolinari** [comment] 2018-08-26 11:52
If you don't mind. Close this issue and open a new thread on the forum or post your question in Discord. :) If we figure out it is an issue with Quasar, we can open an issue with a proper description and reproduction of the problem.

I am also not certain what the problem is, to be honest. I see strange text, but not the problem in general. The best way to describe a problem is to create a Fiddle for it too. :)

https://jsfiddle.net/rstoenescu/waugrryy/

Scott

**Closed** 2018-08-26 11:56 UTC
