### ISSUE TITLE
BUG Q-btn-dropdown

### ISSUE THREAD

**Issue by balazStefan** [quasarframework/quasar#15901] opened 2023-05-25 09:42 UTC
### What happened?

I expecting when I am using q-btn-dropdown inside q-table , if I have for example 100 results in table I mean rows 
the option q-list going with scroll

### What did you expect to happen?

list item should be stick to button 

### Reproduction URL

https://codepen.io/tefan-Bal-the-bold/pen/BaqMeoG

### How to reproduce?

Go to link
select more then 5 rows, in pagination 
open some dropdown 
scroll 
the list with options in q-btn-dropdown is going with you 
<img width="200" alt="Snímka obrazovky 2023-05-25 o 11 36 02" src="https://github.com/quasarframework/quasar/assets/86514753/2bb8f58b-2fcc-4877-9fa2-684b0022e120">
<img width="361" alt="Snímka obrazovky 2023-05-25 o 11 35 59" src="https://github.com/quasarframework/quasar/assets/86514753/f48339a2-68b3-4cbe-a9b6-5c2c4e5a4655">

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

**Comment by pdanpdan** [comment] 2023-05-25 09:45
duplicate of ~#15899~ #15894 keep it there

**Closed as completed by pdanpdan** 2023-05-25 09:45 UTC
Labels: kind/bug 🐞, Qv2 🔝, bug/1-repro-available, area/components, flavour/quasar-cli-vite

**Comment by balazStefan** [comment] 2023-05-25 09:50
is it really same ? I am referring to table
