### ISSUE TITLE
New Feature: QUploader Limit of simultaneously uploading files

### ISSUE THREAD

**Issue by tpoxa** [quasarframework/quasar#1845] opened 2018-03-27 14:04 UTC
Hello.

Would be nice to limit somehow number of simultaneously uploading files. Because currencly all files selected are uploading same time, which is not good for user experience.

Thank you for such great framework!

**Comment by rstoenescu** [comment] 2018-03-30 05:36
Hi, Duplicate of https://github.com/quasarframework/quasar/issues/1146
Will do.

**Closed by rstoenescu** 2018-03-30 05:36 UTC
