### ISSUE TITLE
QEditor text decorations bold, underline, italic not working in Safari. 

### ISSUE THREAD

**Issue by rakishanav** [quasarframework/quasar#4866] opened 2019-08-11 11:46 UTC
It works fine in mozilla and chrome. I tried running execCommands on click of buttons and it's working but if I replace button with div and run on click, the selection is lost.  Is it because the toolbar items are not buttons ? Did an inspect element and found them to be anchor tags.

**Comment by jacksonGross** [comment] 2019-10-29 23:37
I am having this issue too, and also affects the hyperlink action due to selections being lost.

**Comment by rstoenescu** [comment] 2019-10-30 17:52
Duplicate of #5277

**Closed by rstoenescu** 2019-10-30 17:52 UTC
Labels: bug

**Comment by RobertoLangarica** [comment] 2020-04-17 19:44
**Here is a fix in case someone is stuck with an older version of Quasar.**

As stated in the first comment the problem is because the tags used in the editor are not buttons, so the workaround is to tweek a little bit the properties used by QEditor where the tag <a> is hardcoded.

> Note: The workaround was tested with quasar v1.1.2 y Safari v13.0.4.

The next code was in a boot script, but it will work in any other place. Basically when the platform is Safari we are replacing  the previous button type from anchor to button, so when the toolbar gets created it will use buttons instead of anchors.


```javascript
import {QEditor, Platform} from 'quasar'

function fixedButtonProps() {
  const flat = this.toolbarOutline !== true &&
          this.toolbarPush !== true

  return {
    type: 'button',
    flat,
    noWrap: true,
    outline: this.toolbarOutline,
    push: this.toolbarPush,
    rounded: this.toolbarRounded,
    dense: true,
    color: this.toolbarColor,
    disable: !this.editable,
    size: 'sm'
  }
}

// "async" is optional
export default async ({ Vue }) => {
  // Change only for Safari
  if (Platform.is.safari) {
    QEditor.options.computed.buttonProps = fixedButtonProps
  }
}
```
