### ISSUE TITLE
Dialog plugin - persistent property is not working

### ISSUE THREAD

**Issue by juppdes** [quasarframework/quasar#4034] opened 2019-05-03 21:03 UTC
QDialog - persistent property is not working

https://codepen.io/Jupp/pen/rgBGjM

Quasar:
@quasar/app (v1+ only): 1.0.0-beta.6
OS: windows 10 64bits
Node: 11.9.0
NPM: 6.9.0

**Comment by rstoenescu** [comment] 2019-05-03 21:35
Duplicate of https://github.com/quasarframework/quasar/issues/4028
Fixed and will be available in beta.21

**Closed by rstoenescu** 2019-05-03 21:35 UTC
