### ISSUE TITLE
Request for a new boolean props for Chinese Label for Dense Input

### ISSUE THREAD

**Issue by cyfung1031** [quasarframework/quasar#10661] opened 2021-09-14 11:58 UTC
Can you make a boolean prop `label-on-outline` for the label floating to the outline of the input field? 

## Current Design for Outline Input with `Dense="true"`

* https://quasar.dev/vue-components/input#example--outlined
In the current design for outline input field, it is okay for English Label.
![image](https://user-images.githubusercontent.com/44498510/133251364-96bb11f4-3d9d-4a55-b384-f18eee6bf759.png)
But it is ugly for Chinese Label as the spacing is insufficient.
![image](https://user-images.githubusercontent.com/44498510/133251474-574c0526-afa0-4b17-b3bd-c6165d0b45b7.png)
If the text get highlighted, you can see that the spacing for the text is overlapped with the label.
![image](https://user-images.githubusercontent.com/44498510/133251568-c8642c3f-97d2-408c-a913-f54e512cddc9.png)

## Reference to Google's universal design for all languages

To solve this issue, I think you can give developer an option to use the floating label style like Google's form inputs.

* https://accounts.google.com/
![image](https://user-images.githubusercontent.com/44498510/133251740-73b0c2d1-d5ac-4753-83b8-99859de919a9.png)

### reference css for such design:

* https://tailwindcomponents.com/component/login-form-with-float-label-input
![image](https://user-images.githubusercontent.com/44498510/133252954-a4237c8f-6fc8-4bfd-bb03-211b890dbe5e.png)

**Comment by pdanpdan** [comment] 2021-09-14 17:08
duplicate of #3262

**Closed as completed by pdanpdan** 2021-09-14 17:08 UTC
Labels: kind/feature 💡
