### ISSUE TITLE
[V1] QSelect display value instead of label

### ISSUE THREAD

**Issue by aquadk** [quasarframework/quasar#4429] opened 2019-06-20 12:31 UTC
**Describe the bug**
QSelect display value instead of label

**Codepen/jsFiddle (required)**
https://codepen.io/aquadk/pen/JQbbKw?editors=1010

**To Reproduce**
1. Enter select field
2. Type space
3. Leave select field

**Expected behavior**
Only show label, never display value

**Platform (please complete the following information):**
OS: Windows
Node: https://cdn.jsdelivr.net/npm/quasar@1.0.0-rc.5/dist/quasar.umd.min.js
Browsers: All

**Comment by metalsadman** [comment] 2019-06-21 16:39
@aquadk change your filterfn https://codepen.io/metalsadman/pen/mZWBrv?editors=1010

**Comment by pdanpdan** [comment] 2019-06-21 17:55
Duplicate of https://github.com/quasarframework/quasar/issues/4288 and https://github.com/quasarframework/quasar/issues/4250

See the later for how you should proceed.

**Comment by aquadk** [comment] 2019-06-24 07:13
I still think it should be handled by QSelect. 
in https://github.com/quasarframework/quasar/blob/dev/ui/src/components/select/QSelect.js
the function __resetInputValue should handle this and never show values on labels.

**Comment by pdanpdan** [comment] 2019-06-25 16:49
And what should `__resetInputValue` display, what label? You are not providing the full object to `QSelect` and the current value is not found in the existing list of options (because it is filtered).

You have working example in the referenced issues.

**Comment by H3r3zy** [comment] 2019-06-26 14:25
You can use this workaround:
https://gist.github.com/H3r3zy/55b4656321cd6005ee340d868964ef28

It's a QSelect component with a filter. It filters in function of the label.
Like I said on the Gist description the 'label' and 'value' key will be override.
And you can't change the filter method.

**Comment by pdanpdan** [comment] 2019-09-09 09:21
Closing this. The right thing to do (and the only way that can work) is to provide the full object in the model.

**Closed by pdanpdan** 2019-09-09 09:21 UTC
Labels: bug
