### ISSUE TITLE
[Feature Request] Add support to option groups in QSelect

### ISSUE THREAD

**Issue by marcelo-rebello** [quasarframework/quasar#2651] opened 2018-10-03 03:37 UTC
I think that would be nice to add support to Options groups inside a QSelect in a way similar to the HTML tag <optgroup>. 
This keeps a reasonable mapping between HTML tags and Quasar awesome components and enables a better visualisation of data in a long options list.
One simple way to do it is to test if the value of an item on "options" prop is an array of objects with label and value attributes.
Can be even more clear if we have another prop "optionGroups" to use this composite options list.

**Comment by smolinari** [comment] 2018-10-03 14:27
Duplicate of #557

Scott

**Comment by rstoenescu** [comment] 2018-10-03 15:58
Hi @marcelo-rebello ,

This is scheduled for v1.0. Please follow the duplicate link.
Thank you.

**Closed by rstoenescu** 2018-10-03 15:58 UTC
