### ISSUE TITLE
[Request] QSelect- Suggest to add "Select All" and "Clear" Option for multiple selection

### ISSUE THREAD

**Issue by jamesYapKM** [quasarframework/quasar#2076] opened 2018-05-25 02:27 UTC
Suggest to add a "Select All" and "Clear" Option in QSelect components

**Comment by rstoenescu** [comment] 2018-05-25 08:30
Duplicate of https://github.com/quasarframework/quasar/issues/828

**Closed by rstoenescu** 2018-05-25 08:30 UTC
