### ISSUE TITLE
q-img calls @click handler twice

### ISSUE THREAD

**Issue by Claus1** [quasarframework/quasar#10644] opened 2021-09-11 14:19 UTC
If define @click on q-img it is called twice when only a click.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/Claus1/pen/VwWbxbR?editors=1011

**To Reproduce**
Click on loaded picture (it works slow, wait a bit) and then in console you will see double output for @click.

**Expected behavior**
@click has to be called once.

**Screenshots**
![image](https://user-images.githubusercontent.com/1247062/132950897-96900413-4e4d-4781-8dd9-0ec9d668010f.png)

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version: the latest

Quasar mode:
  - [ x] SPA

Tested on:
  - [x ] SPA

OS: Linux mint 19.1
Node: the latest
NPM: the latest
Yarn: the latest
Browsers: Chrome the latest

**Comment by pdanpdan** [comment] 2021-09-11 14:23
Duplicate of #10522

**Closed as completed by pdanpdan** 2021-09-11 14:23 UTC
Labels: Qv2 🔝

**Comment by Claus1** [comment] 2021-09-11 14:50
Where duplicate? I did not see. Read carefully.

**Comment by pdanpdan** [comment] 2021-09-11 15:29
I know it is closed, but if there is something to comment put it there, it doesn't make sense to have 2 issues
