### ISSUE TITLE
IconGenie will not install on MacOS Sonoma 14.1

### ISSUE THREAD

**Issue by bkirvin** [quasarframework/quasar#17463] opened 2024-08-27 12:31 UTC
### What happened?

Upgraded my Mac dev machine to a MacBookPro with M3 chip running Sonoma 14.1 and my Quasar projects all failed on npm install with

`Error: pngquant failed to build, make sure that libpng is installed`

ran

`brew install libpng`

but still getting the same error. I've removed IconGenie from the package.json and now the projects install and run. Thankfully, I have all of my previously generated assets from IconGenie but would like to use the tool on future projects. Is IconGenie just not available to new Mac machines?

### What did you expect to happen?

Project installs with npm install and runs

### Reproduction URL

https://stackblitz.com/edit/quasarframework-s6g23w?file=package.json

### How to reproduce?

run 
`$ npm i -g @quasar/icongenie`

The StackBlitz reproduction URL doesn't recreate the problem because it isn't running on MacOS Sonoma 14.1

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Icon Genie CLI (@quasar/icongenie)

### Platforms/Browsers

Other

### Quasar info output

```Shell
> quasar-project@0.0.1 info
> quasar info


Operating System - Darwin(23.1.0) - darwin/arm64
NodeJs - 20.17.0

Global packages
  NPM - 10.8.2
  yarn - Not installed
  @quasar/cli - undefined
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.16.9 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.9.5 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.16.12 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.4.38 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.4.3
  pinia - 2.2.2 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 2.9.18 -- Native-ESM powered web dev build tool
  eslint - 8.57.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  @electron/packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*
```

### Relevant log output

```Shell
npm warn deprecated phin@2.9.3: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm warn deprecated @hapi/formula@2.0.0: Moved to 'npm install @sideway/formula'
npm warn deprecated @hapi/address@4.1.0: Moved to 'npm install @sideway/address'
npm warn deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm warn deprecated @hapi/joi@17.1.1: Switch to 'npm install joi'
npm error code 1
npm error path /Users/.../quasar-project/node_modules/pngquant-bin
npm error command failed
npm error command sh -c node lib/install.js
npm error compiling from source
npm error spawn Unknown system error -86
npm error pngquant pre-build test failed
npm error Error: pngquant failed to build, make sure that libpng is installed
npm error     at /.../quasar-project/node_modules/bin-build/node_modules/execa/index.js:231:11
npm error     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm error     at async Promise.all (index 0)
npm error A complete log of this run can be found in: /Users/.../.npm/_logs/2024-08-27T12_01_48_256Z-debug-0.log
```

**Comment by bkirvin** [comment] 2024-08-27 14:30
Just noticed that I did not have quasar/cli installed. After installing quasar/cli the problem persists.

**Comment by bkirvin** [comment] 2024-08-27 14:34
> quasar-project@0.0.1 info
> quasar info


Operating System - Darwin(23.1.0) - darwin/arm64
NodeJs - 20.17.0

Global packages
  NPM - 10.8.2
  yarn - Not installed
  @quasar/cli - undefined
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.16.9 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.9.5 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.16.12 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.4.38 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.4.3
  pinia - 2.2.2 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 2.9.18 -- Native-ESM powered web dev build tool
  eslint - 8.57.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  @electron/packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

**Comment by bkirvin** [comment] 2024-08-27 14:36
Operating System - Darwin(23.1.0) - darwin/arm64
NodeJs - 20.17.0

Global packages
  NPM - 10.8.2
  yarn - Not installed
  @quasar/cli - 2.4.1
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.16.9 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.9.5 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.16.12 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.4.38 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.4.3
  pinia - 2.2.2 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 2.9.18 -- Native-ESM powered web dev build tool
  eslint - 8.57.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  @electron/packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

**Comment by yusufkandemir** [comment] 2024-08-28 11:00
Duplicate of #17459

**Closed as not planned by yusufkandemir** 2024-08-28 11:00 UTC
Labels: kind/bug 🐞, Qv2 🔝, bug/1-repro-available, area/icongenie, flavour/quasar-cli-vite
