### ISSUE TITLE
Quasar.conf.js can not configure watchOptions

### ISSUE THREAD

**Issue by susnux** [quasarframework/quasar#9906] opened 2021-07-01 16:10 UTC
**Describe the bug**
When I configure `watchOptions` like in the [documentation](https://quasar.dev/app-extensions/development-guide/introduction#install-and-prompts-scripts), meaning I would like to exclude module from `node_modules` so the `devServer` also watches that module, and run `quasar dev` I get an error message:

```
message: 'Invalid configuration object. Object has been initialized using a configuration object that does not match the API schema.\n' +
    " - configuration has an unknown property 'watchOptions'. These properties are valid:\n" +
    '   object { bonjour?, client?, compress?, devMiddleware?, firewall?, headers?, historyApiFallback?, host?, hot?, http2?, https?, liveReload?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, port?, proxy?, public?, setupExitSignals?, static?, transportMode?, watchFiles? }'
```

**Codepen/jsFiddle/Codesandbox (required)**
https://codesandbox.io/s/crazy-poincare-iprrq?file=/quasar.conf.js:1975-1997

**To Reproduce**
1. Edit `quasar.conf.js` -> `devServer` -> add `watchOptions` section.
2. run `yarn quasar dev`
3. See error

**Expected behavior**
No error, webpack dev server starting and watching project and that node module.

**Platform (please complete the following information):**
Quasar Version: 2.0.1
@quasar/app Version: 3.0.1

Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: openSUSE Tumbleweed
Node: 16.4
NPM:
Yarn: 1.22.10

**Additional context**
Log file: 
[logs.txt](https://github.com/quasarframework/quasar/files/6749484/logs.txt)

**Comment by rstoenescu** [comment] 2021-07-01 16:14
Duplicate of https://github.com/quasarframework/quasar/issues/9838

**Closed as completed by rstoenescu** 2021-07-01 16:14 UTC
Labels: kind/bug 🐞, Qv2 🔝

**Comment by Karnith** [comment] 2021-11-22 10:18
watchOptions is still available, just not on devserver. If you're using docker dev containers add the following to your quasar.config.js
```js
extendWebpack(cfg) {
  cfg.watchOptions = {
    aggregateTimeout: 200,
    poll: 1000,
  };
},
```
this will set the watcher to polling and make quasar v2 webpack file watcher functional in docker containers.
