### ISSUE TITLE
Provide for enhancement requests for quasarframework separate from the quasar codebase

### ISSUE THREAD

**Issue by julie777** [quasarframework/quasar#10946] opened 2021-10-10 17:05 UTC
**Is your feature request related to a problem? Please describe.**
Currently the quasarframework repo is just a home page and a way to group other repos. 

**Describe the solution you'd like**
I would like to see the framework page describe the quasar framework, provide some details about the repo organization, such as noting that the main codebase is in the quasar repo, talk about starter kits. 
And --- have it's own issues, to allow suggestions about repo organization, structuring that is framework based and not quasar based.

For example, my view of quasar is
```
quasarframework
   /quasar-cli
   / quasar
        /components
        /test
    /starter-kits
       /ui
       /pwa
   /extensions
      /eslint
      /vuex
```
**Describe alternatives you've considered**

**Additional context**
Pinning 6 repos and then just listing all 50+ repos that are part of quasar is unstructured and doesn't help the new user.

When a third part creates an extension or starter kit, it doesn't alwasy have to be moved into the quasarframework repo. The quasarframework/starter-kits/readme could have a list of the ones in the repo and the ones outside the repo, which would enable quasar create to use them all. Similarly for extensions.

This implies multiple levels of trust. The quasar team created it, the quasar team acknowledged that it is worthwhile to publish in the readme and everthing else.

**Comment by MilosPaunovic** [comment] 2021-10-10 17:35
You can't pin more than 6 repos.

**Comment by julie777** [comment] 2021-10-10 18:53
> 
> 
> You can't pin more than 6 repos.
I am not a github expert. What kind of page it quasar-framework?

**Comment by pdanpdan** [comment] 2021-10-14 05:58
Please move this to Discussions. Also it's almost a duplicate of your own 10806

**Closed as completed by pdanpdan** 2021-10-14 05:58 UTC
Labels: kind/feature 💡
