### ISSUE TITLE
Vite 4 support for Quasar Vite Plugin (@quasar/vite-plugin)

### ISSUE THREAD

**Issue by fr3dbayl3** [quasarframework/quasar#15095] opened 2022-12-12 09:02 UTC
### What happened?

Hi there ! 
It seems to be a dependency issue when creating a new quasar project when using the @quasar/vite-plugin. 
When scaffolding a new project using vite@latest, @vitejs/plugin-vue version is now 4.0.0.

During the installation procedure, the command ```npm install -D @quasar/vite-plugin``` fails due to a broken dependency. It will produce the following output :

``` bash
npm ERR! Could not resolve dependency:
npm ERR! peer @vitejs/plugin-vue@"^2.0.0 || ^3.0.0" from @quasar/vite-plugin@1.2.3
```

### What did you expect to happen?

I hope this dependency error will disapear soon :)

Thank you for this great framework and ecosystem.

### Reproduction URL

none

### How to reproduce?

1. Follow the project scaffolding procedure described in this page : ```https://quasar.dev/start/vite-plugin```

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Platforms/Browsers

Other

**Comment by Shinigami92** [comment] 2022-12-12 09:15
I think we just need to update

https://github.com/quasarframework/quasar/blob/c5804791e61ba301d57f68dc4a23455b221a3e6d/vite-plugin/package.json#L35

to `"@vitejs/plugin-vue": "^2.0.0 || ^3.0.0 || ^4.0.0",`

**Comment by yusufkandemir** [comment] 2022-12-12 09:24
To make it clear, it's not a broken dependency. We are just not officially supporting Vite 4 yet. I am not sure if all it takes to support it is to allow that version for peer dependency. @Shinigami92 can you confirm it's all that's needed to support Vite 4, please?

**Comment by fr3dbayl3** [comment] 2022-12-12 09:55
I'm sorry for the incorrect semantic and I hope that the fix will be as easy as the @Shinigami92 proposal.

**Comment by Shinigami92** [comment] 2022-12-12 09:55
> To make it clear, it's not a broken dependency. We are just not officially supporting Vite 4 yet. I am not sure if all it takes to support it is to allow that version for peer dependency. @Shinigami92 can you confirm it's all that's needed to support Vite 4, please?

I'm not sure from Vite's side, but I just installed it anyway and ignored the warning, and everything works just fine
So yes, I think nothing else needed, just widen the range

**Comment by pmiguelmartins** [comment] 2022-12-13 15:26
Hi

With Vite 4.0.1 gives this error : 


Uncaught (in promise) TypeError: (intermediate value)() is null
    setup quasar.esm.prod.js:6


With Vite 4.0.0 all works just fine.

**Comment by fr3dbayl3** [comment] 2022-12-13 17:38
The problem seems to be in the ```getViteConfig``` function. the ```externalViteCfg``` parameter doesn't contain the mode property anymore.
the plugin isn't able to detect the development env.
Replacing the instruction ```if(externalViteCfg.mode === 'development')``` by ```if ((externalViteCfg.mode || process.env.NODE_ENV) === 'development')``` solves the issue and is backward compatible.
I saw in the vite repository that they did modifications related to the runtime environment.
The real question is : Is it a vite regression or simply aa wanted behavior ???

**Comment by vincentauger** [comment] 2022-12-15 17:46
To confirm, the changes suggested by @fr3dbayl3 fixed the problem for me. I just tried Vite 4.0.1 on my project and can do a successful production build, but I do run into the TypeError when running in dev.

```console
vue-router.mjs:3451 TypeError: Cannot destructure property 'proxy' of 'getCurrentInstance(...)' as it is null.
    at setup (quasar.esm.prod.js?v=cf6dd992:6:294258)
    at callWithErrorHandling (runtime-core.esm-bundler.js:157:22)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7246:29)
    at setupComponent (runtime-core.esm-bundler.js:7201:11)
    at mountComponent (runtime-core.esm-bundler.js:5524:13)
    at processComponent (runtime-core.esm-bundler.js:5499:17)
    at patch (runtime-core.esm-bundler.js:5101:21)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5638:21)
    at ReactiveEffect.run (reactivity.esm-bundler.js:187:25)
    at instance.update (runtime-core.esm-bundler.js:5745:56)
```
I also confirmed that the change was backward compatible with my project using Vite 3.2.5.

However, with Vite 3.2.5; both `externalViteCfg.mode` and `process.env.NODE_ENV` are `undefined`.  With Vite 3, I can change to `false` as shown below, and the dev build still functions properly. However, the code below doesn't work with Vite 4. In Vite 4, process.env.NODE_ENV is set by the `resolveConfig()` function in [config.ts](https://github.com/vitejs/vite/blob/e58a4f00e201e9c0d43ddda51ccac7b612d58650/packages/vite/src/node/config.ts)

```js
    if (false) {
      viteCfg.resolve = {
        alias: [
          { find: /^quasar$/, replacement: 'quasar/dist/quasar.esm.js' }
        ]
      };
    }
```

It looks like in `getConfigPlugin (opts)`, we should return the resolved configuration and not the user configuration.

```js
function getConfigPlugin (opts) {
  return {
    name: 'vite:quasar:vite-conf',

    config (viteConf) {
      const vueCfg = viteConf.plugins.find(entry => entry.name === 'vite:vue');

      if (vueCfg === void 0) {
        console.warn('In your Vite config file, please add the Quasar plugin after the Vue one');
        process.exit(1);
      }
      // remove this .. move it in configResolved below
      //return getViteConfig(opts.runMode, viteConf)
    },
    configResolved(config){
      return getViteConfig(opts.runMode, config)
    }
  }
}
```

The above works with both Vite 3 and Vite 4. Pull request #15117 should address the above but was not tested with Vite 2.0

**Comment by yusufkandemir** [comment] 2022-12-16 09:40
Thanks for testing it out and help discovering the potential problems. It turns out the `config` hook has a second parameter that contains `mode` which is always defined. Vite [2](https://v2.vitejs.dev/guide/api-plugin.html#config), [3](https://v3.vitejs.dev/guide/api-plugin.html#config), and [4](https://vitejs.dev/guide/api-plugin.html#config) all have this parameter. So, I created #15125 which uses that parameter instead. Everyone, please try if that works for you. If it does, I will merge it, and it will be included in the next Vite plugin release.

**Comment by pmiguelmartins** [comment] 2022-12-16 10:14
> 

Hi .. 

It works just fine 

Thanks

**Closed as completed** 2022-12-16 11:06 UTC
Labels: kind/feature 💡, Qv2 🔝, flavour/vite-plugin

**Comment by rstoenescu** [comment] 2022-12-16 11:07
Will be available in `@quasar/vite-plugin` v1.3.0

**Comment by fr3dbayl3** [comment] 2022-12-16 11:11
I confirm that it solves the problem. Dev server and production build work like a charm now :)
Thank you.

**Comment by adarshmadrecha** [comment] 2022-12-16 15:03
Release planed in next couple of days?

**Comment by agroebe** [comment] 2022-12-16 15:37
Any idea when version will be available on registry?

**Comment by rstoenescu** [comment] 2022-12-17 13:19
Released it today

**Comment by NicolasReibnitz** [comment] 2023-05-24 19:02
> Released it today

So if I understand this correctly, and all compatibility issues and breaking changes are handled with this update to @quasar/vite-plugin, then the dependency in @quasar/app-vite could also be updated to include vite 4, right?

I'm wondering because [vite-plugin-vue-devtools](https://github.com/webfansplz/vite-plugin-vue-devtools) looks interesting and requires vite 4.
