### ISSUE TITLE
[Bug] QHeader and QFooter reveal is triggered when a QDialog or QPopupProxy is fired.

### ISSUE THREAD

**Issue by danielcommesse** [quasarframework/quasar#5213] opened 2019-10-03 07:24 UTC
**Describe the bug**
A page has enough content to scroll through that the QHeader or QFooter reveal is triggered at scrolling hiding the given QHeader or QFooter, then if a QDialog or QPopupProxy is fired within the scrolled content, the QHeader and/or QFooter are revealed while the QDialog/QPopupProxy is displayed, on iOS it actually breaks the Layout.

**Codepen**
https://codepen.io/danielcommesse/pen/GRRKgYR?&editable=true&editors=101

**To Reproduce**
1. Set your viewport to smartphone dimensions.
2. Create a page that has enough content for it to have a scroll area enough to trigger the offset of the reveal prop of a QHeader/QFooter.
3. Scroll through the content till QHeader/QFooter reveals trigger hiding the QHeader/QFooter.
4. Within the scrolled content, click trough an element that displays a QDialog/QPopupProxy.
5. The QHeader/QFooter should reveal when the QDialog/QPopupProxy is fired causing the Layout to behave strange like flickering on the hide of QDialog/QPopupProxy and causing the Layout to break with iOS top and bottom padding.

**Expected behavior**
The QDialog/QPopupProxy should not trigger the reveal prop of the QHeader/QFooter when displayed.

**Screenshots**
Please check the Codepen

**Platform (please complete the following information):**
OS: MacOs Mojave
Node: v11.12.0
NPM: 6.9.0
Browsers: Chrome, Firefox
iOS: 13.0 (iPhone 8, iPhone 11)
Android: Not tested
Electron: Not tested

**Comment by rstoenescu** [comment] 2019-10-03 08:46
Hi,

The problem is very deep. I'll try to summarize it with a high level overview. The biggest problem on iOS due to its webview (many tickets have been reported on this) is that you can't prevent user from scrolling when having a popup **in all possible scenarios**, so the page content has to be transferred to a fixed position (while maintaining scroll position) -- and so no scroll is available, which in turn triggers some layout elements' events. This cannot be prevented.

**Closed by rstoenescu** 2019-10-03 08:46 UTC
Labels: bug
