### ISSUE TITLE
QSelect multiple returns undefined

### ISSUE THREAD

**Issue by ShoneMSG** [quasarframework/quasar#2482] opened 2018-08-29 09:28 UTC
### Software version

Quasar: 0.17.10
OS: Linux
Browsers: Chrome, Firefox

### JsFiddle (for Quasar v0.15+ only)

https://jsfiddle.net/oqp4wmxk/41/

### What did you get as the error?
When using mutliple prop on QSelect, deselecting items returns undefined.

### What were you expecting?
It sould retrun an empty array.
### What steps did you take, to get the error?
Selected multiple items in the QSelect  than deselected them.

**Comment by pdanpdan** [comment] 2018-08-29 09:36
The value is correct, only the display is broken. Fixed for the next version.
Duplicate of #2479

**Comment by ShoneMSG** [comment] 2018-08-29 09:42
Ok great, thank you.

**Closed** 2018-08-29 12:49 UTC
