### ISSUE TITLE
Strange issue with Toast (not allways showing)

### ISSUE THREAD

**Issue by ircop** [quasarframework/quasar#914] opened 2017-09-22 21:16 UTC
I have some strange behavior of Quasar Toast :( (latest quasar version)

In my main.js i have mixed in $fetch function, that is my wrapper for regular fetch().
In case of fetch errors, it should show an UI error to user.

But the toast is showing from time to time, not always =\

the situation is similar to that, as if Toast component is loading (or not loading) once:
When i refreshing whole app with f5, if i'm lucky, Toast will work always. But on next reload, if i'm not lucky this time, this Toast will not work at all.

And one more note: the chance of Toast to get work is much greater if developer console is opened in my Firefox, when i'm reloading page. as if Toast need some little lag when Dom loading, and then it loads successful.

Sorry for my bad english :)

My code:

```javascript
// Global functions
Vue.mixin({
    methods: {
        $fetch: function( url, method, data, callback, failCallback ) {
            this.$Progress.start()
            var body = null;
            if( method == "POST" || method == 'PUT' ) {
                body = JSON.stringify(data);
            }
            fetch( url, {
                method: method,
                body: body,
                credentials: "same-origin",
                headers: {
                    "Accept": "application/json"
                }
            })
                .then((resp) => {
                    if( resp.status != 200 ) {
                        // bus.$emit('snackbar-error', "Ошибка при запросе сервера (код " + resp.status + "): " + resp.statusText);

                        Toast.create.negative({
                            html: "Ошибка при запросе сервера (код " + resp.status + "): " + resp.statusText,
                            icon: 'warning',
                            timeout: 3000,
                            onDismiss: () => {
                                this.error = false;
                                console.log('toast dismissed');
                            }
                        });
                        console.log('code!=200');
                        this.$Progress.fail();
                        if( failCallback != undefined ) {
                            failCallback();
                        }
                        return false;
                    }

                    this.$Progress.finish()
                    return resp.json();
                });
`

**Comment by odranoelBR** [comment] 2017-09-30 17:25
Hello. I encountered a similar problem when using direct QLoading on Axios, on every request. The problem is that the requests are asynchronous.
Then in the reload of the page, if 5 calls were executed and the first had returned in 1seg the loading closed, but the other 4 were running. I believe you are experiencing the same problem.

**Comment by odranoelBR** [comment] 2017-09-30 17:27
in my case Loading sometimes worked 100% and sometimes not, as in your ..
From the .14 version of the quasar, I'm using QInnerLoading, controlling the open / close on each request and also because it brings a better user experience.
Hope it help.

**Comment by ircop** [comment] 2017-09-30 18:49
I use them for different cases.
But, with QInnerLoading i have another issue :) https://github.com/quasarframework/quasar/issues/944

**Comment by odranoelBR** [comment] 2017-09-30 23:07
Maybe your Toast not working right beacause of assyncornous too.

**Comment by odranoelBR** [comment] 2017-09-30 23:09
Btw you can use 
`.catch(function(error) {
  console.log('There has been a problem with your fetch operation: ' + error.message);
});`

to grab the errors, better and cleaner than manualy check the status code

**Comment by odranoelBR** [comment] 2017-09-30 23:11
Maybe u missing .catch

fetch('flowers.jpg').then(function(response) {
  if(response.ok) {
    response.blob().then(function(myBlob) {
      var objectURL = URL.createObjectURL(myBlob);
      myImage.src = objectURL;
    });
  } else {
    console.log('Network response was not ok.');
  }
})
.catch(function(error) {
  console.log('There has been a problem with your fetch operation: ' + error.message);
});

**Comment by ircop** [comment] 2017-10-01 06:52
I've pasted here shorter variant :) Actually, i am using catch(), but no errors reported.
Log is dumping to console just before and just after Toast call, but Toast itself is not showing

**Comment by gcshri** [comment] 2017-11-08 03:26
@ircop - had the same issue. Are you using the 'load()' function in your router.js to load the component? Try to import and see if that works better?

**Comment by visadb-io** [comment] 2017-11-21 20:49
We are having the same issue with the toasts. Its Randomly showing up ... Any work around ? :) really appreciate.

**Comment by ircop** [comment] 2017-11-21 20:54
Sorry, i've switched to element :(

**Comment by rstoenescu** [comment] 2017-11-21 22:14
v0.15 will ensure there won't be any such cases. Sorry for the delay. Maybe the documentation should be more clear for v0.14 but currently don't have time now as I'm pushing very hard for v0.15 release.

**Comment by visadb-io** [comment] 2017-11-22 13:17
Rizwan, hope you are good. No worries at all. I really wanted to Thank you for this great framework and efforts you make :) appreciate it.

**Comment by rstoenescu** [comment] 2018-02-02 18:19
Hi, Toast has been replaced by the bulletproof Notify in v0.15, so closing this.

**Closed by rstoenescu** 2018-02-02 18:19 UTC
