### ISSUE TITLE
SassVariables declaration path does not work if src/ is used

### ISSUE THREAD

**Issue by Messoz** [quasarframework/quasar#17593] opened 2024-10-22 09:13 UTC
### What happened?

Following this docs [Quasar Scaffolding with Vite Plugin](https://quasar.dev/start/vite-plugin). Build fails with this vite.config.js:

```

import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import { quasar, transformAssetUrls } from '@quasar/vite-plugin'
import { fileURLToPath, URL } from 'node:url'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vue({
      template: { transformAssetUrls }
    }),

    // @quasar/plugin-vite options list:
    // https://github.com/quasarframework/quasar/blob/dev/vite-plugin/index.d.ts
    quasar({
      sassVariables: './quasar-variables.sass'
    })
   
  ]
})

```

Build is correct with this vite.config.js:

```
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import { quasar, transformAssetUrls } from '@quasar/vite-plugin'
import { fileURLToPath, URL } from 'node:url'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vue({
      template: { transformAssetUrls }
    }),

    // @quasar/plugin-vite options list:
    // https://github.com/quasarframework/quasar/blob/dev/vite-plugin/index.d.ts
    quasar({
      sassVariables: '@/quasar-variables.sass'
    })
   
  ],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url))
    }
  },
})
```

### What did you expect to happen?

Build is correct with the first vite.config.js

### Reproduction URL

https://codesandbox.io/p/github/Messoz/testSaasQuasarBug/main?import=true

### How to reproduce?

1. Go to provided link for reproduction
2. try build -> build is ok
3. specify src instead @ in quasar config in vite.config.js

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Plugins (quasar), Style & Identity (quasar), Quasar Extras (@quasar/extras)

### Quasar info output

```Shell
error during build:
[vite:css] [sass] Error: Can't find stylesheet to import.
  ╷
1 │ @import 'src/quasar-variables.sass'
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  ../../../quasar/src/css/index.sass 1:9  root stylesheet
file: /project/workspace/node_modules/quasar/src/css/index.sass
    at handleCompileResponse (/project/workspace/node_modules/sass-embedded/dist/lib/src/compiler/utils.js:158:15)
    at AsyncCompiler.compileRequestAsync (/project/workspace/node_modules/sass-embedded/dist/lib/src/compiler/async.js:70:54)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.run (file:///project/workspace/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:37516:22)
    at async Object.process (file:///project/workspace/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:37566:24)
    at async compileCSSPreprocessors (file:///project/workspace/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:36733:28)
    at async compileCSS (file:///project/workspace/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:36787:32)
    at async Object.transform (file:///project/workspace/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:36170:11)
    at async transform (file:///project/workspace/node_modules/rollup/dist/es/shared/node-entry.js:19581:16)
    at async ModuleLoader.addModuleSource (file:///project/workspace/node_modules/rollup/dist/es/shared/node-entry.js:19797:36)
```

**Comment by rstoenescu** [comment] 2024-10-22 11:50
Duplicate of https://github.com/quasarframework/quasar/issues/17592 (see ticket for solution)

**Closed by rstoenescu** 2024-10-22 11:50 UTC
Labels: kind/bug 🐞, Qv2 🔝, flavour/vite-plugin, bug/1-hard-to-reproduce, bug/1-repro-available, area/ui, area/extras, area/plugins, area/style

**Comment by HTY-DBY** [comment] 2025-01-10 15:54
Yes, you need to add one@, like:
import {fileURLToPath, URL} from 'node:url';
import legacy from '@vitejs/plugin-legacy';
import {defineConfig} from 'vite';
import vue from '@vitejs/plugin-vue';
import {quasar, transformAssetUrls} from '@quasar/vite-plugin';

export default defineConfig({
    plugins: [
        vue({
            template: {transformAssetUrls},
        }),
        legacy({
            targets: ['ie>=11'],
            additionalLegacyPolyfills: ['regenerator-runtime/runtime'],
        }),
        quasar({
            sassVariables: '@/css/quasar.sass'
        })

    ],
    resolve: {
        alias: {
            '@': fileURLToPath(new URL('./src', import.meta.url)),
        },
    },

    base: './',
});
