### ISSUE TITLE
[request] An input mask for Quasar

### ISSUE THREAD

**Issue by Underzzoo** [quasarframework/quasar#635] opened 2017-06-22 03:49 UTC
Hello!

I'm trying to use an plugin for input mask  [v-mask](https://github.com/probil/v-mask) in Quasar 0.14 Beta.

But, using with the component q-input, the mask not work.
What i need to do for fix this is create an normal input and hide.

If possible Quasar has some kind of mask plugin natively or an sugested plugin like vuelidate ?

Thanks @rstoenescu for these amazing framework.

**Comment by smolinari** [comment] 2017-06-22 05:54
The [q-input component](https://github.com/quasarframework/quasar/tree/dev/src/components/input) has a pattern prop, which isn't documented (yet), as it only currently checks for numbers. That would be the start to an input mask functionality and I believe that is the plan to have at some point.  

Other than that, there is nothing to stop you from using v-model and placeholder to build your own. 

If you want validation, vuelidate is recommended to use with Quasar.

Also, please use the [forum](http://forum.quasar-framework.org/) or the [chat](https://gitter.im/quasarframework/Lobby) for questions. Thanks for your understanding! 😄 

Scott

**Comment by rstoenescu** [comment] 2017-06-22 10:25
Hi,

Yes, such feature will be added.
Closing this as it's a duplicate of https://github.com/quasarframework/quasar/issues/462

-Razvan.

**Closed by rstoenescu** 2017-06-22 10:25 UTC
