### ISSUE TITLE
autocomplete input inside q-popover having issue

### ISSUE THREAD

**Issue by Mohanrau** [quasarframework/quasar#1274] opened 2017-12-11 10:36 UTC
### Software version

Quasar:0.14.7
OS:
Node:
NPM:
Browsers:chrome
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
Placing autocomplete input inside q-popover makes parent popover disappear after autocomplete list pop up.

### What were you expecting?
screens with multiple popover

### What steps did you take, to get the error?
```
<q-popover v-model="toggleNewOrderPopover" anchor="bottom right" self="top right" fit>
        <div class="row">
                <div class="col-12 pd-20">
                        <q-toggle v-model="downline" label="Order for downline"/>
                          <div class="without-downline" v-if="!downline">
                                <q-search v-model="terms"
                                                      placeholder="Search IBO ID / Name / IC"
                                                      :after="[{icon: 'chevron_right', handler () {}}]"
                                                      @change="reset">
                                                <q-autocomplete @search="search" @selected="selected"/>
                              </q-search>
                            </div>
                       </div>
             </div>
</q-popover>
```

![popoverr-1](https://user-images.githubusercontent.com/1044660/33827104-1d91fa5a-dea2-11e7-915c-d9a362288dd3.PNG)
![popoverr-2](https://user-images.githubusercontent.com/1044660/33827105-1dd5cbae-dea2-11e7-8b35-751f89a7b034.PNG)
![popoverr-3](https://user-images.githubusercontent.com/1044660/33827106-1e07b128-dea2-11e7-9cf2-78ba125fba70.PNG)

**Comment by Mohanrau** [comment] 2017-12-19 07:23
Hi guys any updates on this issue. what about the pull request going to be merged or not.

**Comment by rstoenescu** [comment] 2018-02-02 17:58
Duplicate of https://github.com/quasarframework/quasar/issues/1114

**Closed by rstoenescu** 2018-02-02 17:58 UTC
