### ISSUE TITLE
can quasar add global dark mode?

### ISSUE THREAD

**Issue by nunuqq1** [quasarframework/quasar#4231] opened 2019-05-28 10:06 UTC
https://docs.docker.com/get-started/part4/

there's a dark mode switch on the right side of docker doc site, which is very amazing, and comfortable.

**Comment by rstoenescu** [comment] 2019-05-28 10:14
Duplicate of https://github.com/quasarframework/quasar/issues/3968

**Closed by rstoenescu** 2019-05-28 10:14 UTC
