### ISSUE TITLE
SSR: DOM tree rehydratation warning when using <q-input>

### ISSUE THREAD

**Issue by jigarzon** [quasarframework/quasar#4267] opened 2019-05-31 12:34 UTC
NPM - 6.9.0
  yarn - 1.16.0
  @quasar/cli - 1.0.0-beta.7
  cordova - Not installed

### JsFiddle

Cannot include JsFiddle because only happens on SSR mode. This happens on this piece of code:
```
<q-input v-model="search">
</q-input>
```
If I remove the `q-input`, the warning disappears and no full client render happens

### What did you get as the error?
```
[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.
```

**Comment by jigarzon** [comment] 2019-05-31 13:46
This is a high priority issue in my opinion, because:
1) The `q-input` is one of the most used components
2) It invalidates completely the benefits of `SSR`

**Comment by nothingismagick** [comment] 2019-05-31 14:05
<q-input v-model="search>

Seems like there is a missing quote in there... no? Or is there a larger
issue here? Can you please post the results of

quasar info

>

**Comment by jigarzon** [comment] 2019-05-31 14:20
@nothingismagick it was a typo in the example. I tested extensively before creating this issue

**Comment by nothingismagick** [comment] 2019-05-31 14:28
Can you please post the results of

quasar info

because at least your @quasar/cli is out of date

>

**Comment by jigarzon** [comment] 2019-05-31 14:36
@nothingismagick Thanks a lot, after executing `npm install --global @quasar/cli` and updating to `@quasar/cli - 1.0.0-rc.2` the error disappeared. Never suspected that it was an issue of quasar cli, very strange don't you think?

My `quasar info` now is:
```

**Comment by nothingismagick** [comment] 2019-05-31 14:50
Yes, its strange - but we've other problems with the transition to RC, so its better for now to stick with bleeding edge.

If it's resolved, please close the issue.

**Comment by m00nk** [comment] 2019-07-31 17:13
The issue is still present.

Info:
```
Operating System - Linux(4.15.0-34-generic) - linux/x64
NodeJs - 12.7.0

Global packages
  NPM - 6.10.0
  yarn - 1.17.3
  @quasar/cli - 1.0.0
  cordova - Not installed

Important local packages
  quasar - 1.0.5 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 1.0.4 -- Quasar Framework local CLI
  @quasar/extras - 1.2.0 -- Quasar Framework fonts, icons and animations
  vue - 2.6.10 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.7 -- Official router for Vue.js 2
  vuex - 3.1.1 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.5.5 -- Babel compiler core.
  webpack - 4.35.3 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 3.7.2 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.3.1 -- A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

Quasar App Extensions
  *None installed*
```

**Comment by pdanpdan** [comment] 2019-07-31 17:33
Can you please show the code (the specific QInput line at least)?

**Comment by m00nk** [comment] 2019-07-31 19:13
@pdanpdan I have done the full rebuilding of the project and issue is gone. Looks like the hot reloading process works not very fine and the described issue appears if I add to the project some new components without full rebuilding. I will be watching and will inform you if the issue appears. Thank you.

**Comment by pdanpdan** [comment] 2019-07-31 19:16
Then I will close this issue. If it happens again please open a new one and specify that it's related to bad SSR hydration in HMR.

Thank you

**Closed by pdanpdan** 2019-07-31 19:16 UTC
