### ISSUE TITLE
QInput hint can bleed into other elements

### ISSUE THREAD

**Issue by dlbass** [quasarframework/quasar#8561] opened 2021-03-01 18:06 UTC
**Describe the bug**
When a user provides an absurdly long string for use in the QInput hint, it can bleed into other elements.

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/Lxzbm47t/1/

**To Reproduce**
1. Create a QInput with a very long hint.
2. Place another element after it, such as a second input, or a button.

**Expected behavior**
The QField should grow to contain the hint text. I've been unable to fix it in Chrome Dev Tools, but the boss feels like these stupidly long hint texts aren't stupid...

**Screenshots**
![image](https://user-images.githubusercontent.com/4282090/109538750-131ff580-7a86-11eb-9ee0-b16a0ddc5d98.png)

**Platform (please complete the following information):**
Quasar Version: 1.14.5
@quasar/app Version: 2.1.8
Quasar mode:
  [x] SPA
  [x] Capacitor
Tested on:
  [x] SPA
  [x] Capacitor
OS: Windows 10, Mac OS, Android, iOS
Node: 14.4.0
NPM: 6.14.5
Browsers: Chrome 88
iOS: 14.4
Android: 11

**Comment by pdanpdan** [comment] 2021-03-01 18:22
Duplicate of https://github.com/quasarframework/quasar/issues/4142

**Closed by pdanpdan** 2021-03-01 18:22 UTC
Labels: :beetle: bug, Qv1
