### ISSUE TITLE
[BUG] date utils not working as expected on mobile browsers

### ISSUE THREAD

**Issue by kipouras** [quasarframework/quasar#2748] opened 2018-11-11 06:37 UTC
### Software version

quasar-cli: 0.17.11	
quasar-framework: 0.17.9	
OS: Linx, OSX, Windows 10
Node: 8.10.0
NPM: 3.5.2
Browsers: Chrome, Safari, Firefox
iOS: Chrome, Safary

### JsFiddle (for Quasar v0.15+ only)

https://jsfiddle.net/9ecq68y7/8/

### What did you get as the error?
The date utilities give out a NaN value on mobile browsers.

### What were you expecting?
The date utilities should give a valid value on mobile browsers. 

### What steps did you take, to get the error?
The date utilities work fine on every desktop browser i have used (Safari, Firefox, Chrome), but whenever I access my app from a mobile browser (Safari or Chrome on IOS) I get a NaN value as the value of  the date utilities result.

**Comment by smolinari** [comment] 2018-11-11 09:11
Related discussion on the forum: https://forum.quasar-framework.org/topic/2888/date-utils-on-mobile-browsers

Scott

**Comment by kipouras** [comment] 2018-11-11 11:40
I’ve started that one too...

**Comment by fansanelli** [comment] 2018-12-03 16:31
I confirm this issue is present on iPhone 5/6/6S using Safari

**Comment by fansanelli** [comment] 2018-12-05 16:04
Hello @kipouras
I tracked the problem:
https://github.com/fansanelli/quasar/tree/fix-iOS-IE-date-format
can you please test it?
Cheers,
Francesco

**Comment by fansanelli** [comment] 2018-12-06 08:41
Hello,
the Date object can be created with this options:
new Date();
new Date(value);
new Date(dateString);
new Date(year, monthIndex [, day [, hours [, minutes [, seconds [, milliseconds]]]]]);
(from: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) 
for the dateString both: "2013-03-01T01:10:00" and "December 17, 1995 03:24:00" are valid.
On almost every modern browser (read not IE and iOS/Safari) the "T" is not mandatory.
I tested formatDate() against:
- 2013-03-01T01:10:00
- 2013-03-01 01:10:00
- new Date()
- 98534954
and it works the same on every browser.
Please let me know if it is a reasonable approach @smolinari and if fixes your problem too @kipouras :
https://github.com/quasarframework/quasar/pull/2838/files
I hope it can be merged before the next point release.
Thanks
Francesco

**Comment by smolinari** [comment] 2018-12-06 11:49
@rstoenescu or @pdanpdan would be the ones to make the decision on your approach. :smiley: 

Scott

**Comment by fansanelli** [comment] 2018-12-06 12:35
It is fixed for me. Hope to hear if it is fixed also for someone else.

**Comment by kipouras** [comment] 2018-12-07 05:58
I've changed my date.js file to reflect the changes from this pull request. If the date is formatted as listed above, everything works as expected. 

From MySQL documentation: 
**_A DATETIME or TIMESTAMP value can include a trailing fractional seconds part in up to microseconds (6 digits) precision.....the range for DATETIME values is '1000-01-01 00:00:00.000000' to '9999-12-31 23:59:59.999999'_** 

When trying to use formatDate() function on a date with 6-digit microseconds precision the error is still there.

Since I do not own an Android device, I can not use Chrome Remote debugging to check for errors while the dateFormat() function is running. I might be able to try it out during the weekend.

My approach on dealing with this bug is to remove the 6-digit millisecond precision from the date data through my php backend before sending it to my frontend for further manipulation. It does not affect my current project, but it might affect other projects that need microsecond precision.

**Comment by fansanelli** [comment] 2018-12-07 07:51
Hello @kipouras 
the problem is that old browsers can reach max 3 precision... I pushed a new version..
I did a test on iOS and Android an it works for me.
Thanks
Francesco

**Comment by kipouras** [comment] 2018-12-07 09:47
Hello @fansanelli,
I've gone through the changes on the pull request. I've noticed that the buildDateVal() function verifies the date string based on reMySQLDateTimeStr regular expression. A date string with 6-digit microsecond precision is being accepted and returned as  a substring containing the first 25 characters (0,24). On a date string like **2018-10-30 09:41:32.123456** it returns a date with a **5-digit** microsecond precision. That is **2018-10-30 09:41:32.12345**. In order for older browsers and iOS devices to correctly use the dateUtils without getting the NaN value as a result, the date string should be **2018-10-30 09:41:32.123** (3-digit precision). To get that, the command creating the substring in the buildDateVal() function should be changed from d.substring(0, 24).replace(' ', 'T')   to   d.substring(0, **22**).replace(' ', 'T'). 

I've changed the value on my local build from 24 to 22 and it seems to fix everything. Tried it on iOS Chrome and Safari.

I hope this will do it.

**Comment by fansanelli** [comment] 2018-12-07 10:31
I think you are half right.. I didn't do my homework and 24 returned one extra value...
Can you please test with 23 instead?
I'll force push a change in a second after you reply

**Comment by kipouras** [comment] 2018-12-07 10:43
23 characters isn't from 0 to 22??? **2018-10-30 09:41:32.123** is 23 characters right? or am I counting wrong?

**Comment by fansanelli** [comment] 2018-12-07 10:46
try in your console:
var d = '2018-10-30 09:41:32.123'
d.substring(0, 22).replace(' ', 'T')
"2018-10-30T09:41:32.12"

**Comment by kipouras** [comment] 2018-12-07 11:11
You are right. I’ll test it in a few minutes and let you know

**Comment by kipouras** [comment] 2018-12-07 11:58
works file with substring(0,23)

**Comment by fansanelli** [comment] 2018-12-07 12:41
Pushed. thanks @kipouras

**Comment by fansanelli** [comment] 2018-12-09 20:30
@kipouras you can now close this issue. The pr got merged:
https://github.com/quasarframework/quasar/commit/c2f99ca9f14e5560787ccb84b8e1a53a016bddcf

**Closed** 2018-12-09 20:50 UTC
