### ISSUE TITLE
[Request] Select all for QDataTable

### ISSUE THREAD

**Issue by lyquocnam** [quasarframework/quasar#679] opened 2017-07-01 08:56 UTC
i see currently, quasar is beta, but this still missing. Author, please add more features to QDataTable, this really need when multi select on many records.

**Comment by mstaack** [comment] 2017-07-01 09:42
datatable will  be redone after 0.14 is done... so please wait

**Comment by rstoenescu** [comment] 2017-07-01 11:45
This will get done. As mstaack said, please be patient.
Closing as it is duplicate of https://github.com/quasarframework/quasar/issues/560

**Closed by rstoenescu** 2017-07-01 11:45 UTC

**Comment by lyquocnam** [comment] 2017-07-01 14:48
thanks so much @mstaack @rstoenescu
