### ISSUE TITLE
q-layout bug report

### ISSUE THREAD

**Issue by soluty** [quasarframework/quasar#2509] opened 2018-09-02 00:37 UTC
### Software version

Quasar: 0.17.11
OS: Darwin(16.6.0) - darwin/x64
Node:8.9.4
NPM:5.6.0
Browsers: chrome
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
can't scroll page in mobile 
### What were you expecting?
can scroll
### What steps did you take, to get the error?
when i  use layout in mobile，or in chrome mock mobile， i use a long page to scroll，if i click menu  to show left drawer，it will add a class q-body-prevent-scroll in <body> ，but if i hide the drawer the q-body-prevent-scroll not remove，so i cant scroll my page now.

**Comment by pdanpdan** [comment] 2018-09-02 08:10
Duplicate of #2499. Already fixed.

**Comment by rstoenescu** [comment] 2018-09-02 08:56
Fixed in 0.17.12

**Closed by rstoenescu** 2018-09-02 08:56 UTC
