### ISSUE TITLE
White Screen of death in iOS 10.x / Quasar 0.17.4

### ISSUE THREAD

**Issue by steveclarke** [quasarframework/quasar#2359] opened 2018-07-31 16:29 UTC
Compiling a Cordova app for iOS 10.x using Quasar 0.17.4 results in a white screen after the initial splash screen. The Quasar app doesn't initialize.

I discovered this shortly after I upgraded my app from 0.16 to 0.17. Because I hadn't checked on my iOS 10.x device in a while I couldn't be sure it was related to the 0.17 upgrade. To confirm, I created a stock Quasar app and confirmed that the same issue exists with a fresh install.

Steps to repro:

* Install Quasar 0.17.4
* Create a new project with default settings
* Add Cordova to the project `npx quasar mode -a cordova`
* `cd src-cordova`
* `cordova platform add ios`
* Ensure you have iOS simulators installed for 11.4 and 10.3. (I found that the iPhone 7 simulator was the only one that I could set up with both 10.x and 11.x. iPhone 8/X only seem to allow 11.x in the simulator.)
* Test with iOS 11.4: `npx quasar dev --mode cordova --target ios --theme ios --emulator 'iPhone-7-Plus, 11.4`. This should show the default Quasar app first screen.

![simulator screen shot - iphone 7 plus - 2018-07-31 at 13 49 30](https://user-images.githubusercontent.com/1305/43472896-2cef3566-94c9-11e8-9212-4c6ff90188c3.png)

* Test with iOS 10.3: `npx quasar dev --mode cordova --target ios --theme ios --emulator 'iPhone-7-Plus, 10.3'`. This should show just a blank white screen.

![simulator screen shot - iphone 7 plus - 2018-07-31 at 13 50 55](https://user-images.githubusercontent.com/1305/43472903-303f3d2e-94c9-11e8-8bd4-04a29863fc94.png)

### Software version
Quasar CLI 0.17.5

```
Operating System                Darwin(17.7.0) - darwin/x64
NodeJs                          10.6.0

Global packages
  NPM                           6.2.0
  yarn                          1.7.0
  quasar-cli                    0.17.5
  vue-cli                       2.9.6
  cordova                       8.0.0

Important local packages
  quasar-cli                    0.17.5  (Quasar Framework CLI)
  quasar-framework              0.17.4  (Build responsive websites, PWAs, hybrid mobile apps and Electron apps, all simultaneously using same codebase)
  quasar-extras                 2.0.4   (Quasar Framework fonts, icons and animations)
  vue                           2.5.16  (Reactive, component-oriented view layer for modern web interfaces.)
  vue-router                    3.0.1   (Official router for Vue.js 2)
  vuex                          3.0.1   (state management for Vue.js)
  electron                      Not installed
  electron-packager             Not installed
  electron-builder              Not installed
  @babel/core                   7.0.0-beta.53   (Babel compiler core.)
  webpack                       4.16.3  (Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.)
  webpack-dev-server            3.1.5   (Serves a webpack app. Updates the browser on changes.)
  workbox-webpack-plugin        3.4.1   (A plugin for your Webpack build process, helping you generate a manifest of local files that workbox-sw should precache.)
  register-service-worker       1.4.1   (Script for registering service worker, with hooks)

Networking
  Host                          mac.local
  en0                           192.168.77.7
```

**Comment by rstoenescu** [comment] 2018-07-31 16:42
This is duplicate of https://github.com/quasarframework/quasar-cli/issues/160
-- Should have been reported to Quasar CLI repo as it's a CLI issue.

**Closed by rstoenescu** 2018-07-31 16:42 UTC
