### ISSUE TITLE
provide server answer in finish callback from Uploader

### ISSUE THREAD

**Issue by delueg** [quasarframework/quasar#404] opened 2017-02-19 19:46 UTC
I would need the possibility to get server answer of the uploader component.

I think the best way would be to change

this.$emit('finish')
to
this.$emit('finish', this.response) //so finish already there and can be used as callback with the response

and 

if (xhr.readyState < 4) {
      this.response = xhr. responseText
      return
}

i am not sure if this is the right way..

**Comment by rstoenescu** [comment] 2017-02-19 19:57
Duplicate of #384 .

`finish` event is triggered after ALL uploads are done (there can be multiple).

**Closed by rstoenescu** 2017-02-19 19:57 UTC

**Comment by delueg** [comment] 2017-02-19 20:15
Ah ok I didn't think about that. Mhh what would be your suggestion to have the Server answers for each Upload?

**Comment by rstoenescu** [comment] 2017-02-19 20:22
Through an `@upload` event. First param should be file, then xhr.
