### ISSUE TITLE
quasar new store is creating vuex stores instead of pinia stores

### ISSUE THREAD

**Issue by Dekay21** [quasarframework/quasar#14016] opened 2022-07-22 06:27 UTC
### What happened?

After creating a new Quasar App (```npm init quasar```) with pinia as state management, using ```quasar new store <storeName>``` a new vuex store is created instead of a pinia store.
Additionally the counterStore created at project initialization with ```npm init quasar``` is not usable.

### What did you expect to happen?

```quasar new store <storeName>``` should create a pinia store when used in a project created with pinia as state management

### Reproduction URL

Can't provide a URL

### How to reproduce?

1. ```npm init quasar```
2. Choose ```App with Quasar Cli```
3. Choose ```Quasar v2```
4. Choose ```Typescript```
5. Choose ```Quasar App CLI with Vite``` (But also tried with webpack but also didn't work)
6. Choose Composition API
7. Add ```State Management (Pinia)```
8. ```quasar new store <storeName>``` creates a vuex store instead of a pinia sttore

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Quasar info output

```Shell
Operating System - Windows_NT(10.0.19041) - win32/x64
NodeJs - 18.4.0

Global packages
  NPM - 8.12.1
  yarn - Not installed
  @quasar/cli - 1.3.2
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.7.5 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.0.5 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.15.0 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.37 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.1.2
  pinia - 2.0.16 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 2.9.13 -- Native-ESM powered web dev build tool
  eslint - 8.20.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*
```

### Relevant log output

```Shell
>quasar new store mainStore

App • Generated src/store

App • Generated store: src\store\mainStore
App • Make sure to reference it in src/store/index.js
```

**Comment by rowild** [comment] 2022-07-22 07:53
Question to @github-actions : Why do you need a reproduction URL in this case? After all it is about the installation process that has to be checked, right?

Anyway, I ran through the above provided install steps, but I actually DO get a pinia store and therefore CANNOT confirm the issue. Also running "quasar dev" opens a site where I can click on various points in a list, and they do increment the counter successfully (even thought the example itself does not really make sense).

![Bildschirmfoto 2022-07-22 um 09 49 27](https://user-images.githubusercontent.com/213803/180391182-ed541adb-be7f-4c3e-993a-cbd43232e8bc.png)

![Bildschirmfoto 2022-07-22 um 09 49 19](https://user-images.githubusercontent.com/213803/180391169-5bf5e692-236d-4a31-8a50-82c6bcb581e9.png)

**Comment by Dekay21** [comment] 2022-07-22 09:05
By default the example components do not use the store (atleast when i create a new project)
![image](https://user-images.githubusercontent.com/43781572/180403233-a7a6bbf1-72bd-4d15-83f6-8dbfb70ee38b.png)

And when i try to use the store in a component i get the following error
![image](https://user-images.githubusercontent.com/43781572/180403828-e669c4d6-b348-4569-acd9-7aa92dd2c963.png)

I actually found a work-around for myself by adding this in ```quasar.config.js```
```javascript
sourceFiles: {
 store: 'src/stores/index'
}
```

If this is not reproducible then i am not sure why it always does that when i try to create a new project

**Comment by rowild** [comment] 2022-07-22 09:37
Hmmm... just to make sure: you did import the store?
`import { useCounterStore } from 'stores/example-store'`

Googling the error message leads to results like 
` it's most likely because you're calling useAuthStore() from outside a component's setup, and it's called before Pinia is setup.`

E.g.: https://github.com/vuejs/pinia/discussions/971

Anything like that going on in your code?

**Comment by Dekay21** [comment] 2022-07-22 09:45
Yes i am importing the store correctly and inside a component.

It's just that when i don't do the work-around the pinia plugin doesn't get registered by app.use()
I see the auto-generated .quasar/app.js change to use the store when i do the work around, it's just weird it doesn't do it by default for me when selecting pinia as state management plugin

**Comment by rowild** [comment] 2022-07-22 09:53
And this happens with EVERY new project that you create?

**Comment by Dekay21** [comment] 2022-07-22 10:12
Yes it happens on every project i created.

But I just tested this on a different computer and i can't reproduce it myself.
It seems my quasar/cli installation is faulty on the other computer or atleast some part of it, I will try to reinstall it completely to see if it works, but either way this problem seems to be resolved.

Thank you for taking your time.

**Comment by rowild** [comment] 2022-07-22 10:22
I think you can close the issue.

**Closed as completed** 2022-07-22 10:23 UTC
Labels: kind/bug 🐞, bug/0-needs-info, Qv2 🔝, area/cli, flavour/quasar-cli-vite

**Comment by tornadosk** [comment] 2022-10-07 02:23
I can confirm that this issue still exists, just installed new quasar cli and created new project, no much coded added rather then initial setup, which was regular spa with pinia store, options selected was: npm, web-pack, and pinia with axios.

**Comment by tornadosk** [comment] 2022-10-07 02:27
And work around with adding sourceFiles: {
 store: 'src/stores/index'
} into quasar.config works for me too. Thank you @Dekay21

**Comment by Codebreaker101** [comment] 2022-12-16 08:06
If pinia is installed (and vuex is not) by default quasar will try to find pinia in `src/stores/index.(js|ts)`. Setting `sourceFiles.store` option overrides that behavior. 

Solution is to rename the `src/store` directory to `src/stores` for those who are upgrading from older verions. (Don't forget to rerun `quasar dev`)

**Comment by flaviodonze** [comment] 2023-03-14 15:00
Make sure to not only remove the `vuex` entry in the **package.json** but actually uninstall it.<br>
In the project folder, call:

**yarn: uninstall vuex**

    yarn remove vuex

**npm: uninstall vuex**

    npm uninstall vuex

This will also remove it from the **package.json**.<br>
After uninstalling I could also remove the `sourceFiles` entry in **quasar.config.js**.

Result in console:

    quasar new store demo
    App • Generated store: src\stores\demo.js

**Comment by VincenzoZizza** [comment] 2023-03-29 11:31
I had the same problem and solved it by deleting all node_module folders in my pc with the `npx npkill` tool.

this solved the problem for me

**Comment by sargilla** [comment] 2024-01-08 18:36
I have the same issue, I'm delete the node_modules folder, make yarn upgrade and :
λ quasar new store lpm

 App • Generated src/store

 App • Generated store: src\store\lpm
 App • Make sure to reference it in src/store/index.js


λ quasar info

Operating System - Windows_NT(10.0.22621) - win32/x64
NodeJs - 18.14.1

Global packages
  NPM - 9.3.1
  yarn - 1.22.19
  @quasar/cli - 2.3.0
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.14.2 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.7.1 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.16.9 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.4.6 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.2.5
  pinia - 2.1.7 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 2.9.16 -- Native-ESM powered web dev build tool
  eslint - 8.56.0 -- An AST-based pattern checker for JavaScript.
  electron - 21.4.4 -- Build cross platform desktop apps with JavaScript, HTML, and CSS
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

how can switch to stores with pinia?
regards
Santiago

**Comment by Codebreaker101** [comment] 2024-01-08 18:41
@sargilla I'll quote myself here: 

> If pinia is installed (and vuex is not) by default quasar will try to find pinia in `src/stores/index.(js|ts)`. Setting `sourceFiles.store` option overrides that behavior.
> 
> Solution is to rename the `src/store` directory to `src/stores` for those who are upgrading from older verions. (Don't forget to rerun `quasar dev`)

**Comment by sargilla** [comment] 2024-01-08 18:55
If I do that, quasar dev does not put the store in the .quasar/app.js file:

`
import { Quasar } from 'quasar'
import { markRaw } from 'vue'
import RootComponent from 'app/src/App.vue'


import createRouter from 'app/src/router/index'





export default async function (createAppFn, quasarUserOptions) {
  // Create the app instance.
  // Here we inject into it the Quasar UI, the router & possibly the store.
  const app = createAppFn(RootComponent)

  
  app.config.performance = true
  

  app.use(Quasar, quasarUserOptions)

  

  

  const router = markRaw(
    typeof createRouter === 'function'
      ? await createRouter({})
      : createRouter
  )

  

  // Expose the app, the router and the store.
  // Note that we are not mounting the app here, since bootstrapping will be
  // different depending on whether we are in a browser or on the server.
  return {
    app,
    
    router
  }
}



`

**Comment by Codebreaker101** [comment] 2024-01-13 16:58
I might be wrong but this looks like an app.js from quasar v1. Create a new quasar project and copy app.js from there into your project.
