### ISSUE TITLE
QSelect multiple shows selected as value when using use-input

### ISSUE THREAD

**Issue by Whiskeee** [quasarframework/quasar#4920] opened 2019-08-19 10:40 UTC
**Describe the bug**
When using a `use-input` on a q-select with the `multiple` attribute, when beginning to type to filter results previously selected options will change from displaying their labels to their values.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/LiamHolmes1508/pen/vYBXEwQ

**To Reproduce**
1. Select an option in a multiple q-select that is also using use-input for filtering
2. start filtering after making a selection.

**Expected behavior**
The selected option(s) should continue to display their intended label, like they do when not filtering.

**Screenshots**
![qSelectValueIssue](https://user-images.githubusercontent.com/5392255/63258961-1f15df00-c275-11e9-956a-8ec244526fdc.gif)

**Comment by pdanpdan** [comment] 2019-08-24 13:37
If you use `map-options` you have to take care to provide QSelect a list of options that allows it to render the selected options.

Duplicate of (please check the second one for how you can solve it):
https://github.com/quasarframework/quasar/issues/4288
https://github.com/quasarframework/quasar/issues/4250

**Closed by pdanpdan** 2019-08-24 13:37 UTC
Labels: bug

**Comment by rstoenescu** [comment] 2019-12-04 15:01
Fix will be available in "quasar" v1.5.5
