### ISSUE TITLE
🐛 [BUG] GitHub Actions False Positive on jsfiddle reproduction url

### ISSUE THREAD

**Issue by hinogi** [quasarframework/quasar#12612] opened 2022-02-27 00:48 UTC
### What happened?

Adding a valid jsfiddle url reports as invalid
https://jsfiddle.net/hfnrvo61/
![image](https://user-images.githubusercontent.com/4602609/155863699-25d638e7-f0fb-4f17-9072-d93f0d331fa1.png)

### What did you expect to happen?

Added a valid reproduction url and github action report it as invalid

### Reproduction URL

https://jsfiddle.net/hfnrvo61/

### How to reproduce?

Add https://jsfiddle.net/hfnrvo61/ as reproduction url in bug report

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app)

### Platforms/Browsers

Firefox

**Comment by MilosPaunovic** [comment] 2022-02-28 19:18
Hey Yusuf, sorry for barging in on an issue you've assigned to yourself, but I was curious about the topic so I wanted to investigate a bit more.

Anyway, what seems to be the problem here is the Regex which parses the pathname:
[https://github.com/quasarframework/quasar/blob/dev/.github/workflows/process-created-issue.yml#L114](https://github.com/quasarframework/quasar/blob/dev/.github/workflows/process-created-issue.yml#L114)

Cause Fiddle links could be formed like this `https://jsfiddle.net/hfnrvo61/` but, as well, like this `https://jsfiddle.net/Alice3173/txfcwenx/`.

Simplifying Regex for Fiddle links to `/^\/.+\//` seems to have resolved the issue.

I might be wrong, so another set of eyes is always a good thing 🙂

**Comment by yusufkandemir** [comment] 2022-02-28 19:26
Hey Milos, no problem at all. The problem is exactly that. I wasn't aware of this one-level URL form, and I aimed for being highly precise to avoid more possible invalid URLs. But, now that we noticed that it's a legit thing, we should adjust the regex to respect that. Thanks for the extra pair of eyes.

So, since you also noticed that and proposed a solution, why don't you make the PR? 🙂

**Comment by MilosPaunovic** [comment] 2022-02-28 19:46
Sure thing 🙂

**Closed as completed** 2022-02-28 20:39 UTC
Labels: kind/bug 🐞, bug/0-needs-info, Qv2 🔝, flavour/quasar-cli-webpack, area/cli
