### ISSUE TITLE
[Bug] QDatetime Year default view doesn't work

### ISSUE THREAD

**Issue by VitalyEmelyanov** [quasarframework/quasar#2207] opened 2018-06-25 09:36 UTC
### Software version
Quasar: v0.16
OS: macOS 10.13.4 (High Sierra)
Browsers: Chrome 65

**This issue was mentioned in #1929 but is still reproduced at v0.16** 

### What steps did you take?
1. Click on datetime input with default view set to **year**
2. Click again to hide the calendar (do not select any date, just click outside the calendar)
3. Click outside the datetime field (to remove focus) 
4. Repeat

**Result:** You'll get month view first time. After few clicks you'll finally get year view
Same problem is with **month** 

### What were you expecting?
The calendar should always display year view when opened

### Demo
**JSFiddle** https://jsfiddle.net/7u6soams/10/

![jun-25-2018 12-31-41](https://user-images.githubusercontent.com/15330670/41842536-bfa701da-7873-11e8-9722-2c2edf9d482d.gif)

**Comment by rstoenescu** [comment] 2018-06-25 10:31
Hi,

The initial issue was caused by something else which got fixed.
The cause now is a side-effect of some recent changes. Already reported and fixed in next Quasar version.

**Closed by rstoenescu** 2018-06-25 10:31 UTC
