### ISSUE TITLE
Any plan that tree support drag and drop

### ISSUE THREAD

**Issue by fyeeme** [quasarframework/quasar#12094] opened 2022-01-18 14:55 UTC
### What happened?

Currently tree does not supported  drag and drop

### What did you expect to happen?

Offically supported  drag and drop

### Reproduction URL

https://codepen.io/fyeeme/pen/rNGbzoJ?editors=101

### How to reproduce?

1. click the tree and try to drag and drop 

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

**Comment by fyeeme** [comment] 2022-01-18 14:57
link has been updated

**Comment by pdanpdan** [comment] 2022-01-18 14:57
duplicate of #6044, #7299, #5890, #6959

**Closed as completed by pdanpdan** 2022-01-18 14:57 UTC
Labels: kind/bug 🐞, bug/0-needs-info, Qv2 🔝, flavour/vite-plugin, area/components
