### ISSUE TITLE
Error Messages Not Rendering in Error Slot of Form Components

### ISSUE THREAD

**Issue by ndianabasi** [quasarframework/quasar#8543] opened 2021-02-25 19:54 UTC
**Describe the bug**
Error messages set in the error slot of form components such as QInput are not rendering. Even when there is a error as triggered by the prop ":error=true" and there is a content in the error slot of the component. 

This bug exists even in the documentation site. You can see here: https://next.quasar.dev/vue-components/input#example--slot-for-error-message

**Codepen/jsFiddle/Codesandbox (required)**
I can't get Vuelidate for Vue 3 set up on Codepen.

**To Reproduce**
1. Setup q-input as follows:
```
<q-input
  filled
  clearable
  bottom-slots
  v-model="v$.email_address.$model"
  label="Email Address"
  :dense="dense"
  class="q-mb-md"
  type="email"
  :error="v$.email_address.$error"
>
  <template #before>
    <q-icon name="email" />
  </template>

  <template v-slot:error
    ><small
      v-for="(error, index) in v$.email_address.$errors"
      :key="'email_addresses_error_' + index"
      >{{ error.$message }}</small
    ></template
  >
</q-input>
```

**Expected behavior**
Error message should appear in v-slot:error. 

**Screenshots**
![screenshot-next quasar dev-2021 02 25-20_46_09](https://user-images.githubusercontent.com/13512173/109208612-cea50900-77aa-11eb-9cf8-00d062262bb7.png)
![screenshot-localhost_8080-2021 02 25-20_46_38](https://user-images.githubusercontent.com/13512173/109208628-d2d12680-77aa-11eb-867d-fc8232cdc949.png)

**Platform (please complete the following information):**
Quasar Version: 3.0.0-beta.1
@quasar/app Version:
Quasar mode:
  [ x] SPA
  [ ] SSR
  [ ] PWA
  [ ] Electron
  [ ] Cordova
  [ ] Capacitor
  [ ] BEX
Tested on:
  [ x] SPA
  [ ] SSR
  [ ] PWA
  [ ] Electron
  [ ] Cordova
  [ ] Capacitor
  [ ] BEX
OS:
Node: v14.15.4
NPM: 7.5.4
Yarn: 1.22.5
Browsers: Chrome Version 88.0.4324.182 (Official Build) (64-bit)
iOS: 
Android:
Electron:

**Additional context**

**Comment by rstoenescu** [comment] 2021-02-25 21:07
Duplicate of #8522
Fix already in. Will be available in Quasar v2.0.0-beta.8

**Closed by rstoenescu** 2021-02-25 21:07 UTC
Labels: :beetle: bug, 🔝 Qv2
