### ISSUE TITLE
QTable - rows per page option dropdown 'snaps' on first time opening

### ISSUE THREAD

**Issue by bartduisters** [quasarframework/quasar#11862] opened 2022-01-02 16:20 UTC
**Describe the bug**
When clicking on the 'rows per page option' of a QTable, the popup initially renders 'too low', then it 'snaps' to the correct covered position.

**Codepen/jsFiddle/Codesandbox (required or your issue may be closed)**
This can be reproduce din any of the provided js fiddles on the documentation page: https://quasar.dev/vue-components/table#introduction

**To Reproduce**
1. Go to https://quasar.dev/vue-components/table#introduction
2. Click on any of the 'rows per page' options in the footer

**Expected behavior**
The rows per page dropdown to render in the correct position without it 'snapping'.

**Screenshots**
A video with the 'snapping' is attached.

https://user-images.githubusercontent.com/43420049/147882016-53babd16-88cb-4459-a22e-825382530f76.mp4

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version: 3.0.0

Tested on: Current live documentation. And locally with the version above.

**Comment by pdanpdan** [comment] 2022-01-04 01:36
Duplicate of https://github.com/quasarframework/quasar/issues/11247

**Closed as completed by pdanpdan** 2022-01-04 01:36 UTC
