### ISSUE TITLE
Allow manual input for "Datetime Input" component

### ISSUE THREAD

**Issue by chaitanya-plylabs** [quasarframework/quasar#2423] opened 2018-08-15 05:42 UTC
Currently, there is no provision to enter a date manually, have to incorporate the same.

**Comment by smolinari** [comment] 2018-08-15 06:18
Do you mean like this?

https://quasar-framework.org/components/datetime-input.html

Scott

**Comment by rstoenescu** [comment] 2018-08-15 17:12
Hi,

**This is scheduled for v1.0**.

This ticket is duplicate of another one (more complex) -- but don't have time to look for it to post it here.

**Closed by rstoenescu** 2018-08-15 17:12 UTC
