### ISSUE TITLE
Receive an error during build after changing extractCSS to false

### ISSUE THREAD

**Issue by radinsoft** [quasarframework/quasar#9787] opened 2021-06-24 09:43 UTC
quasar.conf.js

`extractCSS: false`

Output:

 App •  ERROR  •  UI  in ./node_modules/@quasar/extras/material-icons/material-icons.css

ValidationError: Invalid options object. PostCSS Loader has been initialized using an options object that do  es not match the API schema.
   - options has an unknown property 'plugins'. These properties are valid:
     object { postcssOptions?, execute?, sourceMap?, implementation? }

  - validate.js:104 validate
    [quasar]/[webpack]/[schema-utils]/dist/validate.js:104:11

  - NormalModule.js:527 Object.getOptions
    [quasar]/[webpack]/lib/NormalModule.js:527:19

 App •  ERROR  •  UI  in ./src/css/app.scss

Error: Node Sass version 6.0.0 is incompatible with ^4.0.0.

  - loader.js:108 getRenderFuncFromSassImpl
    [quasar]/[sass-loader]/lib/loader.js:108:19

  - loader.js:46 Object.sassLoader
    [quasar]/[sass-loader]/lib/loader.js:46:20

**Comment by yusufkandemir** [comment] 2021-07-05 07:25
Duplicate of #9782.

**Closed as completed by yusufkandemir** 2021-07-05 07:25 UTC
Labels: kind/bug 🐞, Qv2 🔝
