### ISSUE TITLE
Hope to add a Treetable support in QTree component

### ISSUE THREAD

**Issue by sandrew1945** [quasarframework/quasar#8179] opened 2020-12-10 06:48 UTC
I can't make a treetable by the official component like this [TreeTable](超链接地址 "https://jsfiddle.net/fernando2684/p0k8szvj/43/")
Hope to have an official version

**Comment by pdanpdan** [comment] 2020-12-10 06:51
Duplicate of #4099

**Closed by pdanpdan** 2020-12-10 06:51 UTC
Labels: feature request
