### ISSUE TITLE
tooltip doesn't disappear if button state changed to disabled

### ISSUE THREAD

**Issue by vitaly-ignatovich** [quasarframework/quasar#6870] opened 2020-04-23 01:41 UTC
**Describe the bug**
If toolitp is showing for a button and button got disabled, toolip will never disappear.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/vitaly-ignatovich/pen/qBORRwV
**To Reproduce**
1. go to codepen above and click 'disable me'. Tooltip will never disappear

**Expected behavior**
Tooltip should disappear even if in disabled state
**Screenshots**
![image](https://user-images.githubusercontent.com/11555309/80049835-96a7b680-8546-11ea-8074-78beaa6e6cfc.png)

**Platform (please complete the following information):**
OS:
All
NPM:
Yarn:
Browsers:
All
Android:
Electron:

**Additional context**

**Comment by pdanpdan** [comment] 2020-04-23 04:35
Duplicate of https://github.com/quasarframework/quasar/issues/6105, https://github.com/quasarframework/quasar/issues/4179

**Closed by pdanpdan** 2020-04-23 04:35 UTC
Labels: bug

**Comment by smolinari** [comment] 2020-04-23 07:16
https://codepen.io/smolinari/pen/dyYNvJw?editors=1010

Scott
