### ISSUE TITLE
q-form validate input in child component not working

### ISSUE THREAD

**Issue by MIT-bits** [quasarframework/quasar#9597] opened 2021-06-07 13:21 UTC
**Describe the bug**
It is not possible to trigger q-form validation on q-input in a child component.

NOTE! If the input has been touched and the form has been 'Reset', the validation works! This seems to be a bug preventing creation of reusable components, that requires q-form validation e.g. 'required'.

**Codepen/jsFiddle/Codesandbox (required)**
[https://jsfiddle.net/orbit/Lk9x6qnu/40/](https://jsfiddle.net/orbit/Lk9x6qnu/40/)
[https://codepen.io/mit-bits/pen/WNpJBwm?editors=1011](https://codepen.io/mit-bits/pen/WNpJBwm?editors=1011)
[https://codesandbox.io/s/sparkling-tdd-rifqv?file=/src/pages/Index.vue](https://codesandbox.io/s/sparkling-tdd-rifqv?file=/src/pages/Index.vue)

**To Reproduce**
1. Leave the three 'required' input fields untouched
2. Click 'Submit'
3. Validation on input 1 (from child component) does not work
4. NOTE! If input 1 has been touched and the form reset, the validation works

**Expected behavior**
I would expect all q-form controls e.g. q-input to validate on submit also the ones from child components.

**Screenshots**
<img width="214" alt="Screenshot 2021-06-07 at 15 20 01" src="https://user-images.githubusercontent.com/775108/121023795-e9245080-c7a3-11eb-8e38-3d04edb94df1.png">

**Platform (please complete the following information):**
Quasar Version: 1.15.19
@quasar/app Version:
Quasar mode:

  - [ x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [ x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: MacOS 11.2.2
Node: 12.18.1
NPM: 6.14.5
Yarn:
Browsers: Chrome (latest)
iOS:
Android:
Electron:

**Additional context**

**Comment by pdanpdan** [comment] 2021-06-07 19:53
duplicate of #9450

https://jsfiddle.net/cg4yzjwL/

**Closed by pdanpdan** 2021-06-07 19:53 UTC
Labels: :beetle: bug, Qv1

**Comment by qxygene** [comment] 2022-04-09 21:03
Any update??
