### ISSUE TITLE
[v1] QSelect in Dialog cause select options to not display correctly

### ISSUE THREAD

**Issue by smcassar** [quasarframework/quasar#3263] opened 2019-02-14 08:25 UTC
### Software version

Quasar: 1.0.0-beta.1
@quasar/app (v1+ only): 1.0.0-beta.3
OS: Darwin(18.2.0)
Node: 10.6.0
NPM: 6.1.0
Browsers: Firefox, Chrome

### JsFiddle
https://jsfiddle.net/rnfwk9o0/

### What did you get as the error?
Entire dialog becomes scrollable when select options are visible
![1 0 dialog issue](https://user-images.githubusercontent.com/25423886/52772969-c4af8200-3089-11e9-8647-250ef4feba30.png)

(not actually sure if this is a bug or an issue with my layout but we couldnt work it out in the discord channel so it was recommended that I open an issue)

### What were you expecting?

was expecting it to display in a similar way to 0.17:

![pre 1 0](https://user-images.githubusercontent.com/25423886/52772918-a5185980-3089-11e9-8994-3b508c4eaf2c.png)

### What steps did you take, to get the error?

Update my old html from:
```html
<q-dialog v-model="showingStateDialog" @ok="updateState" :cancel="true">
      <span slot="title">Update Ticket State</span>
      <div slot="body">
        <q-field>
          <q-select v-model="selectedState" :options="stateOptions"/>
        </q-field>
      </div>
    </q-dialog>
```
to:

```html
<q-dialog v-model="showingStateDialog">
      <q-card style="min-width: 20vw">
        <q-card-section>
          <div class="text-title">Update Ticket State</div>
        </q-card-section>
        <q-card-section class="row">
          <q-select class="col" v-model="selectedState" filled :options="stateOptions"/>
        </q-card-section>
        <q-separator/>
        <q-card-actions align="right">
          <q-btn flat color="primary" label="Cancel" @click="showingStateDialog = false"/>
          <q-btn flat color="primary" label="Update"/>
        </q-card-actions>
      </q-card>
    </q-dialog>
```

**Comment by rstoenescu** [comment] 2019-02-14 08:27
Duplicate of https://github.com/quasarframework/quasar/issues/3263

**Closed by rstoenescu** 2019-02-14 08:27 UTC

**Comment by rstoenescu** [comment] 2019-02-14 17:04
Duplicate of https://github.com/quasarframework/quasar/issues/3242
