### ISSUE TITLE
Product tour / spotlight capability in Quasar

### ISSUE THREAD

**Issue by rfox12** [quasarframework/quasar#6008] opened 2020-01-05 14:45 UTC
Many websites have a "product tour" that help introduce functional areas of the website.  This is usually essentially two concepts melded together: 1) a "spotlight" capability whereby the majority of the web page is dimmed (e.g. like when a model dialog pops up) and a component is highlighted (with optional decorations/explanations and 2) a stepper capability.  I think this would be a fantastic addition to Quasar.  Here is an example: https://pulsardev.github.io/vue-tour/

I would imagine we could leverage $refs to specify which components to highlight?  This type of functionality could also be used as a help mechanism.

**Comment by tmartty** [comment] 2020-01-05 14:59
This would be **awesome**. I'm thinking probably a plugin like the [Dialog API](https://quasar.dev/quasar-plugins/dialog#Dialog-API) one?

Usability could be something like this:
```javascript
this.$q.spotlight([
  {
    el: '.class',
    opts: { ... } // this would be the same options as the Dialog API
  },
  ...
])
```

**Comment by rfox12** [comment] 2020-01-05 15:16
And I hope it won't be too hard to leverage QTooltip (which is extensible via slots!) to provide the spotlight decoration...  the devil is always in the details.  Do we want to allow more than 1 ref to be highlighted at the same time?  Modal behaviors?(probably same options as QDialog?)  Scroll behaviors?  Before/after event hooks?  I would certainly want the option to use the spotlight without any step functionality at all...

**Comment by smolinari** [comment] 2020-01-05 16:37
How about making a boot file and "Vue.use"ing Vue Tour?

Scott

**Comment by rfox12** [comment] 2020-01-05 16:43
I considered it but it would require cleanup... these are the dependencies of `vue-tour`
"hash-sum": "^2.0.0",
"jump.js": "^1.0.2",
"popper.js": "^1.16.0",
"vue": "^2.6.10"

**Comment by smolinari** [comment] 2020-01-05 16:47
Then make an AE. 😁 This would be something the community would need to put together for sure anyway. I can't speak for Razvan, but I'm super certain this wouldn't be part of the core. 

Scott

**Comment by AfonsoGomes** [comment] 2020-01-08 13:47
Isn't this similar to the Tipster component #79 ?

**Comment by rfox12** [comment] 2020-01-08 15:13
It is indeed!  Good callout Afonso.  I propose we close this issue and perhaps add "product tour / spotlight" keywords to the title of the old open issue...

**Comment by rstoenescu** [comment] 2020-01-18 06:33
Duplicate of https://github.com/quasarframework/quasar/issues/79

**Closed by rstoenescu** 2020-01-18 06:33 UTC
Labels: feature request
