### ISSUE TITLE
q-uploader cannot work on Chrome 122

### ISSUE THREAD

**Issue by shazhou2015** [quasarframework/quasar#17040] opened 2024-03-27 05:47 UTC
### What happened?

The uploader cannot work on Chrome 122

### What did you expect to happen?

The file upload dialog should be opened when click on the q-uploader

### Reproduction URL

https://quasar.dev/vue-components/uploader/

### How to reproduce?

1. Make sure your chrome is `Version 122.0.6261.129 (Official Build) (arm64)`
2. Open the URL: https://quasar.dev/vue-components/uploader/
3. Click on any uploader

Expected:
The upload dialog should be opened.

Actual:
Nothing happens.

https://github.com/quasarframework/quasar/assets/11716841/ad90704d-b279-445c-b8b2-eef98bd1e413

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

**Comment by rstoenescu** [comment] 2024-03-29 08:51
Hi,

Cannot reproduce. Using `Version 123.0.6312.87 (Official Build) (arm64)` on a Mac.
Anyone else being able to reproduce?

**Comment by smolinari** [comment] 2024-03-29 09:52
Works for me with Chrome 123 on Linux. I realize it isn't Chrome 122, but maybe that version had a bug?

@shazhou2015 - What OS are you using?

Scott

**Comment by smolinari** [comment] 2024-03-29 09:59
I switched to Windows (11) and do have Chrome 122 and the uploader works fine for me. This is more than likely in issue with your own PC setup. 

Scott

**Comment by smolinari** [comment] 2024-03-29 10:09
I'm closing the issue, since it is seems to be a local system problem. 

Scott

**Closed as completed by smolinari** 2024-03-29 10:09 UTC
Labels: kind/bug 🐞, not reproducible, Qv2 🔝, area/components, flavour/quasar-cli-vite

**Comment by rstoenescu** [comment] 2024-03-29 10:11
Check if any of your browser extensions interfere.
