### ISSUE TITLE
Vitest failed to mock $q.loading in quasar

### ISSUE THREAD

**Issue by g-Charpe** [quasarframework/quasar#15812] opened 2023-05-10 11:49 UTC
### What happened?

I am having [vue3](https://vuejs.org/guide/quick-start.html) app with [vite](https://vitejs.dev/) and [vitest](https://vitest.dev/api/) and trying to mock the Quasar useQuasar composable which I am using in my custom Composable like:

```
import { useQuasar } from "quasar"

export function useLoginRequestBuilder() {
  const $q = useQuasar()

  async function login() {
    try {
      $q.loading.show()
      const auth = makeUserAuthentication()
      return await auth.signinRedirect()
    } catch (e) {
      console.log(e)
      $q.loading.hide()
      $q.notify({
        color: "red-4",
        textColor: "white",
        icon: "o_warning",
        message: "Login Failed!",
      })
    }
  }

  return {
    login,
  }
}
```

and I am trying to mock **$q.loading** in tests

But I am getting below error - 
**TypeError: Cannot read property 'show' of undefined**

### What did you expect to happen?

Should able to mock $q variables.

### Reproduction URL

https://stackblitz.com/edit/quasarframework-rcz3km?file=README.md

### How to reproduce?

1. run unit:test

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Plugins (quasar)

**Comment by chandrakant-k-nice** [comment] 2023-05-24 10:07
Hi @g-Charpe, Have you find any solution for this?

**Comment by g-Charpe** [comment] 2023-06-05 05:26
No @chandrakant-k-nice.

**Comment by yusufkandemir** [comment] 2023-06-06 13:31
You've provided an invalid reproduction, it's just a plain Quasar project without your code or a testing setup. You also didn't provide any test code.
https://github.com/quasarframework/quasar-testing is a better place to report/discuss this problem. ~~So, I am transferring the issue there.~~ (_I can't due to missing permissions 😅_)

**Comment by g-Charpe** [comment] 2023-06-08 09:43
did not get you @yusufkandemir

**Comment by yusufkandemir** [comment] 2023-06-08 09:46
The reproduction URL you've provided ([stackblitz.com/edit/quasarframework-rcz3km?file=README.md](https://stackblitz.com/edit/quasarframework-rcz3km?file=README.md)) contains an empty Quasar project. It doesn't have the code you've provided, any tests defined, or the testing setup to execute the `run unit:test` command. So, there is not enough information to be able to reproduce the issue, or even understand what you are trying to do because you didn't provide any test code snippet either.

**Closed by yusufkandemir** 2023-06-08 09:46 UTC
Labels: kind/bug 🐞, bug/0-needs-info, area/ui
