### ISSUE TITLE
Multiple files are impossible in q-uploader

### ISSUE THREAD

**Issue by pikil** [quasarframework/quasar#10065] opened 2021-07-13 10:04 UTC
**Describe the bug**
q-uploader send files with undefined key (instead of names) for every file blob, unless ``` :field-name="fileNameFn" ``` prop is specified explicitly.

**Codepen/jsFiddle/Codesandbox (required)**
That can be viewed at https://quasar.dev/vue-components/uploader#uploading-multiple-files (Open DevTools in Google Chrome, Firefox and Safari denied the request so I could not see inside the request).

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://quasar.dev/vue-components/uploader#uploading-multiple-files
2. Open DevTools
3. Try uploading via q-uploader (multiple are better to see that the keys are the same - 'undefined')
4. See 'undefined' in '/upload' xhr in Network tab (DevTools); 

**Expected behavior**
'name' field should needs to be applied automatically, as that would cover most cases.

**Screenshot**
![Screen Shot 2021-07-13 at 9 28 17 PM](https://user-images.githubusercontent.com/26779040/125433038-1fb00957-5c65-4c03-afab-7598577ddcff.png)

**Platform (please complete the following information):**
Quasar Version: v2.0.2
@quasar/app Version: v3.0.2

Tested on:
  - [ ] PWA

OS: MacOSX
Node: v16.4.2
NPM: v7.18.1
Yarn:
Browsers: Google Chrome, Firefox, Safari (latest)

Many thanks!

**Comment by pdanpdan** [comment] 2021-07-13 10:11
duplicate of #10018

**Closed as completed by pdanpdan** 2021-07-13 10:11 UTC
Labels: kind/bug 🐞, Qv2 🔝
