### ISSUE TITLE
quasar v1 feature: QTime fixed time to select

### ISSUE THREAD

**Issue by zinwalin** [quasarframework/quasar#3734] opened 2019-03-28 21:42 UTC
![image](https://user-images.githubusercontent.com/5416196/55194684-43621800-520f-11e9-9180-4d5ecc9e21cc.png)

I used TimePicker in element-ui which provide fixed time to select. It's possible to add support in quasar v1?

**Comment by rstoenescu** [comment] 2019-03-29 05:15
Duplicate of https://github.com/quasarframework/quasar/issues/207

**Closed by rstoenescu** 2019-03-29 05:15 UTC
