### ISSUE TITLE
SessionStorage/LocalStorage plugin in state.js on Vuex store got "....not a function error"

### ISSUE THREAD

**Issue by bakbluelabel** [quasarframework/quasar#8659] opened 2021-03-22 11:08 UTC
**Describe the bug**
This is ONLY happened if using SessionStorage/LocalStorage plugin in state.js file in Vuex store with v2 beta. The error below will be shown only in browser's devTool console (nothing will be shown  on screen - no output). __Note: The same code has no problem with v1.__
```
Uncaught (in promise) TypeError: quasar_src_plugins_SessionStorage_js__WEBPACK_IMPORTED_MODULE_0__.default.getItem is not a function
    at eval (state.js?345d:6)
    at new Module (vuex.esm-browser.js?8074:128)
    at ModuleCollection.register (vuex.esm-browser.js?8074:221)
    at eval (vuex.esm-browser.js?8074:232)
    at eval (vuex.esm-browser.js?8074:97)
    at Array.forEach (<anonymous>)
    at forEachValue (vuex.esm-browser.js?8074:97)
    at ModuleCollection.register (vuex.esm-browser.js?8074:231)
    at new ModuleCollection (vuex.esm-browser.js?8074:192)
    at new Store (vuex.esm-browser.js?8074:362)
```
**Codepen/jsFiddle/Codesandbox (required)**
[https://github.com/bakbluelabel/q2test.git](https://github.com/bakbluelabel/q2test.git)

**To Reproduce**
1. `quasar create q2beta --branch next` 
2. Add "SessionStorage" in quasar.conf.js under `framework: { plugin: ["SessionStorage"] }`
3. `quasar new store test`
4. Open the file - store/test/state.js
5. Add `import { SessionStorage } from "quasar" `
6. Add the below within the return block '{}':
```js
return {
   myVal: SessionStorage.getItem('myKey') || "not found"
}
```
7. `quasar dev`
8. open browser's devTool will see the error

**Expected behavior**
`myVal`  in the store/test/state.js should be able to read by any component (.vue) file by calling `$store.state.test.myVal`  

**Screenshots**
nil

**Platform (please complete the following information):**
Quasar Version: 2.0.0-beta.9
@quasar/app Version: 3.0.0-beta.9
Quasar mode:
  - [ x ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [ x ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Windows 10
Node: v14.10.1
NPM: v6.14.11
Yarn: v1.22.10
Browsers: Chrome
iOS:
Android:
Electron:

**Additional context**
* Using composition API
* It's no problem if SessionStorage.getItem() was placed in actions.js/mutation.js/getters.js or in any .vue file. It only cause problem in state.js on Vuex store.

**Comment by rstoenescu** [comment] 2021-03-22 15:45
Duplicate of https://github.com/quasarframework/quasar/issues/8595
Fix already available in beta.10

**Closed by rstoenescu** 2021-03-22 15:45 UTC
Labels: :beetle: bug, 🔝 Qv2

**Comment by bakbluelabel** [comment] 2021-03-23 04:49
@rstoenescu superb!! thanks. 🍺
