### ISSUE TITLE
"Manifest merger failed" when building android app with capacitor

### ISSUE THREAD

**Issue by karimdjemai** [quasarframework/quasar#7168] opened 2020-06-05 01:30 UTC
**Describe the bug**
When building the capacitor android app in android studio this error emerges:
`Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.2.0] AndroidManifest.xml:24:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:5:5-44:19 to override.
`

**To Reproduce**
1. add capacitor mode `quasar mode add capacitor`
2. Build with quasar cli for android ide `quasar build -m capacitor -T android --ide`
3. Watch as Android studio opens
4. click on build/run
5. See above mentioned error emerging

**Screenshots**
![image](https://user-images.githubusercontent.com/8942592/83826690-d08ae180-a6dc-11ea-9411-d9e4c2eacd50.png)

**Platform (please complete the following information):**
OS: MacOS
Node: v14.3.0
NPM: 6.14.4

**Comment by NickMcBurney** [comment] 2020-06-07 16:35
@karimdjemai I had the same issue and managed to fix by:
1. Updating quasar packages:
`npm update quasar @quasar/app @quasar/extras`
(I had previously be using version 1.0.0 for each package)
2. In Android Studio Refactored to use Android X - as suggested in similar issue #6768 

Not sure if the package updates were required but this is steps I followed (I initially tried running after just updating packages and this didnt work - but with Android X step it did)

**Comment by rstoenescu** [comment] 2020-06-11 12:05
Duplicate of #6768

**Closed by rstoenescu** 2020-06-11 12:05 UTC
Labels: bug
