### ISSUE TITLE
QStep with font awesome as icon seem to disable both icon-active and icon-done (and most likely icon-error)

### ISSUE THREAD

**Issue by janpjens** [quasarframework/quasar#7663] opened 2020-08-22 18:38 UTC
**Describe the bug**
When using an icon from Font Awesome "out of box" as the assigned icon for a step in QStepper it will not apply the icon-active and icon-done. Specifying the attributes makes no difference.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/janpjens/pen/NWNbQEW

**To Reproduce**
1. Copy in the [first example from the documentation](https://quasar.dev/vue-components/stepper#Horizontal)
2. Change the icon attribute of the second QStep to `fas fa-bug`
3. Hit "Continue" in the QStepper and observe that neither the "create" nor the "done" material icons are applied

**Expected behavior**
If using material icons, such as the one provided in the example under step 1. above, the icon will change to "create" when active and "done" when the done conditions are met.

**Screenshots**
![qstep_icon_bug](https://user-images.githubusercontent.com/10227103/90963324-fee7b400-e4b6-11ea-8566-4d10a6e39669.gif)

**Platform (please complete the following information):**
OS: Ubuntu 18.04.3 LTS (vagrant/homestead)
Node: v12.16.2
NPM: 6.14.4
Yarn: 1.21.1
Browsers: Chrome 84.0 / Windows 10

**Additional context**
It may be related SVG, as it worked as expected when loading the webfont version in Codepen. The `icon-error` attribute has not been tested but is most likely also affected.

**Comment by rstoenescu** [comment] 2020-08-23 23:40
Hi,

There is no issue with Quasar. However, there are a few comments about the supplied codepen:
1. You have some QBtn tags that are self-closing -> a big "no" when dealing with UMD.
2. You are adding the fontawesome CSS file AFTER the Quasar's one. This is wrong. You can check what tags to insert by visiting https://quasar.dev/start/umd and selecting your desired icon libs etc etc.
3. But the biggest problem (and **the root cause of the issue that you are experiencing**) is that you are also adding the JS files of fontawesome. They are NOT required and are actually negatively interfering.

Your CSS links should be (in this order):
* https://cdn.jsdelivr.net/npm/@quasar/extras/material-icons/material-icons.css
* https://use.fontawesome.com/releases/v5.0.13/css/all.css
* https://cdn.jsdelivr.net/npm/quasar/dist/quasar.min.css

Your JS tags should be (in this order, and nothing from fontawesome):
https://cdn.jsdelivr.net/npm/vue/dist/vue.js
https://cdn.jsdelivr.net/npm/quasar/dist/quasar.umd.min.js

Do this then transform the self-closing `<q-btn>` tags into `<q-btn ....></q-btn` and you'll see that everything works correctly.

**Closed by rstoenescu** 2020-08-23 23:40 UTC
Labels: bug

**Comment by janpjens** [comment] 2020-08-24 06:57
Apologies! It seems like I may not have had things under control and that there may indeed be some duplicate loading at play in the original code. I will investigate. Thanks for taking the time to give such a detailed answer to what may be a non-issue. 

Concerning self closing Qbtn tags I just grabbed a direct copy from the documentation for demonstration purposes; The project where this originally occured is neither UMD nor does it have self closing buttons 👍
