### ISSUE TITLE
Cannot compile the project if the project path contains "#"

### ISSUE THREAD

**Issue by YongJie-Xie** [quasarframework/quasar#10887] opened 2021-10-04 08:20 UTC
**Describe the bug**
I cannot compile the project if the project path contains "#", a path like "D:\#Project", but I can run it in other paths.
I think this is the cause of webpack, but I can’t be sure about it.

**Codepen/jsFiddle/Codesandbox (required)**
Use Quasar cli to create a project

**To Reproduce**
1. Create project in D:\#Project
```bat
D:\>quasar create #Project
? Project name (internal usage for dev) project
? Project product name (must start with letter if building mobile apps) Quasar App
? Project description A Quasar Framework app
? Author Develop <develop@example.com>
? Pick your CSS preprocessor: SCSS
? Check the features needed for your project: ESLint (recommended), Vuex, Axios, Vue-i18n
? Pick an ESLint preset: Prettier
? Continue to install project dependencies after the project has been created? (recommended) yarn
```
2. Run it
```bat
D:\>cd #Project
D:\#Project>quasar dev
```

**Expected behavior**
```bat
 Dev mode.......... spa
 Pkg quasar........ v2.1.0
 Pkg @quasar/app... v3.1.2
 Pkg webpack....... v5
 Debugging......... enabled

 Configured browser support (>= 88.64% of global marketshare):
 · Chrome for Android >= 94
 · Firefox for Android >= 92
 · Android >= 94
 · Chrome >= 85
 · Edge >= 91
 · Firefox >= 83
 · iOS >= 11.3-11.4
 · Opera >= 75
 · Safari >= 12

 App • Chaining "UI" Webpack config
 App • 'store' feature flag was missing and has been regenerated
 App •  WAIT  • Compiling of "UI" in progress...
 App •  DONE  • "UI" compiled with errors • 3829ms

 App •  ERROR  •  UI  in ../ #Project/.quasar/client-entry.js

Error: Cannot find module 'D:\ #Project\node_modules\babel-loader\lib\index.js'
  Require stack:
  - D:\#Project\node_modules\webpack\lib\ProgressPlugin.js
  - D:\#Project\node_modules\webpack\lib\index.js
  - D:\#Project\node_modules\@quasar\app\lib\dev-server-regular.js
  - D:\#Project\node_modules\@quasar\app\bin\quasar-dev
  - D:\#Project\node_modules\@quasar\app\bin\quasar
  - C:\Users\Administrator\AppData\Local\Yarn\Data\global\node_modules\@quasar\cli\bin\quasar

  - loader.js:902 Function.Module._resolveFilename
    internal/modules/cjs/loader.js:902:15

  - loader.js:746 Function.Module._load
    internal/modules/cjs/loader.js:746:27

  - loader.js:974 Module.require
    internal/modules/cjs/loader.js:974:19

  - helpers.js:93 require
    internal/modules/cjs/helpers.js:93:18

  - ProgressPlugin.js:412
    [#Project]/[webpack]/lib/ProgressPlugin.js:412:9


  - NormalModule.js:776 NormalModule.doBuild
    [#Project]/[webpack]/lib/NormalModule.js:776:24

  - NormalModule.js:928 NormalModule.build
    [#Project]/[webpack]/lib/NormalModule.js:928:15

  - Compilation.js:1357
    [#Project]/[webpack]/lib/Compilation.js:1357:12

  - NormalModule.js:1200 NormalModule.needBuild
    [#Project]/[webpack]/lib/NormalModule.js:1200:32

 App •  ERROR  •  UI  in ../ #Project/node_modules/webpack/hot/dev-server.js

Error: Cannot find module 'D:\ #Project\node_modules\@quasar\app\lib\webpack\loader.js.transform-quasar-imports.js'
  Require stack:
  - D:\#Project\node_modules\webpack\lib\ProgressPlugin.js
  - D:\#Project\node_modules\webpack\lib\index.js
  - D:\#Project\node_modules\@quasar\app\lib\dev-server-regular.js
  - D:\#Project\node_modules\@quasar\app\bin\quasar-dev
  - D:\#Project\node_modules\@quasar\app\bin\quasar
  - C:\Users\Administrator\AppData\Local\Yarn\Data\global\node_modules\@quasar\cli\bin\quasar

  - loader.js:902 Function.Module._resolveFilename
    internal/modules/cjs/loader.js:902:15

  - loader.js:746 Function.Module._load
    internal/modules/cjs/loader.js:746:27

  - loader.js:974 Module.require
    internal/modules/cjs/loader.js:974:19

  - helpers.js:93 require
    internal/modules/cjs/helpers.js:93:18

  - ProgressPlugin.js:412
    [#Project]/[webpack]/lib/ProgressPlugin.js:412:9

  - Hook.js:14 Hook.CALL_DELEGATE [as _call]
    [#Project]/[tapable]/lib/Hook.js:14:14

  - NormalModule.js:776 NormalModule.doBuild
    [#Project]/[webpack]/lib/NormalModule.js:776:24

  - NormalModule.js:928 NormalModule.build
    [#Project]/[webpack]/lib/NormalModule.js:928:15

  - Compilation.js:1357
    [#Project]/[webpack]/lib/Compilation.js:1357:12

 App •  COMPILATION FAILED  • Please check the log above for details.
```

**Screenshots**

**Platform (please complete the following information):**
Quasar Version: 2.1.0
@quasar/app Version: 3.1.0

Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Windows
Node: v14.18.0
NPM: 7.24.1
Yarn: 1.22.15
Browsers: Chrome

**Additional context**
webpack version: 5.56.0

**Comment by pdanpdan** [comment] 2021-10-04 09:21
Duplicate of https://github.com/quasarframework/quasar/issues/10591

**Closed as completed by pdanpdan** 2021-10-04 09:21 UTC
Labels: Qv2 🔝
