### ISSUE TITLE
New CLI projects without Vuex don't compile

### ISSUE THREAD

**Issue by JeremyPasco** [quasarframework/quasar#11434] opened 2021-11-20 23:35 UTC
**Describe the bug**
Creating a new projetcs with CLI without picking Vuex generates a project that won't compile.

**To Reproduce**
1. `quasar create demo`
2. Picking Sass with SCSS syntax
3. Picking ESLint and Axios (no Vuex)
4. Picking Pretiier
5. Picking Yarn
6. `cd demo`
6. `quasar dev`
7. Get the following error:

 App •  ERROR  •  UI  in ./node_modules/@quasar/extras/material-icons/material-icons.css

Error: /projectpath/node_modules/lines-and-columns/build/index.js
  require() of ES modules is not supported.
  require() of /projectpath/node_modules/lines-and-columns/build/index.js from /projectpath/node_modules/parse-json/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines   all .js files in that package scope as ES modules.
  Instead rename /projectpath/node_modules/lines-and-columns/build/ind  ex.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /projectpath/node_modules/lines-and-columns/package.json.
  
  - loader.js:1089 Object.Module._extensions..js
    internal/modules/cjs/loader.js:1089:13
  
  - loader.js:937 Module.load
    internal/modules/cjs/loader.js:937:32
  
  - loader.js:778 Function.Module._load
    internal/modules/cjs/loader.js:778:12
  
  - loader.js:961 Module.require
    internal/modules/cjs/loader.js:961:19
  
  - helpers.js:92 require
    internal/modules/cjs/helpers.js:92:18
  
 App •  COMPILATION FAILED  • Please check the log above for details.

***Note : picking Vuex during the project configuration solves the problem***

**Expected behavior**
Omitting Vuex should not give error during compilation

**Platform:**
Quasar Version:
@quasar/cli Version: 1.2.2

OS: Ubuntu 20.04
Node: 14.17.6
Yarn: 1.22.11

**Comment by JeremyPasco** [comment] 2021-11-20 23:37
Upgrading @quasar/extras didn't help either:
`yarn add @quasar/extras@latest`

**Comment by MilosPaunovic** [comment] 2021-11-21 07:48
You're first try could be to delete `node_modules` folder and  run yarn again to re-install dependecies. If that doesn't work, provide us with the output of `quasar info` command.

**Comment by JeremyPasco** [comment] 2021-11-21 09:18
Removing the node_modules directory and reinstalling dependencies didn't work.
Here is the quasar info:

Operating System - Linux(5.11.0-40-generic) - linux/x64
NodeJs - 14.17.6

Global packages
  NPM - 6.14.15
  yarn - 1.22.11
  @quasar/cli - 1.2.2
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.3.3 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 3.2.3 -- Quasar Framework local CLI
  @quasar/extras - 1.12.1 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.22 -- The progressive JavaScript framework for buiding modern web UI.
  vue-router - 4.0.12
  vuex - Not installed
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.16.0 -- Babel compiler core.
  webpack - 5.64.2 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 4.4.0 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  typescript - 4.4.2 -- TypeScript is a language for application scale JavaScript development
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

**Comment by JeremyPasco** [comment] 2021-11-21 09:23
The following works:

1. Create a project with Vuex
2. Remove vuex dependecy with yarn remove
3. Remove the src/store directory
4. `quasar dev`
If I create a project with Vuex and I remove it with Yarn then, it can compile.
Note : `quasar info` gives the exact same config

**Comment by smolinari** [comment] 2021-11-25 05:56
I can't reproduce. Worked fine for me. 

❯ quasar info

Operating System - Linux(5.10.60.1-microsoft-standard-WSL2) - linux/x64
NodeJs - 14.17.4

Global packages
  NPM - 6.14.14
  yarn - 1.22.5
  @quasar/cli - 1.0.7
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.3.3 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app - 3.2.3 -- Quasar Framework local CLI
  @quasar/extras - 1.12.1 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.22 -- The progressive JavaScript framework for buiding modern web UI.
  vue-router - 4.0.12
  vuex - Not installed
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.16.0 -- Babel compiler core.
  webpack - 5.64.3 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 4.4.0 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  typescript - 4.4.2 -- TypeScript is a language for application scale JavaScript development
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

Networking
  Host - Scotts-PC
  eth0 - 172.21.31.50

**Comment by smolinari** [comment] 2021-11-25 05:58
I'm going to close this as a one-off and since you've found a workaround. If you find the cause of the issue and it has to do with Quasar, please feel free to reopen. 

Thanks for reporting the issue at any rate. 

Scott

**Closed as completed by smolinari** 2021-11-25 05:58 UTC
Labels: Qv2 🔝
