### ISSUE TITLE
Clearing select results in `undefined` display string if no placeholder is provided

### ISSUE THREAD

**Issue by AncaIO** [quasarframework/quasar#2492] opened 2018-08-30 13:25 UTC
### Software version

Quasar: 0.17.10
OS: Fedora 28
Node: 8.11.4
NPM: 6.4.0
Browsers: Choime 68

### What did you get as the error?

When clearing q-select the display string is set to 'undefined' until blur. 

### What were you expecting?

That the component would display empty **if no placeholder was provided.**

### What steps did you take, to get the error?

Select a value from q-select dropdown, then clear it.

**Comment by rstoenescu** [comment] 2018-08-30 13:43
Duplicate of https://github.com/quasarframework/quasar/issues/2482 which is fixed for next Quasar version.

**Closed by rstoenescu** 2018-08-30 13:43 UTC
