### ISSUE TITLE
Add more Form/Input label style option

### ISSUE THREAD

**Issue by adiramardiani** [quasarframework/quasar#10215] opened 2021-07-28 04:59 UTC
**Is your feature request related to a problem? Please describe.**
Maybe this is not a problem, but for some cases of complex forms some people complain about the visibility of labels that are a little hidden. I have complex input form with outline + dense style  (user preference) the label is hard to identify, especially with the fields already filled in making it difficult to see

**Describe the solution you'd like**
I guess because style is taste, this option is not changing, but rather adding an option so that it can be used out of the box.
Currently for outlined input style, position of label is place inside border
![quasar](https://user-images.githubusercontent.com/8703419/127265427-c9d410db-df2d-473c-91a0-3f2e560fab74.png)
I hope there is an option to place a label like in the following image
![gmail_input form](https://user-images.githubusercontent.com/8703419/127265642-04a4a7db-cbff-4349-bf38-6964737d3e72.png)

**Describe alternatives you've considered**
1. regarding the label whether it can add option like bootstrap or something like this, to place label outside input
![bootstrap](https://user-images.githubusercontent.com/8703419/127265824-d28e90b2-ac17-463f-8a05-9ee088406433.png)
2. I think the option to make form/field in grid will be more readable for complex form
![grid_input](https://user-images.githubusercontent.com/8703419/127265910-c1635e05-13cb-4d47-9a6d-e21dbb8646da.png)

**Additional context**
I think if this option is added out of the box it will shorten our code even more, rather than having to do it manually

Thanks

**Comment by pdanpdan** [comment] 2021-07-28 05:11
duplicate of #3262
if you are using Qv1 then you can use my branch:https://pdanpdan.github.io/quasar-docs/vue-components/input#outlined-material-design
for Qv2 nothing yet

**Closed as completed by pdanpdan** 2021-07-28 05:11 UTC
Labels: kind/feature 💡

**Comment by adiramardiani** [comment] 2021-07-28 05:22
@pdanpdan On my issue I suggest some feature grid form/field, is it still relevant as a duplicate feature request ?

Currently I'm using Qv2 btw

**Comment by pdanpdan** [comment] 2021-07-28 10:28
sorry, but both options to place the label outside are not in the material design spirit, but they can be easily implemented in user code - they require no special things except to have an `id` generator and use the same id on the label and on the quasar field.
