### ISSUE TITLE
Add carousel images preview 

### ISSUE THREAD

**Issue by raxor123** [quasarframework/quasar#2055] opened 2018-05-18 14:07 UTC
Allow this type of carousel would be nice

![screenshot from 2018-05-18 10-04-13](https://user-images.githubusercontent.com/25715337/40239093-06417ad0-5a83-11e8-8e4c-386b1251fa73.png)

**Comment by rstoenescu** [comment] 2018-05-18 15:02
Duplicate of https://github.com/quasarframework/quasar/issues/1670

**Closed by rstoenescu** 2018-05-18 15:02 UTC
