### ISSUE TITLE
Browser crash when typing in QSelect

### ISSUE THREAD

**Issue by KNetiin** [quasarframework/quasar#5345] opened 2019-10-18 17:31 UTC
**Describe the bug**
When we type in normal QSelect, the browser gets super slow or the browser crashing

**To Reproduce**
1. Open https://quasar.dev/vue-components/select#Installation
2. Click on first QSelect
3. Type some word, random

**Comment by pdanpdan** [comment] 2019-10-18 17:52
Duplicate of #5343

**Closed by pdanpdan** 2019-10-18 17:52 UTC
Labels: bug
