### ISSUE TITLE
Qlayout bug in safari in dialog

### ISSUE THREAD

**Issue by 9527Lin** [quasarframework/quasar#5287] opened 2019-10-12 09:46 UTC
**Describe the bug**
When the browser is safari, qHeader and qFooter will jitter when qLayout is scrolling in QDialog.

**Codepen/jsFiddle/Codesandbox (required)**
The official documentation example can be reproduced

**To Reproduce**
1.Open official documentation with iphone safari
2.Find the QDialog component
3.Scroll down
4.Find the **With-containerized-QLayout**  example
5.Click the click me button under the example
6.Scroll **left** content
7.See the error

**Expected behavior**
QHeader and QFooter should not jitter

**Screenshots**
![WechatIMG82](https://user-images.githubusercontent.com/14218245/66699364-ce70ae80-ed18-11e9-9f58-2626645ff7b5.jpeg)

**Platform (please complete the following information):**
OS: ios 11.3
Browsers: safari
iOS: yes

**Additional context**
no

**Comment by pdanpdan** [comment] 2019-10-12 09:55
Duplicate of https://github.com/quasarframework/quasar/issues/4127

**Closed by pdanpdan** 2019-10-12 09:55 UTC
Labels: bug
