### ISSUE TITLE
[Request] Default Animation of the Sidemenu&Topbar

### ISSUE THREAD

**Issue by mstaack** [quasarframework/quasar#975] opened 2017-10-09 08:21 UTC
The current sidebar on the left side always uses an animation.

This should be changeable:  Disable or select different Transition Effect.

This is also mentioned here:
http://forum.quasar-framework.org/topic/659/remove-transition-in-side-menu-und-top-bar/7

![demo](https://user-images.githubusercontent.com/2828767/28628251-6ec68a48-7224-11e7-8752-bc192c99f3db.gif)

Cheers Max

**Comment by spectrolite** [comment] 2017-10-10 19:51
top bar has the same issue and would need a similar solution (toggle or choose other transition), it really looks weird being pushed right by the sidemenu and animating over it...

**Comment by rstoenescu** [comment] 2017-10-20 16:48
That's not an animation, it's a CSS transition. Will figure out a way to avoid this. PRs are welcomed to speed things up.

**Comment by spectrolite** [comment] 2017-10-20 17:47
Thanks for clarifying my animation vs transition mistake.
Looking forward to v0.15 with a solution to this.

**Comment by rstoenescu** [comment] 2017-10-20 18:25
Duplicate of https://github.com/quasarframework/quasar/issues/752

**Closed by rstoenescu** 2017-10-20 18:25 UTC
