### ISSUE TITLE
q-select can be cleared by focusing and backspace

### ISSUE THREAD

**Issue by johnstrickler** [quasarframework/quasar#16481] opened 2023-10-17 14:01 UTC
### What happened?

The Select component can be cleared by focusing and hitting backspace.

![Oct-17-2023 09-39-13](https://github.com/quasarframework/quasar/assets/302192/d26e2b0f-cc3b-4804-865d-07b2b0d79936)

### What did you expect to happen?

Hitting backspace should do nothing.  I would expect the default behavior of a Select to not be clearable similar to a native select.  A select has a finite amount of options which the user must choose from.   

### Reproduction URL

https://codepen.io/johnstrickler/pen/gOZNzyJ

### How to reproduce?

1. Go to the provided Codepen link
2. Select an option from the select dropdown
3. Hit backspace to clear the value

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

### Quasar info output

```Shell
Operating System - Darwin(21.5.0) - darwin/arm64
NodeJs - 16.15.1

Global packages
  NPM - 8.11.0
  yarn - 1.22.19
  @quasar/cli - undefined
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.11.10 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.2.1 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.16.2 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.47 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.1.6
  pinia - 2.0.34 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 2.9.15 -- Native-ESM powered web dev build tool
  eslint - 8.37.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

Networking
  Host - ip-192-168-86-29.ec2.internal
  en0 - 192.168.86.29
  utun3 - 10.250.1.34
```

**Comment by rstoenescu** [comment] 2023-10-17 14:14
Duplicate of #16478

**Closed as completed by rstoenescu** 2023-10-17 14:14 UTC
Labels: kind/bug 🐞, Qv2 🔝, bug/1-repro-available, area/components, flavour/quasar-cli-vite

**Comment by LuSrackhall** [comment] 2024-12-09 23:39
Sorry to bother everyone!

Regarding the content in [https://quasar.dev/vue-components/select#keyboard-navigation](https://quasar.dev/vue-components/select#keyboard-navigation), can provide an option to choose whether or not to use them? For example, when use-chips or clearable is enabled, the functionality of the <kbd>BACKSPACE</kbd> key to delete the last item is enabled by default, and there is no method provided to disable it.
> Although it can be solved at the moment, it is quite cumbersome -> because it requires using the `@keydown` event and nextTick to write the old value back to the original model.
