### ISSUE TITLE
q-form captures all click events of q-btn

### ISSUE THREAD

**Issue by yangjiafu** [quasarframework/quasar#11851] opened 2021-12-31 09:27 UTC
**Describe the bug**

**Codepen/jsFiddle/Codesandbox (required or your issue may be closed)**
Fork a Codepen (https://codepen.quasar.dev) or a jsFiddle (https://jsfiddle.quasar.dev) or a Codesandbox (https://codesandbox.quasar.dev) and hit save then copy-paste link here.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version:

Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX
  - [ ] Vite Plugin

Additonal Info:
- [x] Typescript
- [x] SFC usage with `<script setup>`
- [x] Vuex
- [] Prettier (eslint)
- [] Standard (eslint)
  
Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS:
Node:
NPM:
Yarn: [x]
Browsers:
iOS:
Android:
Electron:

**Additional context**

q-form should not capture all click events of q-button and button for verification

**Comment by yangjiafu** [comment] 2021-12-31 09:44
q-form should not capture all click events of q-button and button (not type) for verification

**Comment by pdanpdan** [comment] 2021-12-31 09:52
Hello. Please fill the issue template (especially the quasar version) and add a reproduction.
Because I suppose it's a duplicate of https://github.com/quasarframework/quasar/issues/11794

**Closed as completed by pdanpdan** 2021-12-31 09:52 UTC

**Comment by rstoenescu** [comment] 2021-12-31 10:01
This has been adressed in the next Quasar version (to be released next week).

**Comment by yangjiafu** [comment] 2021-12-31 10:04
> Hello. Please fill the issue template (especially the quasar version) and add a reproduction. Because I suppose it's a duplicate of #11794

quasar version 2.4.2

**Comment by yangjiafu** [comment] 2021-12-31 10:04
> This has been adressed in the next Quasar version (to be released next week).

thanks
