### ISSUE TITLE
Chrome Bug on Android - Side Effect on Footer with touchable Elements embeded (eg Tabs) glitches away when Scroll and Stop

### ISSUE THREAD

**Issue by ibrainventures** [quasarframework/quasar#8276] opened 2020-12-29 15:07 UTC
**Describe the bug**

Long time no issue ;)  .. Hope you are fine. 

When a longer List is scrolled by a swipe and stopped by a finger tip the footer embedded elements
(e.g. tabs , buttons or href) are non clickable (glitching under or over the bar). 
It happens often when the Adressbar resizes during scroll.

**Codepen/jsFiddle/Codesandbox (required)**

Default quasar with a list and a footer / tabs:

https://twvjt.sse.codesandbox.io/

**To Reproduce**

Scroll the list, stop it apprupt by a finger tip, and the clickable area is glitching under
or over the visual footer.

Video for visualization.:

https://vimeo.com/495493102

**Expected behavior**
The clickable area should always be there, where the button is.

**Screenshots**

**Platform (please complete the following information):**

Anroid 10, Chrome Browser

Different Smartphones (Nokia etc.) tested.
Also tested with Firefox on Android -> issue always happens.

**Comment by pdanpdan** [comment] 2020-12-29 15:20
Hello, long time no issue, you are right.
Not expecting to be fixed, but can you please check with:
`"quasar": "https://github.com/pdanpdan/quasar#quasar-pdan-v1.14.7-beta.11"`
I need to know if the problem is not solved as a side-effect of my changes :)

**Comment by ibrainventures** [comment] 2020-12-29 15:44
Nice to read you. Thanks for the fast response.

Fyi: It no "new" issue. I am working on a 1.12 based patched package and there is this 
issue also. So no effects by any new versions / changes.

Tested with you -beta.11 package, the glichting is still there (unchanged), but a new issue happens, 
the tabs are jumping around :-) (on Android / Chrome)  ..

Its really a **hard nut / issue:**

Because the "seeable" element (qtab, button or a simple href) is positionated right, but the
Browser calculated "hot / clickable / reactive area" is calculated wrong. (like a different layer).

As a simple test, if i change the: css rule

.fixed-bottom, .absolute-bottom {
	right: 0;
	bottom: 0;  
	left: 0;
}

.fixed-bottom, .absolute-bottom {
	right: 0;
	top: 300px;
	left: 0;
}

the glitching is away (and the footer is in middle) ;.) 

So the browser calculation for the "hot area" is wrong, if it is relatived to the bottom ..

**Comment by pdanpdan** [comment] 2020-12-29 17:55
Ok, it's the browser that is funky (I suppose Firefox dropped any self-respect and started using webview on android also).
I opened a ticker on Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1162291

**Comment by ibrainventures** [comment] 2020-12-30 11:28
Oh dear, thats really a weird / funky browser bug .. 
Thank you for opening the perfect Chromium Bug Ticket. 

To get always a stable, reactive footer menu i quick work arounded-it with:

```
body.platform-android:not(.native-mobile) .fixed-bottom, .absolute-bottom
  top: calc(100vh - 92px) !important
  bottom: unset !important
```
Not really super-nice, because it expands the height if the adressbar is minimized, but
it gives a un-interrupted, stable userinterface experience. (and in our app the footer bar is a
main navigation feature). (and i made the toolbar / tabs background a little transparent so its 
not sooo visual blocking :) )

May there are some deeper / better ways with observers or scroll eventlisteners, but
after some testings, that when the scroll is interrupted by the finger tip there are often no
(exact) events fired .. so the problem is imho not easy solveable without the help of the chrome devs.

Have a nice New Year festival.

**Comment by pdanpdan** [comment] 2021-01-22 16:17
I'll close this because it's a browser thing, nothing we can do about it :(

**Closed by pdanpdan** 2021-01-22 16:17 UTC
Labels: :beetle: bug

**Comment by ibrainventures** [comment] 2021-01-22 16:22
Thanks for taking time on this issue. As is see, that there are also older Android-Chromes Editions effected and you sometimes see / find a better workaround for bypassing the glitching for those older / unupdated chromes pls post it here.

I am also watching on the chromium bug and i saw that it is listed as a bug .. thats a good sign (i hope :-) )

**Comment by pdanpdan** [comment] 2021-01-22 16:30
There is a workaround, but it's very ugly - on touchend/touchcancel on document to do something (like a scroll or refocus) - it might help or not, the problem is even chrome is schyzo (thinks the elements are in 2 different places)

**Comment by ibrainventures** [comment] 2021-09-05 22:39
Hi Dan,

fyi, with the 31.8.2021 / 93.0.4577.62 Release of the Android Chrome Browser, this nasty Bug seems to gone away.

All (my) bottom 0 fixed wraped elements are now always touch/clickable in my tests and sites.
In total, the updated Chrome Browser feels a lot faster on my 3+ years old cheapy-test-phones.
May you can also take a look and we can close the chromium ticket..

**Comment by pdanpdan** [comment] 2021-09-06 04:19
I put a comment there that I can no longer reproduce the problem. But I would have liked somebody to identify what they have fixed :)
