### ISSUE TITLE
Unable to add custom route on Cordova backButton

### ISSUE THREAD

**Issue by SahilKindarle** [quasarframework/quasar#8466] opened 2021-02-12 17:26 UTC
**Describe the bug**
backButton is not working for custom routing (unable to override)

I'm using the below code 
` onBackButton: function(e) {

      if (this.$route.path == "/apps/iron") {
        e.stopPropagation();
        navigator.app.exitApp();
      } else if (this.$route.path == "/apps/dryclean") {
        this.$router.replace("orders"); -----------------> I'm always redirects to home page or previous route
      } else {
        e.stopPropagation();
        // this.$q.notify("Back btn of apps layout else");
        this.$router.replace("/");
      }
    },`

`mounted() {
    document.addEventListener("backbutton", this.onBackButton, false);
  }`

**Expected behavior**
I want to redirect to desired route on clicking backbutton(Cordova)

**Platform (please complete the following information):**
@quasar/cli v1.0.7
@quasar/app v2.1.14
Quasar mode: SPA
Tested on: Cordova
OS: Android
Node: v12.13.1
NPM: 6.14.5

**Comment by pdanpdan** [comment] 2021-02-13 13:04
Check here:
https://quasar.dev/vue-directives/go-back#Cordova%2FCapacitor

I suppose you want to disable back button processing in Quasar.

duplicate of #7827

**Closed by pdanpdan** 2021-02-13 13:04 UTC

**Comment by SahilKindarle** [comment] 2021-02-13 18:25
I disabled it successfully, but I want to know how to redirect to some other path (other than previous path) on clicking Cordova backbutton
