### ISSUE TITLE
Easy way to style q-table cells. Allow function for classes?

### ISSUE THREAD

**Issue by SharpBCD** [quasarframework/quasar#7190] opened 2020-06-08 23:44 UTC
**Is your feature request related to a problem? Please describe.**
A simple style like negative color for numbers < 0, now requires to use a template.

**Describe the solution you'd like**
A prop based on functions, like `format`, to insert css classes at cell level.

**Comment by pdanpdan** [comment] 2020-06-09 07:32
Duplicate of https://github.com/quasarframework/quasar/issues/5427

**Closed by pdanpdan** 2020-06-09 07:32 UTC
Labels: feature request

**Comment by SharpBCD** [comment] 2020-06-09 11:03
I'm aware of the templates for cells and I use them extensively in other tables where I insert components to deal with them. However, simple css classes that only change the color could be simplified. There are cases where my columns are dynamically as well so, with templates, would be an overkill to implement them just to change color.
