### ISSUE TITLE
Disable the bundling of server into one file (SSR)

### ISSUE THREAD

**Issue by laekem34** [quasarframework/quasar#6658] opened 2020-03-23 09:05 UTC
**Is your feature request related to a problem? Please describe.**
Since @quasar/app 1.5.0 The feature is the Webpack production config for Webserver which compile all src-ssr into one file index.js file
The problem is that we may need the entire folder in production. I take my project as an example, i have 2 node process in my src-ssr, one is the normal quasar server, and another that communicates with the first one. When bunbling production, the second process isn't kept

**Describe the solution you'd like**
Eventually an option in quasar.conf.js that let us disable this new bundling system an keep the entire folder in production

**Additional context**
I know this issue was already mentioned in #6188, but  **th3l0g4n** had no answer however this feature could be interesting

Thanks you

**Comment by rstoenescu** [comment] 2020-05-06 05:09
Duplicate of https://github.com/quasarframework/quasar/issues/6188

**Closed by rstoenescu** 2020-05-06 05:09 UTC
Labels: feature request

**Comment by laekem34** [comment] 2020-05-06 07:53
Sorry @rstoenescu , i saw it, but there are no response in the #6188
