### ISSUE TITLE
[V1] - QSelect options in QTabPanel

### ISSUE THREAD

**Issue by sn0rcha** [quasarframework/quasar#3841] opened 2019-04-09 21:05 UTC
Operating System - Linux(4.15.0-47-generic) - linux/x64
NodeJs - 9.11.2

Global packages
  NPM - 6.9.0
  yarn - 0.32
  @quasar/cli - 1.0.0-beta.3
  cordova - Not installed

Important local packages
  quasar - 1.0.0-beta.15
  @quasar/app - 1.0.0-beta.15
  @quasar/extras - 1.1.1
  vue - 2.6.10
  vue-router - 3.0.2
  vuex - 3.1.0
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.3.4
  webpack - 4.29.6
  webpack-dev-server - 3.2.1
  workbox-webpack-plugin - 4.1.1
  register-service-worker - 1.6.2 

### What did you get as the error?
The QSelect options dissapear when hitting the QTabPanel boundary

### What were you expecting?
The Qselect options to appear over the QTabPanel boundary

### What steps did you take, to get the error?
Placed a QSelect inside a QTabPanel

We should really be able to force where the options show (like above, below, left, right) if this can't be fixed.

Thanks!

**Comment by rstoenescu** [comment] 2019-04-09 23:44
Hi,

Duplicate of https://github.com/quasarframework/quasar/issues/3242
It's gonna get fixed in beta.16

**Closed by rstoenescu** 2019-04-09 23:44 UTC
