### ISSUE TITLE
Directory Path with Turkish Characters Causes File Not Found Error

### ISSUE THREAD

**Issue by strnclk** [quasarframework/quasar#17552] opened 2024-10-01 12:33 UTC
### What happened?

When there are Turkish characters in the directory path, the system throws an error stating it can't find the file, even though the file is present. This error consumes significant time, and I believe adding a specific check for UTF-8 incompatible characters in the path could help prevent this issue.

### What did you expect to happen?

I expected the system to either correctly handle Turkish characters in the directory path or show a more informative error message specifically pointing out the unsupported characters in the path.

### Reproduction URL

https://hizliresim.com/a27duhx

### How to reproduce?

Set up a project with a directory path that contains Turkish characters (e.g., C:\ProjeTürkçe).
Try running quasar dev using the Vite setup.
You should see the file not found error for /quasar/dev-spa/client-entry.js, even though the file exists in the directory.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Platforms/Browsers

Chrome, Other

### Quasar info output

```Shell
Run quasar info in your project’s root directory and paste the output here.
```

### Relevant log output

```Shell
Add the log output of the error. For example:
15:10:46 [vite] Pre-transform error: Failed to load url /quasar/dev-spa/client-entry.js (resolved id: /quasar/dev-spa/client-entry.js). Does the file exist?
```

### Additional context

This issue happens only when the directory path contains Turkish characters. Handling non-UTF-8 characters properly or showing an error message that highlights the unsupported characters in the file path would save time and effort for developers.

**Comment by strnclk** [comment] 2024-10-01 13:25
It is not possible for me to show you this error with those applications because they work on a server basis and since I used Turkish characters, they converted and renamed them on the server, so I did not encounter this error.

I could only show you this error locally with a picture.
When the project directory is FUPİCO/Blog/Ui, I get an error because the "İ" in "FUPİCO" is a Turkish character. It took me a long time to discover that this error occurs when you use Turkish characters in a folder above the project directory and the warning is not correct.

**Comment by yusufkandemir** [comment] 2024-10-01 13:46
I couldn't reproduce it with a fresh project on macOS Sonoma 14.7.
![image](https://github.com/user-attachments/assets/82cb0020-19e6-4acb-8b20-db6ee3e095ff)
![image](https://github.com/user-attachments/assets/ab688e7b-33a4-49d3-9b4f-c52d0b8dd24c)

Can you test it on a new project to see if it happens there as well? If yes, then it might be specific to Windows, I would need to test that separately.

**Comment by strnclk** [comment] 2024-10-01 14:13
Thank you for your interest Mr. Yusuf, I tested it again and shared another image with you. There may be a problem only with the letter "İ", by the way, "Ü" did not cause a problem for me either, but I created a name with the letter "İ" again, "TÜRKÇEUİ" and got the same error again.

![Ekran görüntüsü 2024-10-01 170815](https://github.com/user-attachments/assets/1892d1f4-10a5-48e4-a62d-93489251d5ac)

I named the project from scratch in both folders, one Turkish and the other English, and used the quasar command.

**Comment by yusufkandemir** [comment] 2024-10-01 14:20
![image](https://github.com/user-attachments/assets/94c24499-cde3-4d51-9e25-e6ee29ec3e92)

As I said earlier, please create a fresh project using `npm init quasar` with this naming.

**Comment by strnclk** [comment] 2024-10-02 06:22
Hello Mr. Yusuf,
I applied what you said and got the error again. But don't get me wrong, I discovered that this was due to the naming and my problem was solved, I can now work. I wrote the notification in case others get the same error and spend a lot of time trying to solve it because they didn't get a warning about it.
I lost a lot of time, I don't want others to lose it, it would be great if a warning about this came.
Best regards.

![errocpic2](https://github.com/user-attachments/assets/5e761550-5859-42f5-bff2-c0187dbd8c58)

**Comment by yusufkandemir** [comment] 2024-10-02 10:26
`npm init quasar` is supposed to be executed outside of a Quasar project. So, you would run it inside `FUPİCO`, not `FUPİCO/Ui`.

If we find out that this problem is not specific to your device/project, we can add a warning about this to help other people.

**Comment by strnclk** [comment] 2024-10-02 10:46
I created a new project and tested it. It's not about the project. I did what you asked. You tested it in another way. I think you may not be getting the error because you do not use Windows. Maybe this error only occurs to Windows users.

![11](https://github.com/user-attachments/assets/5b5e7631-6d12-4ade-9026-717c61745734)
![2](https://github.com/user-attachments/assets/afa2ffa0-5163-4203-bc6a-86de4b42447b)

**Comment by yusufkandemir** [comment] 2024-10-02 10:57
The problem is related to npm itself as can be seen at https://stackoverflow.com/a/70936424

I've tested and npm works fine with Turkish characters on MacOS. So, this problem is specific to npm and Windows.

Since this is not related to Quasar, I am closing this issue. People can still search and find this issue to understand the problem. Thanks for reporting.

**Closed as not planned by yusufkandemir** 2024-10-02 10:57 UTC
Labels: kind/bug 🐞, bug/0-needs-info, Qv2 🔝, area/cli, flavour/quasar-cli-vite

**Comment by strnclk** [comment] 2024-10-02 11:11
Thank you. Good work.
