### ISSUE TITLE
Drawer: make disable open by swipe on iOS optional

### ISSUE THREAD

**Issue by darrenahunter** [quasarframework/quasar#366] opened 2017-02-02 05:36 UTC
In 0.13 the changelog mentions

Disabled Drawer open by swipe on iOS platform (not theme) because it interferes with Safari's page back/forward swipe feature

Could this be made a switch or optional - so it can be controlled by the developer.

**Comment by rstoenescu** [comment] 2017-02-02 09:11
Hi, yes it can be made optional, but it's completely useless. Do you have a specific use-case for it?

**Comment by darrenahunter** [comment] 2017-02-04 22:29
Hi
I'm trying to understand the behaviour here then. I understand that safari uses the left and right swipe to move through the browser history. But that would be 'interrupting' the designed navigation of the app. Also it would mean one style in iOS and another in Android. I do recall many discussion on this in the ionic threads but I can't now find the resolution - I also can't see any optional swipe attributes for iOS on there sidemenu.
Razvan I dont have a specific use case in mind at the moment but I can see the benefit in having like behaviour between iOS and Android so much as possible.
Cheers
Darren

**Comment by rstoenescu** [comment] 2017-02-04 22:57
@darrenahunter 

I have nothing against adding a prop for iOS as flag IF this is really useful. But what I'm saying is that due to how Safari works it renders the swipe feature useless. Instead of swiping to open Drawer, Safari goes back one page... It looks as if this is a bug in Quasar (which is not).
You can do a quick test. Take a look at https://github.com/quasarframework/quasar/blob/dev/src/vue-components/drawer/Drawer.vue#L140 --> remove the ios from the `if` there then `quasar dev` on Quasar repo and use Safari on iOS on the Drawer dev page. You'll see what I mean.

So the way I see it at the moment is to also use a button to trigger Drawer opening (while user is still able to swipe on Drawer to close it). This way you won't have to deal with each platform separately.

Please correct me if I am wrong or if there is a better way to still enable swiping while not having the current buggy behavior in Safari.

**Comment by darrenahunter** [comment] 2017-02-06 02:40
Hi

I do recall this issue caused a lot of discussion on the ionic forums a while back (year or so ago). I have tried to track down the threads but couldn’t find the exact one I recalled.

This is an issue for all and I have a feeling the behaviour may be different when running under a cordova complied app rather than a straight web app. 

relevent threads I found that may give ideas as to how it was handled in ionic land.

https://forum.ionicframework.com/t/disable-ios-swipe-to-go-back-for-specific-views/18808/11 <https://forum.ionicframework.com/t/disable-ios-swipe-to-go-back-for-specific-views/18808/11>

https://github.com/driftyco/ionic/issues/3470#issuecomment-100291172# <https://github.com/driftyco/ionic/issues/3470#issuecomment-100291172%23>

Cheers
Darren

**Comment by rstoenescu** [comment] 2017-03-16 21:30
Help me out a little. Can you pinpoint the exact thread you are talking about, please? Reopen with a link. Thanks!

**Closed by rstoenescu** 2017-03-16 21:30 UTC
Labels: discussion

**Comment by NikitaKA** [comment] 2017-09-18 14:57
The problem is still relevant. Use-case: I'm building an application with my own WebView, so I able to turn off Safari forward/back feature. I changed sources, removed if-statement and it works.
