### ISSUE TITLE
QDate multiple event color

### ISSUE THREAD

**Issue by AruXc** [quasarframework/quasar#7110] opened 2020-05-26 06:00 UTC
**Is your feature request related to a problem? Please describe.**

Can we add multiple event color in QDate? 

**Describe the solution you'd like**

It's will be like [v-calendar bar attribute](https://vcalendar.io/attributes.html#bars) 

one date allow multiple color

**Comment by metalsadman** [comment] 2020-05-27 18:17
@AruXc there's an example for that just below the first one https://quasar.dev/vue-components/date#Highlighting-events

**Comment by pdanpdan** [comment] 2020-06-28 12:11
Duplicate of https://github.com/quasarframework/quasar/issues/7076

**Closed by pdanpdan** 2020-06-28 12:11 UTC
Labels: feature request, has PR
