### ISSUE TITLE
After upgrading app-vite-v1.1.0, the quasar scss variable cannot be referenced normally in scss xx.vue: Undefined variable

### ISSUE THREAD

**Issue by LetFree** [quasarframework/quasar#14423] opened 2022-09-18 03:49 UTC
### What happened?

Undefined variable.
   ╷
43 │   border: 1px solid $teal-3;
   │                     ^^^^^^^
   ╵
  src\pages\index\CustomerApp\[projId]\index.vue 43:21  root stylesheet
Undefined variable.

### What did you expect to happen?

I tried to restore @quasar/vite-plugin in pnpm-lock.yaml to version 1.1.1 and solved the problem (currently the latest is not 1.2.1)

### Reproduction URL

none

### How to reproduce?

The local project has obtained the vite server, I suspect it is related to the judgment of the ssr mode in the vite-plugin
```
configureServer(server) {
      addWatcher(server.watcher, server.ws, server.moduleGraph)
      wsMap = scanWsConfig(startSocket(server.ws))
    }
```

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Style & Identity (quasar)

### Platforms/Browsers

Chrome

### Quasar info output

```Shell
Operating System - Windows_NT(10.0.19043) - win32/x64
NodeJs - 16.15.1

Global packages
  NPM - 8.19.2
  yarn - 1.22.19
  @quasar/cli - 1.3.2
  @quasar/icongenie - 2.5.3
  cordova - Not installed

Important local packages
  quasar - 2.7.7 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.0.6 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.15.3 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.39 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.1.5
  pinia - Not installed
  vuex - Not installed
  vite - Not installed
  eslint - 8.22.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - Not installed
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*
```

### Relevant log output

```Shell
Undefined variable.
   ╷
43 │   border: 1px solid $teal-3;
   │                     ^^^^^^^
   ╵
  src\pages\index\CustomerApp\[projId]\index.vue 43:21  root stylesheet
Undefined variable.
```

**Comment by rstoenescu** [comment] 2022-10-03 08:05
Please provide a reproduction repo.

**Comment by rstoenescu** [comment] 2022-10-12 17:43
Closing due to lack of a reproduction repo.
Feature is working correctly as we see it.

**Closed as completed by rstoenescu** 2022-10-12 17:43 UTC
Labels: kind/bug 🐞, bug/0-needs-info, Qv2 🔝, area/style, flavour/quasar-cli-vite
