### ISSUE TITLE
[Proposal] Minimized Icon Drawer

### ISSUE THREAD

**Issue by ralphchristianeclipse** [quasarframework/quasar#1837] opened 2018-03-26 07:30 UTC
![image](https://user-images.githubusercontent.com/25447231/37892488-93db93fa-310a-11e8-87ff-365039dfdab3.png)

Can we have a prop like mini="true" on the drawer and turn it to the image above

**Comment by rstoenescu** [comment] 2018-03-26 07:49
Duplicate of [request] Mini-drawer #661
Work on this has started. It will probably get into 0.15.10

**Closed by rstoenescu** 2018-03-26 07:49 UTC
