### ISSUE TITLE
My site has a problem since i updated to 2.66

### ISSUE THREAD

**Issue by modemb** [quasarframework/quasar#13166] opened 2022-04-13 10:29 UTC
### What happened?

all form disappeared, so request not working  

### What did you expect to happen?

it is supposed to work as usual  

### Reproduction URL

https://suguffie.com/

### How to reproduce?

 login register

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Platforms/Browsers

Chrome

**Comment by MilosPaunovic** [comment] 2022-04-13 10:33
You're gonna need to provide more details for this to make sense; from which version you've updated to 2.6.6, where the forms are supposed to appear etc.

**Comment by modemb** [comment] 2022-04-13 13:40
What king of browser are you using? It is working the link, if not try to refresh it, once you go on the site will will see the issues I am talking about

**Comment by modemb** [comment] 2022-04-13 13:41
The version was 2.6.5

**Comment by MilosPaunovic** [comment] 2022-04-13 13:42
Run `npm i vue@3.2.31` to fix the issue for now.
Related https://github.com/quasarframework/quasar/issues/13154

**Comment by modemb** [comment] 2022-04-13 13:43
Larasar.modemb.com was broke also once I updated to 2.6.6, but I did not upload it

**Comment by modemb** [comment] 2022-04-13 13:43
> You're gonna need to provide more details for this to make sense; from which version you've updated to 2.6.6, where the forms are supposed to appear etc.

Check my comments please

**Comment by modemb** [comment] 2022-04-13 14:02
> Run `npm i vue@3.2.31` to fix the issue for now.
> Related https://github.com/quasarframework/quasar/issues/13154

That did not fix it

**Comment by MilosPaunovic** [comment] 2022-04-13 15:49
Check the error in your console. It's related to latest Vue version, 3.2.32. Where do you experiencee your problem, in local dev environment, only on server...?

**Comment by modemb** [comment] 2022-04-13 18:30
> Check the error in your console. It's related to latest Vue version, 3.2.32. Where do you experiencee your problem, in local dev environment, only on server...?

The problem occurs only on build not if I run local server

**Comment by modemb** [comment] 2022-04-13 18:59
> > Check the error in your console. It's related to latest Vue version, 3.2.32. Where do you experiencee your problem, in local dev environment, only on server...?
> 
> The problem occurs only on build not if I run local server 

If you want to see the code it is the same as larasar.modemb.com

**Comment by MilosPaunovic** [comment] 2022-04-13 20:44
The problem is with newest Vue release, version 3.2.32, which was released two days ago.

When you run build command, it installs newest version and breaks things; I presume you havent run `npm i` in your local environment in the last two days, which is why you have a bit older version, which works.

**Comment by modemb** [comment] 2022-04-13 20:50
> The problem is with newest Vue release, version 3.2.32, which was released two days ago.
> 
> When you run build command, it installs newest version and breaks things; I presume you havent run `npm i` in your local environment in the last two days, which is why you have a bit older version, which works.

No I have installed that today on your command, and my local is updated first before the build so it is also 3.2.32, the problem occurs only on build production

**Comment by MilosPaunovic** [comment] 2022-04-13 20:54
If that is the case, please provide a minimal reproduction for someone to be able to take a look.

**Comment by modemb** [comment] 2022-04-13 21:52
> If that is the case, please provide a minimal reproduction for someone to be able to take a look.

Yes larasar.modemb.com, there is the link to GitHub

**Comment by MilosPaunovic** [comment] 2022-04-14 11:20
Patch version of Vue, `3.2.33` is released with a solution to this problem. Anyone stumbling upon it should run `npm i vue` to get the newest version.

[https://github.com/vuejs/core/releases/tag/v3.2.33](https://github.com/vuejs/core/releases/tag/v3.2.33)

**Comment by modemb** [comment] 2022-04-14 13:56
> Patch version of Vue, `3.2.33` is released with a solution to this problem. Anyone stumbling upon it should run `npm i vue` to get the newest version.
> 
> [https://github.com/vuejs/core/releases/tag/v3.2.33](https://github.com/vuejs/core/releases/tag/v3.2.33)

Wow, it is fixed, did lot of people had the issue?

**Closed as completed** 2022-04-14 17:15 UTC
Labels: kind/bug 🐞, bug/0-needs-info, Qv2 🔝, area/cli, flavour/quasar-cli-vite
