### ISSUE TITLE
Double render Dynamic component in q-dialog.

### ISSUE THREAD

**Issue by Basil87** [quasarframework/quasar#14598] opened 2022-10-11 08:26 UTC
### What happened?

When the opened element is opened, the Dynamic Component is rendered twice. This applies to q-tabs, q-dialog and q-expansion-item. The first time the component is rendered "before-show", and it renders a second time when "show".

### What did you expect to happen?

I expect the element to be rendered once, even before the parent element is opened.

### Reproduction URL

https://stackblitz.com/edit/vitejs-vite-cvmdpx

### How to reproduce?

1. Go to the provided reproduction lnk
2. Click on button "Open dialog"
3. Look at console, you will see double rendering

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome

**Comment by pdanpdan** [comment] 2022-10-11 08:28
duplicate of #14491

**Closed as completed by pdanpdan** 2022-10-11 08:28 UTC
Labels: kind/bug 🐞, Qv2 🔝, flavour/vite-plugin, bug/1-repro-available, area/components
