### ISSUE TITLE
QBtn loading attribute makes it freeze

### ISSUE THREAD

**Issue by danielcommesse** [quasarframework/quasar#6946] opened 2020-05-04 06:01 UTC
**Describe the bug**
1. Set the `loading` attribute to `true` of a QBtn.
2. Then set to `false`.
3. The button is now frozen it no longer responds to click events.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/danielcommesse/pen/bGVYmej?editable=true&editors=101%3Dhttps%3A%2F%2Fquasar.dev%2Fvue-components%2Fbutton

**To Reproduce**
See the `Describe the bug section`

**Expected behavior**
The button to be able to respond to clicks when the `loading` attribute is changed.

**Screenshots**
Please see the codepen above.

**Platform (please complete the following information):**
OS: MacOS Catalina 10.15.4
Quasar: 1.10.3
Browsers: Chrome & Firefox (only ones tested)

**Additional context**

**Comment by jacksonGross** [comment] 2020-05-04 06:27
Can confirm the same issue is happening to me

**Comment by pdanpdan** [comment] 2020-05-04 06:42
duplicate of #6945

**Closed by pdanpdan** 2020-05-04 06:42 UTC
Labels: bug
