### ISSUE TITLE
Q-Select with v-model and Vuex not emitting events

### ISSUE THREAD

**Issue by dhax** [quasarframework/quasar#517] opened 2017-04-18 12:37 UTC
Quasar: 0.13.4

Using q-select and binding v-model to a computed property stored in a veux state does not call the setter for this property but modifies the array in place without emitting events. This conflicts with vuex pattern only allowing changes store state within mutations, which in below example is called by the setter.

```
<q-select
  type="toggle"
  label="Status"
  v-model="status"
  :options="statusOptions"
></q-select>
```

```
computed: {
    status: {
      get () { return this.$store.state.search.status },
      set (value) { this.$store.commit('setStatus', value) }
    }
  }
```

**Comment by rstoenescu** [comment] 2017-04-18 14:22
Fixed in edge and future v0.14.

**Comment by dhax** [comment] 2017-04-21 15:44
So I tried this with 0.13.7 but with the same result. While the getter is being called correctly, the setter is never being called after change in select. Should the above work or am I missing some detail that's not documented yet?

**Comment by rstoenescu** [comment] 2017-04-22 10:22
Can you provide a reproduction repo with the isolated problem, please? Just to eliminate any confusion on my or your part.

**Comment by dhax** [comment] 2017-04-22 11:47
Hi, thanks for replying!
I made a basic example following these steps:
1. quasar init sample
2. install 0.13.7 using github.com/quasarframework/quasar-edge
3. add vuex store holding select state with simple select example in components/index.vue

http://github.com/dhax/quasar-select-test

I cannot get q-select to not modify vuex state directly, but use the provided setter instead.
As I am new to vue and quasar I am not sure what I am doing wrong here, maybe it needs another approach at all.
So thanks again for having a look and for this great framework!

**Comment by rstoenescu** [comment] 2017-04-24 09:50
Will take a look today or in max 1-2 days. Sorry for the delay.

**Comment by jsfeldman** [comment] 2017-04-26 21:20
I believe I'm experiencing the same issue (except I'm trying to listen to `@input`). It seems to only occur on `q-select` types that are multiple (like toggle and checkbox). I think it might be due to `this.emit('input', value)` not being called when `optModel` [changes](https://github.com/quasarframework/quasar/blob/dev/src/components/select/QSelect.vue#L147), but I could be misunderstanding the code.

**Comment by rstoenescu** [comment] 2017-04-27 07:44
Yes, this is due to how Vue detects changes. Will get fixed.

**Comment by rstoenescu** [comment] 2017-04-27 11:49
Hmm, seems like I didn't port the fix to v0.13 branch. Sorry.
Edge now has the fix.

**Closed by rstoenescu** 2017-04-27 11:49 UTC

**Comment by jsfeldman** [comment] 2017-04-27 13:55
I think I might have a unique case that's not fixed if you [pass arguments in your getters](https://vuex.vuejs.org/en/getters.html) and use their method of [form handling](https://vuex.vuejs.org/en/forms.html)
For instance, my HTML looks roughly like this:
```
<template v-for="prop in obj">
  <q-select type="checkbox" :value="getArr(prop)" @input="setArr({value: $event, prop})"></q-select>
</template>
```
and my store looks like this:
```
const state = {
  obj: {
    foo: [],
    bar: [],
    baz: []
  }
}

const getters = {
  getArr: (state, getters) => (prop) => {
    return state.obj[prop]
  }
}

const mutations = {
  setArr (state, {prop, value}) => {
    state.obj[prop] = value
  }
}

const store = new Vuex.Store({
  state,
  getters,
  mutations
})
```

It seems that the @input function isn't triggered in this scenario. But it looks like it works using a regular `select` element.
This may be too weird of a use case to bother fixing though haha.

**Comment by rstoenescu** [comment] 2017-04-28 13:53
I'll put this on my todo list. I'm interested into why the patch doesn't catch this particular scenario too. Thanks for sharing the details!

**Comment by Goopil** [comment] 2018-05-13 12:07
Hi, I'm experiencing the same trouble with a standard q-input
````html
<q-input  v-model="taskList.name"  />
````

```js
  computed: {
    ...mapGetters('tasks', ['taskListPerId']),
    taskList: {
      get () {
        return this.taskListPerId(this.taskListId)
      },
      set (name) {
        this.upsertTaskList({
          id: this.taskList.id,
          name
        })
      }
    }
  }
```
the set command is never called.

I'm using the quasar starterKit 1.0.3

**Comment by rstoenescu** [comment] 2018-05-13 12:12
@Goopil It's because you're setting getter/setter on taskList, then use taskList.name as model. It's taskList.name that changes, not taskList, so your set() doesn't gets called.
