### ISSUE TITLE
Significat tap delay in Fresh cordova app

### ISSUE THREAD

**Issue by kjetilge** [quasarframework/quasar#1269] opened 2017-12-10 13:34 UTC
Quasar: v0.14.4
OS: macOs Sierra
Node: v8.9.0
NPM: 5.5.1
iOS: 11.1.2

### Error
When running a simple Quasar app with a toggle button in Cordova on simulator and iPhone there is a very noticeable delay when clicking a button.

### Expected
I expected the button to be as fast as for example clicking a toggle button found in the admin example:
https://github.com/odranoelBR/vue-quasar-admin-example

- which after testing and comparing it to the admin example I found it is clearly not.

### Created new app
```
quasar init default Qtest
cd Qtest
yarn install
quasar build
quasar wrap cordova
cd cordova
cordova platform add ios
```

### Added build.json file to cordova root:
```
{
    "ios": {
        "debug": {
            "codeSignIdentity": "iPhone Developer",
            "developmentTeam": "XXX",
            "packageType": "development",
            "buildFlag": [
                "EMBEDDED_CONTENT_CONTAINS_SWIFT = YES",
                "ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES=NO",
                "LD_RUNPATH_SEARCH_PATHS = \"@executable_path/Frameworks\""
            ]
        },
        "release": {
            "codeSignIdentity": "iPhone Developer",
            "developmentTeam": "XXX",
            "packageType": "app-store",
            "buildFlag": [
                "EMBEDDED_CONTENT_CONTAINS_SWIFT = YES",
                "ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES=NO",
                "LD_RUNPATH_SEARCH_PATHS = \"@executable_path/Frameworks\""
            ]
        }
    }
}
```

### Changed Hello.vue to:
```
<template>
  <q-layout>
    <div class="layout-padding">
      <h3>Click speed test</h3>
      <q-toggle v-model="checked" label="Toggle Label" />
      <h3 v-if="checked">Showing!</h3>
    </div>
  </q-layout>
</template>

<script>
  import { QLayout, QToggle } from 'quasar'
  export default {
    data () {
      return {
        checked: false
      }
    },
    components: {
      QLayout,
      QToggle
    }
  }
</script>
```

### Started the app:
```
cordova run ios
```

To me it seems like fastclick is not working. The delay is at least 300ms.

**Comment by rstoenescu** [comment] 2017-12-10 14:23
Hi, What Quasar version are you using? 0.6.4 is the Quasar CLI version.

**Comment by kjetilge** [comment] 2017-12-10 14:54
I'm using 0.14.4. I guess It was automatically selected by the CLI ? I can see there is a version 0.15 how do I initiate with latest version ?

**Comment by kjetilge** [comment] 2017-12-10 15:02
I tried to switch to 0.15 but was unable. However I managed to upgrade to 0.14.7. But it did not help.

**Comment by rstoenescu** [comment] 2017-12-11 22:15
Can anyone reproduce this?

**Comment by pjschmidt3** [comment] 2017-12-22 17:36
I'm noticing similar results, though I haven't explored it very much yet.

**Comment by JosielFaleiros** [comment] 2017-12-27 11:20
I'm noticing similar results too :[

**Comment by cdnrg** [comment] 2018-01-05 04:34
Same here. I am also seeing the q-tab bar get stuck on multiple tabs and unable to reproduce when running on a browser or in the simulator. Screenshot is from iPad running latest iOS 11.2
![img_0002](https://user-images.githubusercontent.com/1187622/34595689-b50d0db2-f18e-11e7-8f57-57d2a96ac14f.jpg)

**Comment by Frondor** [comment] 2018-01-22 13:34
As stated in #1369 I've been experiencing this as well, but on chrome dev tools android emulator (device toolbar) and chrome browser (android app), there's a slight delay when pressing a **router-link tab**.

Looks like the underlying implementation of `router-link` component has some performance issue.

**Comment by rstoenescu** [comment] 2018-01-31 00:27
Hi All,

This is NOT Quasar related. It is iOS alone specific. Even with the latest webkit updates, unfortunatley iOS standalone apps still have the 300ms click delay, so we need to bring in fastclick to alleviate this.

What to do for pre v0.15: npm install fastclick, then in main.js
```
require('fastclick')
document.addEventListener('DOMContentLoaded', () => {
   FastClick.attach(document.body)
}, false)
```

In v0.15, this will be handled automatically (injected only when building with cordova mode for iOS platform) so you don't need to worry about it. Pushing a commit tomorrow for this (on v0.15) and closing the bug.

**Comment by Frondor** [comment] 2018-01-31 01:03
How can this be an iOS specific issue if I'm experiencing it on android 5.1 and Chrome's devtools android emulator as well. Probably you meant WebKit itself?

I already tried integrating fastclick but it didn't work, I don't think the 300ms rule has something to do with this see this answer https://stackoverflow.com/a/27175671/2474872
I'm already using `<meta name="viewport" content="width=device-width, user-scalable=no" />` and there's no such 300ms delay, besides of these tabs (which I can't really measure to be exact)

**Comment by rstoenescu** [comment] 2018-01-31 09:03
@Frondor Ok, these are two separate issues. I re-read yours and it's nothing to do with this one. So let's continue your talk on the initial ticket (reopened it). Agreed?

This one relates to iOS only and on iOS they haven't removed the 300ms delay (for standalone apps only! -- so that's PWA or Cordova). It's easily reproducible and the fix I mentioned above is valid. With Android, on the other hand, there's another story. It's been a long time since they removed the delay. Pushing a fix today for v0.15.

**Comment by rstoenescu** [comment] 2018-01-31 09:07
@Frondor Actually, pls open a new ticket with your issue. Thanks.

**Comment by rstoenescu** [comment] 2018-01-31 09:42
Pushed a commit for CLI just now to automatically inject Fastclick when building a Cordova app targetting iOS. Thanks for reporting.

**Closed by rstoenescu** 2018-01-31 09:42 UTC

**Comment by gecko-8** [comment] 2018-02-04 18:14
Confirmed the workaround! Thanks.

**Comment by danicholls** [comment] 2018-08-30 06:39
This helped until I found the fastclick iOS resume bug, where it freezes on app resume.

So I edited my package.json (calling [this repo](https://github.com/lasselaakkonen/fastclick/tree/master), based off [this pull request](https://github.com/ftlabs/fastclick/pull/550), responding to [this issue](https://github.com/ftlabs/fastclick/issues/549)), npm uninstalled and reinstalled fastclick, and then the workaround above continued to work:

```json
"dependencies": {
  "axios": "^0.18.0",
  "fastclick": "github:lasselaakkonen/fastclick"
},
```

**Comment by AstashevNikita** [comment] 2019-08-02 08:56
I had problem with IOS delay in cordova app, and just solution that offered  @danicholls  solved my problem! THX!

**Comment by danicholls** [comment] 2019-08-02 12:35
> p.s i have very strange problem. on ios i had tap on some inputs around 300ms and just after that input going selected.

Without seeing any specifics, especially if wrapped in a `label` (if I recall my own debugging correctly), you might experiment with adding the [`needsclick` class](https://github.com/ftlabs/fastclick#ignore-certain-elements-with-needsclick).
