### ISSUE TITLE
Modal cannot be closed

### ISSUE THREAD

**Issue by dfmelicor** [quasarframework/quasar#994] opened 2017-10-13 11:24 UTC
### Software version

Quasar: 0.14.4
OS: Windows 7
Node: 4.2.4
NPM: 2.14.12
Browsers: Chrome 61.0.3163.91 64 Bit
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
There is an un-handled case where modal cannot be closed

### What were you expecting?
Modal should be closed when one of the configured events are triggered

### What steps did you take, to get the error?
This can be replicated in the quasar play app.
http://quasar-framework.org/quasar-play/android/index.html#/showcase/popups/modal

Steps:
1. Open a modal
2. Refresh the page
3. Open a modal again

The modal opened in step 3 cannot be closed.

**Comment by dmig** [comment] 2017-10-16 06:44
I cannot reproduce this in quasar play app, but often experience it in my project. Can't tell why this happens, maybe js errors.

Somehow, `toggleInProgress` prop left with `true` value and nothing happens then. Changing it to `false` doesn't help.

**Comment by igorgo** [comment] 2017-10-17 19:01
It seems I've I managed to reproduce bug in browser (chrome & ff).

1. While on the page (the forward nav button of the browser is disabled - the last in the history) open a maximized modal.
2. Close modal (with button on modal). After that the forward nav button becomes available.
3. Press forward nav button - nothing happens.
4. Open modal again.

After that modal becomes not closable.

**Comment by dmig** [comment] 2017-10-18 02:28
Yes, that somehow related to history. Modal is not necessary to be maximized.
I have one case that's 100% reproducible on dev server, but doesn't occur on production build. May be vue-devtool for chrome is connected to this issue

**Comment by Iworb** [comment] 2017-10-20 12:16
It also could be reproduced in the `dev` server:
1. Open (local link)[http://localhost:8080/#/components/modal]
2. Open any modal
3. Refresh page
4. Open any modal again: it can't be closed now. Only page refresh helps.

**Comment by TKafassis** [comment] 2017-10-20 14:23
I can reproduce something similar, dunno if it's intended. 

1. Open a modal
2. Close it and forward nav button becomes available.
3. Click forward nav button and then open modal again.
4. Now modal 2 clicks on Close button to close and forward nav button becomes available again but can now be pressed 2 times.

And so on and so forth, seems like each time you do that you get 1 more History and you need to click +1 times for a new modal to close.

**Comment by jkole** [comment] 2017-10-23 18:06
@igorgo Same issue here

**Comment by jkole** [comment] 2017-10-23 19:12
Don't have time to dig into this further at the moment, but seems to me the issue arises where the modalId is checked in line 184 of QModal.vue.  I think the flow goes like this:

1. After opening then closing the first modal, we are left with openModelNumber == 0, but with the last entry in window.history containing a state object with modalId == 1. (This is what produces the odd forward nav button after closing the modal).
2. Clicking the browser forward nav button points the current window history state to the one containing that state object with modalId == 1.
3. Opening a new modal then assigns a modalId of 1 again, and a new window.history state object with modalID of 1 is pushed to the top of the stack.
4. When we try close that modal, line 184 checks if state.modalId >= this.__modalId...and since both == 1, it returns immediately rather than closing the modal.

I imagine something similar must be happening with browser refresh rather than clicking the forward nav button.

**Comment by zagreusinoz** [comment] 2017-10-25 05:16
The same thing appears to also be happening with Dialogs and ActionSheets.  The cannot be closed, either with the esc key or through code.

**Comment by zagreusinoz** [comment] 2017-10-26 05:02
Actually, I've noticed the doco mentions this issue:

> During development open/close might not be triggered because of HMR. Best would be before updating source files to close the Modal. This way HMR will correctly do its job. In production this scenario can’t happen, so no bugs for final product.

Having said that, I'm not sure what it means we should do to fix it in development.  We should close the dialog on the destroy method?

**Comment by jkole** [comment] 2017-10-26 10:48
Don’t think the entire issue is due to HMR since the quasar docs desktop examples have the same behavior (though maybe not after page refresh - need to check that).

**Comment by codedog76** [comment] 2017-11-03 08:22
@zagreusinoz have you found a development fix for this yet? Its really really annoying to constantly refresh the page to close a modal.

**Comment by rstoenescu** [comment] 2017-11-03 08:23
Fixed in future v0.15 already. Closing this. Please be patient. Sorry for the inconvenience.

**Closed by rstoenescu** 2017-11-03 08:23 UTC

**Comment by rettigd** [comment] 2017-11-15 15:53
I was able to work around this issue by setting the toggleInProgress to false on the nextTick. No idea if there are any side-effects or will work in all circumstances.
```        
  this.$refs.modal.close()
  this.$nextTick(() => {
     this.$refs.modal.toggleInProgress = false
  })
```

**Comment by Trellian** [comment] 2017-12-06 15:37
@rettigd Thanks for that, it solved my modal close problem on Chrome!

**Comment by AYapejian** [comment] 2018-01-03 02:28
Just ran into this myself, found the same workaround except it was the `active` property that needed deferred changing.   Not sure if it's related however I saw this issue when emitting an event from within a custom component contained within the q-modal, the listener hook in the parent is doing the dialog toggling.  Here is my workaround in the parent emit listener (just different prop than above)

```javascript
this.$nextTick(() => {
    this.$refs.theModal.active = false;
    this.$refs.theModal.toggleInProgress = false; 
});
```

**Comment by Cheese-Yu** [comment] 2018-05-07 07:06
I can reproduce something similar in production(Quasar: 0.14.4). 
Here is my work to fix this.
``` js
// in main.js
import { Platform } from 'quasar'
Platform.has.popstate = false
```

**Comment by vhq2016** [comment] 2018-09-10 10:32
@Cheese-Yu Thanks for that,it works!
