### ISSUE TITLE
error using commit-ish suffix on package

### ISSUE THREAD

**Issue by anktx** [quasarframework/quasar#13487] opened 2022-05-21 07:39 UTC
### What happened?

I'm trying to install leaflet version, pointing to some commit.

`package.json:`
```
{
  "dependencies": {
    "vue": "^3.0.0",
    "@vue-leaflet/vue-leaflet": "https://github.com/vue-leaflet/vue-leaflet#6bda39424bcb90c06a704e19022bc3f70f895fd7",
  },
}
```

### What did you expect to happen?

I expect Vite use specified commit version, but I have an error:

`$ yarn quasar build`
```
[vite:resolve] Failed to resolve entry for package "@vue-leaflet/vue-leaflet".
The package may have incorrect main/module/exports specified in its package.json:
Failed to resolve entry for package "@vue-leaflet/vue-leaflet".
The package may have incorrect main/module/exports specified in its package.json.
```

### Reproduction URL

--

### How to reproduce?

run `yarn quasar build`

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Quasar info output

```Shell
yarn run v1.22.19
$ /home/proj/quasar-front/node_modules/.bin/quasar info

Operating System - Linux(5.15.32-gentoo-r1-x86_64) - linux/x64
NodeJs - 16.14.2

Global packages
  NPM - 8.5.0
  yarn - 1.22.19
  @quasar/cli - undefined
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.6.6 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.0.0-beta.14 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.13.6 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.33 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.0.14
  pinia - 2.0.13 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 2.9.1 -- Native-ESM powered web dev build tool
  eslint - 8.14.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

Networking
  Host - pegasus
  eth0 - 192.168.21.100

Done in 0.44s.
```

**Comment by MilosPaunovic** [comment] 2022-05-21 11:02
Why do you think this is Quasar related problem? Have you tried creating non-Quasar repo and inmporting that component in the same way, to test does it work?

As it can be seen in the readme of the repo in question:
`This is a Beta version! And may yet be unstable! If you want to help, please reach out in an [issue](https://github.com/vue-leaflet/vue-leaflet/issues) or on [discord](https://discord.gg/uVZAfUf), or join the [discussions](https://github.com/vue-leaflet/vue-leaflet/discussions).`

**Comment by yusufkandemir** [comment] 2022-05-21 11:11
According to this URL: https://docs.npmjs.com/cli/v7/configuring-npm/package-json#github-urls
It should be `"@vue-leaflet/vue-leaflet": "vue-leaflet/vue-leaflet#6bda39424bcb90c06a704e19022bc3f70f895fd7` instead.

Also, please cross-link any issues/posts you create on other platforms to improve discoverability, decrease duplicate effort, etc. [This StackOverflow post](https://stackoverflow.com/questions/72321472/vite-internal-server-error-failed-to-resolve-entry-for-package-vue-leaflet-vu) is probably created by you as the content is basically the same, but without Quasar specifics.

This might be a problem caused by the package manager, by the library, or by Vite, but it's not a Quasar one. If this is a Vite problem and they release a fix, you need us to bump the package version, that's another story, you can create a PR or issue for a version bump if such a thing happens. So, I am closing this issue as this is not a Quasar problem.

**Closed as not planned by yusufkandemir** 2022-05-21 11:11 UTC
Labels: kind/bug 🐞, :outbox_tray: external lib issue, bug/0-needs-info, Qv2 🔝, area/cli, flavour/quasar-cli-vite
