### ISSUE TITLE
Allow last element of QBreadcrumbs to be a link

### ISSUE THREAD

**Issue by robz95** [quasarframework/quasar#10774] opened 2021-09-22 11:22 UTC
The QBreadcrumbs component of Quasar v2 always grayes out the last element:

![image](https://user-images.githubusercontent.com/18308239/134334214-5b4fea5e-84b7-42b3-86ca-35f285f6e849.png)

I am in a need to not display last element at all, therefore my last link should work as normal router link and should not be grayed out. To hack it I needed to add empty breadcrumb at the end, which I do not like at all, because I ended up with / at the end.

![image](https://user-images.githubusercontent.com/18308239/134334544-2ab2202f-6c9f-4720-b0bf-46f7130dae61.png)

Feature request:
Please, add a boolean value for QBreadcrumbs component to allow making last element work like all the others.

**Comment by yusufkandemir** [comment] 2021-09-22 11:45
Duplicate of #6042.

**Closed as completed by yusufkandemir** 2021-09-22 11:45 UTC
Labels: kind/feature 💡
