### ISSUE TITLE
the uploader in ios 10

### ISSUE THREAD

**Issue by ceau** [quasarframework/quasar#534] opened 2017-04-26 08:21 UTC
hello, everyone, I like the component uploader. it works in android and iphone under ios9 , but not work in ios 10. I review the source code , It trigger the file input . I find a paper , the trigger doesn't work in ios 10 . 
link [WebKit on iOS ignores trigger(‘click’) on file input](https://forums.meteor.com/t/webkit-on-ios-ignores-trigger-click-on-file-input/29828)

**Comment by rstoenescu** [comment] 2017-04-26 08:25
Duplicate of https://github.com/quasarframework/quasar/issues/476
Thanks for the link. Will take care of it.

**Closed by rstoenescu** 2017-04-26 08:25 UTC
