### ISSUE TITLE
Drowndown button and dynamic list with v-for

### ISSUE THREAD

**Issue by mberrg** [quasarframework/quasar#6873] opened 2020-04-23 12:38 UTC
I've a dropdown button with a div containing a list. The list has elements from a store, v-for, each element /row in the list has a button for removing that element from store. The dropdown button does not have persistent prop and remove button has a click handler. 

The error is when I click the button for removing the element, the store removes it and the list is redrawn as it should. But, then the dropdown closes. It seems that the dropdown thinks this is a click outside the dropdown since the element was removed. 

If I set persistent prop on dropdown button or use @onmousedown instead of @click on the remove button it works. But, this is not the behavior I want.

**Comment by pdanpdan** [comment] 2020-04-23 12:57
exact duplicate of https://github.com/quasarframework/quasar/issues/6737

**Closed by pdanpdan** 2020-04-23 12:57 UTC
Labels: bug
