### ISSUE TITLE
[Violation]Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.

### ISSUE THREAD

**Issue by hks2002** [quasarframework/quasar#13614] opened 2022-06-05 15:22 UTC
### What happened?

Got message in debug cosole : [Violation]Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.

### What did you expect to happen?

without it.

In my prject every page, it show 5 times of this message, but I can't locate which component caused it. so I create an new empty project, and this message still exists.

### Reproduction URL

none

### How to reproduce?

1. use quasar cli to create an new project by default.
2. check all level message, include verbose.

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

### Platforms/Browsers

Microsoft Edge

### Quasar info output

```Shell
Operating System - Windows_NT(10.0.22000) - win32/x64
NodeJs - 16.14.2

Global packages
  NPM - 8.5.0
  yarn - 1.22.18
  @quasar/cli - undefined
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.7.1 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-webpack - 3.5.3 -- Quasar Framework App CLI with Webpack
  @quasar/extras - 1.14.0 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.36 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.0.15
  pinia - Not installed
  vuex - Not installed
  electron - 18.0.4 -- Build cross platform desktop apps with JavaScript, HTML, and CSS
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.18.2 -- Babel compiler core.
  webpack - 5.73.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support
 loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 4.8.1 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  typescript - 4.5.5 -- TypeScript is a language for application scale JavaScript development
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

Networking
  Host - HKS02
  vEthernet (WSL) - 172.24.224.1
  WLAN - 192.168.3.4

Done in 1.41s.
```

**Comment by pdanpdan** [comment] 2022-06-07 09:57
duplicate of https://github.com/quasarframework/quasar/issues/12822

**Closed as completed by pdanpdan** 2022-06-07 09:57 UTC
Labels: kind/bug 🐞, bug/0-needs-info, Qv2 🔝, flavour/quasar-cli-webpack, area/components
