### ISSUE TITLE
Error creating new project: Cannot find module loader-utils

### ISSUE THREAD

**Issue by thomas66777** [quasarframework/quasar#15282] opened 2023-01-16 16:01 UTC
### What happened?

After upgrading quasar, the default scaffold project does not deploy:

```
 App •  ERROR  •  UI  in ./src/layouts/MainLayout.vue

Error: Cannot find module 'loader-utils/lib/stringifyRequest'
```

### What did you expect to happen?

should build and deploy after `quasar upgrade`

### Reproduction URL

NA

### How to reproduce?

* upgrade quasar to the latest versions using `quasar upgrade -i`
* `npm init quasar`
* `quasar dev`

The follow error is produced.  The issue appears to be in `@quasar/app-webpack` v3.7.0.  If I force version in the `package.json` to be `"@quasar/app-webpack": "3.6.2"` it works.

```
 App •  ERROR  •  UI  in ./src/layouts/MainLayout.vue

Error: Cannot find module 'loader-utils/lib/stringifyRequest'
```

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

**Comment by rstoenescu** [comment] 2023-01-16 16:41
Duplicate of https://github.com/quasarframework/quasar/issues/15280
Fixed in q/app-webpack 3.7.1 (released it moments ago)

**Closed as completed by rstoenescu** 2023-01-16 16:41 UTC
Labels: kind/bug 🐞, Qv2 🔝
