### ISSUE TITLE
autocomplete demo on Android 7.1 shows list 2 times

### ISSUE THREAD

**Issue by fsgiudice** [quasarframework/quasar#320] opened 2017-01-12 21:31 UTC
Hi,
Using quasar-framework.org from my Nexus 6p, under Android demo part from autocomplete, I got popover list displayed 2 times: first when keyboard is on screen, 2nd when keyboard hides.
Francesco

**Comment by fsgiudice** [comment] 2017-01-12 21:40
URL: http://quasar-framework.org/quasar-play/android/index.html#/showcase/form/autocomplete

**Comment by rstoenescu** [comment] 2017-01-13 08:21
@fsgiudice Hi, could you do a test please? On your Quasar clone, can you git pull and "npm run dev" then visit the autocomplete page with your Nexus? Is there a problem anymore? Have made a few enhancements to Modals and Popovers.

**Comment by rstoenescu** [comment] 2017-01-13 08:25
Also, please supply a screenshot. Thanks so much!

**Comment by fsgiudice** [comment] 2017-01-13 14:58
Hi @rstoenescu,
attached screenshots from my repo. Same behaviuor.
In first I wrote 'fre' chars and 'enter'.

![1_keyboard_active](https://cloud.githubusercontent.com/assets/2513426/21934238/fc0110d2-d9a8-11e6-9329-bb7b9a4415a3.jpeg)
![2_keyboard_hidden](https://cloud.githubusercontent.com/assets/2513426/21934239/fc0101e6-d9a8-11e6-9813-028ed8c9bc6c.jpeg)

**Comment by fsgiudice** [comment] 2017-01-14 08:33
Sorry, repeating steps I see that no enter key, but selecting item the keyboard is hidden, but the search is repeated as for picture 2.

**Comment by rstoenescu** [comment] 2017-01-16 20:27
@fsgiudice can we talk on gitter to solve this faster? Can't reproduce it no matter what I do :(

**Comment by rstoenescu** [comment] 2017-01-28 18:34
Can you guys check edge version if it has this behavior anymore? It should be fixed now.

**Comment by rstoenescu** [comment] 2017-01-28 18:34
There's one slight change to this component. Not displaying the loading part anymore. Mimicking Google Places Autocomplete feature.

**Comment by mygnu** [comment] 2017-01-30 01:15
I can confirm this issue

**Comment by rstoenescu** [comment] 2017-01-30 23:14
Finally set up an emulator with Android 7.1. Working with it is a pain. But, I managed to reproduce the issue. For some reason it seems that when Google Keyboard gets closed it sets the value again on the input (in this case "Al" which overrides the value set by Quasar).
So you type "Al", click outside of keyboard --> Quasar sets "Albania" then Google keyboard sets "Al" back. Will investigate more and write a workaround if necessary.
Thanks for your patience :)

**Comment by rstoenescu** [comment] 2017-01-31 17:14
Root caused it in Search component.
Autocomplete without using Search component works correctly.

Working on a solution.

**Comment by rstoenescu** [comment] 2017-02-01 14:44
Pushed fix to edge.

* New Popover method "reposition()"
* Fix race condition in Search
* Lots of improvements & fixes for Autocomplete (still not 100% ready for iOS)

Some small changes for Autocomplete:
* `set-width` prop has been removed. It's set automatically.
* `delay` prop has been renamed to `debounce` for consistency.
* When using an input with its own debounce (like Search component), set `:debounce="0"` on the Autocomplete otherwise you get input model debounced twice.

Examples:
```html
<q-autocomplete v-model="terms" @search="search" @selected="selected" :debounce="0">
  <q-search v-model="terms" placeholder="Start typing a country name" />
</q-autocomplete>
```

**Comment by rstoenescu** [comment] 2017-02-01 14:44
@fsgiudice & @mygnu can you test with edge version and confirm this is fixed, pls? Thanks!

**Closed** 2017-02-01 14:46 UTC

**Comment by fsgiudice** [comment] 2017-02-04 11:58
@rstoenescu,
it seems ok now.
Thank you
