### ISSUE TITLE
Feature Request QTree/QTable combination

### ISSUE THREAD

**Issue by RobertOwenJack** [quasarframework/quasar#4151] opened 2019-05-20 14:19 UTC
I am interested in a control (sometimes known as a TreeTable) which combines the navigational, filtering and selection facilities of the current QTree with the ability to display tabular data related to each node. So each node that is selected will show the node header, but also display a row with extra data. This allows the exploring of a tree structure but view data associated with each node in fixed columns. 
There is a jfiddle example here https://jsfiddle.net/fernando2684/p0k8szvj/43/  but it does not support multiple selection as far as I can tell, although it may support filtering.  I have tried looking at modifying the header slot in the qtree, but had problems with aligning columns.

**Comment by rstoenescu** [comment] 2019-09-14 18:39
Duplicate of https://github.com/quasarframework/quasar/issues/4099

**Closed by rstoenescu** 2019-09-14 18:39 UTC
