### ISSUE TITLE
Enhancements for stepper

### ISSUE THREAD

**Issue by murbanowicz** [quasarframework/quasar#204] opened 2016-11-17 20:51 UTC
Hi,
I would like to propose to build something like that: [https://assets.materialup.com/uploads/f8b108ae-94a2-48b1-a61a-1fef8019457f/preview.png](https://assets.materialup.com/uploads/f8b108ae-94a2-48b1-a61a-1fef8019457f/preview.png)

It would need key features:
1. horizontal
2. target div (so you are able to design it nicer like in the pic, not being sticked to one fixed design.

What you think?

**Comment by rstoenescu** [comment] 2016-11-17 20:57
Sounds good.

**Comment by rstoenescu** [comment] 2016-12-30 17:34
Just realized this is a duplicate of #89

**Closed by rstoenescu** 2016-12-30 17:34 UTC
Labels: proposal
