### ISSUE TITLE
Q-Date only year or year+month

### ISSUE THREAD

**Issue by cimpok** [quasarframework/quasar#11049] opened 2021-10-20 15:13 UTC
Is it possible to use Q-Date to ask for the year or year+month only and not the full date? If not, could you please consider adding this feature. Thank you.

**Comment by MilosPaunovic** [comment] 2021-10-20 15:19
Take a look at the `QScroller` extension.
https://quasarframework.github.io/quasar-ui-qscroller/docs

**Comment by pdanpdan** [comment] 2021-10-20 15:40
duplicate of https://github.com/quasarframework/quasar/issues/9419

**Closed as completed by pdanpdan** 2021-10-20 15:40 UTC

**Comment by sinbino** [comment] 2021-12-21 02:15
QScroller does not support vue3...

**Comment by hawkeye64** [comment] 2021-12-21 23:48
> QScroller does not support vue3...

It does not and will likely be deprecated.
