### ISSUE TITLE
quasar new page -f ts-composition creates an incorrect import for Vue 3

### ISSUE THREAD

**Issue by abraxxa** [quasarframework/quasar#8764] opened 2021-04-04 19:55 UTC
When running the command `quasar new page -f ts-composition pagename` the created javascript isn't correct for Vue 3 (Quasar 2)

**Codepen/jsFiddle/Codesandbox (required)**
Only Codesandbox allowed to create additional files but requires an account so I can't provide one.

**To Reproduce**
1. run `quasar new page -f ts-composition pagename`
2. Open src/pages/pagename.vue
3. Scroll down to `import { defineComponent } from '@vue/composition-api'`
4. See incorrect import

**Expected behavior**
```
<template>
  <q-page padding>
    <!-- content -->
  </q-page>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
export default defineComponent({
  // name: 'PageName'
})
</script>
```

**Platform (please complete the following information):**
Quasar Version: v2.0.0-beta11
@quasar/app Version: v3.0.0-beta.10
Quasar mode:
  - [ x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [ x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Ubuntu 20.10
Node: v14.16.0
NPM: 6.14.11
Yarn:
Browsers: -
iOS: -
Android: -
Electron: -

**Comment by abraxxa** [comment] 2021-04-04 20:49
@IlCallo ping

**Comment by bazuka5801** [comment] 2021-04-05 06:48
Same problem with Qv2

**Comment by IlCallo** [comment] 2021-04-08 10:14
@bazuka5801 yeah, the issue is Qv2 related, generated files are correct in Qv1.
The related PR has been merged, thanks @susnux for the fix

The fix will be included in next beta release

**Closed by IlCallo** 2021-04-08 10:14 UTC
Labels: :beetle: bug, 🔝 Qv2
