### ISSUE TITLE
Text not vertically centered in Firefox

### ISSUE THREAD

**Issue by webleaf** [quasarframework/quasar#14366] opened 2022-09-12 07:42 UTC
### What happened?

![image](https://user-images.githubusercontent.com/1824308/189597427-6e646320-c4a6-422a-a80c-2f29091f80c1.png)
![image](https://user-images.githubusercontent.com/1824308/189597738-e7360ade-4a90-4e72-aef7-485743f13627.png)
![image](https://user-images.githubusercontent.com/1824308/189597868-e1935b85-e638-4fbf-83ad-8684cb03e57b.png)

### What did you expect to happen?

Text should be centered

### Reproduction URL

https://codepen.io/rstoenescu/pen/xxEvBLR

### How to reproduce?

1. Go to provided reproduction link in Firefox 104.0 (64-bit) on Ubuntu
2. Text in button not vertically centered

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

SPA Mode

### Platforms/Browsers

Firefox

### Additional context

Firefox 104.0 (64-bit) on Ubuntu

**Comment by pdanpdan** [comment] 2022-09-12 09:32
duplicate of https://github.com/quasarframework/quasar/issues/13186

**Closed as completed by pdanpdan** 2022-09-12 09:32 UTC
Labels: kind/bug 🐞, Qv2 🔝, mode/spa, flavour/quasar-cli-webpack, bug/1-repro-available
