### ISSUE TITLE
The Quasar UI css was introduced when the Quasar UI was not used.

### ISSUE THREAD

**Issue by varjay** [quasarframework/quasar#5302] opened 2019-10-14 09:56 UTC
**Description error**
Since Quasar's components are optional, Quasar should not be forced to import Quasar's css without using Quasar.

Or increase can be configured in quasar.conf.js.

** Codepen / jsFiddle / Codesandbox (required)**
In the @quasar/app/template/entry/client-entry.js `import 'quasar/dist/quasar.<%= __css.quasarSrcExt %>'`, there are no configurable items.

**Expected behavior**
When you do not use Quasar components, you do not force the import of css.

** Platform (please fill in the information below): **
Operating system: macOS10.15
Browser: Chrome

**Comment by rstoenescu** [comment] 2019-10-14 10:02
Duplicate of https://github.com/quasarframework/quasar/issues/5204

**Closed by rstoenescu** 2019-10-14 10:02 UTC
Labels: bug
