### ISSUE TITLE
Tooltips on Ratings - Not working for v2

### ISSUE THREAD

**Issue by tohagan** [quasarframework/quasar#10077] opened 2021-07-14 04:18 UTC
**Describe the bug**

The tooltips feature for ratings on **your documentation page** does not work. Works for your v1 doc demo.

**Codepen/jsFiddle/Codesandbox (required)**

This demo does not show tooltips ... Testing in Chrome for Windows 
https://quasar.dev/vue-components/rating#tooltips

**To Reproduce**
1. Go to https://quasar.dev/vue-components/rating#tooltips
2. Hover on any of the 3 rating stars and no tool tip is displayed.
3. Repeat for Quasar v1 page and they work fine.   https://v1.quasar.dev/vue-components/rating#tooltips
  
**Expected behavior**
As described above.

**Comment by xwyzsn** [comment] 2021-07-15 05:51
for the docs, it's easy to fix. just set a default icon value to the rating component. By default, it's **SVG** tag, maybe something weird happened on it.
more deeply, the code of tooltip may need to reconsider. I think it may due to that vue3 changed its **slots** property

**Comment by hawkeye64** [comment] 2021-07-22 13:44
Just to add a bit more info. The tooltip is actually being created. This took a mouse doing the hover and a touchscreen to open the created div that is the tooltip in dev tools. The tooltip looks "normal". I can't see why it's not displaying, unless it's being displayed in a place other than expected.

**Comment by xwyzsn** [comment] 2021-07-22 15:04
compare to v1, the difference is that the div tag  was  wrapped by another div, 
v1
![image](https://user-images.githubusercontent.com/55912637/126661376-34760793-deaf-41ac-9874-37bcbc9a8c3d.png)
v2
![image](https://user-images.githubusercontent.com/55912637/126661945-deafc436-f1f4-46f3-89fa-329d12964eb8.png)
maybe related to this change [https://v3.vuejs.org/guide/migration/slots-unification.html#overview](https://v3.vuejs.org/guide/migration/slots-unification.html#overview)

**Comment by pdanpdan** [comment] 2021-07-22 15:08
The problem is that after it is created the div of the tooltip does not have offsetWidth and offsetHeight.

**Comment by rstoenescu** [comment] 2021-10-24 01:03
Fixed in Quasar v2.2.0

**Closed as completed by rstoenescu** 2021-10-24 01:03 UTC
Labels: kind/bug 🐞, verified :heavy_check_mark:, Qv2 🔝
