### ISSUE TITLE
Dropdown elements not closing when scrolling outside the element.

### ISSUE THREAD

**Issue by Derasm** [quasarframework/quasar#15680] opened 2023-04-05 06:59 UTC
### What happened?

Q-dropdown / Q-menu sticks on the page when scrolling outside of the page - sticking to top / bottom when scrolling far from the element. 

### What did you expect to happen?

The Dropdown / q-menu would close when scrolling outside of the element.

### Reproduction URL

https://codepen.io/Derasm/pen/vYVBjRm

### How to reproduce?

Make a background element taller than screen, that requires scrolling.
Implement a q-dropdown button / q-menu.
Open the dropdown
scroll outside the dropdown
dropdown now follows down instead of closing when you scroll

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome

### Quasar info output

```Shell
Operating System                Windows_NT(10.0.19045) - win32/x64
NodeJs                          18.12.1

Global packages
  NPM                           9.2.0
  yarn                          1.22.4
  @quasar/cli                   1.4.0
  @quasar/icongenie             Not installed
  cordova                       Not installed
```

### Additional context

This occurs on all drop-down effects

**Comment by pdanpdan** [comment] 2023-04-05 07:02
Hello
They are not designed to close when scrolled outside.
And I don't think it would be good design by default
If you want you can use a scroll observer inside the menu and close it when they are scrolled outside

**Closed as completed by pdanpdan** 2023-04-05 07:02 UTC
Labels: kind/bug 🐞, Qv2 🔝, flavour/vite-plugin, bug/1-repro-available, area/components

**Comment by Derasm** [comment] 2023-04-18 13:16
Hey PDan, is there a way i can wrap the q-select to add this functionality? Right now when i wrap it i dont get the functionality of the slots's functions, for instance: 
![image](https://user-images.githubusercontent.com/22821429/232789004-0a8312ae-bce0-427d-9373-edabda0d5d3a.png)
becomes:
```const scope = any ```

Is there a way to get the functionality of the slots after wrapping the component?

**Comment by pdanpdan** [comment] 2023-04-19 09:52
check:
https://github.com/quasarframework/quasar/discussions/14415
https://github.com/quasarframework/quasar/discussions/8761

**Comment by suhailchouhan** [comment] 2023-08-01 06:29
@pdanpdan When we scroll the window the opened q-select menu is stuck to the top of the window. As I can see the q-select menu has a position fixed which is with respect to the window/document. But the menu should be position absolute with respect to the QSelect menu.

@pdanpdan Is there any way we can make a q-select menu position absolute with respect to the QSelect component so that it can scroll with the QSelect component only?

![image](https://github.com/quasarframework/quasar/assets/118250961/60af5d66-7756-4f6d-acb1-5e81baca7bf0)

**Comment by pdanpdan** [comment] 2023-08-01 07:05
That is by design in official Quasar
If you use Qv1 then you can use a fork: https://pdanpdan.github.io/quasar-docs/vue-components/select#example--design-overview

**Comment by suhailchouhan** [comment] 2023-08-01 07:09
@pdanpdan I'm currently using Qv2. So, is there any way we can get this feature in Qv2 or any modification which I can do to achieve this feature in Qv2?

**Comment by pdanpdan** [comment] 2023-08-01 07:11
not really - it's the internal positioning algorithm

**Comment by lwpinion** [comment] 2024-09-13 18:43
> That is by design in official Quasar

Surely it's not intentional for your menus to do stuff like this?
![Screenshot 2024-09-13 132325](https://github.com/user-attachments/assets/7e1e52ce-21cf-490a-9fde-aed326a2c735)


It's really not ideal/good design for the menu to stay in the viewport as one scrolls. (If you could provide a scenario in which this would be useful, that would help me to see the bigger picture.) That being said, if you could at least change the default z-index for the menus so it sits below headers and such, that would at least be a good compromise.
