### ISSUE TITLE
QDialog/Loading breaks the page scroll in certain scenarios

### ISSUE THREAD

**Issue by jbty** [quasarframework/quasar#6754] opened 2020-04-06 17:59 UTC
**Describe the bug**
When I open and close q-dialog, the scroll bug, It's impossible to scoll down

**Video capture of the scroll bug**
[https://media.giphy.com/media/XDvaTXvXT9OQ26HRmF/giphy.gif](https://media.giphy.com/media/XDvaTXvXT9OQ26HRmF/giphy.gif)

**Codesandbox**
[https://codesandbox.io/s/priceless-resonance-119xj](https://codesandbox.io/s/priceless-resonance-119xj)

**To Reproduce**
1. open code sandbox in full screen
2. use chrome dev tools for open iphone 6/7/8 responsive screen
2. refresh page
3. click to a bodypart for go to /exercices/list/:type route
4. click to FILTER button and select any filter you want
5. click to the cross for delete filter 
5. try to scroll down in the ex list and the bug appear 

**Expected behavior**
When I select and delete a filter, I want to scroll down in the list

**Platform (please complete the following information):**
OS: windows
Node: 10
NPM: 6
Browsers: Chrome Version 80.0.3987.149 

**Additional context**
This bug appear only to **Iphone 6/7/8** mode all other screen mode works

**Comment by rstoenescu** [comment] 2020-04-06 21:07
Hi,

For the life of me, I cannot reproduce :|

**Comment by rstoenescu** [comment] 2020-04-06 21:07
Can you make a screen recording of what you are doing exactly pls? Maybe I am missing something.

**Comment by jbty** [comment] 2020-04-07 09:10
Hi,
(thanks for quasar framework <3)

![https://media.giphy.com/media/XDvaTXvXT9OQ26HRmF/giphy.gif](https://media.giphy.com/media/XDvaTXvXT9OQ26HRmF/giphy.gif)


to repeat the bug you have to do exactly the step that I wrote,

This bug appear only Iphone 6/7/8 mode, if I dont click on filter in v-dialog, or if I delete v-dialog, I can scroll down normaly. I think there is a problem with v-dialog

**Comment by pdanpdan** [comment] 2020-04-07 09:17
I suppose there is something wrong with the chrome emulation for the version you use - I'm using Chrome dev (83) on windows and all looks good.

**Comment by jbty** [comment] 2020-04-07 09:21
I use Chrome Version 80.0.3987.149, I will try with your version

**Comment by jbty** [comment] 2020-04-07 09:30
Same bug with chrome Version 83.0.4100.3 (Build officiel) dev (64 bits),

Have you refresh the page after passed in iphone 6/7/8 mode ?

**Comment by jbty** [comment] 2020-04-07 12:44
On any browser if follow exactly steps what I worte the bug appear in codesandbox

**Comment by pdanpdan** [comment] 2020-04-07 12:54
Can you try and disable the browser extensions?

**Comment by jbty** [comment] 2020-04-07 12:59
Yes, same bug in private mode without extentions

**Comment by pdanpdan** [comment] 2020-04-07 13:01
Any errors in the console? Can you make a screenshot of the elements panel including the opening body tag?

**Comment by jbty** [comment] 2020-04-07 13:07
of course,

![](https://i.ibb.co/Dzx8f6m/Annotation-2020-04-07-150414.jpg "no bug")

**Comment by pdanpdan** [comment] 2020-04-07 13:09
Elements panel :)

**Comment by jbty** [comment] 2020-04-07 13:14
![](https://i.ibb.co/QrzZ6ZB/Annotation-2020-04-07-151120.jpg "elements")

Yes when I scroll down on this list the page scroll back on top

**Comment by pdanpdan** [comment] 2020-04-07 13:37
And you can reproduce the problem on the codesandbox you shared?

**Comment by jbty** [comment] 2020-04-07 13:49
yes of course both local env and code sandbox

**Comment by thugic** [comment] 2020-04-07 14:47
I am facing the same issue. Not on Chrome, but on Safari on iOS and on Safari on a MacBook ...

**Comment by thugic** [comment] 2020-04-07 15:36
Here's my CodeSandbox example.

[https://imd3g.sse.codesandbox.io/](https://imd3g.sse.codesandbox.io/)

**Comment by pdanpdan** [comment] 2020-04-07 15:57
Ok. I can reproduce the last example on real iPhone.

**Comment by thugic** [comment] 2020-04-07 16:13
Inspecting and tracing the events, it has something to do with the `wheel` event.
If I remove the `wheel` event from the events panel, scroll gets restored.

**Comment by jbty** [comment] 2020-04-07 17:10
I confirm I have the same behavior

**Comment by thugic** [comment] 2020-04-07 17:12
I think this is the same as #6739  (which got closed as solved, but looks like things are related)

**Comment by rstoenescu** [comment] 2020-04-07 23:16
Ok, could reproduce the behavior. Will fix it.

**Comment by rstoenescu** [comment] 2020-04-08 12:18
@thugic What's the source code for your codepen pls?

**Comment by pdanpdan** [comment] 2020-04-08 12:22
https://codesandbox.io/s/imd3g

**Comment by rstoenescu** [comment] 2020-04-08 13:17
Problem is with calling internal preventScroll() with wrong second parameter in Loading.
Testing fix...

**Comment by rstoenescu** [comment] 2020-04-08 13:36
Fix will be available in "quasar" v1.9.14.

**Closed by rstoenescu** 2020-04-08 13:36 UTC
Labels: bug

**Comment by jbty** [comment] 2020-04-08 13:46
Thanks !
