### ISSUE TITLE
Problem with auto-import and functional component

### ISSUE THREAD

**Issue by eduardodgarciac** [quasarframework/quasar#5799] opened 2019-12-05 12:18 UTC
**Describe the bug**
Auto-import quasar components does not import components inside a functional component.

**Codepen/jsFiddle/Codesandbox (required)**
Sorry, I dont have one but the steps are pretty simple

**To Reproduce**
1. Create a quasar project
2. Create a functional component using a quasar component
3. Use the component somewhere

**Expected behavior**
Show the functional component without problem

**Comment by pdanpdan** [comment] 2019-12-05 12:22
Exact duplicate of https://github.com/quasarframework/quasar/issues/5373

**Closed by pdanpdan** 2019-12-05 12:22 UTC
Labels: bug
