### ISSUE TITLE
Codesandbox not working for quasarv2

### ISSUE THREAD

**Issue by kirianguiller** [quasarframework/quasar#11198] opened 2021-11-03 09:02 UTC
**Describe the bug**
Forking the codesandbox quasar minimal demo app doesn't works, it result in an error.

**To Reproduce**
1 : Fork a code sandbox from the quasar demo app  link : https://codesandbox.quasar.dev
2 : Start the app

Here is my version of the fork : https://codesandbox.io/s/eager-sky-b35nq?file=/src/App.vue 
I just forked it, and run it. I straightly got the error 

**Expected behavior**
We hsould see a working quasar app

** Error **
##### Main error
The server output this error on startup : 
```
(Use `node --trace-warnings ...` to show where the warning was created)
(node:121) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejectinga promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:121) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

##### Error with esling
The quasar app is outputting an error when starting which make the dev server failing to build
Moreover, the integrated ESLint ouptut this error : 
```
Parsing error: Adjacent JSX elements must be wrapped in an enclosing tag. Did you want a JSX fragment <>...</>?

  3 | </template>
  4 | 
> 5 | <script>
    | ^
  6 | export default {
  7 |   name: 'App'
  8 | } (null)eslint
```

**Platform (please complete the following information):**
Quasar Version: 2.0.0

Thank you !

**Comment by rstoenescu** [comment] 2021-11-03 11:23
@yusufkandemir if u have time to dig into it pls:
* Make sure the codesandbox runs latest Quasar and q/app
* Check HMR to work
* Check linting error from above

**Comment by yusufkandemir** [comment] 2021-11-03 12:39
There is something wrong with CodeSandbox's caching mechanism. In another fork, I restarted the sandbox and server, played around with some stuff, now the original fork @kirianguiller posted works as-is. However, there is still something wrong with the templates, and you can't restart or do something to get it to work.

Our current URL points to an outdated **fork** which probably got created during the transition to Qv2. From what I could understand is that the correct **template** links are:
 - https://codesandbox.io/s/quasar-cus2t (I don't exactly know where did this come from)
 - https://codesandbox.io/s/github/quasarframework/quasar-codesandbox/ (It's also set in here: https://github.com/codesandbox/codesandbox-client/blob/master/packages/common/src/templates/quasar.ts#L8)

https://codesandbox.io/s/quasar-cus2t needs to be updated(_if possible_) and pointed out to the `dev` branch. Also, I inspected other templates out there(e.g. React), I think there should be a way to update the slug from `quasar-cus2t` to `quasar` or `quasar-framework`, the template name from `quasar` to `Quasar` or `Quasar Framework`, and the icon from Node.js's logo to our logo. @rstoenescu can you make these changes if they are possible, and then make codesandbox.quasar.dev point to the new URL after those changes(e.g. https://codesandbox.io/s/quasar, https://codesandbox.io/s/quasar-framework, etc.). I am not really sure what's wrong, because with https://github.com/codesandbox/codesandbox-client/blob/master/packages/common/src/templates/quasar.ts we should already be getting them. @smolinari might have something to say too because we were investigating this some time ago.

From that point, we should be able to make some changes on https://github.com/quasarframework/quasar-codesandbox and everything would stay in sync as usual.

I found that templates and forks can get broken from time to time, and I couldn't find the main reason behind it. It might be related to how CodeSandbox manages yarn.lock files and other means of locking and caching about the environment.

**Comment by smolinari** [comment] 2021-11-03 13:09
I'm not getting that error. I'm getting this:

![image](https://user-images.githubusercontent.com/3314957/140065719-e23633f6-fd98-47d6-b527-fc9993ab6f95.png)

Scott

**Comment by MilosPaunovic** [comment] 2021-11-03 13:19
That is the error produced by the latest release [8.x.x](https://github.com/vuejs/eslint-plugin-vue/releases/tag/v8.0.0) of [eslint-plugin-vue](https://github.com/vuejs/eslint-plugin-vue) and their addition of the `vue/multi-word-component-names` rule.

**Comment by smolinari** [comment] 2021-11-03 13:21
Yeah. Success changing the 404 page component name to `ErrorPage`. 

![image](https://user-images.githubusercontent.com/3314957/140067628-3c1a3918-3817-473e-9375-f9830a4306e8.png)

I'd say it is a linting bug though, as `Error404` shouldn't be knocked under that rule. 

Scott

**Comment by MilosPaunovic** [comment] 2021-11-03 13:23
They released [8.0.2](https://github.com/vuejs/eslint-plugin-vue/releases/tag/v8.0.2) with fix for that rule; maybe CodeSandbox deps should be updated to that patch.

**Comment by smolinari** [comment] 2021-11-03 15:07
I just updated the template for codesandbox and it installs 8.0.3. It's still broken. 😢 

I've also made a comment in that issue to ask the maintainer about our problem. Ours is different than the OP of that issue. 

Scott

**Comment by rstoenescu** [comment] 2021-11-03 17:34
* Fixed legacy-v1 (for some reason had Qv2 files in it).
* Fixed codesandbox.quasar.dev to point to https://codesandbox.io/s/github/quasarframework/quasar-codesandbox
* Removed linter from codesandbox. It makes no sense to have it there. It's for rapid prototyping/experimenting and for github tickets reproductions.

However,

1. @yusufkandemir HMR not working. Maybe you can take a look at the devServer > client config and correct it pls?
2. @smolinari And for some reason, the template icon is the old one, with lowercase "q":

<img width="256" alt="image" src="https://user-images.githubusercontent.com/4665641/140159712-b1c4e5ba-00de-4321-8d20-0fbac1829af5.png">

3. @smolinari Also, the official Quasar template is yet again lowercased, and without the logo.

<img width="496" alt="image" src="https://user-images.githubusercontent.com/4665641/140162046-dd68fe1c-4b1a-47ae-bfa2-a8fb00ce8784.png">

**Comment by rstoenescu** [comment] 2021-11-03 17:36
Also, by default, when visiting the codesandbox.quasar.dev (points to  https://codesandbox.io/s/github/quasarframework/quasar-codesandbox) -- that sandbox needs a restart, cause it seems to not start properly. Not sure, but I think you're the only one that can do it @smolinari

**Comment by smolinari** [comment] 2021-11-03 18:03
@rstoenescu - 

The codesandbox.quasar.dev link is an older sandbox it seems. 

The "template" should be taken from master of the quasar-codesandbox repo to create the Quasar sandbox. So, somehow the quasar.dev link should do the same. I'll see if I can figure that out and I'll see if I can get the new logo into the codesandbox template so it shows up when creating a new sandbox, However, I asked the question on how to make that happen some time ago and never got an answer. 

Scott

**Comment by smolinari** [comment] 2021-11-04 12:52
We are getting closer. 

![image](https://user-images.githubusercontent.com/3314957/140316450-8c228ed4-1fdb-46fc-8098-54e5e3c782e1.png)

One of the maintainers is going to add the new logo to the button. 

The button now works to create a new sandbox with a properly compiling and running Quasar app. 

And, we are working on the URL to put under codesandbox.quasar.dev. Currently, what he has given me leads to a sandbox with broken compilation. 

Scott

**Comment by smolinari** [comment] 2021-11-04 15:09
@rstoenescu - This URL works for starting a Quasar app sandbox. 

https://codesandbox.io/s/github/quasarframework/quasar-codesandbox/tree/master

Working on the logo still. 

Scott

**Comment by rstoenescu** [comment] 2021-11-04 19:17
Progress being made. I love it! Thanks @smolinari ! Can you tell them to add a second row below "Quasar" to say "by Quasar Team" in the same style with the other options?

Now onto the URL. That's the thing. Made it point to the "dev" branch. And "dev" branch is the same as the "master" one. But for some reason, codesandbox caches stuff and the "dev" seems broken.... until you fork it then it works :) Unsure how to "refresh" it. If I fork it there is an option to "restart the sandbox" which would fix it.. but the links pointing directly to github have no owner (I presume) so no one can do it.

Regardless, changing our link to point to the "master" branch after I post this.
BUT there is still one issue and I need someone to play with the quasar.conf > devServer > client part to make HMR work correctly in codesandbox (which is why I was asking @yusufkandemir )

**Comment by rstoenescu** [comment] 2021-11-05 07:10
Let's close this one as the codesandbox works, but we can continue talking about the icons/logo/etc.

**Closed as completed by rstoenescu** 2021-11-05 07:10 UTC
Labels: Qv2 🔝

**Comment by smolinari** [comment] 2021-11-19 19:04
Just a quick update, we are almost there. I've asked the Q be made a capital Q. Also, they said because the template is coming from Github, they can't add the "by the Quasar Team" below the name, but they'll be doing some work in the future to make it possible. 

![image](https://user-images.githubusercontent.com/3314957/142677460-7daf1377-e00a-4474-bea8-78560937d48b.png)

Scott

**Comment by rstoenescu** [comment] 2021-11-19 20:17
Thanks for taking care of this @smolinari
