### ISSUE TITLE
Tab swipe (like on Native device)

### ISSUE THREAD

**Issue by bake09** [quasarframework/quasar#7926] opened 2020-10-20 11:11 UTC
Are any change for "swipeable Tabs" (espacially on mobile) planed?

- tabs are clickable and the content is also swipable
- tab indicator is also reactive for tab swipe position
- Content is scrollable
- tabs are swipeable (like Whatsapp on Android) with postion

This has a very fast and native feeling!

I've made a 100% Native like swiping implemantation with slider.js and materialize css Framework.

Here is an Example:

Please test this on nativly on mobile:

http://doner.io/details.html

**Comment by Theorian** [comment] 2020-11-04 17:54
q-panel could even be rebuilt to allow for native style swiping and ultimately exposed as a new quasar component. It could be handled very similarly to the drawer's "native" swiping functionality. We are very excited for this feature.

**Comment by bake09** [comment] 2020-11-04 20:00
Hi,

 

How to rebuilt this?

And espacially who would make the rebuild?

 
 

Gesendet: Mittwoch, 04. November 2020 um 18:54 Uhr
Von: "Theorian" <notifications@github.com>
An: "quasarframework/quasar" <quasar@noreply.github.com>
Cc: "bake09" <basar.oekke@gmx.de>, "Author" <author@noreply.github.com>
Betreff: Re: [quasarframework/quasar] Tab swipe (like on Native device) (#7926)


 

q-panel could even be rebuilt to allow for native style swiping and ultimately exposed as a new quasar component. It could be handled very similarly to the drawer's "native" swiping functionality. We are very excited for this feature.

**Comment by pdanpdan** [comment] 2020-12-08 07:37
duplicate of #7795, follow it there

**Closed by pdanpdan** 2020-12-08 07:37 UTC
Labels: feature request
