### ISSUE TITLE
Disabled button and tooltip

### ISSUE THREAD

**Issue by mberrg** [quasarframework/quasar#15145] opened 2022-12-19 12:15 UTC
### What happened?

A button tooltip is not showing when a q-btn is in disable state. E.g. It is usefull to have a tooltip to describe why the button is disable. 

The second issue is that if a active button is showing tooltip and then gets disabled, the tooltip text is stuck, and no longer react on mouse leave.

### What did you expect to happen?

Tooltip shown for disable button, and auto hide does is not affected by disable state.

### Reproduction URL

https://jsfiddle.net/b1sctg8f/3/

### How to reproduce?

1. Go to https://jsfiddle.net/b1sctg8f/3/
2. The first button has a tooltip that is not showing
3. The second button has a toolip and is showing. This button also has a @click that set disable to true. The tooltip is then not removed when button focus is changed.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

**Comment by pdanpdan** [comment] 2022-12-19 12:17
duplicate of https://github.com/quasarframework/quasar/issues?q=is%3Aissue+tooltip+disable+button

**Closed as completed by pdanpdan** 2022-12-19 12:17 UTC
Labels: kind/bug 🐞, Qv2 🔝, bug/1-repro-available, area/components, flavour/quasar-cli-vite

**Comment by mberrg** [comment] 2022-12-19 12:28
Ok thanks for the quick feedback. Setting type="a" on q-btn did fix both issues. 

Maybe add this to the documentation of tooltip?
