### ISSUE TITLE
[v1] [QDate] [Feature Request] Add support non-Gregorian calendars

### ISSUE THREAD

**Issue by behnoodk** [quasarframework/quasar#3359] opened 2019-02-22 08:41 UTC
Quasar's full support for RTL layouts is great and removes the first big obstacle for developers writing applications in an RTL language. 
Almost in every country that has a RTL language, the official calendar is not Gregorian, and this is the next big pain-point for developers using standard component libraries like Quasar.
Right now there are 3 RTL languages in `quasar/lang` folder with `rtl: true`.

1. Hebrew: official language in Israel where official calendar is Hebrew calendar
2. Farsi (Persian): official language in Iran (Persian calendar), Afghanistan(Persian calendar), Tajikistan, Uzbekistan.
3. Arabic: official language in about 22 countries many with Islamic calendar as their official calendar. (I may be wrong about the exact number)

I wanted to see if it is possible to make QDate play nice with Persian calendar and after a few hours I was able to add a property `persian: Boolean` to QDate and make relevant changes, which to my surprise were very few, and have a working QDate based on Persian calendar.

I have a few questions:

1. Is non-Gregorian calendars and specifically Persian calendar something that Quasar team is interested in adding support for?
2. If the answer to question 1 is yes, what is the best way I can go about it and make a PR?
3. Is the new app-extensions something that will let me add this functionality to QDate?

**Comment by rstoenescu** [comment] 2019-02-22 11:26
Hi,

For RTL languages we rely on the community to guide us. If the community does not raise any issues then we can't know something can be improved.

So, **please do the PR**. With one small amendment: `persian` Boolean should go into the RTL language pack files under `date` (only for languages that require it). Then you can make the necessary changes to QDate by referencing `this.$q.lang.date.persian === true`.

Will close this PR as it's more of a question, but looking forward to your PR!

**Closed by rstoenescu** 2019-02-22 11:26 UTC

**Comment by nothingismagick** [comment] 2019-02-22 12:20
This is a really, really good point. I know that the issue is closed, but @behnoodk I would like to talk with you about this. I am going to be working on the new "advanced i18n app-extension for Quasar 1.0" and I would love to pick your brain about this. Would you mind joining us on discord and pinging me?

https://discord.gg/Ujq2fBD
