### ISSUE TITLE
[Request] QDatetime - Adding a "Today" and/or "Now" button the the datetime popup panel.

### ISSUE THREAD

**Issue by Lou-Der** [quasarframework/quasar#1779] opened 2018-03-14 21:21 UTC
Having a date entry in the far past makes setting current date a chore by having to select year/month/date and possibly time all individually.

If you wanted  the current date/time within the panel a simple button added would make things more user friendly.

**Comment by rstoenescu** [comment] 2018-03-14 22:38
Duplicate of https://github.com/quasarframework/quasar/issues/796

**Closed by rstoenescu** 2018-03-14 22:38 UTC
