### ISSUE TITLE
Ripple animation

### ISSUE THREAD

**Issue by ODtian** [quasarframework/quasar#6543] opened 2020-03-03 19:21 UTC
**Is your feature request related to a problem? Please describe.**
A real material design ripple,which have a good implement in vuetify

**Describe the solution you'd like**
I just try to replace the ripple directive js file,and it's work perfectly.

**Describe alternatives you've considered**
Just like above,but i must build everything when the framework update

**Additional context**

**Comment by pdanpdan** [comment] 2020-03-03 19:36
Duplicate of https://github.com/quasarframework/quasar/issues/6524

**Closed by pdanpdan** 2020-03-03 19:36 UTC
Labels: feature request

**Comment by squareloop1** [comment] 2020-09-11 11:04
Also related: https://github.com/quasarframework/quasar/issues/6593
To further improve the ripple effect.
