### ISSUE TITLE
Request: support paste image into q-uploader

### ISSUE THREAD

**Issue by mjmare** [quasarframework/quasar#958] opened 2017-10-04 20:40 UTC
It would be very convenient to be able to paste an image into the q-uploader. 
It seems that this is not possible in all browsers, but even limited browser support would be nice.

TIA

**Comment by rstoenescu** [comment] 2017-10-05 07:30
Hi, isn't this a duplicate of https://github.com/quasarframework/quasar/issues/957 ? You are saying when you drag'n'drop an image... or...?

**Comment by mjmare** [comment] 2017-10-05 07:54
Don't *think* so, but being a javascript novice I might be wrong. 
By pasting I mean copying the image in another program (Ctrl-C, Command-C), switching to the browser, then pasting it (Ctrl-V, Command-V).
For pasting an image (I think other files types are not supported) requires different code than #957. I would expect drag&drop to be implemented in the q-uploader component, whereas #958 might require a separate page level component. There must be a mechanism to determine the paste target (although by default it could be the q-uploader component if there was only one). 
As a user pasting an image would be convenient if the image comes from another program (say a screenshot program), so that without first saving the image, it could be directly pasted in the web app.   
What also made me create 2 issues, is the fact that image pasting is not supported in all browsers.

**Closed** 2019-05-06 15:12 UTC

**Comment by Hugobsan** [comment] 2025-02-13 20:57
I made this in my project overwritting the header scope of q-uploader.

in Template i made this:
```
<q-uploader
...
>
<template v-slot:header="scope">
                            <div
                                class="row no-wrap items-center q-pa-sm q-gutter-xs"
                            >
                                <q-btn
                                    v-if="scope.queuedFiles.length > 0"
                                    icon="clear_all"
                                    @click="scope.removeQueuedFiles"
                                    round
                                    dense
                                    flat
                                >
                                    <q-tooltip>Limpar tudo</q-tooltip>
                                </q-btn>
                                <q-btn
                                    v-if="scope.uploadedFiles.length > 0"
                                    icon="done_all"
                                    @click="scope.removeUploadedFiles"
                                    round
                                    dense
                                    flat
                                >
                                    <q-tooltip>Remover Arquivos Enviados</q-tooltip>
                                </q-btn>
                                <q-spinner
                                    v-if="scope.isUploading"
                                    class="q-uploader__spinner"
                                />
                                <div class="col">
                                    <div class="q-uploader__title">
                                        Selecione suas imagens
                                    </div>
                                    <div class="q-uploader__subtitle">
                                        {{ scope.uploadSizeLabel }} /
                                        {{ scope.uploadProgressLabel }}
                                    </div>
                                </div>
                                <q-btn
                                    v-if="scope.canAddFiles"
                                    type="a"
                                    icon="add_box"
                                    @click="scope.pickFiles"
                                    round
                                    dense
                                    flat
                                >
                                    <q-uploader-add-trigger />
                                    <q-tooltip>Escolher arquivos</q-tooltip>
                                </q-btn>
                                <q-btn
                                    v-if="scope.canAddFiles"
                                    type="a"
                                    icon="content_paste"
                                    @click="() => handlePasteButtonClick(scope)"
                                    round
                                    dense
                                    flat
                                >
                                    <q-tooltip>Colar imagem da área de transferência</q-tooltip>
                                </q-btn>
                            </div>
                        </template>
</q-uploader
```

In Script:
```
...
const handlePasteButtonClick = async (scope: any) => {
    try {
        const clipboardItems = await navigator.clipboard.read();
        for (const item of clipboardItems) {
            for (const type of item.types) {
                if (type.startsWith("image/")) {
                    const blob = await item.getType(type);
                    const file = new File([blob], "clipboard-image.png", {
                        type,
                    });
                   //handleFileUpload is a function that i call to put files in POST formData, in usual upload or copy-paste upload
                    handleFileUpload([file]);
                    toast.success("Imagem da área de transferência adicionada com sucesso!");
                    // Adding image for q-uploader visualization
                    if (scope) {
                        scope.addFiles([file]);
                    }
                    return;
                }
            }
        }
        toast.warning("Não há imagens na área de transferência.");
    } catch (err) {
        console.error("Erro ao acessar a área de transferência:", err);
    }
};
...

```

**Comment by Hugobsan** [comment] 2025-02-13 21:01
I implemented this feature in my project by overriding the `header` slot of `q-uploader`.

**Template:**

```vue
<q-uploader ...>
  <template v-slot:header="scope">
    <div class="row no-wrap items-center q-pa-sm q-gutter-xs">
      <q-btn
        v-if="scope.queuedFiles.length > 0"
        icon="clear_all"
        @click="scope.removeQueuedFiles"
        round
        dense
        flat
      >
        <q-tooltip>Clear all</q-tooltip>
      </q-btn>

      <q-btn
        v-if="scope.uploadedFiles.length > 0"
        icon="done_all"
        @click="scope.removeUploadedFiles"
        round
        dense
        flat
      >
        <q-tooltip>Remove uploaded files</q-tooltip>
      </q-btn>

      <q-spinner v-if="scope.isUploading" class="q-uploader__spinner" />

      <div class="col">
        <div class="q-uploader__title">Select your images</div>
        <div class="q-uploader__subtitle">
          {{ scope.uploadSizeLabel }} / {{ scope.uploadProgressLabel }}
        </div>
      </div>

      <q-btn
        v-if="scope.canAddFiles"
        type="a"
        icon="add_box"
        @click="scope.pickFiles"
        round
        dense
        flat
      >
        <q-uploader-add-trigger />
        <q-tooltip>Choose files</q-tooltip>
      </q-btn>

      <q-btn
        v-if="scope.canAddFiles"
        type="a"
        icon="content_paste"
        @click="() => handlePasteButtonClick(scope)"
        round
        dense
        flat
      >
        <q-tooltip>Paste image from clipboard</q-tooltip>
      </q-btn>
    </div>
  </template>
</q-uploader>
```

**Script:**
```ts
const handlePasteButtonClick = async (scope: any) => {
  try {
    const clipboardItems = await navigator.clipboard.read();

    for (const item of clipboardItems) {
      for (const type of item.types) {
        if (type.startsWith("image/")) {
          const blob = await item.getType(type);
          const file = new File([blob], "clipboard-image.png", { type });

          // handleFileUpload is a function that adds files to the POST formData,
          // used both for standard file uploads and clipboard paste uploads.
          handleFileUpload([file]);

          toast.success("Clipboard image added successfully!");

          // Adding the image to q-uploader for visualization
          if (scope) {
            scope.addFiles([file]);
          }
          return;
        }
      }
    }

    toast.warning("No images found in the clipboard.");
  } catch (err) {
    console.error("Error accessing clipboard:", err);
  }
};
```
