### ISSUE TITLE
QVirtualScroll - Slot for loading or items of lazy loading with dynamic size

### ISSUE THREAD

**Issue by slowaways** [quasarframework/quasar#8353] opened 2021-01-21 02:59 UTC
**Is your feature request related to a problem? Please describe.**
In QVirtualScroll, when you scrolling quickly, and the item limit of `virtual-scroll-slice-size` combined with `virtual-scroll-slice-ratio-*` is reached, a list with obfuscated items¹ in light and dark (slightly dark) is displayed during lazy loading. No matter the size of the item used in your computed QVirtualScroll list, the size of each item in that obfuscated list is the same: about 25 px. 
I would like to add a `QSkeleton` design to replace this list.

**Describe the solution you'd like**
I would like to have a `template(v-slot:loading)`:
In the template slot, you would put the equivalent for 1 item on the list. If you use a list-type virtual scroll, the suggestion is to use a `q-item` with its respective, `q-item-section`, `q-item-label`, `q-skeleton`, etc.

**Describe alternatives you've considered**
Automatically compute the size of the items in the list that is displayed during lazy loading according to the value of the `virtual-scroll-item-size` prop.

**Additional context**
¹ List with obfuscated items used for lazy loading (size of the items is fixed - 25px):
![Captura de tela 2021-01-20 234325](https://user-images.githubusercontent.com/9668277/105273080-5a5ac280-5b79-11eb-82d4-02dae3a32b84.png)
\* You can hardly see the dark item.

For context: each item in my `QVirtualScroll` have 105 pixel:
![105274933-018d2900-5b7d-11eb-8f84-ffd851d6ddcf](https://user-images.githubusercontent.com/9668277/105275196-8415e880-5b7d-11eb-9cdd-f12ab2362f65.png)

**Comment by pdanpdan** [comment] 2021-01-21 05:32
Duplicate of #7821

**Closed by pdanpdan** 2021-01-21 05:32 UTC
Labels: feature request

**Comment by slowaways** [comment] 2021-01-21 15:20
Ôh, serious? Ok.

**Comment by slowaways** [comment] 2021-02-10 21:02
Thanks PDan for implement the alternative in this Issue in #8357!
