### ISSUE TITLE
QTable in 1.4 shows scrollbars now when it's not necessary

### ISSUE THREAD

**Issue by rfox12** [quasarframework/quasar#5511] opened 2019-11-08 13:01 UTC
Big user of QTable.  (Awesome improvements btw!.  However I've noticed with the most recent update that q-tables which use pagination (e.g. 25 rows per page) *sometimes* now have a scrollbar that scrolls up and down 2 pixels inside the table.  I will try to product a codepen example soon as I can.  

Also as a side note there is this really weird mouse-over effect on every-other-row where the scrollbar appears and disappears.  It's like something is sizing?

**Comment by pdanpdan** [comment] 2019-11-08 14:38
Do you have row selection checkboxes active?

**Comment by pdanpdan** [comment] 2019-11-08 19:31
Also what platform, os, browser?

**Comment by rfox12** [comment] 2019-11-09 00:27
@pdanpdan Thank you for your patience.  This is the codepen https://codepen.io/robert123789/pen/XWWYZGq

The steps to reproduce were very simple... I took the "[Expanded row and custom selector](https://quasar.dev/vue-components/table#Expanding-rows)" codepen and simply added three attributes on the <q-table> tag: **dense**, **flat**, and **bordered**.  I could not replicate the "wiggle" effect yet where the scrollbar appears and disappears.

**Comment by pdanpdan** [comment] 2019-11-11 08:53
I cannot replicate it :(
Can you please try to debug it when you can reproduce it and check to see what element is causing the overflow?

**Comment by metalsadman** [comment] 2019-11-11 16:12
using the doc's example https://quasar.dev/vue-components/table#Example--Expanded-row-and-custom-selector in the codepen, it does show a scroll bar in chrome (Version 78.0.3904.97), not in firefox  (69.0). The docs version doesn't show scrollbars tho.

**Comment by pdanpdan** [comment] 2019-11-11 21:51
Can you please check the scaling set in windows (scale and layout). From what I remember it sometimes does funny things.

**Comment by rfox12** [comment] 2019-11-11 23:00
@pdanpdan You're a genius--that's exactly the case for me.  I have big desktop monitors and I'm running at 125% so I can see the text.  Once I scale back to 100% the scrollbars are gone.  Is there anything we can do to "fix" this?

**Comment by pdanpdan** [comment] 2019-11-11 23:04
I'll have to do some research. I think there was a similar issue opened. I'll keep you posted when I find something.

**Comment by rfox12** [comment] 2019-11-12 00:00
Thanks I'm also taking a more critical look.  Seeing lots of weird things when scaling now...  for instance... now TD cells on the same row (TR) can be different heights (e.g. off by 0.185 at 110% scale).  And I have absolutely no idea why.  All of the CSS inspection has the same source attributes.

**Comment by pdanpdan** [comment] 2019-11-12 10:23
I think it's something related to HiDPI support on stable Windows version of Chrome. Because I cannot reproduce it on Win 10 with HiDPI set to 100%, 125%, 150% - but I'm using Chrome 80.0.3962.2 (Official Build) dev (64-bit).
Let's hope it'll get fixed in the next stable release of Chrome.

**Comment by pdanpdan** [comment] 2020-02-08 18:16
I cannot reproduce in current generation browsers and without HiDPI changes.
With HiDPI changes it depends on OS/browser, it's nothing we can fix, sorry.

**Closed by pdanpdan** 2020-02-08 18:16 UTC
Labels: bug
