### ISSUE TITLE
qheader or qfooter reveal will malfunction in mobile browser

### ISSUE THREAD

**Issue by hanzoz** [quasarframework/quasar#7617] opened 2020-08-12 00:46 UTC
when scroll page using reveal for header or footer on mobile via any browser, it will malfunction, please refer to the video I provided.

At first my app showing this error, and I thought maybe its my app got problem but then I tried using quasar.dev headr and footer documentation page https://quasar.dev/layout/header-and-footer to test and it shows the same error.

Not sure whether is there anyone who notice this problem with the header or footer reveal

please check the video here
https://streamable.com/r7lufn

**Comment by pdanpdan** [comment] 2020-08-12 07:20
duplicate of https://github.com/quasarframework/quasar/issues/7436

**Closed by pdanpdan** 2020-08-12 07:20 UTC
Labels: bug
