### ISSUE TITLE
SSR: Preloading and critical CSS injection features are not functioning

### ISSUE THREAD

**Issue by chetzof** [quasarframework/quasar#8263] opened 2020-12-24 18:30 UTC
**Describe the bug**
I'm not sure if that's a bug, maybe that worked before and stopped working now, or it is a feature that hasn't been implemented yet, but vue-server-renderer has the ability to detect the currently rendered components and actively inline the critical CSS into the HTML source and then preload the rest of the files.

I'm currently migrating from the standalone vue-cli + ssr based app to the quasar standalone app and had encountered this issue that results in low scores for medium-large projects with lots of code (not noticeable if you run the demo quasar app in perf tester) compared to our vanilla vue ssr version.

**Codepen/jsFiddle/Codesandbox (required)**
Install the default demo

**To Reproduce**
Run `quasar build -m ssr`
Start the server and open localhost:3000

**Expected behavior**
If we hit the `/` route backed by the code
```
  {
    path: '/',
    component: () => import('layouts/MainLayout.vue'),
    children: [
      { path: '', component: () => import('pages/Index.vue') }
    ]
  },
```

The components `layouts/MainLayout.vue` and `pages/Index.vue` should be **preloaded** and some of their CSS should be inlined as part of critical CSS  technique. 

**Current behavior**
The render-critical components `layouts/MainLayout.vue` and `pages/Index.vue` js and css assets are loaded by the low-priority **prefetch** tag which significantly decreases the performance. 

https://w3c.github.io/resource-hints/#prefetch
The prefetch link relation type is used to identify a resource that might be required **by the next navigation**

The mentioned assets are not needed on the next navigation, they are needed on the current navigation.

Here's what Lighthouse tool thinks about this and hits the website with a huge penalty
![CleanShot 2020-12-24 at 20 28 26@2x](https://user-images.githubusercontent.com/467230/103102841-b8ea5a80-4626-11eb-8a6b-7034430e11de.png)

**Comment by chetzof** [comment] 2020-12-24 18:35
I would be glad to become a contributor to this truly amazing framework. Maybe someone can point me where I should look and I'll try to fix this myself and submit a pull request.

 I'm still digging in quasar internals but but I don't think i'm getting any close

**Comment by rstoenescu** [comment] 2020-12-24 21:18
Of course that the critical path CSS works. But you are mixing the features here. Are you talking about preloading (this will actually lower the score and it's been removed as an option), about critical path CSS or about lazy loading assets? Or about the vendor chunk which bundles everything from node_modules by default (but can be changed or removed entirely through quasar.conf.js).

**Comment by chetzof** [comment] 2020-12-25 13:22
Sorry for filing such a confusing request. Let me explain: i'm aware about the vendor chuck settings, i know that you can enable, disable or disable it partially. Ignore that, because here i'm discussing what happens with user code mainly stored in /src dir.

So first of all - lazy-loading: yes, all the routes are hooked up using dynamic `import('my-page.vue')` imports. Thus they are extracted from the main app.js/app.css file and loaded separately.  That's a good thing, because the user does not need to receive the assets that are on other pages (which he may not even visit). These assets are properly added to the html as`rel=prefetch` resources. That works in quasar beautifully :white_check_mark:

However if we have two lazy-imported pages
```
 {
    path: '/',
    component: () => import('layouts/MainLayout.vue'),
    children: [
      { path: '/list', component: () => import('pages/ListPage.vue') },
      { path: '/about-us', component: () => import('pages/AboutUsPage.vue') }
    ]
  },
```


**What should happen if we visit the list route `/list`?**
The MainLayout.vue is lazy-loaded thus it has to be loaded separately. Ok lets load it separately. 
Is it needed now or may be potentially needed later? It is needed right now asap: then the following tags should be added to the html source
```
<link rel="preload" href="/css/main-layout.css" as="style">
<link rel="preload" href="/js/main-layout.js" as="script">
<link rel="stylesheet" href="/css/main-layout.css">
<body>
<script src="/js/main-layout.js" defer>
</body>
```

Same goes for the page itself: it is lazy-loaded, thus not included in the app bundle and it is needed now, thus `rel=prefetch` is not acceptable. We should get
```
<link rel="preload" href="/css/list-page.css" as="style">
<link rel="preload" href="/js/list-page.js" as="script">
<link rel="stylesheet" href="/css/list-page.css">
<body>
<script src="/js/list-page.js" defer>
</body>
```

And finally all other pages should be prefetched 
```
<link rel="prefetch" href="/css/about-us-page.css" as="style">
<link rel="prefetch" href="/js/about-us-page.js" as="script">
```


The final output should be

```
<link rel="prefetch" href="/css/about-us-page.css" as="style">
<link rel="prefetch" href="/js/about-us-page.js" as="script">

// This is main-bundle, may or may not include vendor code (not important in this case
<link rel="preload" href="/css/vendor.css" as="style">
<link rel="preload" href="/js/vendor.js" as="script">

<link rel="preload" href="/css/main-layout.css" as="style">
<link rel="preload" href="/js/main-layout.js" as="script">
<link rel="preload" href="/css/list-page.css" as="style">
<link rel="preload" href="/js/list-page.js" as="script">

<link rel="stylesheet" href="/css/vendor.css">
<link rel="stylesheet" href="/css/main-layout.css">
<link rel="stylesheet" href="/css/list-page.css">
<body>
<script src="/js/vendor.js" defer>
<script src="/js/list-page.js" defer>
<script src="/js/main-layout.js" defer>
</body>
```

What happens now, everything is prefetched except the vendor bundle

```
<link rel="prefetch" href="/css/about-us-page.css" as="style">
<link rel="prefetch" href="/js/about-us-page.js" as="script">

// This is main-bundle, may or may not include vendor code (not important in this case
<link rel="preload" href="/css/vendor.css" as="style">
<link rel="preload" href="/js/vendor.js" as="script">

<link rel="prefetch" href="/css/main-layout.css" as="style">
<link rel="prefetch" href="/js/main-layout.js" as="script">
<link rel="prefetch" href="/css/list-page.css" as="style">
<link rel="prefetch" href="/js/list-page.js" as="script">

<link rel="stylesheet" href="/css/vendor.css">
<body>
<script src="/js/vendor.js" defer>
</body>
```


Obviously, if we visit the route `/about-us`, the prefetched and preloaded assets should switch places.
And I did not mention up until now the critical CSS inlining. Some of the css that is preloaded, should be inserted into the html source.
Also please see https://vue-hn.herokuapp.com/ (https://github.com/vuejs/vue-hackernews-2.0)
That's where all the things i've talked are working fine.

Sorry for such a long comment...

**Comment by rstoenescu** [comment] 2020-12-27 03:46
Reopening for reading and replying to comments above when time is available again.

**Comment by laekem34** [comment] 2021-01-08 14:46
Hello @chetzof ,
Since @quasar/app@2.0.0, the `preloadChunk` that handles the injection of styles and scripts relating to components has been removed.
This deletion is temporary, as long as compatibility with the html-webpack-plugin v4 plugin cannot be ensured.
Currently, only vendor and main js/css are preloaded, others are prefetched
[https://quasar.dev/quasar-cli/app-upgrade-guide#What%E2%80%99s-new-in-v2](https://quasar.dev/quasar-cli/app-upgrade-guide#What%E2%80%99s-new-in-v2)

If I'm not mistaken, it was the preload-webpack-plugin that handled this, but vue-server-renderer also handles the preloading of assets based on the components used in the renderer.
[https://github.com/vuejs/vue/blob/dev/src/server/template-renderer/index.js](https://github.com/vuejs/vue/blob/dev/src/server/template-renderer/index.js) L.157

@rstoenescu 
Even if preload-webpack-plugin has been removed, could the assets be preloaded with vue-server-renderer?

**Comment by dmitry** [comment] 2021-02-01 10:34
@laekem34 @chetzof have you found a workaround for this issue?

**Comment by laekem34** [comment] 2021-02-01 10:52
@dmitry No, until the issue is fixed, i use a white overlay on the viewport and i remove it when window was loaded to avoid to see elements that do not have their css loaded yet

_Worst solution ever_ 😅 (directly in index.template.html, very bad but temporary)!

```
 <style>
      #overlay-screen {
        background-color: #fff;
        position: fixed;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        z-index: 9999;
      }
 </style>
<body>
    <div id="overlay-screen"></div>
    <!-- DO NOT touch the following DIV -->
    <div id="q-app"></div>
    <script>
      window.addEventListener('load', function() {
        document.getElementById('overlay-screen').remove();
      })
    </script>
</body>
```

**Comment by dmitry** [comment] 2021-02-01 11:30
@rstoenescu any idea why it can work like that: `app` and `vendor` CSS files has `<link rel="stylesheet"` in SSR HTML result, and the chunked are not?

**Comment by hawkeye64** [comment] 2021-02-01 12:53
It looks like https://github.com/GoogleChromeLabs/preload-webpack-plugin has become deprecated and now the fork at https://github.com/vuejs/preload-webpack-plugin should be used instead.

**Comment by hawkeye64** [comment] 2021-02-01 12:59
Meh, not much improvement or changes. And looks like it's not maintained either.

**Comment by penushkin** [comment] 2021-03-31 14:27
@rstoenescu will this issue not be resolved in quasar-app 2.x? (namely, the absence of dynamically imported modules of this page in the html css changs during server rendering)!

**Comment by rstoenescu** [comment] 2021-03-31 14:40
The critical CSS injection has been implemented. Preloading will be added after the webpack v5 migration.

**Closed by rstoenescu** 2021-03-31 14:40 UTC
Labels: :beetle: bug

**Comment by unsalkorkmaz** [comment] 2022-12-06 10:28
Any update on this?

**Comment by LeoonLiang** [comment] 2023-02-09 03:20
> The critical CSS injection has been implemented. Preloading will be added after the webpack v5 migration.

Hi! Is it usable in quasarv1.0?
