### ISSUE TITLE
Datetime picker selection getting auto update on ios platform.

### ISSUE THREAD

**Issue by sachinkumaram-veoci** [quasarframework/quasar#4885] opened 2019-08-13 13:25 UTC
**Describe the bug**
Datetime picker selection getting auto update on ios platform.

![Datetime error-480 (1)](https://user-images.githubusercontent.com/40174764/62944544-89a0c800-bdfa-11e9-915c-c055f75d802a.gif)

**Comment by hawkeye64** [comment] 2019-08-13 15:12
@sachinkumaram-veoci 
Just to be clear, this looks like you are using the App Extension QDateTimePicker, which has its own repo: https://github.com/TobyMosque/app-extension-qdatetimepicker

A couple of questions:
1. Is this the iOS simulator or actual device? If actual, what is the iOS version number and mobile model?
2. Can you try the examples on your IOS device to see if yu have the same issue at : https://qdatetimepicker.netlify.com/#/

**Comment by TobyMosque** [comment] 2019-08-13 15:59
Strange, unfortunately i don't have a apple ecosystem, so i don't know how to reproduce that.
I tested the lasted version at https://appetize.io, them worked as expected.

**Comment by sachinkumaram-veoci** [comment] 2019-08-13 16:11
> @sachinkumaram-veoci
> Just to be clear, this looks like you are using the App Extension QDateTimePicker, which has its own repo: https://github.com/TobyMosque/app-extension-qdatetimepicker
> 
> A couple of questions:
> 
> 1. Is this the iOS simulator or actual device? If actual, what is the iOS version number and mobile model?
> 2. Can you try the examples on your IOS device to see if you have the same issue at : https://qdatetimepicker.netlify.com/#/
> 
> mentions: @TobyMosque

It happens on both i.e Simulator & actual device.
iOS version: 12.2
Mobile model:iPhone 6s,iPhone 6

**Comment by sachinkumaram-veoci** [comment] 2019-08-13 16:12
> @sachinkumaram-veoci
> Just to be clear, this looks like you are using the App Extension QDateTimePicker, which has its own repo: https://github.com/TobyMosque/app-extension-qdatetimepicker
> 
> A couple of questions:
> 
> 1. Is this the iOS simulator or actual device? If actual, what is the iOS version number and mobile model?
> 2. Can you try the examples on your IOS device to see if you have the same issue at : https://qdatetimepicker.netlify.com/#/
> 
> mentions: @TobyMosque

It actually converts to local times zone, by adding 5:30 in selected time. How to prevent this.

**Comment by hawkeye64** [comment] 2019-08-13 17:03
@sachinkumaram-veoci and the examples were exhibiting the same behavior for you?

**Comment by sachinkumaram-veoci** [comment] 2019-08-14 03:56
@TobyMosque This issue can also be replicated on safari.

**Comment by danicholls** [comment] 2019-08-17 04:21
Note: seems to've been resolved by updating Quasar: https://github.com/TobyMosque/app-extension-qdatetimepicker/issues/38#issuecomment-521951533

**Comment by rstoenescu** [comment] 2019-08-17 08:46
Hi,

Please continue on the appropriate repo (https://github.com/TobyMosque/app-extension-qdatetimepicker). Thank you.

**Closed by rstoenescu** 2019-08-17 08:46 UTC
Labels: bug
