### ISSUE TITLE
Thank you for your excellent framework and it is recommended that the Qtree component provide a prop to specify the propName of childNode

### ISSUE THREAD

**Issue by zxcvc** [quasarframework/quasar#6809] opened 2020-04-14 03:49 UTC
Thank you for your excellent framework and it is recommended that the Qtree component provide a prop to specify the propName of childNode

E.g：
<q-tree  :nodes="tree"  childName="sub"><q-tree/>

**Comment by zxcvc** [comment] 2020-04-14 03:51
E.g：
<q-tree :nodes="tree" child-name="sub">

**Comment by zxcvc** [comment] 2020-04-14 03:53
E.g：  < q-tree :nodes="tree" child-name="sub">< /q-tree >"

**Comment by pdanpdan** [comment] 2020-04-17 13:54
Duplicate of https://github.com/quasarframework/quasar/issues/6661 on the same page

**Closed by pdanpdan** 2020-04-17 13:54 UTC
Labels: feature request
