### ISSUE TITLE
electron main process can not start again.

### ISSUE THREAD

**Issue by faxinwang** [quasarframework/quasar#8135] opened 2020-12-02 03:01 UTC
**Describe the bug**
Previously the electron mode works fine, but yesterday when I kill the main process from window's task manager, it just cann't start anymore, and aways stoping at here:

 • Compiling:
 ├── Renderer process ████████████████████ 100% done in 3695 ms
 └── Main process     █                    0%

when I modify code of renderer process, it recompiles renderer process and stop at there again. 
when I modify code of main process or quasar.conf.js , nothing happens, it don't recompile the main process as expected.

solutions I have tried:

1. I  shut down my computer and restart it after a while, then I start up vscode and `quasar dev -m electron`, nothing changed.
1. I upgrade my Electron dependency from 10.0.1 to 11.0.3, nothing changed.
1. I delete node_modules and execute `yarn install`, `quasar dev -m electron`, nothing changed.
1. I removed .quasar folder and run `quasar dev -m electron`, nothing changed.
1. I git clone the code into another directory and `yarn install`, `quasar dev -m electron`, nothing changed.

I have struggled on this issue for more then ten hours and still have no progress, I don't know where is the problem. Can anybody help me, please. 

**Platform (please complete the following information):**
OS: Win10
Node: 12.16.1
NPM: 6.13.4
Yarn: 1.22.4
Electron: 10, 11
vscode: 1.51.1  x64

**Comment by faxinwang** [comment] 2020-12-02 03:20
after stucked for several minutes, it generates the following output. Note that before this problem happens, the code was running norminally. And I have never seen error output like the following before.
------------------------------------------------------

 • Compiling:
 ERROR  Failed to compile with 1 errors  

 error  in ./src/pages/Index.vue?vue&type=template&id=4bc9d7de&scoped=true&

Syntax Error:   SyntaxError: Unexpected token (6:835)
  2 :                 borderRadius: '2px',
  3 :                 backgroundColor: '#027be3',
  4 :                 height: '2px',
  5 :                 opacity: 0.25,
  6 :             }},nativeOn:{"mousewheel":function($event){return onTabScroll($event)}}},[_c('q-tabs',{ref:"qtab  s",staticClass:"text-grey fit-width",attrs:{"no-caps":"","dense":"","inline-label":"","active-color":"primary","  align":"left","breakpoint":0},model:{value:(curTabId),callback:function ($$v) {curTabId=$$v},expression:"curTabI  d"}},_l((tabItems),function(item,idx){return _c('q-tab',{key:item.key,staticClass:"note-tab",attrs:{"name":item.  key},on:{"click":function($event){return onTabClicked(idx)}}},[_c('div',[_c('span',[_v(_s(item.name))]),_c('q-ic  on',{staticClass:"tab-icon",attrs:{"name":"close"},on:{"click":function($event){$event.stopPropagation();return   closeTab(item)}}})],1)])}),1)],1),_c('div',{class:{'nav-shadow':showNavShadow}},[_c('Nav',{attrs:{"elnode":tabIt  ems[curIdx].elnode,"note-node":tabItems[curIdx].elnode?.data,"index":curIdx}}),_c('q-resize-observer',{on:{"resi  ze":size => navHeight = size.height}})],1),_c('q-tab-panels',{staticClass:"panels",style:({height: `calc(100% -   ${navHeight}px)` }),attrs:{"keep-alive":"","animated":""},model:{value:(curTabId),callback:function ($$v) {curTa  bId=$$v},expression:"curTabId"}},_l((tabItems),function(item,idx){return _c('q-tab-panel',{key:item.key,staticCl  ass:"q-pa-none q-mx-auto",attrs:{"name":item.key}},[(item.type == 'notebook')?_c('notebook',{key:item.key,attrs:  {"note-node":item.elnode.data,"elnode":item.elnode,"index":idx},on:{"showNavShadow":show => showNavShadow = show  }}):(item.type == 'setting')?_c('setting'):_e()],1)}),1)]],2)}}
                                                                                                                         
                                                                                                             
                                                                                                      
                                                                                               
                                                                                        
                                                                                 
                                                                          
        ^

  - buble.js:2757 Parser.pp$4.raise
    [notehub]/[vue-template-es2015-compiler]/buble.js:2757:13

  - buble.js:647 Parser.pp.unexpected
    [notehub]/[vue-template-es2015-compiler]/buble.js:647:8

  - buble.js:2196 Parser.pp$3.parseExprAtom
    [notehub]/[vue-template-es2015-compiler]/buble.js:2196:10

  - buble.js:6003 Parser.<anonymous>
    [notehub]/[vue-template-es2015-compiler]/buble.js:6003:24

  - buble.js:6129 Parser.parseExprAtom
    [notehub]/[vue-template-es2015-compiler]/buble.js:6129:31

  - buble.js:2047 Parser.pp$3.parseExprSubscripts
    [notehub]/[vue-template-es2015-compiler]/buble.js:2047:19

  - buble.js:2024 Parser.pp$3.parseMaybeUnary
    [notehub]/[vue-template-es2015-compiler]/buble.js:2024:17

  - buble.js:1966 Parser.pp$3.parseExprOps
    [notehub]/[vue-template-es2015-compiler]/buble.js:1966:19

  - buble.js:1949 Parser.pp$3.parseMaybeConditional
    [notehub]/[vue-template-es2015-compiler]/buble.js:1949:19

  - buble.js:1925 Parser.pp$3.parseMaybeAssign
    [notehub]/[vue-template-es2015-compiler]/buble.js:1925:19

  - buble.js:1954 Parser.pp$3.parseMaybeConditional
    [notehub]/[vue-template-es2015-compiler]/buble.js:1954:28

  - buble.js:1925 Parser.pp$3.parseMaybeAssign
    [notehub]/[vue-template-es2015-compiler]/buble.js:1925:19

  - buble.js:2443 Parser.pp$3.parsePropertyValue
    [notehub]/[vue-template-es2015-compiler]/buble.js:2443:87

  - buble.js:2434 Parser.pp$3.parseProperty
    [notehub]/[vue-template-es2015-compiler]/buble.js:2434:8

  - buble.js:2380 Parser.pp$3.parseObj
    [notehub]/[vue-template-es2015-compiler]/buble.js:2380:23

  - buble.js:2179 Parser.pp$3.parseExprAtom
    [notehub]/[vue-template-es2015-compiler]/buble.js:2179:17




 @ ./src/pages/Index.vue?vue&type=template&id=4bc9d7de&scoped=true& 1:0-215 1:0-215
 @ ./src/pages/Index.vue
 @ ./src/router/routes.ts
 @ ./src/router/index.ts
 @ ./.quasar/app.js
 @ ./.quasar/client-entry.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 (webpack)/hot/dev-server.js ./.quasar/client-entry.js

No type errors found
Version: typescript 4.0.5
Time: 1288924 ms

**Comment by jaybo** [comment] 2020-12-02 04:48
Does it run as SPA?

**Comment by faxinwang** [comment] 2020-12-02 05:11
yes, it's run as SPA.

**Comment by hawkeye64** [comment] 2020-12-04 22:23
@faxinwang Seems you have a Vue template (that's been compiled to a render function - vue does this automatically) that's ended up into your style section where the sass compile is now complaining.

Check your <template>, <script> and <style> tags so that the start and end where expected. This could also be caused by missing and ending tag in your html code (would have been caught by a linter, I would think).

**Comment by faxinwang** [comment] 2020-12-05 02:56
@hawkeye64 thank you, before this problem happen, the code runs normally and I did not changed any code after it happened. I checked the code again and have not found any problem. 

I'm wondering what would stop the main process code from compiling and then running.

**Comment by hawkeye64** [comment] 2020-12-05 13:05
Would be best if you post the source to Index.vue in here so we can introspect it.

**Comment by faxinwang** [comment] 2020-12-05 14:08
It's very nice of you to willing to help, Thanks very much!!!.

```vue
<template>
    <q-page class="index-page">
        <div v-if="tabItems.length === 0" class="non-selected">
            <p>no notebook is selected</p>
            <i class="el-icon-back" />
        </div>

        <template v-else>
            <q-scroll-area
                horizontal
                ref="tabsScrollArea"
                class="tabs-scroll-area"
                thumb-style="thumb-style"
                @mousewheel.native="onTabScroll"
            >
                <q-tabs
                    v-model="curTabId"
                    no-caps
                    dense
                    inline-label
                    class="text-grey fit-width"
                    active-color="primary"
                    align="left"
                    ref="qtabs"
                    :breakpoint="0"
                >
                    <q-tab
                        v-for="(item,idx) in tabItems"
                        :key="item.key"
                        :name="item.key"
                        class="note-tab"
                        @click="onTabClicked(idx)"
                    >
                        <div>
                            <span>{{ item.name }}</span>
                            <q-icon class="tab-icon" name="close" @click.stop="closeTab(item)"></q-icon>
                        </div>
                    </q-tab>
                </q-tabs>
            </q-scroll-area>

            <div :class="{'nav-shadow':showNavShadow}" >
                <Nav :elnode="tabItems[curIdx].elnode"
                    :note-node="tabItems[curIdx].elnode?.data"
                    :index="curIdx"
                    />
                <q-resize-observer @resize="size => navHeight = size.height" />
            </div>

            <q-tab-panels v-model="curTabId" 
                class="panels"  
                :style="{height: `calc(100% - ${navHeight}px)` }"
                keep-alive 
                animated>
                <q-tab-panel
                    v-for="(item,idx) in tabItems"
                    :key="item.key"
                    :name="item.key"
                    class="q-pa-none q-mx-auto">
                    <notebook v-if="item.type == 'notebook'"
                        :note-node="item.elnode.data" :elnode="item.elnode" 
                        :index="idx" :key="item.key" 
                        @showNavShadow="show => showNavShadow = show" />
                    <setting v-else-if="item.type == 'setting'" />
                </q-tab-panel>
            </q-tab-panels>
        </template>
    </q-page>
</template>

<script lang="ts">
import {
    defineComponent,
    PropType,
    reactive,
    computed,
    ref,
    toRef,
    watch,
    onMounted,
    onBeforeUnmount,
} from "@vue/composition-api";
import Vue from "vue";

import { NoteNodeImpl,NotebookImpl,DataManager } from "src/store/db";
import bus from "src/common/bus";
import Notebook from "components/notebook/Notebook.vue";
import Nav from 'components/Nav.vue';
import Setting from 'components/setting/Setting.vue';
import store from 'src/store';

interface TabItem{
    key:string;
    name:string;
    type:'notebook' | 'setting';
    elnode?: any;
}

let tabItems: TabItem[] = reactive<TabItem[]>([]);
let tabsScrollArea = ref();
let curIdx = ref<number>(0);
let curTabId = ref<String>("");
let qtabs = ref<Vue>();
let navHeight = ref<number>(20)
let showNavShadow = ref(false)

function init(){
    while(tabItems.length > 0) tabItems.pop();
    // while(panelContents.length > 0) panelContents.pop();
    curIdx.value = 0;
    curTabId.value = "";
    qtabs.value = undefined;
    navHeight.value = 20;
    showNavShadow.value = false;
    bus.$emit("reset:noteTree");
    DataManager.init();
}

function onTabScroll(evt: WheelEvent) {
    evt.stopPropagation();
    let scroll = tabsScrollArea.value;
    scroll.setScrollPosition(scroll.getScrollPosition() + evt.deltaY, 150);
}

function closeTab(item:TabItem) {
    let idx = tabItems.indexOf(item);
    if(idx < 0) return
    item.elnode.notebook = null;
    tabItems.splice(idx, 1);
    if (item.key === curTabId.value) {
        let nextIdx = idx >= tabItems.length ? idx - 1 : idx;
        if(nextIdx >= 0){
            curTabId.value = nextIdx >= 0 ? tabItems[nextIdx].key : "";
            curIdx.value = nextIdx;
            if(tabItems[nextIdx].type == 'notebook'){
                bus.$emit("setCurrentNode", tabItems[nextIdx].elnode)
            }
        }
    }
}

function scrollToActiveTab() {
    if (qtabs.value && qtabs.value instanceof Vue) {
        let children = qtabs.value.$children;
        let offset = 0;
        for (let child of children) {
            if (child.$el.clientWidth) {
                offset += child.$el.clientWidth * 0.7;
            }
            // @ts-ignore
            if (child.isActive && child.name === curTabId.value) {
                offset -= child.$el.clientWidth;
                try {
                    tabsScrollArea.value.setScrollPosition(offset, 100);
                } catch (_) {}
            }
        }
    }
}

async function openNotebook(noteNode: NoteNodeImpl, elnode, place = -1) {
    let idx = tabItems.findIndex(item => item.elnode == elnode);
    if (idx < 0) {
        elnode.notebook = (await NotebookImpl.getById(noteNode.id)) || null;
        showNavShadow.value = false;
        if(!elnode.running) elnode.running = {cntJs:-1}
        elnode = reactive(elnode)
        const item: TabItem = {
             key: elnode.data.id,
            name: elnode.data.name,
            type: 'notebook',
            elnode,
        }
        if (place === -1) {
            tabItems.push(item);
            curIdx.value = tabItems.length - 1;
        } else {
            tabItems.splice(place,0, item);
            curIdx.value = place;
        }
    }
    else{
        curIdx.value = idx;
    }
    curTabId.value = noteNode.id;
    setTimeout(scrollToActiveTab, 100);
}


function onTabClicked(idx:number){
    if(tabItems[idx].type == 'notebook'){
        bus.$emit('setCurrentNode', tabItems[idx].elnode)
    }
    curIdx.value = idx;
}

function openSetting(){
    const item:TabItem = {
        key:"setting",
        name:"setting",
        type:'setting',
    }
    tabItems.push(item);
}


export default defineComponent({
    name: "PageIndex",
    components: { Notebook,Nav, Setting },
    setup(props) {
        init();
        onMounted(() => {
            bus.$on("nodeClicked", openNotebook );
            bus.$on("delNoteNode", closeTab );
            bus.$on("openSetting", openSetting);
        });

        onBeforeUnmount(()=> {
            bus.$off("nodeClicked", openNotebook );
            bus.$off("delNoteNode", closeTab );
            bus.$off('openSetting', openSetting)
        })

        return {
            // refs
            curTabId,
            tabsScrollArea,
            qtabs,
            navHeight,
            // data
            // panelContents,
            tabItems,
            // flags
            showNavShadow,
            curIdx,
            // event handler
            closeTab,
            onTabScroll,
            onTabClicked,
        };
    }
});
</script>

<style lang="less" scoped>
.index-page {
    @tabH: 36px;
    padding-top: @tabH;

    width: 100%;
    height: 100%;

    min-height: 500px !important;
    background-color: @theme-color-bg;
    border-bottom-left-radius: @body-border-radius;
    border-bottom-right-radius: @body-border-radius;
    
    .thumb-style{
        border-radius: '2px';
        background-color: '#027be3';
        height: '2px';
        opacity: 0.25;
    }

    .tabs-scroll-area {
        height: @tabH;
        box-sizing: border-box;
        position: absolute;
        top: 0;
        left: 0;
        right: 0;

        // remove the left and right default icons
        /deep/ .q-tabs__arrow--left {
            display: none;
        }
        /deep/ .q-tabs__arrow--right {
            display: none;
        }
    }

    .panels {
        width: 100%;
        border-bottom-right-radius: @body-border-radius;
    }
   
    .nav-shadow{
        z-index: 20;
        position: relative;
        top: 0;
        left: 0;
        right: 0;
        box-shadow: 0px 3px 3px #bbb;
    }
}

.note-tab {
    padding-left: 14px;
    padding-right: 3px;
    .tab-icon {
        font-size: 1em;
        margin-left: 5px;
        visibility: hidden;
        &:hover {
            color: red;
        }
    }

    &:hover .tab-icon {
        visibility: visible;
    }
}

.non-selected {
    color: #808080;
    margin-top: 40px;
    text-align: center;
    user-select: none;
    i {
        font-size: 1.6em;
    }
}
</style>
```

**Comment by hawkeye64** [comment] 2020-12-05 17:43
@faxinwang Having Github highlight code made finding the issue pretty easy (when the highlighting seemed to get broken).

It's this line of code:
```
:note-node="tabItems[curIdx].elnode?.data"
```
You are using null conditional operator (`?.`), but that's not supported yet in the upstream processors we are using. Adjust your code accordingly and probably best to stick with ES2016 for now.

Closing as this is a non-issue until upstream processors, that we consume, offer this functionality.

**Closed by hawkeye64** 2020-12-05 17:43 UTC
Labels: bug

**Comment by faxinwang** [comment] 2020-12-06 07:38
@hawkeye64 Thank you again, it works now.
