### ISSUE TITLE
No selecting icon display 

### ISSUE THREAD

**Issue by diadal** [quasarframework/quasar#8571] opened 2021-03-04 08:16 UTC
https://next.quasar.dev/vue-components/uploader

no selecting icon display 

<img width="677" alt="Screen Shot 2021-03-04 at 9 14 43 AM" src="https://user-images.githubusercontent.com/19895516/109932284-494db700-7cca-11eb-876e-3a6668b228be.png">

**Comment by rstoenescu** [comment] 2021-03-04 13:10
Duplicate of https://github.com/quasarframework/quasar/issues/8558
Already fixed. Available in next Quasar beta.

**Closed by rstoenescu** 2021-03-04 13:10 UTC
Labels: :beetle: bug, 🔝 Qv2
