### ISSUE TITLE
Quasar Language Packs / Dynamical (non-SSR) 

### ISSUE THREAD

**Issue by HamrerasSlimane** [quasarframework/quasar#11650] opened 2021-12-12 10:03 UTC
**Dynamical (non-SSR) it only works with the languages "de" and "en-US"**
https://quasar.dev/options/quasar-language-packs#dynamical-non-ssr-
src\boot\quasar-lang-pack.js when run in "Quasar CLI".

why does it work with "de" and "en-US" languages and it does not work with "fr", "ar" ...... .
When used with:
 `import { Quasar } from 'quasar'
export default async () => {
  const langIso = 'fr' 
  try {
    await import(     
     /* webpackInclude: /(de|en-US)\.js$/ */
      'quasar/lang/' + langIso
      )
      .then(lang => {
        Quasar.lang.set(lang.default)
      })
  }
  catch (err) {
    console.log(err);
  }
}`
 it generated the following warning message:
`quasar-lang-pack.js?f5b9:16 Error: Cannot find module './fr'
    at app.js:224
    at async Array.__WEBPACK_DEFAULT_EXPORT__ (quasar-lang-pack.js?f5b9:9)
    at async start (client-entry.js?2f39:89)`

**Platform (Browsers : Google Chrome ):**
Quasar Version: v2.3.4
@quasar/app Version: v3.2.5

Quasar mode:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX
  - [ ] Vite Plugin

Additonal Info:
- [ ] Typescript
- [ ] SFC usage with `<script setup>`
- [x] Vuex
- [x] Prettier (eslint)
- [ ] Standard (eslint)
  
Tested on:
  - [x] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Windows 10 Professionnel 21H2
Node: v16.13.1
NPM: 8.2.0
Yarn: 1.22.17
Browsers: Google Chrome Version 96.0.4664.93 (Build officiel) (64 bits)
iOS:
Android:
Electron:

**Comment by pdanpdan** [comment] 2021-12-12 10:07
duplicate of https://github.com/quasarframework/quasar/issues/11529
you can try reading the example you linked to

**Closed as completed by pdanpdan** 2021-12-12 10:07 UTC
Labels: Qv2 🔝

**Comment by HamrerasSlimane** [comment] 2021-12-12 10:21
why does it work with "de" and "en-US" languages and it does not work with "fr", "ar" ......

**Comment by HamrerasSlimane** [comment] 2021-12-22 12:37
OK thank you its walking with
/ * webpackInclude: /(ar|fr|en-US)\.js$/ * /

for more consulted
https://webpack.js.org/api/module-methods/#magic-comments
