### ISSUE TITLE
[V1] reduce delay before Dialog is shown

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#3473] opened 2019-03-05 06:20 UTC
I don't like that there's a small delay before my dialogs are shown.
I looked through the code and think it's this line:
https://github.com/quasarframework/quasar/blob/7186dab1c8dc914c64f97195c1f5fa110acb0547/quasar/src/components/dialog/QDialog.js#L159

#### I'd like to request for us to remove this delay or set it to a different value.

**Comment by webnoob** [comment] 2019-03-05 06:32
@rstoenescu I'd be happy to do a PR for this if needs be. I propose a new prop:

```
delay: {
  type: Number,
  default: 600
}
```

**Comment by mesqueeb** [comment] 2019-03-05 07:09
PS, if no special reason for 600ms, I would set the default to 300 (or 0), just to make the default feel more responsive.

**Comment by webnoob** [comment] 2019-03-06 07:53
Ok, so the `$emit('show')` doesn't actually control the speed of the dialog showing so this isn't just a prop change from what I can see so far.

**Comment by webnoob** [comment] 2019-03-06 08:03
Right, there technically no delay being applied to the display of the modal at all. The modal is added to the dom via:

https://github.com/quasarframework/quasar/blob/7186dab1c8dc914c64f97195c1f5fa110acb0547/quasar/src/components/dialog/QDialog.js#L144

At this point I'm not sure where to take this.

**Comment by mesqueeb** [comment] 2019-03-06 12:41
Are you sure? Show portal could mean the mask and then a show event is emit to show the actual dialog after 600 ms.

**Comment by webnoob** [comment] 2019-03-06 13:11
I debugged it this morning and the setTimeout() delay had no effect. The dialog showed, then my console log would appear after 3 seconds (with a 3000 delay).

**Comment by mesqueeb** [comment] 2019-03-11 01:23
@rstoenescu Do you have any idea why the Dialog feels like there's a short delay before it is shown?

**Comment by mesqueeb** [comment] 2019-03-16 23:21
@webnoob I think Razvan's latest commit might have something to do with this issue:

https://github.com/quasarframework/quasar/commit/f93b6835dd44e0a70dc19ef5e1bddfa313b0bd0b

**Comment by rstoenescu** [comment] 2019-03-16 23:23
@mesqueeb thanks for pointing this out. Closing bug as the transitions are now set to 300ms.
Will be available in beta.11

**Closed by rstoenescu** 2019-03-16 23:23 UTC

**Comment by mesqueeb** [comment] 2019-03-16 23:24
Thanks a lot! I'll see how it feels in next beta!

**Comment by rstoenescu** [comment] 2019-03-16 23:25
It feels snappier, even if it doesn't has to do with performance at all :)

**Comment by webnoob** [comment] 2019-03-17 00:15
@mesqueeb Well it appears he made the same changes I made locally. I "think" the issue is I didn't change the CSS transitions! Will take note for future.
