### ISSUE TITLE
Full conformance with WAI-ARIA Authoring Practices 1.1 - Section 6 - Developing a Keyboard Interface

### ISSUE THREAD

**Issue by svella** [quasarframework/quasar#6736] opened 2020-04-03 12:57 UTC
ARIA tags/attributes and tabindindex are not the whole story of keyboard navigation. With composite widgets like QLIst, QTree, QTab, QTable using a tab index for every embedded item just doesn't cut it when they contain more than about a half dozen items is completely unusable with several dozen or more items because you have to tab through every item in one of these widgets to get past it to the next one.

https://www.w3.org/TR/wai-aria-practices-1.1/#keyboard spells out very clearly the conventions to be followed for keyboard accessibility for these types of widgets, and those conventions are very similar to the desktop application conventions found in WIndows/MacOS/Linux that have been around for decades.

**Comment by pdanpdan** [comment] 2020-04-03 13:13
Generic duplicate of #6562 and #6560. I'm closing it because it cannot be tracked being too generic.

**Closed by pdanpdan** 2020-04-03 13:13 UTC
Labels: feature request

**Comment by svella** [comment] 2020-04-03 14:26
Sorry but this is a systemic problem with the whole framework and I felt it should be dealt with as such. Will log individual tickets for the components that concern me the most, but really every component should be be checked for conformance if you want Quasar to legitimately claim to be accessible.

**Comment by pdanpdan** [comment] 2020-04-03 14:32
I agree with that, but this ticket is too generic, two of the components are already covered, some of them cannot be covered by default (QList) - so it's better to keep them separate.

Also PRs are welcome.
