### ISSUE TITLE
[v1] Persistent dialog forced to close by back button

### ISSUE THREAD

**Issue by tegola** [quasarframework/quasar#4400] opened 2019-06-17 15:10 UTC
**Describe the bug**
A dialog with persistent: true prevents the dialog itself from closing when clicking/tapping the backdrop or when hitting the escape key on a desktop.

However, it doesn't prevent it when tapping the Android back button. I don't know if it's the expected behavior but I guess it's not.

**Codepen/jsFiddle (required)**
Couldn't make it work, event the [demo](https://quasar.dev/vue-components/dialog#Example--Persistent) on the docs won't close the dialog but go back to the previous route

**To Reproduce**
1. Build a simple app with a `<q-dialog :persistent="true">`
2. Open it in your browser and press the escape button on the keyboard or tap the backdrop and see that it won't close (correct)
2. Open it on the android emulator or on a device
3. Press the back button and notice how it closes

**Expected behavior**
The back button shouldn't close the dialog.

**Platform (please complete the following information):**
OS: MacOS 10.13.6
Node: 9.11.1
NPM: 6.9.0
Yarn: 1.15.2
Browsers: Chrome 75 on Desktop, Chrome 74 on Android emulator
Android: 7.1.1 on emulator

**Comment by rstoenescu** [comment] 2019-06-17 15:12
Hi,

Unfortunately, Quasar cannot control the user navigation, so it's impossible to prevent this behavior.

**Comment by tegola** [comment] 2019-06-17 15:20
I don't want to prevent the behavior, I just want to stop the dialog from closing, and this is actually handled by quasar, which is listening to the back button press and closing the dialog instead of going back to the previous route.

My use case is a form that asks the user if it really want to cancel input since it could lose data by closing the dialog, so I'm using `persistent: true` and a "Cancel" button for explicitly closing the dialog, but there is no way to prevent the back button from force-closing the dialog with the current state of things.

**Comment by tegola** [comment] 2019-06-17 16:13
I wanted to add: the best way for my use case is that I could prevent the hiding (maybe catching @before-hide) instead of disabling it and handling myself with the cancel button.

**Comment by rstoenescu** [comment] 2019-06-17 16:51
Pushed a fix to avoid force-closing QDialog when back button is pressed (only for Cordova!) and QDialog is set to be persistent. Back button triggering navigation can only be stopped (and it is) for Cordova only -- on a desktop or mobile browser, it is impossible to stop user from navigating and this is by design in every browser.

Fix will be available in rc.5

**Closed by rstoenescu** 2019-06-17 16:51 UTC
Labels: bug

**Comment by tegola** [comment] 2019-06-18 07:05
Thanks! Any ETA fro rc5?

**Comment by rstoenescu** [comment] 2019-06-18 07:57
@tegola later today ;)

**Comment by AntonERG** [comment] 2025-12-08 20:16
@rstoenescu is it possble to make some prop like 'no-esc-dismiss' for android back button? Or block android back button when 'no-esc-dismiss' is true?
