### ISSUE TITLE
[v1]QDate - years gets fighting for a place

### ISSUE THREAD

**Issue by emprove** [quasarframework/quasar#3613] opened 2019-03-18 20:33 UTC
Beta 11.
All browsers.
Years gets fighting for a place.
https://pasteboard.co/I62sUjI.jpg

**Comment by pdanpdan** [comment] 2019-03-19 06:47
Please provide a codepen with your code. Also what os, what browser.
Here everything looks good: https://v1.quasar-framework.org/vue-components/date

**Comment by pdanpdan** [comment] 2019-03-20 06:56
@emprove Can you provide more details, please? Else we'll just close this as cannot reproduce.

**Comment by emprove** [comment] 2019-03-20 08:06
I use $flex-cols = 24 variable. With default value = 12 its ok.

**Comment by pdanpdan** [comment] 2019-03-20 08:11
Very funny :)
Ok, good point - I'll take a look.

**Comment by rstoenescu** [comment] 2019-03-20 17:08
Fix will be available in beta.12

**Closed by rstoenescu** 2019-03-20 17:08 UTC
