### ISSUE TITLE
QSelect bad call / value of filter function after showPopup()

### ISSUE THREAD

**Issue by woloda375** [quasarframework/quasar#4423] opened 2019-06-19 12:51 UTC
When qselect is showed via showPopup() and there was set input value via updateInputValue(value) before, then filter function with empty value should not be called.

Demo
https://jsfiddle.net/wx2a9tgu/16/

Version
v1.0.0-rc.5

**Comment by rstoenescu** [comment] 2019-06-19 12:56
Duplicate of #4412
Fix will be available in final 1.0.0

**Comment by pdanpdan** [comment] 2019-06-20 10:39
I'm not sure what is the problem in your fiddle.
I attached a modified one that works: https://jsfiddle.net/ryxatezk/4/

**Closed** 2019-06-20 10:40 UTC
Labels: bug

**Comment by woloda375** [comment] 2019-06-20 10:53
@rstoenescu, in your example you used a filter and model property (I used for simplify only model property). But there is a bug too. Please:
1)  run the example, 
2) click on Correct log button
3) Select a Goole from drop down menu (click on it)
4) optional: click elsewhere on page to lose a focus for qselect
5) press Correct log button
6) observe js console log, where val value is empty

**Comment by rstoenescu** [comment] 2019-06-20 11:03
@woloda375 That's not a bug. When you got a non empty model your users want to see all other options as well. Otherwise while user has something selected he/she'd always get that one selected option (and only that), which is bad UX.

**Comment by woloda375** [comment] 2019-06-20 11:21
@pdanpdan, I understand your point of view, but I think, that problem is somewhere else. You could have selected a model and you could want to prefill a new option(but you could have pop up with options opened too). Look at your  modified example https://jsfiddle.net/gwyn19L7/, where model is set on load time. And if button is pressed, you could observe js log, that "val" value is filled with correct value (is not empty).
