### ISSUE TITLE
QDatatable responsiveness breaks on cordova android

### ISSUE THREAD

**Issue by mygnu** [quasarframework/quasar#843] opened 2017-08-29 08:44 UTC
### Software version

Quasar: 0.14.2
OS: Linux
Node: 7.10
NPM: 5.x
Browsers: cordova
iOS:
Android: 7
Any other software related to your bug:

### What did you get as the error?
Qdatatable displayed in desktop mode

### What were you expecting?
it to be responsive
### What steps did you take, to get the error?
Works fine in emulator and/or browser,
if you disable purifyCss in config, works as expected.

**Comment by rstoenescu** [comment] 2017-08-29 10:01
Duplicate of https://github.com/quasarframework/quasar/issues/662

**Closed by rstoenescu** 2017-08-29 10:01 UTC
