### ISSUE TITLE
Wrong QButton text align on long texts

### ISSUE THREAD

**Issue by FragsterAt** [quasarframework/quasar#4871] opened 2019-08-12 13:43 UTC
Quasar 1.0.5

Button text align is always center, if text is longer, than one line.

**Codepen/jsFiddle/Codesandbox (required)**
https://jsfiddle.net/g89mLx5r/2/

**To Reproduce**
see jsfiddle

**Expected behavior**
Same align on short and long texts, passed from align prop.

**Comment by hawkeye64** [comment] 2019-08-12 21:56
Issue confirmed: Here is another example (codepen) to validate the issue: https://codepen.io/Hawkeye64/pen/mdbePyR

**Comment by hawkeye64** [comment] 2019-08-13 12:52
The cause of this is in QBtn.js in this code:
```js
      h('div', {
        staticClass: 'q-btn__content text-center col items-center q-anchor--skip',
        class: this.innerClasses
      }, inner),
```
Even if you try to override this using `style="text-align: left!important"` it won't work. :(

**Comment by hawkeye64** [comment] 2019-08-13 13:50
@FragsterAt 
![image](https://user-images.githubusercontent.com/10262924/62947018-04d49080-bd9f-11e9-9323-159279c3db89.png)

**Comment by FragsterAt** [comment] 2019-08-13 13:58
@hawkeye64 , I cant find this in docs. Anyway, this is confusing behaviour, due to align attribute.

**Comment by rstoenescu** [comment] 2019-08-13 14:08
`align` attribute refers to how icon + label get aligned.

**Comment by FragsterAt** [comment] 2019-08-13 14:34
@rstoenescu https://jsfiddle.net/woh2vb53/ it also works not quite right

**Comment by hawkeye64** [comment] 2019-08-13 15:25
The text is **always** centered at it inherits from `text-center` from parent div. 
My PR fixes this.

**Comment by hawkeye64** [comment] 2019-08-13 15:26
@FragsterAt Sorry, I was just indicating to you that I had done a fix to core and the above image is the results. Should it get merged, then it'll be available to you.

**Comment by hawkeye64** [comment] 2019-08-13 16:30
@FragsterAt I've been convinced that we should not be adding to core if there are ways around. That being said, this is a situation where you'd use slots, rather than reply on the opinions of a component. I have an example does all you asked: https://jsfiddle.net/Hawkeye64/8rv3qo5y/30/

**Comment by hawkeye64** [comment] 2019-08-13 16:31
Check out the bottom row, all done with slots (top row is yours):
![image](https://user-images.githubusercontent.com/10262924/62959229-8800e100-bdb5-11e9-8fd0-d69da95bb654.png)

**Comment by hawkeye64** [comment] 2019-08-13 16:38
Here's last example just to show what you can achieve: 
![image](https://user-images.githubusercontent.com/10262924/62959653-7ec44400-bdb6-11e9-8c8e-73728f8a7145.png)

https://jsfiddle.net/Hawkeye64/8rv3qo5y/35/

**Comment by FragsterAt** [comment] 2019-08-13 17:13
thanx

**Comment by FragsterAt** [comment] 2019-08-14 07:02
May be last two rows in https://jsfiddle.net/Hawkeye64/8rv3qo5y/35/ must be default "align" behavior

**Closed** 2019-08-20 20:17 UTC
Labels: bug
