### ISSUE TITLE
[Request] QScrollArea horizontal scrolling

### ISSUE THREAD

**Issue by florentpeyrard** [quasarframework/quasar#2851] opened 2018-12-10 11:15 UTC
Having horizontal scrolling, including a setHorizontalScrollPosition would be of great help. Example of use case : complex timelines.

**Comment by rstoenescu** [comment] 2018-12-10 15:33
Duplicate of: Feature request: horizontal scroll #2163

**Closed by rstoenescu** 2018-12-10 15:33 UTC
