### ISSUE TITLE
[Bug] Mousedown on element with tooltip, makes tooltip re-appear

### ISSUE THREAD

**Issue by TKafassis** [quasarframework/quasar#1090] opened 2017-11-03 10:57 UTC
I have put a tooltip inside a radio button and I noticed that when I mousedown on that radio button, the tooltip disappears and re-appears (like flickering). Is this intended?

**Comment by rstoenescu** [comment] 2017-11-05 17:46
Will investigate. Thanks for reporting.

**Comment by slowaways** [comment] 2018-07-26 19:06
I cannot reproduce!

**Comment by rstoenescu** [comment] 2018-07-26 19:08
I believe this was fixed a while ago. Closing. Please reopen if it happens again.

**Closed by rstoenescu** 2018-07-26 19:08 UTC
