### ISSUE TITLE
Cannot find module 'loader-utils/lib/stringifyRequest'

### ISSUE THREAD

**Issue by JoseGoncalves** [quasarframework/quasar#15281] opened 2023-01-16 15:58 UTC
### What happened?

After setup a new Quasar CLI project with latest packages (@quasar/cli v2.0.0 & @quasar/app-webpack v3.7.0), performing a `quasar build` command leads to an error:

```
 .d88888b.
d88P" "Y88b
888     888
888     888 888  888  8888b.  .d8888b   8888b.  888d888
888     888 888  888     "88b 88K          "88b 888P"
888 Y8b 888 888  888 .d888888 "Y8888b. .d888888 888
Y88b.Y8b88P Y88b 888 888  888      X88 888  888 888
 "Y888888"   "Y88888 "Y888888  88888P' "Y888888 888
       Y8b


 Build mode................ spa
 Pkg quasar................ v2.11.5
 Pkg @quasar/app-webpack... v3.7.0
 Pkg webpack............... v5
 Debugging................. no
 Publishing................ no

 Configured browser support (>= 86.34% of global marketshare):
 · Chrome for Android >= 108
 · Firefox for Android >= 107
 · Android >= 108
 · Chrome >= 100
 · Edge >= 105
 · Firefox >= 99
 · iOS >= 14.0-14.4
 · Opera >= 88
 · Safari >= 15.2-15.3

 App • Chaining "UI" Webpack config
 App • Cleaned build artifact: "/home/jmpg/quasar-project/dist/spa"
 App •  WAIT  • Compiling of "UI" in progress...
 App •  DONE  • "UI" compiled with errors • 7099ms

 App •  ERROR  •  UI  in ./src/App.vue


Error: Cannot find module 'loader-utils/lib/stringifyRequest'
  Require stack:
  - /home/jmpg/quasar-project/node_modules/@quasar/app-webpack/lib/webpack/loader.vue.auto-import-quasar.js
  - /home/jmpg/quasar-project/node_modules/webpack/lib/ProgressPlugin.js
  - /home/jmpg/quasar-project/node_modules/webpack/lib/index.js
  - /home/jmpg/quasar-project/node_modules/@quasar/app-webpack/lib/cmd/build.js
  - /home/jmpg/quasar-project/node_modules/@quasar/app-webpack/bin/quasar
  - /usr/lib/node_modules/@quasar/cli/bin/quasar.js

  - loader:995 Module._resolveFilename
    node:internal/modules/cjs/loader:995:15
  
  - loader:841 Module._load
    node:internal/modules/cjs/loader:841:27
  
  - loader:1061 Module.require
    node:internal/modules/cjs/loader:1061:19
  
  - helpers:103 require
    node:internal/modules/cjs/helpers:103:18
  
  - loader.vue.auto-import-quasar.js:3 Object.<anonymous>
    [quasar-project]/[@quasar]/app-webpack/lib/webpack/loader.vue.auto-import-quasar.js:3:26
  
  - loader:1159 Module._compile
    node:internal/modules/cjs/loader:1159:14
  
  - loader:1213 Module._extensions..js
    node:internal/modules/cjs/loader:1213:10
  
  - loader:1037 Module.load
    node:internal/modules/cjs/loader:1037:32
  
  - loader:878 Module._load
    node:internal/modules/cjs/loader:878:12
  
  - loader:1061 Module.require
    node:internal/modules/cjs/loader:1061:19
  
  - helpers:103 require
    node:internal/modules/cjs/helpers:103:18
  
  - ProgressPlugin.js:412 
    [quasar-project]/[webpack]/lib/ProgressPlugin.js:412:9
  
  
  - NormalModule.js:809 NormalModule._doBuild
    [quasar-project]/[webpack]/lib/NormalModule.js:809:24
  
  - NormalModule.js:963 NormalModule.build
    [quasar-project]/[webpack]/lib/NormalModule.js:963:15
  
  - Compilation.js:1371 
    [quasar-project]/[webpack]/lib/Compilation.js:1371:12
  
  - NormalModule.js:1253 NormalModule.needBuild
    [quasar-project]/[webpack]/lib/NormalModule.js:1253:32
  
  - Compilation.js:1352 Compilation._buildModule
    [quasar-project]/[webpack]/lib/Compilation.js:1352:10
  
  - AsyncQueue.js:303 
    [quasar-project]/[webpack]/lib/util/AsyncQueue.js:303:10
  
  
  - AsyncQueue.js:293 AsyncQueue._startProcessing
    [quasar-project]/[webpack]/lib/util/AsyncQueue.js:293:26
  
  - AsyncQueue.js:280 AsyncQueue._ensureProcessing
    [quasar-project]/[webpack]/lib/util/AsyncQueue.js:280:12
  
  - timers:471 process.processImmediate
    node:internal/timers:471:21
  


 App •  ERROR  •  UI  in ./src/layouts/MainLayout.vue

Error: Cannot find module 'loader-utils/lib/stringifyRequest'
  Require stack:
  - /home/jmpg/quasar-project/node_modules/@quasar/app-webpack/lib/webpack/loader.vue.auto-import-quasar.js
  - /home/jmpg/quasar-project/node_modules/loader-runner/lib/loadLoader.js
  - /home/jmpg/quasar-project/node_modules/loader-runner/lib/LoaderRunner.js
  - /home/jmpg/quasar-project/node_modules/webpack/lib/NormalModule.js
  - /home/jmpg/quasar-project/node_modules/vue-loader/dist/pluginWebpack5.js
  - /home/jmpg/quasar-project/node_modules/vue-loader/dist/plugin.js
  - /home/jmpg/quasar-project/node_modules/vue-loader/dist/index.js
  - /home/jmpg/quasar-project/node_modules/@quasar/app-webpack/lib/webpack/create-chain.js
  - /home/jmpg/quasar-project/node_modules/@quasar/app-webpack/lib/webpack/index.js
  - /home/jmpg/quasar-project/node_modules/@quasar/app-webpack/lib/quasar-conf-file.js
  - /home/jmpg/quasar-project/node_modules/@quasar/app-webpack/lib/cmd/build.js
  - /home/jmpg/quasar-project/node_modules/@quasar/app-webpack/bin/quasar
  - /usr/lib/node_modules/@quasar/cli/bin/quasar.js
  
  - loader:995 Module._resolveFilename
    node:internal/modules/cjs/loader:995:15
  
  - loader:841 Module._load
    node:internal/modules/cjs/loader:841:27
  
  - loader:1061 Module.require
    node:internal/modules/cjs/loader:1061:19
  
  - helpers:103 require
    node:internal/modules/cjs/helpers:103:18
  
  - loader.vue.auto-import-quasar.js:3 Object.<anonymous>
    [quasar-project]/[@quasar]/app-webpack/lib/webpack/loader.vue.auto-import-quasar.js:3:26
  
  - loader:1159 Module._compile
    node:internal/modules/cjs/loader:1159:14
  
  - loader:1213 Module._extensions..js
    node:internal/modules/cjs/loader:1213:10
  
  - loader:1037 Module.load
    node:internal/modules/cjs/loader:1037:32
  
  - loader:878 Module._load
    node:internal/modules/cjs/loader:878:12
  
  - loader:1061 Module.require
    node:internal/modules/cjs/loader:1061:19
  
  - helpers:103 require
    node:internal/modules/cjs/helpers:103:18
  
  - loadLoader.js:19 loadLoader
    [quasar-project]/[loader-runner]/lib/loadLoader.js:19:17
  
  - LoaderRunner.js:182 iteratePitchingLoaders
    [quasar-project]/[loader-runner]/lib/LoaderRunner.js:182:2
  
  - LoaderRunner.js:398 runLoaders
    [quasar-project]/[loader-runner]/lib/LoaderRunner.js:398:2
  
  - NormalModule.js:819 NormalModule._doBuild
    [quasar-project]/[webpack]/lib/NormalModule.js:819:3
  
  - NormalModule.js:963 NormalModule.build
    [quasar-project]/[webpack]/lib/NormalModule.js:963:15
  
  - Compilation.js:1371 
    [quasar-project]/[webpack]/lib/Compilation.js:1371:12
  
  - NormalModule.js:1253 NormalModule.needBuild
    [quasar-project]/[webpack]/lib/NormalModule.js:1253:32
  
  - Compilation.js:1352 Compilation._buildModule
    [quasar-project]/[webpack]/lib/Compilation.js:1352:10
  
  - AsyncQueue.js:303 
    [quasar-project]/[webpack]/lib/util/AsyncQueue.js:303:10
  
  
  - AsyncQueue.js:293 AsyncQueue._startProcessing
    [quasar-project]/[webpack]/lib/util/AsyncQueue.js:293:26
  
  - AsyncQueue.js:280 AsyncQueue._ensureProcessing
    [quasar-project]/[webpack]/lib/util/AsyncQueue.js:280:12
  
  - timers:471 process.processImmediate
    node:internal/timers:471:21
  



 App •  COMPILATION FAILED  • Please check the log above for details.

```

### What did you expect to happen?

App builds with success.

### Reproduction URL

https://stackblitz.com/edit/quasarframework-webpack-pqnb9b

### How to reproduce?

The build on the previous StackBlitz link does not fail, so I suppose the issue is related with npm and node versions that I'm using.
I use node v18.12.1 and npm v8.19.3.

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Quasar info output

```Shell
Operating System - Linux(5.15.0-57-generic) - linux/x64
NodeJs - 18.12.1

Global packages
  NPM - 8.19.3
  yarn - 1.22.19
  @quasar/cli - 2.0.0
  @quasar/icongenie - 2.5.4
  cordova - Not installed

Important local packages
  quasar - 2.11.5 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-webpack - 3.7.0 -- Quasar Framework App CLI with Webpack
  @quasar/extras - 1.15.9 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.45 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.1.6
  pinia - Not installed
  vuex - Not installed
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.20.12 -- Babel compiler core.
  webpack - 5.75.0 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
  webpack-dev-server - 4.11.1 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  typescript - 4.9.4 -- TypeScript is a language for application scale JavaScript development
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*

Networking
  Host - st-ze
  enp1s0 - 10.154.2.63
```

**Comment by rstoenescu** [comment] 2023-01-16 16:42
Duplicate of https://github.com/quasarframework/quasar/issues/15280
Fixed in q/app-webpack 3.7.1 (released it moments ago)

**Closed as completed by rstoenescu** 2023-01-16 16:42 UTC
Labels: kind/bug 🐞, Qv2 🔝
