### ISSUE TITLE
[QScrollArea] hover event triggers props change inside sub compnent

### ISSUE THREAD

**Issue by xuzuodong** [quasarframework/quasar#13938] opened 2022-07-13 03:47 UTC
### What happened?

When using a component as the default slot of `QScrollArea`, and then pass through a prop [using expression](https://vuejs.org/guide/essentials/template-syntax.html#using-javascript-expressions), like this: 

``` vue
<q-scroll-area style="height: 25vh; width: 75vw; background-color: gray">
      <Sub :arr="arr.map((item) => item)"></Sub>
</q-scroll-area>
```

In `Sub.vue`, 
``` vue
<template>
  <div>sub comp</div>
</template>

<script setup>
import { watch } from 'vue';

const props = defineProps({
  arr: Array,
});

watch(
  () => props.arr,
  () => {},
  {
    onTrigger(e) {
      console.log(e);
    },
  }
);
</script>
```

Every time **mouse in and mouse out**, `arr` prop change will be triggered, which is unexpected, because it has not been changed: 

https://user-images.githubusercontent.com/51878637/178645225-a2d358ba-6717-480e-ad43-1016a9920432.mov

---

Oddly, if I pass through a `computed` value instead of `expression`, this problem disappeared: 

``` vue
<q-scroll-area style="height: 25vh; width: 75vw; background-color: orange">
      <Sub :arr="computedArr"></Sub>
</q-scroll-area>

<script setup>
const computedArr = computed(() => arr.value.map((item) => item));
</script>

```

### What did you expect to happen?

Mouse in and mouse out behavior should not trigger the watch function

### Reproduction URL

https://stackblitz.com/edit/quasarframework-xjihyx?file=src%2Fpages%2FIndexPage.vue,src%2Fpages%2Fsub.vue

### How to reproduce?

1. Go to the provided reproduction link
2. Open console
3. Move mouse to the gray area
4. See console log

### Flavour

Vite Plugin (@quasar/vite-plugin)

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome

### Quasar info output

```Shell
Operating System   	Darwin(21.4.0) - darwin/arm64
NodeJs             	16.15.0

Global packages
  NPM              	8.5.5
  yarn             	1.22.11
  @quasar/cli      	1.2.0
  @quasar/icongenie	Not installed
  cordova          	Not installed

Networking
  Host             	xuzuodongdeMacBook-Air.local
  en0              	172.16.88.100
```

**Comment by pdanpdan** [comment] 2022-07-13 04:09
Duplicate of https://github.com/quasarframework/quasar/issues/13418

**Closed as completed by pdanpdan** 2022-07-13 04:09 UTC
Labels: kind/bug 🐞, Qv2 🔝, flavour/vite-plugin, bug/1-repro-available, area/components
