### ISSUE TITLE
feat(QDate): Improve the event highligting system

### ISSUE THREAD

**Issue by yusufkandemir** [quasarframework/quasar#7290] opened 2020-06-24 07:50 UTC
**Is this feature request related to a problem?**
Currently, highlighting events is limited to just indicating if there is an event or not, and modifying the dot's color. It could be improved to offer more customizations such as changing the class of the dot, adjust the color in place(without another prop), popovers that contain descriptions of events, and more.

**The solution I'd like**
`events` and `eventsFn` props could accept an array of objects while keeping the current behavior(array of strings). Similar approaches are currently being used in other components(e.g. [`q-select` > options](https://quasar.dev/vue-components/select#Options-type)).

**Alternatives I've considered**
This could be done in devland if #7076 is implemented in a way that allows this.

**Additional context**
A Vue plugin which has the described features: [V-Calendar](https://vcalendar.io/attributes.html#highlights)

**Comment by pdanpdan** [comment] 2020-06-28 12:12
It boils down to a duplicate of https://github.com/quasarframework/quasar/issues/7076

**Closed by pdanpdan** 2020-06-28 12:12 UTC
Labels: feature request, has PR
