### ISSUE TITLE
Does select component support remote loading?

### ISSUE THREAD

**Issue by baixiyang** [quasarframework/quasar#2457] opened 2018-08-24 00:57 UTC
### Software version

Quasar: 0.17.9
OS:
Node:
NPM:
Browsers:
iOS:
Android:
Any other software related to your bug:

**Comment by rstoenescu** [comment] 2018-08-24 00:58
Duplicate of https://github.com/quasarframework/quasar/issues/2435

**Closed by rstoenescu** 2018-08-24 00:58 UTC
