### ISSUE TITLE
On android, nativ keyboard appears when selecting an item in q-select

### ISSUE THREAD

**Issue by Brice155** [quasarframework/quasar#7062] opened 2020-05-18 15:17 UTC
**Describe the bug**
Only on mobile device (not reproduced in chrome dev tools), when an item is selected in a q-select, the nativ keyboard appears.

**Codepen/jsFiddle/Codesandbox (required)**
https://codepen.io/Brayce/pen/yLYxqMP

**To Reproduce**
1. Access the link with an android mobile
2. click on the q-select to show the options
3. select an option
4. See the nativ keaybords opening
It also can be reproduce on the quasar q-select home page.

**Expected behavior**
At step 3, the nativ keyboard should not be displayed because no input is requested.

**Screenshots**
No available screenshot

**Platform (please complete the following information):**
OS: 
Node:
NPM:
Yarn:
Browsers: Chrome Mobile v81
iOS:
Android: v10
Electron:

**Additional context**

**Comment by pdanpdan** [comment] 2020-05-18 15:28
Duplicate of #7061

**Closed by pdanpdan** 2020-05-18 15:28 UTC
Labels: bug

**Comment by rstoenescu** [comment] 2020-05-19 12:47
Fix will be available in "quasar" v1.11.4.
