### ISSUE TITLE
[Feature Request] Add a Date Array feature to DateTime Picker

### ISSUE THREAD

**Issue by smolinari** [quasarframework/quasar#2372] opened 2018-08-03 04:10 UTC
Originally reported here: https://forum.quasar-framework.org/topic/2539/show-only-available-dates-qdatetime-feature-request

Basically, add the ability to the Min Max version of the DateTime Picker to have an array of dates, which blanks out or makes available only certain dates within the Min Max range. 

Scott

**Comment by rstoenescu** [comment] 2018-10-13 19:05
Duplicate of https://github.com/quasarframework/quasar/issues/805

**Closed by rstoenescu** 2018-10-13 19:05 UTC
