### ISSUE TITLE
import useStore from vuex will make it undefineded

### ISSUE THREAD

**Issue by gzzchh** [quasarframework/quasar#9369] opened 2021-05-21 20:18 UTC
**Describe the bug**

Folling the docs of next version  
I should import `useStore` from `vuex`  
but if i use the following code, it will cause the `myStore` be undefinded.

here is the code

```ts
import { computed } from "vue";
import { useStore } from "vuex";
import { useRouter } from "vue-router";

export default {
	data() {
		return {
			leftDrawerOpen: false,
			links1: [
				{ icon: "web", text: "项目管理" },
				{ icon: "person", text: "问题追踪" },
			],
		};
	},
	mounted() {
		const router = useRouter();
		if (this.tokenState === "") {
			// 说明还没有准备 Token,自然就是去登陆
			// console.log("还没有登陆");
			router.push({ path: "/login" });
		}
	},
	setup() {
		const myStore = useStore();
		console.log(myStore);
		const tokenState = computed({
			// 相当于重写了返回值,参考 Kotlin
			set: (value) => {
				myStore.commit("token/setBearerToken", value);
			},
			// get: () => myStore.getters["token/getBearerToken"],
			get: () => myStore.state.token.bearerToken,
		});
		return {
			tokenState,
		};
	},
};
```

if I import from `../store` will be ok  
and here is the doc

https://next.quasar.dev/quasar-cli/vuex-store#adding-a-vuex-module-

should I import useState from vuex or from `../state` ?  
is this an error of docs or just my fault?

**To Reproduce**

follow the docs to crate and use store.  
Ensure importing `useStore` from vuex

```ts
import { useStore } from "vuex";
```

then use the state in `setup()`

```ts
setup() {
		const myStore = useStore();
        // here will get undefinded
		console.log(myStore);
		const tokenState = computed({
			set: (value) => {
				myStore.commit("token/setBearerToken", value);
			},
            // here will fail
			get: () => myStore.state.token.bearerToken,
		});
		return {
			tokenState,
		};
	},
```

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/17796830/119192749-32da1f00-bab3-11eb-8897-29f9d66774d7.png)

then the browser will say `Cannot read property 'state' of undefined` .  
if I tried to log what is `myStore` it will return undefined

![image](https://user-images.githubusercontent.com/17796830/119193538-58b3f380-bab4-11eb-88e5-4aac95f978ce.png)

the content of doc
**Platform (please complete the following information):**
Quasar Version: v2.0.0-beta.17
@quasar/app Version: v3.0.0-beta.25
Quasar mode:

- [x] SPA
- [ ] SSR
- [ ] PWA
- [ ] Electron
- [ ] Cordova
- [ ] Capacitor
- [ ] BEX

Tested on:

- [x] SPA
- [ ] SSR
- [ ] PWA
- [ ] Electron
- [ ] Cordova
- [ ] Capacitor
- [ ] BEX

OS: Fedora 33
Node: v14.17.0
NPM: 6.14.13
Yarn: 1.22.10
Browsers: Chrome latest
iOS: N/A
Android: N/A
Electron: N/A

**Additional context**
found alternative problem here  
https://github.com/quasarframework/quasar/issues/4768

**Comment by TobyMosque** [comment] 2021-05-21 20:34
unable to reproduce:
https://codepen.io/tobias-mesquita/pen/vYxxLLX?editors=1010

**Comment by gzzchh** [comment] 2021-05-22 06:52
creating store from ` new Vuex.Store()` will be ok.
have you follow the docs and use it in project instead of codepen ?

**Comment by rstoenescu** [comment] 2021-05-22 10:10
One thing that is out of place (at first glance) in the code that you pasted is that you're using a composition method inside of the `mounted()` hook (useRouter). A big "NO". In your `mounted()` you should use `this.$router`/`this.$route` instead (since the mounted hook is part of Options API). **Composition methods should be used exclusively inside of the `setup()` method**. Also, it's best to not mix Composition API with Options API.

**Comment by rstoenescu** [comment] 2021-05-22 10:12
We can convert this into a GH Discussion if you want (post a reply to do so). So closing this ticket as it has nothing to do with an eventual bug in Quasar.

**Closed by rstoenescu** 2021-05-22 10:12 UTC
Labels: :beetle: bug, 🔝 Qv2

**Comment by gzzchh** [comment] 2021-05-22 10:38
sure， how to convert this issue to discussion？
