### ISSUE TITLE
Select box of type "checklist" or "toggle" doesn't emit "input" event on change

### ISSUE THREAD

**Issue by nborko** [quasarframework/quasar#487] opened 2017-03-29 16:25 UTC
### Software version

Quasar: 0.13.6
OS: Windows 10
Node: 6.0.0
NPM: 4.1.1
Browsers: All
iOS: yes
Android: yes

### What did you get as the error?
The "input" event never fires on a Select box of type "checklist" or "toggle"

### What were you expecting?
The "input" event should fire when any item is checked/unchecked or toggled

### What steps did you take, to get the error?
Use a Select box of type "checklist" or "toggle"

Modifying `this.model` using Array methods doesn't trigger the computed `set(value)`, the only place that emits the input event. Adding `this.$emit('input', this.model)` as the last line of the `toggleValue` method fixed the issue for me.

**Comment by rstoenescu** [comment] 2017-03-29 17:43
Will see about this. I have the feeling there is already an issue posted on this.

**Comment by rstoenescu** [comment] 2017-03-30 07:50
Found it. Duplicate of https://github.com/quasarframework/quasar/issues/395

**Closed by rstoenescu** 2017-03-30 07:50 UTC
