### ISSUE TITLE
Quasar.dev - PWA - Not caching .js files

### ISSUE THREAD

**Issue by acrobid** [quasarframework/quasar#16231] opened 2023-08-22 07:58 UTC
### What happened?

Quasar is not caching .js files in PWA mode. This includes the Quasar.dev site.

### What did you expect to happen?

Quasar uses Workbox to precache assets. Certain static assets like .css or .json files are cached, while .js files are not. This prevents most offline functionality.

### Reproduction URL

https://quasar.dev/

### How to reproduce?

Go to https://quasar.dev/
Open chrome dev tools
Click "Application"
Click "Cache Storage"
Click "quasar.dev-precache-v2..."
Sort by "Content type" and look for "application/javascript"
Observe the "Content-length" of the .js files. Most will be 0 bytes.

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

PWA Mode

### Platforms/Browsers

Chrome, Safari

### Quasar info output

```Shell
Operating System - Windows_NT(10.0.19045) - win32/x64
NodeJs - 18.14.0

Global packages
  NPM - 9.3.1
  yarn - Not installed
  @quasar/cli - 2.2.1
  @quasar/icongenie - 2.5.4
  cordova - Not installed

Important local packages
  quasar - 2.12.0 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.4.3 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.16.4 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.41 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.1.5
  pinia - 2.0.28 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 2.9.16 -- Native-ESM powered web dev build tool
  eslint - 8.26.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  *None installed*
```

### Additional context

The etag headers of the missing .js files are "weak", i.e.:

Cached css: etag: "642fbf46-163"
Non-cached javascript: etag: W/"64df7d7c-318e"

View this by clicking the "headers" tab inside application/cache storage.

This caching behavior is present in both "generateSW" and "injectedManifest" mode.

**Comment by rstoenescu** [comment] 2023-08-22 12:26
Cannot reproduce. I see all the .js files. Everything is working, even if set to "Offline" mode...

**Comment by rstoenescu** [comment] 2023-09-11 17:41
Please offer more details, otherwise I am forced to close this ticket since no one can reproduce it.

**Closed as completed by rstoenescu** 2023-09-11 17:41 UTC
Labels: kind/bug 🐞, bug/0-needs-info, Qv2 🔝, mode/pwa, flavour/quasar-cli-vite
