### ISSUE TITLE
Q-Select always clearable

### ISSUE THREAD

**Issue by CedricDuj** [quasarframework/quasar#16478] opened 2023-10-17 10:07 UTC
### What happened?

q-select with :clearable="false" can still be cleared by focus them and pressing delete/backspace.
It doesn't seem like a behavior you would want.

### What did you expect to happen?

I would expect that delete/backspace do nothing on q-select with clearable set to false.

### Reproduction URL

https://codepen.io/CedricDuj/pen/xxmoPrb

### How to reproduce?

1. create a q-select with :clearable="false"
2. Focus on this q-select
3. Press delete/backspace

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

**Comment by johnstrickler** [comment] 2023-10-17 14:03
I created a duplicate of this issue.  I didn't see this issue which was created just 4 hours before my own.

https://github.com/quasarframework/quasar/issues/16481

**Comment by rstoenescu** [comment] 2023-10-17 14:16
Please note that "clearable" is a Boolean prop. By default, all Boolean props are `false` in Vue. So explicitly setting "clearable" to "false" is equivalent to not setting "clearable" at all.

**Comment by rstoenescu** [comment] 2023-10-17 14:53
Fix will be available in Quasar v2.12.8

**Closed as completed by rstoenescu** 2023-10-17 14:53 UTC
Labels: kind/bug 🐞, Qv2 🔝, bug/1-repro-available, area/components, flavour/quasar-cli-vite
