### ISSUE TITLE
Variables inside quasar.{theme.}styl to persist in app.variables.stylus 

### ISSUE THREAD

**Issue by dobromir-hristov** [quasarframework/quasar#131] opened 2016-10-13 11:31 UTC
If for example you decide to stick to global paddings or extend a button you cant import the main stylus and use the variables there because it will duplicate the whole code. 

The guys over at Foundation have a _settings.scss which has about 90% of the variables defined and commented out. If you need something, you import that file and use everything you want.

Just think it could make things a bit easier.

**Comment by rstoenescu** [comment] 2016-10-13 11:55
There's a bit of comment to do here, but you are right. This can be improved. And it will.

**Comment by dobromir-hristov** [comment] 2016-10-13 12:05
Yeah, I know its not just "copy this there" but I think it will be really helpful, today I needed this like 10 times and decided to mention it.

**Comment by rstoenescu** [comment] 2016-10-13 12:07
Thanks for opening this! Please do open issues where you think things can be improved.

**Comment by rstoenescu** [comment] 2016-10-14 08:18
Why closing?

**Comment by dobromir-hristov** [comment] 2016-10-14 08:25
Mistake. Thought it was something else...

**Comment by rstoenescu** [comment] 2016-12-30 17:38
Just realized this is a duplicate of #106

**Closed by rstoenescu** 2016-12-30 17:38 UTC
Labels: enhancement, proposal
