### ISSUE TITLE
QSelect mobile dialog: Add close button

### ISSUE THREAD

**Issue by lmfmaier** [quasarframework/quasar#8449] opened 2021-02-10 11:43 UTC
The default mobile behaviour of QSelect is to show a dialog with the selectable options, which is nice.

The problem is, especially with larger lists and the "use-input" option set to true (for filtering), that the dialog occupies most of the screen plus the soft keyboard popping up.

It's difficult for the user to understand how to close the dialog after selecting an option in "multiple" mode or how to not select an option at all and just close the dialog. The dialog closes when touching the background, which is hard to achieve in the above situation.

It would be nice to have an optional close button integrated in the dialog.

**Comment by pdanpdan** [comment] 2021-02-10 15:57
Duplicate of https://github.com/quasarframework/quasar/issues/6858

**Closed by pdanpdan** 2021-02-10 15:57 UTC
Labels: feature request
