### ISSUE TITLE
Feature request: More control over behaviour when clicking outside q-popup-edit

### ISSUE THREAD

**Issue by dsl101** [quasarframework/quasar#2682] opened 2018-10-16 12:20 UTC
When using a q-popup-edit clicking away from the popup editor acts like the 'Save' button, rather than the 'Cancel' button. I think this could be counter-intuitive, and there should ideally be an option to control this behaviour:
* Default to cancel via a prop (`dismiss-cancel` or similar)
* Add a `modal` prop (more than `persistent`, it would prevent clicks elsewhere until explicit save / cancel)

### JsFiddle

https://codepen.io/dsl101/pen/xypdwE

To see the effect, click on a title (in the codepen above), make some changes, then click anywhere else in the page. The edit is saved as if the user had clicked the 'Save' button. Clicking Cancel after changing does cancel the change, and behaves as expected.

**Comment by pdanpdan** [comment] 2018-10-16 13:04
If you have buttons then just set `persistent` to disallow closing by clicking outside.
If you have no buttons then click outside and ENTER key is save and ESC key is cancel.
In your example you should use `persistent`.

But I'll think about it.

**Comment by dsl101** [comment] 2018-10-16 13:07
I tried persistent in that fiddle, but it doesn't stop _other_ editors being opened. In my app, this is bad because I'm actually using a local data prop to handle the edit, and then send the edited data to firebase. So there's lots of local complexity if more than one editor can be opened. Hence asking for `modal`, one more than `persistent`.

**Comment by mclate** [comment] 2020-01-06 14:11
I'd like to add to that and say that popup editor here is behaving differently than all other popups. That is, it doesn't behave like a modal popup: it allows one to open several editors at once and clicking outside of the editor, while closes the editor, doesn't suppress the click itself. Even in the official documentation, clicking outside of the popup editor makes new one to appear. More natural and expected behaviour would be to behave as all popups - on the outside click just hide the popup (with corresponding cancel action) and prevent other events from firing. This way it is more natural for user to close popup with first click and do another action with a second one.

**Comment by rstoenescu** [comment] 2020-01-06 14:47
@dsl101 Shouldn't a QDialog be used in your case instead of QPopupEdit? There's no reason to make QPopupEdit act as a QDialog when QDialog exists..

**Comment by mclate** [comment] 2020-01-06 15:00
QPopupEditor provides convenient editor placement right above or next to the item that is being edited. It doesn't look like QDialog is capable of this behaviour. 
On the other hand, what would be the use case when user is having more than one popup editor opened?

**Comment by oskarmaxa** [comment] 2020-01-16 18:03
The behavior has evolved since the original request. Currently, in v1.7.1, without `persistent`, clicking outside *cancels* and closes, pressing Escape does the same, whereas pressing Enter *saves* and closes.

For a soft-edit component, I'd like clicking outside to *save* and close instead, with no change in keyboard behavior. What do you think about adding a toggle prop for that, e.g. `save-on-click-outside="true"`?

**Comment by pdanpdan** [comment] 2020-02-08 18:37
Hello.
This can be done by listening on the `@cancel` event: https://codepen.io/pdanpdan/pen/PoqwQdv?editable=true&editors=101

**Comment by oskarmaxa** [comment] 2020-02-08 21:59
Yes, but pressing Escape now also saves the changes. What I meant was to cancel on Escape, but save on click outside.

For now, I've resorted to a hacky workaround to achieve this.

**Comment by pdanpdan** [comment] 2020-02-08 22:17
Good point, I forgot about ESC.

**Comment by rstoenescu** [comment] 2020-02-10 11:14
@mclate sure you can. you add a @click handler to your table cell which opens a QDialog... it works wonderful if you use $q.dialog() with a custom component to which you can pass the model.

**Comment by rstoenescu** [comment] 2020-02-10 11:15
New Boolean prop "auto-save" will be available in "quasar" v1.9.0.
It will save the value rather than revert it when user clicks outside of the popup (but not when you hit "ESC" key).

**Closed by rstoenescu** 2020-02-10 11:15 UTC

**Comment by mclate** [comment] 2020-02-10 12:29
> @mclate sure you can. you add a @click handler to your table cell which opens a QDialog... it works wonderful if you use $q.dialog() with a custom component to which you can pass the model.

Sure, my point wasn't about the fact that you cannot do that, but rather the placement of the dialog (location on the screen): q-popup-edit places popup right next to the click, while dialog is opened in the middle of the page (or on the border of the screen). Is there a way to place it in the same way as q-popup-edit? (that is, next to the element one clicked on).

P.S. i'm using `$q.dialog` with custom component almost all the time and i'm so thankful that you guys build such a nice tool!
