### ISSUE TITLE
[v1] - QSelect options placement

### ISSUE THREAD

**Issue by sn0rcha** [quasarframework/quasar#3723] opened 2019-03-28 05:02 UTC
Hey There,

I've been having some problems using the QSelect module inside of QSteppers because of this issue that is still happening: #3492 

Is there a way to force the QSelect options to display underneath the container rather then have it decide itself?

Cheers,
Ben

**Comment by rstoenescu** [comment] 2019-03-29 05:31
Hi,

That ticket has been closed because the root cause is a duplicate of #3276, which will be solved really soon (probably beta.14).

Trying to maintain sanity here and closing duplicates as having a ton of tickets on the same thing makes triaging harder.

Please follow ticket #3276. When that gets solved, your issue will too, because like I said above, it's the same root cause.

Thanks.

**Closed by rstoenescu** 2019-03-29 05:31 UTC

**Comment by rstoenescu** [comment] 2019-03-29 18:36
Fix will be available in beta.14

**Comment by rstoenescu** [comment] 2019-03-31 17:49
Delaying this a bit. Not yet "production ready". Didn't went into beta.14.
