### ISSUE TITLE
HMR not working in class components

### ISSUE THREAD

**Issue by mohamadkhani** [quasarframework/quasar#9302] opened 2021-05-17 06:33 UTC
Hey, Good day
I detect a problem with **HMR** in components with class style. The HMR not working when we use the quasar components that auto imported in components with class style.
I spent a long time, to detect the problem. And I realized that the combination of **Vue3** + **Class Style Component** + **Using auto imported Quasar Component** causes the problem.

**Comment by Evertvdw** [comment] 2021-07-01 13:51
I have this issue as well, I managed to reproduce it pretty easely:

1. Create a new quasar starter project with Typescript + Class components
2. Start up the dev server
3. Go to `ClassComponent.vue` and change something in there, hit save and see that HMR works.
4. Go to `MainLayout.vue` and change the title for instance, hit save and see that HMR does not work.

I have confirmed the above to be the case on both SPA and SSR.

quasar: v2.0.1
@quasar/app: v3.0.1

**Comment by Evertvdw** [comment] 2021-07-08 12:57
Here is a repo with the code created from the steps above: https://github.com/Evertvdw/quasar-v2-hmr-bug

**Comment by outofmemoryagain** [comment] 2021-07-20 17:35
I looked at the issue and it is not really clear what is happening.  I can see that it is triggering the HMR pass and our auto-loader webpack plugin is triggered, but it does not trigger the vue component rerender.  It definitely appears to be related to our auto-import loader, but the loader is generating the exact same code for the initial load as it does for the HMR pass.  I don't have time to dive into the details of it but it must be related to the internals of how vue is detecting what parts of the page should be rerended as part of the HMR reload.  I will try to reach out to the Vue team and see if they have any guidance.  I will post any updates here as I have them.

**Comment by FlxEd** [comment] 2021-08-16 11:49
I would like to add my +1 to this issue.
I absolutely love quasar with Class-Based-Components and I would love to go back to the amazing HMR experience it had before Vue 3.
Thank you in advance for future updates  😊

**Comment by IlCallo** [comment] 2021-08-30 21:36
Just spent some hours trying to debug this further.
Let apart confirming what already known, I couldn't discover much

I tried multiple things comparing a Class API and a Composition API project

- the HMR call is the same for both, it only differs in the generated sourcemap (which is correct AFAIK)
- Quasar components are correctly registered into the components, or that's what it seems and by the fact they actually render
- the code generated from the loader is exactly the same for both projects

At this point, the problem could be either in Vue (eg into vue-loader or vue-compiler), into the Class Component library or in webpack dev server directly

I asked advice to the Vue team on this, let's see if they have any suggestion on how to debug it further

**Comment by r3gisc** [comment] 2021-09-10 14:14
I've tried this and it works for me (quasar 2.0.4):
in quasar.conf.js
```
devServer: {
    watchFiles: {
        paths: ['src/**/*', 'public/**/*']
   }
}
```

**Comment by hawkeye64** [comment] 2021-09-12 14:53
https://github.com/vuejs/vue-loader/issues/1795

**Comment by IlCallo** [comment] 2021-09-13 10:38
@r3gisc thanks for sharing!
How did you get to that workaround? Any explaination on why a workaround works and why you tried it in the first place could help us understand what's the real problem and how we can fix it in a definitive way

**Comment by Evertvdw** [comment] 2021-09-13 11:45
@r3gisc @IlCallo This is not a workaround/fix for the problem. What that does is trigger a full page reload on every file change, which is of course not HMR.

**Comment by IlCallo** [comment] 2021-09-14 08:23
I see... I got in touch with Vue Team in relation to the vue-loader issue, but they are clueless
Class API maintainer didn't answer my messages, so we're stuck on this
I'll try to debug this further as time permits, but this seems a bug down to webpack level
Probably need to bring in webpack team too

**Comment by rstoenescu** [comment] 2021-10-22 14:38
We are closing this as this is most likely not a Quasar issue. Either Webpack or vue-loader is misbehaving and there's nothing that we can do about it.

We'll try to comment here about their investigation. Feel free to also do this.

**Comment by rstoenescu** [comment] 2021-11-04 12:46
Found the culprit in vue-loader. It doesn't registers the __hmrId correctly on class components.
Will submit a PR to it later today.

**Comment by rstoenescu** [comment] 2021-11-04 13:15
Submitted the PR: https://github.com/vuejs/vue-loader/pull/1897
Closing this ticket. Please follow the PR that I mentioned.

**Closed by rstoenescu** 2021-11-04 13:15 UTC
Labels: :outbox_tray: external lib issue
