### ISSUE TITLE
[Request] q-input: Mask number separator (eg. 5,000,000)

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#2101] opened 2018-05-30 13:20 UTC
On [q-input](https://quasar-framework.org/components/input-textfield.html) I currently require the function to mask the number input as a price.

eg.
`¥5,000`
or
`$50.00`

Prefix and decimals are already an option, so now I'd just need the option to set `,` to show every 3 numbers.

**Comment by rstoenescu** [comment] 2018-05-30 14:03
Duplicate of v

**Closed by rstoenescu** 2018-05-30 14:03 UTC
