### ISSUE TITLE
[webpack] Setting breakpoints doesn't work in dev

### ISSUE THREAD

**Issue by brokenalarms** [quasarframework/quasar#275] opened 2016-12-21 01:17 UTC
This is off a newly generated template - I can still manually debug the scripts using `debugger` statements, but setting breakpoints using dev tools in either Chrome or Firefox appears to have no effect. Some issue with the source maps?

The same thing does work in the vue-browserify and vue-webpack template build systems (right through to tracing the error back to the actual code in the `.vue` files), so it doesn't look like a limitation of working with .vue files (and affects .js files the same).

**Comment by rstoenescu** [comment] 2016-12-21 15:18
Hi, will investigate.

**Comment by brokenalarms** [comment] 2016-12-22 18:51
Hi, I have identified the issue. In `webpack-dev.conf.js`, it is the default `#eval-source-map` there which causes this problem. Setting this string to either `inline-source-map` or `source-map` solved it for me.

This seems to be a current Chrome issue, fixed in Canary: https://github.com/webpack/webpack/issues/2145#issuecomment-223752424

**Comment by rstoenescu** [comment] 2016-12-22 19:01
Hi, first of all thanks for investigating and even finding a solution. Current source map option was chosen because it is fastest.
Since the issue is fixed in the canary build don't know if it's worth to sacrifice some speed for this because it would be temporary. Will document it however!
Many thanks for handling this before me!

**Comment by brokenalarms** [comment] 2016-12-22 22:39
it's not actually fixed in the canary build, and looks like a webpack issue as it is across all browsers. Even with `source-map` option, it is still highly unreliable and any breakpoints or even debugger commands don't stop while the modules are bootstrapping in the event of a thrown error, making it impossible to debug anything that is actually preventing the app from fully starting.

This fix [here](https://github.com/webpack/webpack/issues/2145#issuecomment-236429079) eventually did it for me (removing `devtool` line and adding: 
```javascript
new webpack.SourceMapDevToolPlugin({
            filename: '[file].map'
        })
```
to `plugins`.

**Comment by rstoenescu** [comment] 2016-12-23 14:52
Reopening until we sort this out and find a final solution to work for all.

**Comment by rstoenescu** [comment] 2017-01-05 02:02
Will add this to the documentation until browser bugs are fixed.

**Closed by rstoenescu** 2017-01-05 02:02 UTC
