### ISSUE TITLE
quasar create has errors

### ISSUE THREAD

**Issue by geoidesic** [quasarframework/quasar#8650] opened 2021-03-20 21:30 UTC
**Describe the bug**
`quasar create <projectname>` should run without warnings or errors but currently does not.

**Codepen/jsFiddle/Codesandbox (required)**
I can't demonstrate this on any of those platforms. 

**To Reproduce**
1. `quasar create <projectname>` at the terminal
2. select all the defaults
3. note the errors when yarn runs

**Expected behavior**
hould run without warnings or errors.

**Screenshots**
<img width="1192" alt="Screenshot 2021-03-20 at 21 27 35" src="https://user-images.githubusercontent.com/4637995/111886045-425dbe80-89c3-11eb-8770-11993fb47197.png">

<img width="1059" alt="Screenshot 2021-03-20 at 21 28 20" src="https://user-images.githubusercontent.com/4637995/111886056-4e498080-89c3-11eb-9685-dfa3bb0e8107.png">

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version:
Quasar mode:
  - [*] SPA
  - [*] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [*] SPA
  - [*] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Mac OS X 10.15.7 (19H524)
Node: v12.6.0
NPM: 7.6.3
Yarn: 1.22.10
Browsers: It's nothing to do with the browser
iOS:
Android:
Electron:

**Additional context**

**Comment by hawkeye64** [comment] 2021-03-20 22:04
@geoidesic There's a couple of different issues I see here and I am going to just put down what I learned and maybe Raxvan will have some ideas:

First is the fsevents issue. I don't have a Mac, so fsevents doesn't install on my Linux computer, but there is 2 issues here:
1) I see 3 different packages using fsevents and all three are using different versions (not sure how hoisting is going to handle that)
2)  The one that `@quasar/app` is using wants to be upgraded: 
![image](https://user-images.githubusercontent.com/10262924/111886742-ad909c00-8995-11eb-9eef-d31317cec7ff.png)

The second issue is `eslint-plugin-vue-libs` - I am not sure how or why this is in your eslintrc file. This is an internal tool for Vue itself and not for Vue apps: https://github.com/vuejs/eslint-plugin-vue-libs

**Comment by geoidesic** [comment] 2021-03-21 14:13
Thans for the feedback. The `.eslint.js` file is generated by `quasar create`.

**Comment by hawkeye64** [comment] 2021-03-21 18:38
@geoidesic Do you see it in the file?

**Comment by geoidesic** [comment] 2021-03-21 21:30
No. Here's the generated .eslintrc.js file https://gist.github.com/geoidesic/17d7ba1d7da1e5dd6a02ae42f941129e

**Comment by rstoenescu** [comment] 2021-03-21 23:44
Why is this tagged with Qv2 when the steps to reproduce are creating a Qv1 project?
Also, cannot reproduce.

**Comment by rstoenescu** [comment] 2021-03-21 23:46
I think that you're running something else in the background too? The lines between "Author" and "Pick your favorite CSS preprocessor..." should not contain what appears to be another process running yarn...

**Comment by rstoenescu** [comment] 2021-03-24 10:19
Fixed in the starter kit a few days ago.

**Closed by rstoenescu** 2021-03-24 10:19 UTC
Labels: :beetle: bug, Qv1, not reproducible
