### ISSUE TITLE
[Request] Support q-tooltip in q-chat-message component 

### ISSUE THREAD

**Issue by jlanzarotti** [quasarframework/quasar#2866] opened 2018-12-14 06:36 UTC
It would be nice if for each chat you can mouse over and trigger a q-tooltip.
`
q-chat-message(
v-for="msg in message"
...
:tooltip="msg.tooltip"
)
`

**Comment by jlanzarotti** [comment] 2018-12-15 09:52
I see, thanks. 

I've tried the following: 

``` pug
template(v-for="(msg, index) in messages")
  q-chat-message(
       v-if="msg.text"
          ...
    )
      q-tooltip
        | {{ msg.stamp }}
```

However, I still see two `q-message-text` generated

```
<div class="q-message-container row items-end no-wrap">
  <div>
    <div class="q-message-name">
      ....
    <div class="q-message-text">
      <span class="q-message-text-content text-black">
      ...
    <div class="q-message-text">
      <span class="q-message-text-content text-black">
        <!---->
        <div class="q-message-stamp">
         ....
```

**Comment by metalsadman** [comment] 2018-12-15 16:40
@jlanzarotti 
yep, looks like q-chat-message element only have a self closing tag option. anyway try this, https://codesandbox.io/s/4rxzlnpow. 
the problem is that q-chat-message has wrapper div that span across the width so the tooltip will show somewhere in the middle, you could try playing with display:inline-block etc..

**Comment by rstoenescu** [comment] 2019-04-21 15:50
This has been fixed long time ago for v1 betas.

**Closed by rstoenescu** 2019-04-21 15:50 UTC
