### ISSUE TITLE
How to apply colResizable to q-table for quasar ? 

### ISSUE THREAD

**Issue by ravimule22** [quasarframework/quasar#6195] opened 2020-01-23 06:46 UTC
@rstoenescu How can i apply colResizable to a Q-Table so i can manually drag the size of a columns from a table or any other way to colResize to table in quasar ?

 I tried with jquery but it is not working here.

**Comment by rstoenescu** [comment] 2020-01-23 11:55
Duplicate of: https://github.com/quasarframework/quasar/issues/5115

Some background info: this is not easy to implement and won't drop in Quasar as soon as you'd like (like this week).

However, you can take a look at (it's not the right approach but might do the job if you're really in a hurry): https://github.com/quasarframework/quasar/pull/5460

**Closed by rstoenescu** 2020-01-23 11:55 UTC

**Comment by ravimule22** [comment] 2020-01-23 13:08
@rstoenescu Thank you, Will this feature(colResizable) include in q-table like q-colresizable or something.
