### ISSUE TITLE
Docs Outline Sidebar Double Scrollbar Popping Jitter

### ISSUE THREAD

**Issue by PowerWeb5** [quasarframework/quasar#11948] opened 2022-01-07 21:01 UTC
When viewing the documentation site like at https://quasar.dev/video-tutorials there the inner panel has a second nested vertical and horizontal scrollbar that keeps appearing and disappearing several times a second, just to show a few pixels worth of scrolling, causing a very distracting jittering effect like seen in this video.

It seems like the scrollbar may be appearing/disappearing for div with classes "q-scrollarea__container scroll relative-position fit hide-scrollbar".

https://user-images.githubusercontent.com/4053734/148606722-ed9b4e06-c6fc-4188-98ec-2d91048fa1f5.mp4

**Comment by pdanpdan** [comment] 2022-01-07 21:08
duplicate of #10281
Fixed in Quasar v2.4.4 & v1.17.1 (to be released)

**Closed as completed by pdanpdan** 2022-01-07 21:08 UTC
