### ISSUE TITLE
when I refresh the page,then datetime component will flash first then disappear

### ISSUE THREAD

**Issue by KrisyOne** [quasarframework/quasar#1823] opened 2018-03-23 03:25 UTC
### Software version

Quasar:
OS:
Node:
NPM:
Browsers:
iOS:
Android:
Any other software related to your bug:

**Comment by rstoenescu** [comment] 2018-03-23 16:55
Any video screen capture please? I cannot reproduce.
A jsfiddle would also be wonderful as it might help me reproduce this faster.

**Comment by slowaways** [comment] 2018-07-27 00:46
@KrisyOne More detail please!

**Comment by rstoenescu** [comment] 2018-08-13 22:42
Closing as no details have been provided.

**Closed by rstoenescu** 2018-08-13 22:42 UTC
