### ISSUE TITLE
QInput Mask non-ASCII characters

### ISSUE THREAD

**Issue by VSG24** [quasarframework/quasar#6643] opened 2020-03-20 09:14 UTC
I'm trying to use a QInput mask to allow for non-ASCII characters such as ب in the input field however it seems like it is not easily possible with the provided mask tokens. I also couldn't find any info on creating a custom mask.

Is it possible to use input masks on non-ASCII characters?

**Comment by pdanpdan** [comment] 2020-03-20 09:22
duplicate of https://github.com/quasarframework/quasar/issues/6424

**Closed by pdanpdan** 2020-03-20 09:22 UTC
