### ISSUE TITLE
Skip optional ESLint during init quasar will throw error

### ISSUE THREAD

**Issue by hobeas** [quasarframework/quasar#12797] opened 2022-03-15 04:36 UTC
### What happened?

Skip optional ESLint during init quasar will throw error

### What did you expect to happen?

Go to the next step

### Reproduction URL

None

### How to reproduce?

1. Run `pnpm init quasar`
2. Uncheck ESLint when check features
3. See the error

![220315_122809](https://user-images.githubusercontent.com/41267951/158306602-0140d997-0ae5-4b03-a102-5a3a3a2318e9.jpg)

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack | @quasar/app-vite)

### Relevant log output

```Shell
undefined:21
 if (lintConfig === 'prettier') { ;
 ^
ReferenceError: lintConfig is not defined
```

### Additional context

- OS: Darwin x64 18.7.0
- Node.js: v16.14.0
- Pnpm: v6.32.3
- Quasar: v2.6.0

**Comment by yusufkandemir** [comment] 2022-03-15 08:09
Duplicate of #12796.

**Closed as completed by yusufkandemir** 2022-03-15 08:09 UTC
Labels: kind/bug 🐞, bug/0-needs-info, Qv2 🔝, area/cli, flavour/quasar-cli-vite
