### ISSUE TITLE
bug in persian range datepicker

### ISSUE THREAD

**Issue by mohammadfiroozi** [quasarframework/quasar#7977] opened 2020-10-31 06:49 UTC
in range date picker when use persian language , sum of selected day in subtitle is show undefined

https://forum.quasar-framework.org/assets/uploads/files/1603864761972-range.png

`   <q-input
      label-color="teal-10"
      :label="dateModel.fromLabel"
      input-style="text-align: center;"
      outlined
      square
      v-model="selectedRange.from"
      mask="date"
      :rules="[isFromDateValid]"
    >
      <template v-slot:append>
        <q-icon name="event" class="cursor-pointer">
          <q-popup-proxy
            ref="qDateProxy"
            transition-show="scale"
            transition-hide="scale"
          >
            <q-date
              :locale="persianLocale"
              v-model="selectedRange"
              calendar="persian"
              color="dp-header"
              range
              :options="limitDate"
            >
              <div class="row items-center justify-end">
                <q-btn v-close-popup label="بستن" color="primary" flat />
              </div>
            </q-date>
          </q-popup-proxy>
        </q-icon>
      </template>
    </q-input>`

and my data prop: 
`  persianLocale: {
        /* starting with Sunday */
        days: [
          "یکشنبه",
          "دوشنبه",
          "سه شنبه",
          "چهارشنبه",
          "پنجشنبه",
          "جمعه",
          "شنبه",
        ],
        daysShort: [
          "یکشنبه",
          "دوشنبه",
          "سه شنبه",
          "چهارشنبه",
          "پنجشنبه",
          "جمعه",
          "شنبه",
        ],
        months: "فروردین_اردیبهشت_خرداد_تیر_مرداد_شهریور_مهر_آبان_آذر_دی_بهمن_اسفند".split(
          "_"
        ),
        monthsShort: "فروردین_اردیبهشت_خرداد_تیر_مرداد_شهریور_مهر_آبان_آذر_دی_بهمن_اسفند".split(
          "_"
        ),
        firstDayOfWeek: 6,
      },
    };
`

**Comment by Saeid-Za** [comment] 2020-11-01 11:16
Hello, I tried to replicate the problem you're having with calendar, this is my minimal setup inspired by yours:

```vue
<template>
  <q-input :label="dateModel.fromLabel"
    outlined
    square
    v-model="selectedRange.from"
    mask="date"
    :rules="['date']">
    <template v-slot:append>
      <q-icon name="event"
        class="cursor-pointer">
        <q-popup-proxy ref="qDateProxy"
          transition-show="scale"
          transition-hide="scale">
          <q-date v-model="selectedRange"
            calendar="persian"
            range>
            <div class="row items-center justify-end">
              <q-btn v-close-popup
                label="بستن"
                color="primary"
                flat />
            </div>
          </q-date>
        </q-popup-proxy>
      </q-icon>
    </template>
  </q-input>
</template>

<script>
export default
  data: () => ({
    selectedRange: {
      from: null,
      to: null
    },
    dateModel: {
      fromLabel: "تاریخ"
    }
  })
</script>

```

Note that I didn't use any of your data prop, because i'm assuming you are using `fa-ir` language pack, so it would be unnecessary.
Here's the result that I have at the end: [Image](https://ibb.co/zJvHF31), Hope this helps.
If this setup doesn't resolve your problem, please consider providing a minimal reproducible example.

**Comment by webnoob** [comment] 2020-11-04 01:00
Closing in light of the above post that shows it working and waiting a reproducible example.

Thanks @Saeid-Za for your help.

**Closed by webnoob** 2020-11-04 01:00 UTC
Labels: bug

**Comment by rstoenescu** [comment] 2020-11-04 11:36
@mohammadfiroozi u sure you've also enabled quasar.conf.js > build > rtl: true ?

**Comment by mohammadfiroozi** [comment] 2020-11-10 12:56
@rstoenescu  my direction should be ltr and my default langueage is english but my date picker should be Shamsi.
@webnoob  this issue is not resolved

**Comment by rstoenescu** [comment] 2020-11-11 12:48
@mohammadfiroozi Use the ad-hoc method of supplying a locale for your QDate. Make sure that you tell it's `rtl: true` and also, enable quasar.conf.js > build > rtl: true
