### ISSUE TITLE
Initial button hover transition not working in chrome

### ISSUE THREAD

**Issue by pxDot** [quasarframework/quasar#11967] opened 2022-01-10 08:40 UTC
### What happened?

The initial hover transition is not working correctly in Chrome (96.0.4664.110). It seems to be missing the transition on first hover. It has a slight delay until the hover style gets applied. This is creating a feel of "lag". After the initial hover the transition is working correctly on subsequent mouseovers.

See this screen capture for clarification:
![quasar_hover_transition_chrome](https://user-images.githubusercontent.com/36505652/148737558-474878df-b173-4092-a49b-597994bdea63.gif)

It seems to be working correctly in Firefox.

### What did you expect to happen?

The transition should work correctly on initial and subsequent hover.

### Reproduction URL

https://quasar.dev

### How to reproduce?

1. Go to quasar.dev in Chrome
2. Hover any button

### Flavour

Quasar CLI (@quasar/cli | @quasar/app)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

**Comment by angelhdzmultimedia** [comment] 2022-01-10 11:04
Working fine on 97.0.4692.71.


https://user-images.githubusercontent.com/10191085/148755719-92bae13e-c772-4d6f-a932-b5b8155d8070.mp4

**Comment by pxDot** [comment] 2022-01-10 11:35
Just updated Chrome to 97.0.4692.71 (windows) and disabled all browser extensions. Sadly still with the same behaviour.

**Comment by MilosPaunovic** [comment] 2022-01-10 11:50
Can confirm that new Chrome `Version 97.0.4692.71 (Official Build) (x86_64)` on Mac `BigSur 11.4 (20F71)` still has the same issue on official docs page.

**Comment by angelhdzmultimedia** [comment] 2022-01-10 12:11
> Just updated Chrome to 97.0.4692.71 (windows) and disabled all browser extensions. Sadly still with the same behaviour.

What operating system?

**Comment by metalsadman** [comment] 2022-01-11 07:40
not happening on my mac HS 10.13.6
chrome Version 97.0.4692.71 (Official Build) (x86_64)

**Comment by darkopetreski** [comment] 2022-01-11 14:31
I have the same issue, Chrome 97, Kubuntu 20.04, no external graphic card.

![148795180-e3dbd457-6e92-4630-9b75-c5eeb53b9d26](https://user-images.githubusercontent.com/4987585/148961658-ab254d86-1d5f-4a1f-bafb-7ce18af9324e.gif)

**Comment by rstoenescu** [comment] 2022-01-17 11:47
Can someone that reproduces this issue try Chrome 98 (beta/next) and see if this is still happening? Or with other browsers?
Seems like there is a bug in Chrome that might have been fixed in the next Chrome version.

Thanks for the feedback in advance.

**Comment by MilosPaunovic** [comment] 2022-01-17 11:56
Tried on Chrome `Version 98.0.4758.55 (Official Build) beta (x86_64)` for Mac `BigSur 11.4 (20F71)`, seems to be working okay; screen recording attached.

https://user-images.githubusercontent.com/62475782/149765294-86eee836-efe7-4582-8add-ea280a1db097.mov

**Comment by jakobnoergaard** [comment] 2022-01-18 21:16
I can confirm that the bug has been fixed in Chrome 98 (beta).

**Comment by jakobnoergaard** [comment] 2022-01-19 14:36
I think the bug is still there when using: Chrome Version 98.0.4758.55 (Official Build) beta (arm64). In Safari everything works as expected.


https://user-images.githubusercontent.com/20745759/150151756-c3ddaee4-611a-4504-a141-4efeb87f43e0.mov

**Comment by twktue** [comment] 2022-01-22 00:11
I am experiencing this lag issue as well: `Version 97.0.4692.71 (Official Build) (arm64)` on `macOS 12.1 (21C52)`. 

I installed [Chrome Beta](https://www.google.com/chrome/beta/) `Version 98.0.4758.66 (Official Build) beta (arm64)` and the **lag disappeared**. 

I told my IT admin about this and he said that we are using the "Enterprise" version of Chrome, so I installed [Chrome Beta Enterprise](https://chromeenterprise.google/browser/download/#mac-tab) `Version 98.0.4758.66 (Official Build) beta (arm64)` and the **lag returned**.

**Comment by rstoenescu** [comment] 2022-01-22 06:55
Thank you all for commenting. All we can do is hope that the Chrome team fixes this soon.

If not, or as is the case with Chrome "Enterprise", please raise a bug ticket to them. There is nothing that we can do from within Quasar other than remove the focusing feature, which would be absurd.

**Closed as completed by rstoenescu** 2022-01-22 06:55 UTC
Labels: kind/bug 🐞, :outbox_tray: external lib issue, Qv2 🔝, area/components

**Comment by darkopetreski** [comment] 2022-01-25 07:57
I have reported the bug here https://bugs.chromium.org/p/chromium/issues/detail?id=1290371

The problem is, it cannot animate currentColor. If instead of current color, specific color is provided, example gray, it works.
```css
body.desktop .q-focusable:focus>.q-focus-helper, 
body.desktop .q-hoverable:hover>.q-focus-helper, 
body.desktop .q-manual-focusable--focused>.q-focus-helper {
    background: currentColor;     /** This causes the glitch. with specific color it works **/
    opacity: .15;
}
```

**Comment by darkopetreski** [comment] 2022-01-25 09:21
If someone needs a quick fix for this, the following css can be used in the app.css

```css
body.desktop .q-focusable:focus>.q-focus-helper,
body.desktop .q-hoverable:hover>.q-focus-helper,
body.desktop .q-manual-focusable--focused>.q-focus-helper {
    background: gray !important;
}
```

**Comment by pxDot** [comment] 2022-01-25 11:20
> I have reported the bug here https://bugs.chromium.org/p/chromium/issues/detail?id=1290371
> 
> The problem is, it cannot animate currentColor. If instead of current color, specific color is provided, example gray, it works.
> 
> ```css
> body.desktop .q-focusable:focus>.q-focus-helper, 
> body.desktop .q-hoverable:hover>.q-focus-helper, 
> body.desktop .q-manual-focusable--focused>.q-focus-helper {
>     background: currentColor;     /** This causes the glitch. with specific color it works **/
>     opacity: .15;
> }
> ```



> If someone needs a quick fix for this, the following css can be used in the app.css
> 
> ```css
> body.desktop .q-focusable:focus>.q-focus-helper,
> body.desktop .q-hoverable:hover>.q-focus-helper,
> body.desktop .q-manual-focusable--focused>.q-focus-helper {
>     background: gray !important;
> }
> ```

Awesome, tyvm for tracking this down. I will keep a close look to your issue on the chromium issue tracker.

**Comment by nataliedemma** [comment] 2022-07-12 17:03
I'm still having this problem with macOS Monterey 12.4 and Chrome 103.0.5060.114. 
Switching off the hardware acceleration in chrome solved the issue.

**Comment by thf24** [comment] 2022-07-27 10:00
Can confirm that this is still a problem, but only with Chrome. Also its not just on the initial transition but always. The Quasar website seems fine but if you create the sample project with the Quasar CLI the problem is already visible.

**Comment by harshiet** [comment] 2022-08-03 11:14
Updated chrome to Version 104.0.5112.79 (Official Build) (x86_64), macOS Monterey 12.4 - working fine on chrome now.
