### ISSUE TITLE
Overriding quasar scss variables doesn't work when I change the quasar.variables.scss location in quasar.config.js

### ISSUE THREAD

**Issue by doox911** [quasarframework/quasar#14594] opened 2022-10-10 20:58 UTC
### What happened?

I moved the quasar.variables.scss to `./src/app/css/`. And then redefined the value of the $primary variable:

```
/* Prev */
/* $primary: #00b4ff; */
$primary: green;

/* ... */
```

But the variable has not been redefined.

### What did you expect to happen?

The variable had to be redefined.

### Reproduction URL

https://stackblitz.com/edit/quasarframework-webpack-nvwe18?file=src/components/AppBtn.vue

### How to reproduce?

Follow the link above

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app-webpack)

### Platforms/Browsers

Chrome

### Additional context

I tried to configure this through various properties(scssLoaderOptions, sassLoaderOptions) in property build in quasar.config.js, for example:
```
scssLoaderOptions: {
  additionalData: '@import "App/src/app/css/quasar.variables.scss"; ',
},
sassLoaderOptions: {
  additionalData: '@import App/src/app/css/quasar.variables.scss;',
},
```

Perhaps the problem lies in the fact that it is impossible to pass the path to the quasar.variables.scss:

https://github.com/quasarframework/quasar/blob/dev/app-webpack/lib/helpers/css-variables.js

**Comment by pdanpdan** [comment] 2022-10-11 07:48
duplicate of #14540

**Closed as completed by pdanpdan** 2022-10-11 07:48 UTC
Labels: kind/bug 🐞, Qv2 🔝, flavour/quasar-cli-webpack, bug/1-repro-available, area/cli
