### ISSUE TITLE
[Request] QSelect with "All values" option

### ISSUE THREAD

**Issue by marcelo-rebello** [quasarframework/quasar#2440] opened 2018-08-21 03:56 UTC
I would like an property for the QSelect component that includes an "All values" at the top/bottom of the options list so that user can easily select all values.
It is quite similar to the 'clearble' property, just selecting all values.
It is a common use case to fetch a list of values from server/store and then display then to user make a selection, but manually include an "All values" to every time can be tedious...

**Comment by olegvakulenko** [comment] 2018-08-21 07:12
IMHO, it is over complicated.

1. To select all values model must be array.
2. After selection all values option "All values" doesn't highlighted because it value doesn't match with model. At this time, as I can see, Quasar doesn't compare array in option value and array in model. It compare option value with each element in model array.
3. If add new property to component it must to support i18n, or manual define option label: `"All values"` or `"Все значения"` or other.

Thanks.

**Comment by panstromek** [comment] 2018-08-21 13:52
You should be able to do this yourself - just hook some button to a function which pushes all values from the options to a an array that you use a s `v-model`.

**Comment by panstromek** [comment] 2018-08-21 14:07
did a quick POC as an excercise ;), can be tweaked to work more user-friendly  but just to show it is possible it works ;)

**Comment by rstoenescu** [comment] 2018-08-21 15:26
Duplicate of https://github.com/quasarframework/quasar/issues/828

**Closed by rstoenescu** 2018-08-21 15:26 UTC
