### ISSUE TITLE
Inf scroll cannot read property concat of undefined

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#5473] opened 2019-11-05 10:42 UTC
Hello!

I'm using Inf Scroll example from the docs with a very small change:
default `items = []`

![Screen Shot 2019-11-05 at 1 40 53 PM](https://user-images.githubusercontent.com/3635352/68201070-1f9b5780-ffd2-11e9-9040-e833d614f899.png)

Getting the error:
![Screen Shot 2019-11-05 at 1 40 49 PM](https://user-images.githubusercontent.com/3635352/68200983-ff6b9880-ffd1-11e9-8579-4b6bfd1cb717.png)

https://codepen.io/jean-moldovan/pen/bGGvbOY?&editable=true&editors=101

Looks like this happens on v1.3.0 only

**Comment by rstoenescu** [comment] 2019-11-05 11:30
Duplicate of https://github.com/quasarframework/quasar/issues/5452
Already fixed. Will be available in next Quasar version.

**Closed by rstoenescu** 2019-11-05 11:30 UTC
Labels: bug

**Comment by s4ntosbruno** [comment] 2020-07-29 14:42
I am having the same issue (Cannot read property 'concat' of undefined) on the QBtnDropdown 
![image](https://user-images.githubusercontent.com/43258154/88814546-c4d20d80-d1a9-11ea-9c99-b67e6a0c8ecf.png)

**Comment by pdanpdan** [comment] 2020-07-29 14:50
@s4ntosbruno some info from you would help. Please check the issue template and fill it.
