### ISSUE TITLE
QBtn outline render bug on hover (Safari only)

### ISSUE THREAD

**Issue by jean-moldovan** [quasarframework/quasar#1549] opened 2018-02-08 20:17 UTC
Have seen this happening with v0.14 and latest v0.15.

There is some sort of a render issue when hovering over the round outlined button in Safari.

Please see: https://jsfiddle.net/a99fkq97/1/

Thanks!

**Comment by jean-moldovan** [comment] 2018-02-08 20:18
![screen shot 2018-02-08 at 23 11 20](https://user-images.githubusercontent.com/3635352/35996035-5a6e9480-0d26-11e8-961b-2993a0913759.png)

**Comment by rstoenescu** [comment] 2018-02-08 20:40
Hi, I can't reproduce it in Safari. Any details? What version of Safari? Safari on a desktop or on a mobile? Give me something to work with :)

**Comment by jean-moldovan** [comment] 2018-02-08 20:42
Safari desktop 11.0.3

**Comment by jean-moldovan** [comment] 2018-02-08 20:50
![feb-08-2018 23-48-39](https://user-images.githubusercontent.com/3635352/35997504-bc0675a6-0d2a-11e8-8010-07cb592c56a8.gif)

**Comment by rstoenescu** [comment] 2018-02-08 21:33
I am also running Version 11.0.3 (13604.5.6)... can't reproduce... can anyone else reproduce?

**Comment by olegvakulenko** [comment] 2018-02-08 21:51
I see same problem with outline, but I run MacOS under VMWare.

**Comment by rstoenescu** [comment] 2018-02-08 21:57
@jean-moldovan are you running unde VMWare or Virtualbox too?

**Comment by spectrolite** [comment] 2018-02-09 00:42
MacOS 10.13.1
Safari Version 11.0.1 (13604.3.5)
Hovering the button breaks it as seen in the above pic, and it stays broken after mouse exits area.
If I click it, it changes to a circle again, and is fine until I exit the area, then it breaks again.
I also noticed that if I exit the area before the ripple effect finishes, it fixes itself when the ripple ends.
Finally, it fixes itself when the last alert on bottom clears out.

**Comment by MoacirSchmidt** [comment] 2018-02-09 00:43
I can't reproduce running on Safari 10.1.2, MacOS Sierra 10.12.6 (Virtual Machine VMWare Workstation)

**Comment by jean-moldovan** [comment] 2018-02-09 06:15
@rstoenescu , I'm on Mac Sierra 10.13.3

**Comment by maciekkus** [comment] 2018-02-09 09:10
@rstoenescu MacOs High Sierra 10.13.2, Safari 11.0.2 (13604.4.7.1.6)
it reproduces

**Comment by rstoenescu** [comment] 2018-02-10 23:01
@jean-moldovan @olegvakulenko @spectrolite @maciekkus 
Can you tell me if the issue is still reproducible in this jsfiddle pls? https://jsfiddle.net/rstoenescu/50cobw6x/

**Comment by olegvakulenko** [comment] 2018-02-10 23:31
In macOS High Sierra 10.13.3 under VMWare issue is still reproduce (attachment). But I see issues with shadow in notify message. IMHO this problem is Safari bug or video driver bug in hardware acceleration.
 
In Chrome on mac outline work fine, but I see some blinking when notify appear. In Firefox on mac work perfect. So I think this Safari issue, or even WebKit and Blink issue.

![untitled-1](https://user-images.githubusercontent.com/30389307/36067634-74eebc78-0ec9-11e8-94cd-b52327e6ed4e.jpg)

**Comment by maciekkus** [comment] 2018-02-11 00:01
@rstoenescu still reproducible from your fiddle.

but I would like to ask others about that fix: https://jsfiddle.net/vkg5g7z3/
(not sure why it works on my safari :) )
@jean-moldovan @olegvakulenko @spectrolite

**Comment by jean-moldovan** [comment] 2018-02-11 09:21
hey, @maciekkus , your fix worked for me!

**Comment by olegvakulenko** [comment] 2018-02-11 10:59
@maciekkus 
Your fix work for outline effect in my system.

**Comment by rstoenescu** [comment] 2018-02-11 13:43
Embedded fix. Will be in next v0.15 beta. Thanks for helping out!

**Closed by rstoenescu** 2018-02-11 13:43 UTC
