### ISSUE TITLE
The bingding value of directive V-model is changing when inputing in the QInput component

### ISSUE THREAD

**Issue by zouzg7829** [quasarframework/quasar#8116] opened 2020-11-27 11:39 UTC
**Describe the bug**
When using QInput component, the The bingding value of directive v-model will change when inputing with [IME](https://en.wikipedia.org/wiki/Input_method) (Chinese, Japanese, Korean, etc.).
For languages that require an [IME](https://en.wikipedia.org/wiki/Input_method) (Chinese, Japanese, Korean, etc.), the directive v-model of the QInput component would display the same as v-mode of Vue official website that inputing with [IME](https://en.wikipedia.org/wiki/Input_method) would not update the value

**Codepen/jsFiddle/Codesandbox (required)**
none

**To Reproduce**
none

**Expected behavior**
the directive v-model of the QInput component would display the same as v-mode of Vue official website that inputing with [IME](https://en.wikipedia.org/wiki/Input_method) would not update the value.
for more information, see [Vue Official Document](https://vuejs.org/v2/guide/forms.html):
`For languages that require an [IME](https://en.wikipedia.org/wiki/Input_method) (Chinese, Japanese, Korean, etc.), you’ll notice that v-model doesn’t get updated during IME composition.`

**Screenshots**
none

**Platform (please complete the following information):**
none

**Additional context**
none

**Comment by pdanpdan** [comment] 2020-11-27 21:36
Hello.
Can you please explain the problem, detailed step by step (sequence of keys pressed, with what is emitted by QInput after each interaction)?
A video capture of the screen would help also.

**Comment by zouzg7829** [comment] 2020-12-01 12:02
@pdanpdan you can follow the below steps to reproduce the bug.
1. focus the QInput component
2. change the input method for other language(not english), for example chinese
3. when IME opend, for exammple, to input the char '中', you should input 'zhong' chars, but when input ‘z’, you will find the v-model does get updated, but the language char '中' yet not be completed, so the v-model **SHOULD** doesn’t get updated.

**Comment by pdanpdan** [comment] 2020-12-04 18:47
Sorry, I just tested and in my opinion all is good.
Due to lack of any details about version, browser and exact method to reproduce I'll close this.
If you can provide a clear step by step reproduction we'll reopen.

**Closed by pdanpdan** 2020-12-04 18:47 UTC
Labels: bug, need more info
