### ISSUE TITLE
[QSelect with multiple] Clear the filter field when and option is selected

### ISSUE THREAD

**Issue by DaedalusDev** [quasarframework/quasar#5038] opened 2019-09-06 14:49 UTC
**Is your feature request related to a problem? Please describe.**
When a user pick an option on a QSelect with `multiple` && `use-input` props, it would be a good think to clean the search field.
Ex : 
-  I have an autocomplete to select multiple `nationality`
- Sometime, the user type `Fr`, then select `French`
- The option `French` is added to field model
- Unfortunately, `Fr` is keeped, and the user need to clear the field to search another nationality

**Describe the solution you'd like**
Always clear the search field when an option is selected

**Describe alternatives you've considered**
Add a clear-search-field props to allow this feature to be available.

**Additional context**
Thanks for your your attention.

**Comment by rachitpant** [comment] 2019-09-06 15:51
The second part of issue #4732 highlights the same issue.

**Comment by pdanpdan** [comment] 2019-09-06 15:51
Duplicate of https://github.com/quasarframework/quasar/issues/4600 - check there for the reasons to behave this way.

If you want you can call `setInputValue('')` on `@input` to clear the filter.

**Closed by pdanpdan** 2019-09-06 15:51 UTC
Labels: feature request

**Comment by rachitpant** [comment] 2019-09-06 16:03
I am not able to call `setInputValue` within `@input`. Can you please update this snippet with your solution. https://codepen.io/matheusoluz/pen/ZdVvQL?editors=1010

**Comment by pdanpdan** [comment] 2019-09-06 16:41
Sorry, it was `updateInputValue`

https://codepen.io/pdanpdan/pen/wvwpNGv?editors=1010

**Comment by DaedalusDev** [comment] 2019-09-07 16:44
> Duplicate of #4600 - check there for the reasons to behave this way.
> 
> If you want you can call `setInputValue('')` on `@input` to clear the filter.

I'm sorry but... This isn't an elegant solution to handle this feature...

As it's explained is [Vue's style guide](https://vuejs.org/v2/style-guide/index.html#Implicit-parent-child-communication-use-with-caution), when a developper use VueJs in most case, he must **not** manipulate a children component, even less a component from an external library (will you forever name your method `updateInputValue` ?) This is a best way to introduce undebuggable behaviours. 

👍  #5041

**Comment by pdanpdan** [comment] 2019-09-07 17:54
Tell me you are joking?

**Comment by rstoenescu** [comment] 2019-09-08 11:26
`updateInputValue()` is a method of the component. It's not the same thing as "manipulating a child component".

**Comment by alexfaus08** [comment] 2025-02-27 15:59
For a q-select with multiple, you have to use create a method that is called in `@add` such as this:

```
  <q-select
        v-model="value"
        ref="myInput"
        use-input
        use-chips
        multiple
        input-debounce="0"
        :options="options"
        @add="clearInputAfterFilterSelection"
        @filter="filterOptions"
/>

clearInputAfterFilterSelection() {
    const inputRef = this.$refs.myInput 
    if (inputRef !== void 0) {
        inputRef.updateInputValue('')
    }
}
```
