### ISSUE TITLE
[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive

### ISSUE THREAD

**Issue by pengtech** [quasarframework/quasar#13963] opened 2022-07-15 02:45 UTC
### What happened?

Chrome waring: [Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive

### What did you expect to happen?

avoid these warning message

### Reproduction URL

https://foo

### How to reproduce?

1. using chrome to open  a page with q-scrollbar component
2. develop mode-->console, check warning messages

 [Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive

### Flavour

Quasar CLI with Webpack (@quasar/cli | @quasar/app-webpack)

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

**Comment by pdanpdan** [comment] 2022-07-15 06:27
duplicate of 12822

**Closed as completed by pdanpdan** 2022-07-15 06:27 UTC
Labels: kind/bug 🐞, bug/0-needs-info, Qv2 🔝, flavour/quasar-cli-webpack, area/components
