### ISSUE TITLE
QFile: onRejected is only called the first time when selecting a file

### ISSUE THREAD

**Issue by Evertvdw** [quasarframework/quasar#14047] opened 2022-07-25 13:13 UTC
### What happened?

When selecting a file that is too big it should emit an event that we can listen to. This only happens the first time you select a file, if afterwards you select another file which is too big the event is not emitted again.

### What did you expect to happen?

It should emit the event every time you select a file that does not meet constraints.

### Reproduction URL

https://codepen.io/Mett-codepens/pen/ExEvwjM?editors=101

### How to reproduce?

1. Select a file bigger than 2kb
2. Notice the notification
3. Wait for notification to disappear
4. Select another file bigger than 2kb
5. Notice the absence of the notification

### Flavour

UMD

### Areas

Components (quasar)

### Platforms/Browsers

Chrome

**Comment by pbkompasz** [comment] 2022-07-26 03:44
Cannot reproduce, notification appears after every rejected file pick as expected.

**Comment by Evertvdw** [comment] 2022-07-26 06:27
@pbkompasz I have it using Chrome on Windows, there I do have this problem. I also tried Firefox and Edge but those two I cannot reproduce the problem. It seems to be a Chrome only issue, possibly related to using Windows, what combination of OS/Browser are you on?

**Comment by yusufkandemir** [comment] 2022-07-26 08:41
#### Windows 11 Version 21H2 (Build 22000.795)
- Microsoft Edge 103.0.1264.62
	- If I select a different file one after the other(_including the previous ones I selected_), it shows the notification. (x -> y -> x -> z -> y -> x, etc.)
	- If I select the same file consecutively, it doesn't show the notification. (x -> x -> x, y -> y -> y, etc.)
- Firefox Developer Edition v103.0b9
	- It always shows the notification

#### macOS Monterey 12.5
- Microsoft Edge 103.0.1264.62
	- Same behavior as Edge on Windows 11

**Comment by pbkompasz** [comment] 2022-07-26 10:51
@yusufkandemir For the same file the notification doesn't appear on Chrome 99.0 and Ubuntu 20.04

**Comment by yusufkandemir** [comment] 2022-07-26 11:30
It looks like the error is Chromium-only and OS-independent. So, I've searched through our code to see where the validation starts getting triggered initially, and it's here: https://github.com/quasarframework/quasar/blob/a8f749c79d53a76b647b979cbc487e906d46e306/ui/src/components/uploader/uploader-core.js#L332
then searched the stuff about input[type="file"] and the change event through the Chromium issues and found this: https://bugs.chromium.org/p/chromium/issues/detail?id=1309893
Closing as this is not something we can fix. If the related issue gets addressed but there are still problems in Quasar-side, we can re-open this issue.

**Closed as completed by yusufkandemir** 2022-07-26 11:30 UTC
Labels: kind/bug 🐞, Qv2 🔝, flavour/umd, bug/1-repro-available, area/components

**Comment by rstoenescu** [comment] 2022-07-26 16:46
Fix will be available in Quasar v2.7.6 and 1.19.5
