### ISSUE TITLE
On Edge, while the input method (IME) is on, numbers entered cannot be bound to QInput

### ISSUE THREAD

**Issue by LXBsmall** [quasarframework/quasar#7356] opened 2020-07-06 08:19 UTC
Hi,

**Describe the bug**

On Edge, type some numbers when the Chinese input method is on, the `v-model` doesn't work, the `@input` event isn't triggered, so no value is bound.

- quasar\src\components\input\QInput.js:189

```js
if (e && e.target && e.target.composing === true) {
  return
}
```

And the `e.target.composing` is always true, while others browsers don't have this property.

**Expected behavior**

Enter correctly, bind correctly.

**Platform (please complete the following information):**

OS:
Node: v12.16.1
NPM: 6.13.4
Browsers: Microsoft Edge 44.17763.831.0， Microsoft EdgeHTML 18.17763
quasar: 1.12.7
@quasar/app: 1.8.5
quasar/extras: 1.7.0
quasar-cli: 1.8.5

**Additional context**

I've tested for the latest code, problems remain.

**Comment by pdanpdan** [comment] 2020-07-06 08:28
does this happen on IE11, Chrome, Firefox, Safari or the new Edge?
else it would look like a wrong implementation of composition in Edge and can be used as designed to download a browser :D

**Comment by pdanpdan** [comment] 2020-07-07 19:25
@LXBsmall ping

**Comment by LXBsmall** [comment] 2020-07-08 02:40
Other browsers have not found this condition for the time being，The new Edge didn't try, the company computer couldn't download it.

**Comment by LXBsmall** [comment] 2020-07-10 07:37
```javascript
if (e && e.target && e.target.composing === true) {
   return
}
```

I found that only Edge has composing property, and neither firefox nor chrome has the property. But only Edge has a problem, comment the code above, and the code doesn't work in other browsers because there is no composing property

Can you change the code, the company uses all the old Edge, the new Edge deployment is not my decision
Or could I pull a request? comment the code above.

**Comment by pdanpdan** [comment] 2020-07-10 08:59
Hello. I'm sorry but there is no way to test the old Edge because it was removed from from the distribution.
If you need a special build for that case you can just download from github and patch that code for your specific use case.
But watch out you'll lose all composition checking.

**Comment by webnoob** [comment] 2020-07-15 22:47
Does this still need to be open?

**Comment by pdanpdan** [comment] 2020-07-15 23:00
Leave it open some more, please. Maybe someone can test and give a solution, or at least a check that it only happens on Edge (old)

**Comment by LXBsmall** [comment] 2020-07-17 04:01
What I want to ask is how to replace @quasar/cli in local code

**Comment by pdanpdan** [comment] 2020-07-17 04:14
What do you mean by this?

**Comment by LXBsmall** [comment] 2020-07-17 04:29
I created the project with the @quasar/cli, and now I want to download code localization from github, what do I do?

**Comment by pdanpdan** [comment] 2020-07-17 04:35
Please head to our discord channel or to the forum for discussions

**Comment by LXBsmall** [comment] 2020-07-17 04:38
ok, thanks

**Comment by pdanpdan** [comment] 2021-01-22 16:59
closing this as edge is dead and buried :)

**Closed by pdanpdan** 2021-01-22 16:59 UTC
Labels: :beetle: bug
