### ISSUE TITLE
[V1] Outlined Input label to follow the Material Design Spec

### ISSUE THREAD

**Issue by wannymiarelli** [quasarframework/quasar#4082] opened 2019-05-09 18:21 UTC
The outlined q-input looks like this at the moment

![image](https://user-images.githubusercontent.com/2851947/57476880-d626b580-7297-11e9-868b-c05ee6dafee9.png)

looking at the [Material Design Spec in the official website](https://material.io/design/components/text-fields.html#usage) it should actually look like this

![image](https://user-images.githubusercontent.com/2851947/57476821-b2fc0600-7297-11e9-897b-e66697820cac.png)

**This is not urgent - would be great to have this after RC**

**Comment by lucasfernog** [comment] 2019-05-09 21:18
Duplicate of #3262

**Closed** 2019-05-10 09:15 UTC
