### ISSUE TITLE
[v1] QFooter and elements inside QDrawer on iPad pro with iOS 12.2 are not reactive

### ISSUE THREAD

**Issue by martinflorek** [quasarframework/quasar#3716] opened 2019-03-27 13:04 UTC
### Software version
v1.0.0-beta.13

Quasar: 1.0.0-beta.13
@quasar/app (v1+ only):
OS: iOS 12.2 on iPad pro only
Node:
NPM:
Browsers: Mobile Safari
iOS: 12.2 on iPad pro 12.9" only
Android:
Any other software related to your bug:

### JsFiddle
[JsFiddle](https://jsfiddle.net/vxztLpdf/)

### What did you get as the error?
UI is not updated when changing reactive properties.

### What were you expecting?
UI should change when the properties change.

### What steps did you take, to get the error?
QLayout with QDrawer and QFooter with reactive values. This is happening only on iPad pro with iOS 12.2 (tested on 3rd generation iPad pro 12.9" and also on its simulator). This works on iPhone with iOS 12.2 and also on the same iPad pro with iOS 12.1. Everything also works on all other platforms, including Safari on macOS.

See the attached JsFiddle and click the "show footer" button in the header. It should show the footer and the text in the right drawer should change from "Before" to "After".

**Comment by rstoenescu** [comment] 2019-04-21 15:19
Duplicate of https://github.com/quasarframework/quasar/issues/3784
Fix available in beta.18 (released already).

**Closed by rstoenescu** 2019-04-21 15:19 UTC
