### ISSUE TITLE
depth bug with non-active tabs

### ISSUE THREAD

**Issue by Boid-John** [quasarframework/quasar#1195] opened 2017-11-28 04:13 UTC
When tabs are inverted, the tabs which are not active will appear below text on the page.

https://i.imgur.com/bKTtmlO.png

Using tabs in layout navigation slot of layout

`    <q-tabs
      inverted
      slot="navigation"
      align="left"
      v-if="showMenu"
    >
    <q-route-tab
      icon="home"
      to="/"
      exact
      slot="title"
    />
    <q-route-tab
    icon="account_circle"
    to="/u"
    exact
    slot="title"
    />
  </q-tabs>`

**Comment by pdanpdan** [comment] 2017-11-28 17:41
It'll be fixed in the upcoming version

**Comment by rstoenescu** [comment] 2017-11-28 17:48
Hi,

This is not a bug. When using "inverted" tabs, the background color is intentionally left out, because there are situations where you would want that effect to occur.
In your case, simply put a background color on QTabs tag.

**Closed by rstoenescu** 2017-11-28 17:48 UTC

**Comment by Boid-John** [comment] 2017-11-28 23:53
Thanks for the clarification. I'd be curious to see an example of the intended usage.
