### ISSUE TITLE
Memory leak in QSelect component with "use-input" prop enabled

### ISSUE THREAD

**Issue by letehaha** [quasarframework/quasar#14647] opened 2022-10-18 21:49 UTC
### What happened?

"use-input" prop on QSelect, wrapped in QDialog, produces a memory leak.

### What did you expect to happen?

"use-input" prop on QSelect, wrapped in QDialog, doesn't produce a memory leak.

### Reproduction URL

https://jsfiddle.net/dmytro_svyrydenko/jx1trcLv/14/

### How to reproduce?

1. Go to the provided reproduction link.
2. Go to the "Memory" tab, and select the second VM instance, where the code result is running. Make a Heap Snapshot. It will be the initial value.
3. Click on the "TOGGLE" button.
4. Focus on any field so that the dropdown with options is opened.
5. Close the dropdown, and click "TOGGLE" to hide elements.
6. Go to the "Memory" tab, and select the second VM instance, where the code result is running.
7. Make Heap Snapshot (Garbage Collection is called automatically, but you can force it manually if you wish).
8. Filter both initial and newly created Snapshots by "Detached".
9. See the difference in Detached elements on the page. Each repetition of steps 2-4 just increases the number of detached nodes.

Happens on both UMD and Vue CLI plugin versions. Didn't test others.

### Flavour

UMD

### Areas

Components (quasar)

### Platforms/Browsers

Firefox, Chrome, Safari, Microsoft Edge

### Quasar info output

```Shell
Operating System        Darwin(22.1.0) - darwin/x64
NodeJs                  12.18.3

Global packages    
  NPM                   6.14.6
  yarn                  1.16.0
  @quasar/cli           1.3.2
  @quasar/icongenie     Not installed
  cordova               Not installed
```

**Comment by letehaha** [comment] 2022-10-26 18:36
Okay, so there's an update. I've tried to replace "q-select + use-input prop" with "q-input + q-menu + custom code" to get rid of the memory leak but keep the same functionality, but I faced the same problem with the memory leak. So I've checked and seems like it's q-input leaking itself **when it's inside q-dialog**.

Here is the reproduction link: https://jsfiddle.net/dmytro_svyrydenko/70bwm6jf/1/

The reproduction steps are the same as on the original topic.

Screenshots for your understanding. There're 40 input fields in the test env. As you can see from the table, after a single open-close and focus on a single field, there're now 40 fields leaked (as you can see on the screenshot below they're "Detached from DOM tree").

<img width="418" alt="image" src="https://user-images.githubusercontent.com/12257282/198108447-f429bf05-5acb-404d-ba7b-d41c79be4055.png">


<table>
<tr>
<td>When opened and closed dialog, but not focused any field</td>
<td>When opened and closed dialog, but focused a single field</td>
</tr>
<tr>
<td>
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/12257282/198107971-b7cfcb87-9390-446a-8324-f09dd320f9ba.png">
</td>
<td>
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/12257282/198108100-3919c711-5bcd-4203-be3e-f3048f5deb5d.png">
</td>
</tr>
</table>

**Comment by rstoenescu** [comment] 2022-10-29 10:11
This seems like a Vue problem. I replaced QInput with a native `<input>` element and still got detached input els.
Investigating further.

**Comment by rstoenescu** [comment] 2022-10-29 13:12
Root caused it. Unbelievable reason. Looking for a fix.

**Comment by rstoenescu** [comment] 2022-10-29 15:52
```html
<!DOCTYPE html>
<html>
  <body>
    <div id="root">
      <button id="btn">Click me</button>
      <input>
    </div>

    <script>
      const id = document.getElementById('root')
      const btn = document.getElementById('btn')

      function fn () {
        btn.removeEventListener('click', fn)
        id.remove()
      }

      btn.addEventListener('click', fn)
    </script>
  </body>
</html>
```

If you run the above, you'll get the same result. It's actually a browser bug/behavior (!?!) due to references in the emitted Event (siblings, parent, children, relatedTarget, etc etc).

Created an SPA with multiple routes and it seems that changing the route allowed GC to free up the memory. But this is by far a stretch.

I initially thought that retaining the Event object (so that it's emitted later then discarded from memory) was the problem in Quasar Portal, since an Event references lots of DOM Elements. I then dropped this algorithm from it and it "solved" the problem. But then I did more experiments and it seems that wherever an Event is emitted and afterwards that DOM Element that triggered it is removed from DOM it then causes this issues. But obviously, we can't remove all Event from everywhere in Quasar because it would cripple the framework. And it's not even a solution, as developers can create this "issue" in their own code (without even using Quasar or Vue).

So having the above html file reproducing the same issue (which uses just vanilla JS), I can only close this ticket as it's actually not related to Quasar or to Vue. Since in one of my experiments (the one with the route change) freed up the memory, I can only guess that the GC in Chrome is not triggered immediately, but at certain points in time (when thresholds are met).

**Closed as completed by rstoenescu** 2022-10-29 15:52 UTC
Labels: kind/bug 🐞, Qv2 🔝, flavour/umd, bug/1-repro-available, area/components

**Comment by rstoenescu** [comment] 2022-10-29 15:54
PS: in my html example I have one `<input>` element, but it does not really matter to the core issue at hand here. It just helps in identifying the detached HTMLInputElement from the memory snapshot and does NOT influence the browser behavior anyway even if you remove it.

**Comment by letehaha** [comment] 2022-10-31 16:53
That's very interesting 🤯 Didn't dive that much since even didn't expect that. Thanks a lot for your time! Will investigate how to handle that, since in my case this issue/behavior takes too much memory.

**Comment by rstoenescu** [comment] 2022-11-01 10:15
More findings:

1. There are no detached elements when devtools is not opened (and never was opened for the respective page). So basically this is a non-issue in production. Tested with Edge (Chromium & Blink based, not perfectly equivalent to Chrome) and its "Detached Elements" feature in devtools (+ forced GC, important!).
2. Just be more accurate with the methodology used to test (the previous example kept references to btn and root elements):

  ```html
  <!DOCTYPE html>
  <html>
    <body>
      <div id="root">
        <button id="btn">Click me</button>
        <input>
      </div>

      <script>
        function fn () {
          document.getElementById('btn').removeEventListener('click', fn)
          document.getElementById('root').remove()
        }

        document.getElementById('btn').addEventListener('click', fn)
      </script>
    </body>
  </html>
  ```

  It DOES matter if there is an input element (that got focused!). When the previously focused input element gets removed and devtools was opened then a bug in chromium hinders GC to do its job fully. Eventually, GC will kick in, but definitely not immediately.

---

Conclusion: At some point, this will get fixed in the Chromium/Blink engine. But we really can't do anything about it in Quasar. But it seems to not affect a production environment.

**Comment by letehaha** [comment] 2022-11-01 10:34
Thanks a lot for sharing your findings!

> There are no detached elements when devtools is not opened

Just to clarify, do I understand correctly that this part was tested by first removing the DOM node with devtools not opened, and only then you opened devtools to make a snapshot?

**Comment by rstoenescu** [comment] 2022-11-01 10:44
Yes.
