### ISSUE TITLE
props is not declared in QuasarLanguage interface

### ISSUE THREAD

**Issue by cap1024** [quasarframework/quasar#16790] opened 2024-01-20 13:43 UTC
### What happened?

`props` identifier is not declared in `QuasarLanguage` interface.
```
Quasar.lang.props.label.close
```
This is actual path to `close` localization from script.

### What did you expect to happen?

```
Quasar.lang.label.close
```
This is path to `close` localization from script according to interfaces declaration.

### Reproduction URL

https://codepen.io/cap1024/pen/ZEPyGJL

### How to reproduce?

`$q.lang.label.close` - from template
`Quasar.lang.props.label.close` - from script

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

TypeScript Support

**Comment by yusufkandemir** [comment] 2024-01-20 21:07
Duplicate of #14569

**Closed as not planned by yusufkandemir** 2024-01-20 21:07 UTC
Labels: kind/bug 🐞, area/typescript, Qv2 🔝, bug/1-repro-available, flavour/quasar-cli-vite
