### ISSUE TITLE
Shrink Toolbar on scroll

### ISSUE THREAD

**Issue by musicformellons** [quasarframework/quasar#81] opened 2016-09-05 19:24 UTC
Maybe add this feature as an option:

https://github.com/dalphyx/vue-headroom

**Comment by rstoenescu** [comment] 2016-09-06 05:44
You mean for the Layout header? I've already opened up a Proposal issue for Toolbars. Quasar had an even smarter scrolling behavior for Layout header on the previous architecture, but only up to some point. It needs to be resurrected for current architecture, but just didn't have the time for it :)

Anyway, seeing the vue-headroom gave me some new ideas on top of what Quasar had at one point in time, so this is good! First chance I get I'll do something about it.

**Comment by musicformellons** [comment] 2016-09-06 09:56
I think both for Layout header and for Toolbars are cool and useful. Especially on mobile all screen-estate savers are important. Looking forward to it.

**Comment by rstoenescu** [comment] 2016-11-23 18:47
Closing duplicate of #38 . Will continue tracking this issue from there.

**Closed by rstoenescu** 2016-11-23 18:47 UTC
Labels: proposal
