### ISSUE TITLE
No slot available in q-icon when using custom image

### ISSUE THREAD

**Issue by gaw89** [quasarframework/quasar#11917] opened 2022-01-05 18:19 UTC
**Describe the bug**
When using `name="img:<url>"`, in a q-icon, the default slot does not get rendered.

**Codepen/jsFiddle/Codesandbox (required or your issue may be closed)**
[codepen](https://codepen.io/gaw89/pen/LYzreQd)

**To Reproduce**
1. Hover over the X icon - you see a tooltip
2. Hover over the Quasar icon - you don't see a tooltip

**Expected behavior**
I expect to see a tooltip when hovering each icon.

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version: v2.4.3

Quasar mode:
  - [X] SPA

Tested on:
  - [X] SPA

**Additional context**
It looks like [this line](https://github.com/quasarframework/quasar/blob/a5994932817212ed799825144629fb7ab077da4c/ui/src/components/icon/QIcon.js#L180) is missing ` hSlot(slots.default)`.

Hopefully the fix is as simple as adding this to that line!

p.s. Quasar rocks!!

**Comment by pdanpdan** [comment] 2022-01-05 18:23
Duplicate of https://github.com/quasarframework/quasar/issues/5967

**Closed as completed by pdanpdan** 2022-01-05 18:23 UTC

**Comment by gaw89** [comment] 2022-01-05 18:25
Oops, sorry @pdanpdan !  I did search for an existing issue but failed to find this #5967.

Thanks so much!!
