### ISSUE TITLE
Indeterminate State for the Loading Bar Plugin & Ajax Bar

### ISSUE THREAD

**Issue by mkarras** [quasarframework/quasar#7473] opened 2020-07-21 21:32 UTC
**Describe the solution you'd like**

To achieve a more realistic loading behavior/feedback (instead of faking the progress) it would be great if the Loading Bar Plugin & Ajax Bar would have a Indeterminate Mode/State like QLinearProgress here: https://quasar.dev/vue-components/linear-progress#Indeterminate-state

**Comment by pdanpdan** [comment] 2020-07-21 22:01
duplicate of #2823

**Closed by pdanpdan** 2020-07-21 22:01 UTC
