### ISSUE TITLE
Delay in page transition with tabs

### ISSUE THREAD

**Issue by gecko-8** [quasarframework/quasar#1369] opened 2018-01-01 17:46 UTC
Hi there,
I'm just wrapping my head around Quasar and setup a simple Cordova wrapped app with a q-tabs component in the navigation slot of a q-layout component. I added 4 simple routes and added tabs for each (added the code at the bottom of this post). When I run in Chrome using "cordova run browser" or "npm run dev" it's very responsive but when I run in an iOS emulator or on a device, there's a significant delay from when the tab is tapped and the app responds by navigating. I'm not sure if this is expected behaviour but it really makes the app feel sluggish.

This may be related to this older bug but that has been closed so this may be something new: [https://github.com/quasarframework/quasar/issues/187](url)

### Software version

Quasar: 0.14.7
OS: OSX 10.13.2 High Sierra
Node: 7.5.0
NPM: 4.1.2
Browsers: Chrome 63.0.3239.84
iOS: 11.2.1
Android:
Any other software related to your bug:

### What did you get as the error?
Slow navigation between routes.

### What were you expecting?
Responsive navigation.

### What steps did you take, to get the error?
Built basic Quasar app with Cordova wrapper. Added q-layout with q-tabs to App.vue. Added components for 4 simple pages (just title, e.g. Page 1 in each page).

### App.vue
```
<template>
    <!-- Don't drop "q-app" class -->
    <div id="q-app">
        <q-layout ref="layout" view="lHh Lpr fff">
            <q-tabs slot="navigation">
                <q-route-tab icon="mail" to="/page1" replace slot="title">Page 1</q-route-tab>
                <q-route-tab icon="mail" to="/page2" replace slot="title">Page 2</q-route-tab>
                <q-route-tab icon="mail" to="/page3" replace slot="title">Page 3</q-route-tab>
                <q-route-tab icon="mail" to="/page4" replace slot="title">Page 4</q-route-tab>
            </q-tabs>
            <router-view />
        </q-layout>
    </div>
</template>

<script>
import { QLayout, QTabs, QRouteTab } from "quasar";

/*
 * Root component
 */
export default {
    components: {
        QLayout,
        QTabs,
        QRouteTab
    }
};
</script>

<style>
</style>
```

### Page1.vue (Page2, 3, and 4 are the same)
```
<template>
  <div>Page 1</div>
</template>

<script>
export default {
  data () {
    return {}
  }
}
</script>

<style>
</style>
```

**Comment by rstoenescu** [comment] 2018-01-02 16:37
This has same root cause as https://github.com/quasarframework/quasar/issues/1269,
so closing it. Seems like iOS 11 is "naughty". Will get fixed. Thanks!

**Comment by gecko-8** [comment] 2018-01-02 17:22
Sounds good, thanks for the quick response!

**Closed** 2018-01-31 09:06 UTC
