### ISSUE TITLE
'mat' theme looks different between dev and prod

### ISSUE THREAD

**Issue by amaranthius** [quasarframework/quasar#750] opened 2017-07-26 08:04 UTC
### Software version

Quasar: v14 beta
OS: macOS Sierra
Node: 6.11.1
NPM: 5.3.0
Browsers: Chrome, Firefox (latest)
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?
After upgrading to v14 I noticed inconsistencies in the **mat** theme between _dev_ and _prod_ mode (please refer to screenshots as an example).

**dev:**
<img width="427" alt="screen shot 2017-07-26 at 10 52 13" src="https://user-images.githubusercontent.com/964863/28615750-dcc46974-7202-11e7-8584-cbe629976013.png">

**prod:**
<img width="424" alt="screen shot 2017-07-26 at 10 52 42" src="https://user-images.githubusercontent.com/964863/28615751-dccb9366-7202-11e7-8bc2-ff05b2535ca1.png">

### What were you expecting?
Theme to look the same

### What steps did you take, to get the error?
1. Run `quasar dev` - everything looks normal
1. Run `npm build`, then run express server - theme is messed up

**Comment by JCharante** [comment] 2017-07-26 13:54
Is there a reproduction repo so someone else can confirm the bug?

And why `npm build`? Did you mean `quasar build`? `npm build` doesn't seem to do anything for me.

**Comment by a47ae** [comment] 2017-07-27 01:39
@JCharante `quasar build` is basically the same as `npm run build` :)

**Comment by amaranthius** [comment] 2017-07-27 13:12
@JCharante I meant `npm RUN build`, yes. Just a typo there. And yes, the two are interchangeable.

**Comment by rstoenescu** [comment] 2017-08-01 08:15
It's probably a problem with PurifyCSS. Disable it from config. Any repo I can take a look?

**Comment by rstoenescu** [comment] 2017-08-01 08:16
Can't reproduce it.

**Comment by amaranthius** [comment] 2017-08-01 08:52
@rstoenescu, just tried disabling purifyCSS and the problem is still visible. As for the repo - sure, I can setup one, just let me know what exactly do you need

**Comment by rstoenescu** [comment] 2017-08-01 09:12
I need a repo where this problem can be reproduced. Can contain anything you want as long as it highlights the issue. Thx.

**Comment by amaranthius** [comment] 2017-08-01 11:36
@rstoenescu here it is:
https://github.com/amaranthius/quasar750

**Comment by rstoenescu** [comment] 2018-02-24 23:52
No longer a problem in v0.15. Forgot to close this.

**Closed by rstoenescu** 2018-02-24 23:52 UTC
