### ISSUE TITLE
Q-Btn-Dropdown split color is not inherited from color prop when used with outline design 

### ISSUE THREAD

**Issue by mv-go** [quasarframework/quasar#7331] opened 2020-06-30 17:11 UTC
**Describe the bug**
When `split` prop is enabled on `q-btn-dropdown` with `outline` design its color (split's) is not inherited from `q-btn-dropdown` `color` prop.

**Codepen/jsFiddle/Codesandbox (required)**
Slightly modified codepen from https://quasar.dev/vue-components/button-dropdown#Example--Split
https://codepen.io/mv-go/pen/xxZPZeP

**To Reproduce**
1. Set `split` prop to `q-btn-dropdown`
2. Set `outline`prop to `q-btn-dropdown`
2. Set `color` prop to `q-btn-dropdown` to something noticeable (`teal` for example)
3. Notice the split separator line has its own color of `rgba(255, 255, 255, 0.3)`

**Expected behavior**
Split line color to use the same color as set in the `q-btn-dropdown` `color` prop OR
Have a separate prop (like `split-color`) to control in directly

**Screenshots**
<img width="160" alt="image" src="https://user-images.githubusercontent.com/28507807/86155178-b9d58000-bb0c-11ea-957d-09cab001b5cd.png">

**Additional context**
This may only useful when `outline` design is used, however some issues with other design options may still arise (see the screenshot below)
<img width="147" alt="image" src="https://user-images.githubusercontent.com/28507807/86155709-82b39e80-bb0d-11ea-8804-1fd28da96717.png">

**Comment by pdanpdan** [comment] 2020-06-30 22:12
That color was set so by design. I don't remember the reasons like now, but you can easily change it.
If you need to customize that color use some CSS, like here:
https://codepen.io/pdanpdan/pen/eYJegNL

**Comment by webnoob** [comment] 2020-06-30 22:48
Given that changing this would be a breaking change in the current version and it can be easily rectified using CSS, I'm closing this for now.

**Closed by webnoob** 2020-06-30 22:48 UTC
Labels: bug
