### ISSUE TITLE
QSelect filter and select all

### ISSUE THREAD

**Issue by Lukino2000** [quasarframework/quasar#3859] opened 2019-04-11 14:08 UTC
in beta 16 QSelect, with autocomplete and filter features enabled, does select all after filter result but it shouldn't cause user can input other keystrokes

you can see differences between two version using
[beta16](https://codepen.io/Lukino2000/pen/jRmKda)
[beta15](https://codepen.io/Lukino2000/pen/Pgmdzd)

try search "ROSARNO"
after you type "RO", filter works as expected and show first 10 records, but if you type "S" it clear all cause the value was selected

### Software version

Quasar: 1.0.0-beta.16
@quasar/app (v1+ only): 1.0.0-beta.16
OS: Windows_NT(10.0.17763) - win32/x64
Browsers: Chrome

### What did you get as the error?
nothing, but it clear user input

### What were you expecting?
you can continue typing for filtering

**Comment by rstoenescu** [comment] 2019-04-11 15:00
Duplicate of https://github.com/quasarframework/quasar/issues/3850
Fix already pushed and will be available in beta.17

**Closed by rstoenescu** 2019-04-11 15:00 UTC
