### ISSUE TITLE
Possible to emit same filename for multiple chunks

### ISSUE THREAD

**Issue by nothingismagick** [quasarframework/quasar#5904] opened 2019-12-17 18:55 UTC
**Describe the bug**
I am consuming my own local app extensions (in a yarn workspace) and am running bleeding edge everything. Only if I use `framework.all = 'true'` will I get Quasar to run dev - but I cannot for the life of me get a build to succeed (either spa or ssr).

I am 100% positive that this is a regression introduced in @quasar/app@1.3.4

This is the error I am seeing on `quasar build` at the end:
```
Conflict: Multiple chunks emit assets to the same filename js/bba68bf6.ab4bf0d5.js (chunks bba68bf6 and bba68bf6)
```

This is pretty clearly a regression that appeared with the release of @quasar/app@1.3.4 -  I validated this today by downgrading to app@1.3.3 and quasar@1.5.1 and logged my webpack cfg. At this version constellation I could run `quasar build -m ssr` without problems. 

So I `diff`ed this webpack cfg with the webpack log afterwards with what bleeding edge should be:
```
Operating System - Darwin(16.7.0) - darwin/x64
NodeJs - 12.13.0

Global packages
  NPM - 6.12.0
  yarn - 1.21.1
  @quasar/cli - 1.0.3
  cordova - 9.0.0 (cordova-lib@9.0.1)
  quasar - 1.5.9
  @quasar/app - 1.4.1
  @quasar/extras - 1.3.3
  vue - 2.6.11
  vue-router - 3.1.3
```

This is the diff:
```
$ diff webpack-build-ssr-1.3.3.txt webpack-build-ssr-1.4.1.txt 

<  app:webpack Chaining Server Webpack config +347ms
---
>  app:webpack Chaining Server Webpack config +350ms
```

## What I have tried
I forked @webnoob 's qautomate and adapted it for my yarn workspace - but it only partially worked - and the errors didn't go away because I am still getting the Conflict mentioned at the top.

## What I would like:
To have the @quasar/app properly merge `all: 'auto'` with the components that are injected by the local app extensions. I know, kiddo - first world problems - I should just manually go through the errors and add the components / directives and plugins myself. But that won't solve the multiple chunk conflict - and I am pretty sure the two are connected in some abstract way that I don't grok... And maybe someone else has found a trivial solution to this too - I am all ears.

## What I cannot do:
- Downgrade to vue 2.6.10 * security compliance prohibits this

**Comment by rstoenescu** [comment] 2019-12-18 08:11
This has been fixed already in "@quasar/app" v1.4.1.

**Comment by nothingismagick** [comment] 2019-12-18 09:22
No it hasn't. I am still getting the multiple chunks error since 1.3.4

>

**Comment by rstoenescu** [comment] 2019-12-18 09:42
I see now. It's not duplicating stuff. The algorithm for asset name needs some tweaking.

**Comment by rstoenescu** [comment] 2019-12-18 09:44
The duplication of chunks has been fixed in 1.4.0, but it introduced this possible asset name problem. Fixing.

**Comment by rstoenescu** [comment] 2019-12-18 09:46
@nothingismagick any chance I can get a hand on your repo pls?

**Comment by nothingismagick** [comment] 2019-12-18 11:13
I'll make a repo to show this behavior. Can't share private code repo unfortunately.

**Comment by nothingismagick** [comment] 2019-12-18 20:55
I can't really replicate this without tons of work. However, I did find that the issue is resolved for me if i do the following:

```
cacheGroups.vendors.chunks = 'initial' 
```
In https://github.com/quasarframework/quasar/blob/dev/app/lib/webpack/create-chain.js#L212

**Comment by nothingismagick** [comment] 2019-12-18 21:30
I obviously don't have the insight to know if this might have side-effects on other modes that need create-chain - but need it right now so that our pipelines work again. So I made a patch - you can apply it with: https://github.com/ds300/patch-package

In case anyone else needs this or wants to check it out:

[@quasar+app+1.4.1.patch.zip](https://github.com/quasarframework/quasar/files/3980606/%40quasar%2Bapp%2B1.4.1.patch.zip)

**Comment by rstoenescu** [comment] 2019-12-19 08:44
It's ok to do that, BUT:

1. You'll end up with the initial bug which was fixed in v1.4+. Vendor chunk will only contain the initial page load deps. Since 99% of devs using Quasar are dynamically importing their layouts/pages in routes.js, you'll end up duplicating Quasar source code in all those layouts/pages.

2. The chunk naming algorithm hasn't changed in "years". I can't improve it since I don't have a reproducible case where it fails. As a sidenote, I was curious how this is handled in vue-cli and the same naming algorithm is used.

3. Instead of patching q/app, why not use quasar.conf.js > build > extendWebpack()/chainWebpack() to change that prop?

Sorry but until I have a reproducible use-case there's nothing that I can do. Feel free to reopen with a link to a repo.

**Closed by rstoenescu** 2019-12-19 08:44 UTC
Labels: bug

**Comment by bmansfie** [comment] 2019-12-20 06:19
I'm having this issue as well after an update to @quasar/app 1.4.2.  I will try to find some time to create a use case I can export and share with you to look at.

**Comment by rstoenescu** [comment] 2019-12-20 06:34
Awesome

**Comment by bmansfie** [comment] 2019-12-26 23:56
ERROR in chunk 8daa19ae
js/8daa19ae.8a00ee1b.js
Conflict: Multiple chunks emit assets to the same filename js/8daa19ae.8a00ee1b.js (chunks 8daa19ae and 8daa19ae)


 app:build [FAIL] Build failed with errors. Check log above. +0ms

I prepared a smallish project with the build issue.  The packages are part of the issue so this has the dependencies included, a private package that seems to be at the heart of the issue and you can't just install that with npm/yarn so I've bundled it all up for you.

https://www.sharpsoftware.dev/dl/quasar/buildIssueDebug.tar.gz

**Comment by bmansfie** [comment] 2020-01-10 20:44
opened new issue here https://github.com/quasarframework/quasar/issues/6071
