### ISSUE TITLE
Auto-import seems to be not working inside functional components

### ISSUE THREAD

**Issue by panstromek** [quasarframework/quasar#5373] opened 2019-10-22 14:38 UTC
**Describe the bug**
When I use quasar component inside functional component, using auto-import feature, I get
```
Unknown custom element: <q-icon> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
```

**To Reproduce**
1. Start new project
2. Create functional component inside it
```vue
<template functional>
  <div>
    <q-icon name="warning" />
  </div>
</template>
<script>
export default {
  name: 'FunctionalComponent'
}
</script>
```
3. Use it on some page

**Comment by huy-tran** [comment] 2019-10-27 23:12
https://quasar.dev/quasar-cli/quasar-conf-js#Property%3A-framework

Did you try to have `"framework": { "all": "auto" }` in quasar.conf.js file ?

**Comment by nothingismagick** [comment] 2019-11-07 12:26
I'm seeing similar in components from app extensions. Even if I manually add them to the boot-file in the index.js rigger, when combined with auto in the consuming quasar.conf.js, they are not hooked. It would probably make sense to merge auto with whatever is manually configured. @webnoob

**Comment by ejez** [comment] 2019-11-17 08:52
Quasar `auto-import` loader automatically adds code to import the detected components and also adds them in the `components` option of the component defined in a vue file, for the example given above, the following is automatically added:
```js
import {QIcon} from 'quasar'
component.options.components = Object.assign({QIcon}, component.options.components || {})
```
Functional components however do not accept the `components` option, thus the following code added by quasar auto-import loader gets disregarded by Vue:
```js
component.options.components = ...
```

We can't declare (locally register) vue components inside a functional component, this is by design. Why functional components do not accept `components` option? because they are simplified for performance and do not accept all the options normal (stateful) components do.
See: https://github.com/vuejs/vue/pull/8287#issuecomment-432327101 (point n 4)

To be able to use a vue component inside a functional component you need to [register it globally](https://vuejs.org/v2/guide/components-registration.html#Global-Registration) (not recommended) or use a workaround like: https://github.com/vuejs/vue/issues/7492#issuecomment-379570456

Now for the auto import feature, the `auto-import` loader can be modified to detect a functional component, and instead of adding `component.options.components = Object.assign({QIcon}, component.options.components || {})` , it adds the global registration `Vue.component("q-icon", QIcon)`, but I think it is not worth it especially with the upcoming Vue 3 (see link above)

In any case this is a bug, and quasar should not add extra code that gets disregarded (assigning to `components` option in a functional component)

**Comment by rstoenescu** [comment] 2019-11-18 08:39
Thank you for the write-up @ejez ! It's 100% accurate.

**Closed by rstoenescu** 2019-11-18 08:39 UTC
Labels: bug
