### ISSUE TITLE
Expect the components QChipsInput can work with QAutocomplete

### ISSUE THREAD

**Issue by rason560** [quasarframework/quasar#1905] opened 2018-04-10 03:54 UTC
I had try but QAutocomplete can`t work, it can`t capture the input or @change event from <q-chips-input ></q-chips-input>
Is that possiable to make it work ?

**Comment by rstoenescu** [comment] 2018-04-10 09:10
Duplicate of https://github.com/quasarframework/quasar/issues/400

**Closed by rstoenescu** 2018-04-10 09:10 UTC
