### ISSUE TITLE
Request: Card Style Carousel

### ISSUE THREAD

**Issue by arjitkhullar** [quasarframework/quasar#1486] opened 2018-01-25 00:05 UTC
This is a request for card style container.

Examples: 
 [Example 1](http://element.eleme.io/#/en-US/component/carousel#card-mode)
 [Example 2](https://codepen.io/anon/pen/WdqemV)

**Comment by nsbabrah** [comment] 2018-01-25 01:49
yes this will be a good add on.

more example here

[Slick Js](http://kenwheeler.github.io/slick/)

**Comment by arjitkhullar** [comment] 2018-04-06 21:31
#1670

**Comment by rstoenescu** [comment] 2018-04-07 01:54
Duplicate of #1670

**Closed by rstoenescu** 2018-04-07 01:54 UTC
