### ISSUE TITLE
Text field with label position outlined

### ISSUE THREAD

**Issue by masidiq** [quasarframework/quasar#8214] opened 2020-12-16 04:11 UTC
**Is your feature request related to a problem? Please describe.**
Im just like vuetify because this design about outined text field

**Describe the solution you'd like**
On input component have new prop like outlined-label for this options

**Describe alternatives you've considered**
Overide css at label but its lag animation

**Additional context**
![image](https://user-images.githubusercontent.com/7765289/102303787-92755100-3f8e-11eb-8a35-4a6c9bc02a53.png)

**Comment by pdanpdan** [comment] 2020-12-16 05:08
Duplicate of #3262

**Closed by pdanpdan** 2020-12-16 05:08 UTC
Labels: feature request
