### ISSUE TITLE
[Request] Add a way to exclude specific dates from the datetime input/picker

### ISSUE THREAD

**Issue by wc-matteo** [quasarframework/quasar#2135] opened 2018-06-07 12:18 UTC
For example, using the datetime input/picker to create an event and then being able to exclude that date from being picked again.

**Comment by rstoenescu** [comment] 2018-06-07 12:56
Duplicate of https://github.com/quasarframework/quasar/issues/805

**Closed by rstoenescu** 2018-06-07 12:56 UTC
