### ISSUE TITLE
Uploader to have "Max File Size" request.

### ISSUE THREAD

**Issue by BenHayat** [quasarframework/quasar#2630] opened 2018-09-27 16:43 UTC
Hello Team;

Is it possible to add a property to the "Uploader" component where we can set the "Max File size" which the user is allowed to upload a file, i.e. an image?
Many users may have the Mobile camera resolution set very high and take pictures, but for upload it can cause problem (bandwidth issue, time and server side storage). So we would like the uploader component to check that and issue an error to user if it exceeds the set file size.

A bonus feature would be, if the file is an image file, to offer the user to resize the image to lower size (w/h), so the newly created image becomes loadable. 

Thanks!

**Comment by rstoenescu** [comment] 2018-09-27 17:16
Hi, this is duplicate of https://github.com/quasarframework/quasar/issues/883

**Closed by rstoenescu** 2018-09-27 17:16 UTC
