### ISSUE TITLE
resetValidation()

### ISSUE THREAD

**Issue by TokyConstellation** [quasarframework/quasar#17367] opened 2024-07-11 08:01 UTC
### Description

validation error display immediately after reset string input and submitting, i use the resetValidation() but nothing work ,
then trying async but nothing . I create another method  event (onclick) to put resetValidation and it work but i dont need that, just put inside submit method.

const formData = ref({
      name: '',
      email: ''
    });
    const formRef = ref(null)

    const submitForm = () => {
      formRef.value.validate().then(success => {
        if (success) {
          alert('test')
          formData.value.name = ''
          formData.value.email = ''

          formRef.value.resetValidation()
        }
      });
    };

### Documentation Section URL

https://quasar.dev/vue-components/input#internal-validation

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

**Comment by stefanvanherwijnen** [comment] 2024-08-09 15:22
I can´t seem to reproduce this at all, i.e. it seems to work just fine:
https://codepen.io/stefanvh/pen/RwzZzdr

**Comment by yusufkandemir** [comment] 2024-08-20 20:53
It's hard to understand what the problem is about. This doesn't look like a documentation report either. So, I am closing this issue. If you think this is a bug, open an issue using the bug template and make sure to include a reproduction.

**Closed as not planned by yusufkandemir** 2024-08-20 20:53 UTC
Labels: kind/docs 📄, Qv2 🔝, area/components, flavour/quasar-cli-vite
