### ISSUE TITLE
Return to same position in list after back button

### ISSUE THREAD

**Issue by rkedward** [quasarframework/quasar#500] opened 2017-04-02 15:19 UTC
I am using quasar lists with vue router-link to show the details of a selected list item.  The problem is that when I return for the details screen via the back button, the list scroll position is at the top of the list.  It would be great if it returned to the same position for a better user experience.

**Comment by rstoenescu** [comment] 2017-04-03 11:05
Yes, this is duplicate of https://github.com/quasarframework/quasar/issues/72
In v0.14 when using Vue Router "history" mode this will work by default.

**Closed by rstoenescu** 2017-04-03 11:05 UTC
