### ISSUE TITLE
[Cordova] QSelection opens my phone keyboard when I select an option

### ISSUE THREAD

**Issue by slowaways** [quasarframework/quasar#7084] opened 2020-05-21 18:14 UTC
**Describe the bug**
When I compile a Quasar mobile application using Cordova, QSelection opens my phone keyboard when I select an option, every time.

**Codepen/jsFiddle/Codesandbox (required)**
Not applied, Cordova App.

**To Reproduce**
1. Create a QSelect with Standard Design (only this props: v-model, options, label)
2. Create an Options Object with Label and Value
3. Compile the Application with Cordova and generate the APK
4. Install the .apk in your Android Phone and select any options in your QSelection
5. After selected any option, the keyboard of your phone will open.

**Expected behavior**
Do not open the phone keyboard when selecting the option.

**PoC**
![video_2020-05-20_16-15-30](https://user-images.githubusercontent.com/9668277/82590616-60288000-9b74-11ea-9d27-c764ac42712d.gif)

**Platform:**
OS: Android
Node: v12.16.3
NPM: 6.14.4
Yarn: - Not used -
Browsers: - No applied -
iOS: - Not applied -
Android: 8.0.0
Electron: - No applied -

**Additional context**
Usign v-model with Vuex
Keyboard of my phone: SwiftKey

**Comment by pdanpdan** [comment] 2020-05-21 18:22
Duplicate of #7061, duplicate of #7062

**Closed by pdanpdan** 2020-05-21 18:22 UTC
Labels: bug
