### ISSUE TITLE
QRouteTab - QBtn doesn't fire @click event inside QRouteTab (only @mousedown)

### ISSUE THREAD

**Issue by tarik23** [quasarframework/quasar#7917] opened 2020-10-18 09:43 UTC
**Describe the bug**
Buttons inside QRouteTab does not fire click event (only mousedown)
But at the same time buttons inside QTab still fire click event and mousedonw as well

Can be reproduced on fresh installation of starter kit with quasar CLI 

**Codepen/jsFiddle/Codesandbox (required)**
can't reproduce it using UMD version on codepen

**To Reproduce**
1. Create fresh project using quasar CLI using defatult options (!BUT disable LINT)
2. Change pages/Index.vue as below

```<template>
  <q-page class="q-ma-md">
    <q-tabs>
      <q-tab name="a" label="q-tab">
        <q-btn label="btn-1" @click="onClick" @mousedown="onMouseDown"></q-btn>
      </q-tab>
      <q-route-tab to="/" name="b" label="q-route-tab" exact>
        <q-btn label="btn-2" @click="onClick" @mousedown="onMouseDown"></q-btn>
      </q-route-tab>
    </q-tabs>
  </q-page>
</template>

<script>
  export default {
    name: 'PageIndex',
    data() {
      return {
        tabName: '',
      }
    },
    methods: {
      onClick() {
        console.log('click on btn');
      },
      onMouseDown() {
        console.log('mousedown on btn');
      },
    }
  }
</script>
```
3. run quasar dev (for default single spa)
4. Open browser console
5. Click btn-1 (you'll see mousedown and click events handlers output)
6. Click btn-2 (you'll see ONLY mousedown event handler)
7. Repeat step 4 and 5 and watch results at vue devtools extension (you will not find any click event for btn-2)

**Expected behavior**
@click event should be fired for button insige QRouteTab

**Screenshots**
btn-1:
![chrome_2020-10-18_13-26-27](https://user-images.githubusercontent.com/4692632/96363452-8cf1bb00-1145-11eb-9399-54d1f9af7198.png)

btn-2:
![chrome_2020-10-18_13-25-33](https://user-images.githubusercontent.com/4692632/96363435-7b101800-1145-11eb-9c17-8a21982ab9e9.png)

**Platform (please complete the following information):**
OS: Windows 10
Node: v13.7.0.
NPM: 6.13.6
Yarn: 1.22.4
Browsers: Google Chrome 86.0.4240.75

**Additional context**

**Comment by rstoenescu** [comment] 2020-10-19 19:08
Duplicate of https://github.com/quasarframework/quasar/issues/7686

**Closed by rstoenescu** 2020-10-19 19:08 UTC
Labels: bug, investigation needed
