### ISSUE TITLE
Cross-browser compatibility issue with vectors using q-img

### ISSUE THREAD

**Issue by amirhoseinbagheri99** [quasarframework/quasar#10195] opened 2021-07-26 07:01 UTC
**Description**
Hi, I'm a junior developer working with Quasar v2. We're currently developing a new website, and we usually test the results on Chrome, but recently I've come to realize that there's an unexpected behavior with vector images on firefox. I've tested out some of the methods that I could think of, but still, no luck. The image's height HAS to be defined or it will be maximized upon rendering. And as you know, considering the importance of responsiveness, you can't rely on hard-coding the sizes for all the various breakpoints. I wanted to know whether it's possible to fix that. I appreciate your help.

P.S: the codepen doesn't actually represent anything but a simple image, since this issue is browser-based and not code-dependant. Just wanted to follow protocol ;D

**Codepen**
https://codepen.io/palempr/pen/ExmooYE

**To Reproduce**
Nothing fancy here... just use a vector with q-img with a defined width but WITHOUT a strict height

**Expected behavior**
It won't automatically set the desired height of the image, whereas it would for other formats i.e. .jpg or. png

**Platform**
Quasar Version:
@quasar/app Version: 3.0.2

Quasar mode:
  - [ ] SPA
  - [x] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [ ] SPA
  - [x] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS:
Node: 12.22.1
NPM: 6.14.12
Yarn: 1.21.1
Browsers: FireFox 90.0.2

**Comment by pdanpdan** [comment] 2021-07-26 12:47
duplicate of https://github.com/quasarframework/quasar/issues/7137, https://github.com/quasarframework/quasar/issues/8569

**Closed as completed by pdanpdan** 2021-07-26 12:47 UTC
Labels: kind/bug 🐞, Qv2 🔝
