### ISSUE TITLE
QTable grid mode cant't showing the header even hide-header=false

### ISSUE THREAD

**Issue by zknic** [quasarframework/quasar#5146] opened 2019-09-25 05:52 UTC
Describe the bug

Using quasar 1.1.3:

QTable grid mode cant't showing the header even hide-header=false

Codepen/jsFiddle/Codesandbox (required)

N/A

To Reproduce

Go to q-menu quasar 1.1.3 documentation, and see section of Basic -> Idea for content

Inside q-menu there are two toggles that don't update its visible state

Expected behavior

A q-toggle or q-checkbox should update its visible state when used inside a q-menu, as it was with quasar 1.0.5 - 1.1.0

Platform (please complete the following information):
OS: Ubuntu 18.04 / Windows 10
Node:8.15.0
NPM:6.4.1
Yarn:N/A
Browsers:Chrome desktop browser Versión 71.0.3578.98 (Build oficial) (64 bits)
iOS: N/A
Android: N/A
Electron: N/A

Additional context

**Comment by pdanpdan** [comment] 2019-09-25 06:03
Duplicate of #5131

**Closed by pdanpdan** 2019-09-25 06:03 UTC
Labels: bug
