### ISSUE TITLE
Beta 0.14 firefox issues

### ISSUE THREAD

**Issue by IgorDePaula** [quasarframework/quasar#641] opened 2017-06-23 13:44 UTC
Quasar: 0.14
OS: ubuntu 15.10
Browsers: firefox 47

### What did you get as the error?
The scroll bar from components, like left menu is not work with mouse scroll, only click and drag. On chrome works fine.
The data table don't render correctly on firefox, on chrome works fine.
### What were you expecting?
The scrollbars work together with mouse scroll, and the data table render correctly, showing the data.
### What steps did you take, to get the error?
Access the beta page, try roll the scrollbar with mouse scroll, and access the data table page.

![quasar play app - mozilla firefox_009](https://user-images.githubusercontent.com/2833993/27484801-f7ba9f30-5800-11e7-9375-a87c60c32f92.png)
![quasarscroll](https://user-images.githubusercontent.com/2833993/27484802-f7c43054-5800-11e7-9e22-1ef72ad550e2.png)

**Comment by spectrolite** [comment] 2017-06-23 13:55
Confirmed bug on :
MacOS 10.12.5
Firefox 53.0.3 (64-bit) and 55.0b3 (64-bit)

**Comment by mstaack** [comment] 2017-06-23 21:17
yeah can confirm that too on firefox@54.0  with ubuntu ...looks like bug

**Comment by gpolitog** [comment] 2017-06-23 23:40
## Firefox on Windows

Confirmed bug on:
Win 10
Firefox 44.0

## Firefox on Android

There are other different issues on Mobile:
Android 4.3
Firefox 34.0

- Select (standard) is not rendered
- Collapsible is not rendered
- Autocomplete brings no results
- Ripples are slow.  Showcase has no ripples today, but I tested on Tuesday (there were ripples) and they were very slow.  In fact, the whole Showcase for 0.14 was slow compared to 0.13.  Today (because no ripples?) is not that slow.

I'm attaching screenshots for the frist 3 bullets.

![screenshot_select_standard](https://user-images.githubusercontent.com/29667516/27503494-2a9bfaca-5842-11e7-959a-b82278fd0b74.jpg)
![screenshot_collapsible](https://user-images.githubusercontent.com/29667516/27503498-3195d008-5842-11e7-9261-825f130dd723.jpg)
![screenshot_autocomplete](https://user-images.githubusercontent.com/29667516/27503501-382b0122-5842-11e7-9589-260a9f09d615.jpg)

**Comment by pdanpdan** [comment] 2017-06-26 08:11
Data Table bug confirmed and fixed in PR.
Scroll problem seems to be specific to Quasar Play - need more investigation.
Select / Collapsible / Autocomplete are working as expected on newer Firefox (both desktop and mobile). Come on, Firefox 44 (January 26, 2016) and 34 (December 1, 2014) - current is 54?

**Closed** 2017-06-26 12:40 UTC

**Comment by spectrolite** [comment] 2017-06-26 13:55
tested http://beta.quasar-framework.org/quasar-play/android/index.html#/showcase again
Scroll now works, but it behaves strangely... I can't do a video, so I'll try to explain it:
when you scroll by rolling, the scrollbar makes small (10-50px) and very fast up and down jumps, more up than down if you scroll up, and vice versa... totally useable, but looks buggy. 
If you grab the handle and scroll, it goes smoothly (it seems like it still does this weird thing but on a scale of a couple pixels, so barely noticeable).
Firefox 55 (dev) on macos latest

**Comment by IgorDePaula** [comment] 2017-06-26 13:57
On my firefox, all works fine.

**Comment by spectrolite** [comment] 2017-06-26 13:59
@IgorDePaula which OS ?

**Comment by IgorDePaula** [comment] 2017-06-26 14:00
@spectrolite 

Quasar: 0.14
OS: ubuntu 15.10
Browsers: firefox 47

**Comment by pdanpdan** [comment] 2017-06-26 14:01
There is jumpiness in scrolling on all platforms and browsers - just in different degrees.
I'll take a look.

**Comment by spectrolite** [comment] 2017-06-26 14:02
@pdanpdan jumpiness of this intensity is really not up to the level of quasar components... there's something really wrong at play in there.

**Comment by spectrolite** [comment] 2017-06-26 14:07
decomposing the movement, seems to point somewhere: for each "bit" I scroll down (rolling the wheel away form me), the scrollbar seems to go first UP, by as much as the menu is going up, and just afterwards it goes (correctly) DOWN to its correct position. If you scroll faster it just seems to jump like crazy.

**Comment by pdanpdan** [comment] 2017-06-26 14:08
yes, that's what's happening

**Comment by mstaack** [comment] 2017-06-26 16:43
this is how it looks currently on firefox 54
![firefox54-ubuntu-scroll-bug](https://user-images.githubusercontent.com/10169509/27550243-45f9a0e2-5a9f-11e7-8ea8-65b32a7313db.gif)

**Comment by rstoenescu** [comment] 2017-06-26 17:29
Pushed patch to fix it. Update quasar-framework.

**Comment by spectrolite** [comment] 2017-07-03 13:42
It works like a charm now. Thanks Razvan.
