### ISSUE TITLE
QToggle : [Violation] Added non-passive event listener to a scroll-blocking ...

### ISSUE THREAD

**Issue by ggregg** [quasarframework/quasar#2730] opened 2018-11-05 15:16 UTC
### Software version

Quasar: 0.17.20
Browsers: Chrome 70.0.3538.77

**Chrome** notify this warning in console verbose mode [warning](https://www.chromestatus.com/feature/5745543795965952) when i use QToggle.

To reproduce it's easy, go on [quasar components page](https://quasar-framework.org/components/toggle.html) and just have a look in the javascript console.

Thank's :)

**Comment by pdanpdan** [comment] 2018-11-06 05:19
I cannot reproduce it on https://quasar-framework.org/quasar-play/android/index.html#/showcase/forms/toggle, Chrome 72.

**Comment by ggregg** [comment] 2018-11-06 06:43
Hello, i understand,
1 - open page
2 - open chrome développement tools
3 - refresh the page

![quasar_play](https://user-images.githubusercontent.com/2576033/48047160-72f88100-e197-11e8-9fb9-f732b0c9196b.png)

**Comment by ggregg** [comment] 2018-11-06 06:45
> I cannot reproduce it on https://quasar-framework.org/quasar-play/android/index.html#/showcase/forms/toggle, Chrome 72.



> I cannot reproduce it on https://quasar-framework.org/quasar-play/android/index.html#/showcase/forms/toggle, Chrome 72.

**Comment by MadeMyDay** [comment] 2018-11-16 21:41
@ggregg Why have you closed it? Having the exact same issue.

**Comment by MadeMyDay** [comment] 2018-11-17 09:33
But opening the 
https://quasar-framework.org/quasar-play/android/index.html#/showcase/forms/toggle results in lots of errors in latest Chrome (Mac), too. So how can this be an error on your part? ;-)

**Comment by msinkgraven** [comment] 2018-12-03 13:06
See: https://developers.google.com/web/tools/lighthouse/audits/passive-event-listeners.
It seems as though the origin of the error comes from a scroll-blocking touch event on `q-toggle`. I'd be happy to open a PR with a fix.

**Comment by pdanpdan** [comment] 2018-12-03 13:37
Please make the PR

**Comment by rstoenescu** [comment] 2019-04-21 16:03
This has been thoroughly taken care of in v1 beta.
It's due to browsers suddenly making a breaking change in the web standards which flip the way passive listeners are registered.

**Closed by rstoenescu** 2019-04-21 16:03 UTC
