### ISSUE TITLE
Using Quasar without ui components?

### ISSUE THREAD

**Issue by Catsvilles** [quasarframework/quasar#5490] opened 2019-11-07 09:42 UTC
I'm sorry, I couldn't find any answers to my question. I'm just considering to start using Quasar for my project and what I'm trying to achieve is super minimalistic, lightweight codebase for it. What I would like to use Quasar for is only for it's SSR, PWA cross platform possibliities, at the moment I do NOT plan using ui components as all the html/css is kinda already written. So, how does it work if do not include them will they still be in the final bundle? Is easy to make Quasar as minimalistic as possible?

**Comment by rstoenescu** [comment] 2019-11-07 10:15
duplicate of https://github.com/quasarframework/quasar/issues/5204

**Closed by rstoenescu** 2019-11-07 10:15 UTC
