### ISSUE TITLE
Add "size" prop in "QFab"

### ISSUE THREAD

**Issue by mayur091193** [quasarframework/quasar#6599] opened 2020-03-11 16:15 UTC
**Is your feature request related to a problem? Please describe.**
I'am working on building a chrome extension and using QFab in that, as it's a new tab extension I am ignoring scroll, so making everything compact, so want to decrease the size of QFab but there is no proper way I can do it. I can do using css but that's not the better way of doing the same.

**Describe the solution you'd like**
It would be great if you can add "size" prop same as QBtn.

**Describe alternatives you've considered**
I am applying css on compiled DOM. I am applying height-width on "a" and adding max-height-max-width = unset and paddig 0. Still it's not proper.

**Comment by pdanpdan** [comment] 2020-03-11 16:31
Duplicate of https://github.com/quasarframework/quasar/issues/3739

**Closed by pdanpdan** 2020-03-11 16:31 UTC
Labels: feature request
