### ISSUE TITLE
Locale-Based Inconsistency in getDayOfWeek Method of Quasar Date Utility

### ISSUE THREAD

**Issue by BenJackGill** [quasarframework/quasar#16237] opened 2023-08-23 08:58 UTC
### What happened?

The Quasar date utility `getDayOfWeek` doesn't adapt according to the locale.

It always returns `1` for Monday and `7` for Sunday.

It contradicts `QDate` which does adjust the week based on locale. Making it difficult to create quick select date ranges button such as "This Week" and "Last Week" that align with the weeks shown on `QDate`.

### What did you expect to happen?

`getDayOfWeek` should adjust based on the locale.

Some examples:

- In Iran (`fa-IR`) the week starts on Saturday. For the `fa-IR` locale `getDayOfWeek` should return `1` for Saturday and `7` for Friday.
- In United States (`en-US`) the week starts on Sunday. For the `en-US` locale `getDayOfWeek` should return `1` for Sunday and `7` for Saturday.
- In England (`en-GB`) the week starts on Monday. For `en-GB` locale `getDayOfWeek` should return `1` for Monday and `7` for Sunday. This currently aligns with the default.

Is there an alternative method to retrieve the 1-indexed position of a day in the week as determined by the locale?

### Reproduction URL

https://stackblitz.com/edit/quasarframework-pd3c2c?file=src%2Fpages%2FIndexPage.vue

### How to reproduce?

1. Go to the repo link
2. See that the `QDate` start of week will adjust based on locale, but the `getDayOfWeek` util always returns `1` for a Monday

### Flavour

Quasar CLI with Vite (@quasar/cli | @quasar/app-vite)

### Areas

Components (quasar)

**Comment by BenJackGill** [comment] 2023-08-25 04:30
I have just found this issue which I think is related: https://github.com/quasarframework/quasar/issues/12783

**Comment by yusufkandemir** [comment] 2023-08-25 07:47
@BenJackGill yes, this issue is a duplicate of it, thanks. The other issue was poorly described compared to this issue, so I updated the other issue's description to make it clearer without having to follow the entire discussion.

**Closed as not planned by yusufkandemir** 2023-08-25 07:47 UTC
Labels: kind/bug 🐞, Qv2 🔝, bug/1-repro-available, area/components, flavour/quasar-cli-vite

**Comment by rstoenescu** [comment] 2023-08-25 07:49
@BenJackGill set the Quasar language pack that you want, otherwise it's the default English everywhere

**Comment by yusufkandemir** [comment] 2023-08-25 07:50
@rstoenescu `getDayOfWeek` doesn't have any logic in it to respect the language packs, so setting a language pack won't change anything.

**Comment by rstoenescu** [comment] 2023-08-25 09:11
Took a closer look at what I did there.
The idea is that getDayOfWeek() indeed doesn't care about the Q language pack. But it's so by design. It "normalizes" to the ISO weekdays: 1-7 (Monday-Sunday) for multiple internal reasons.

**Comment by BenJackGill** [comment] 2023-08-25 09:21
> Took a closer look at what I did there. The idea is that getDayOfWeek() indeed doesn't care about the Q language pack. But it's so by design. It "normalizes" to the ISO weekdays: 1-7 (Monday-Sunday) for multiple internal reasons.

@rstoenescu that may be the case, but this makes it difficult to create buttons such as "This Week" and "Last Week" which conform to the weeks shown in QDate.

Can we add an option like `getDayOfWeek(newDate, { matchLocaleWeek: true })`?
