### ISSUE TITLE
[Bug] Right-clicking any slide of QCarousel throws a ReferenceError

### ISSUE THREAD

**Issue by Frondor** [quasarframework/quasar#1490] opened 2018-01-25 12:30 UTC
Quasar: v0.14.7
Browsers: Only tested on Chrome

### Reproduce
http://quasar-framework.org/quasar-play/android/index.html#/showcase/grouping/carousel

### What did you get as the error?
```
Uncaught ReferenceError: o is not defined
    at HTMLDocument.document.addEventListener.t (<anonymous>:1:784)
```

### What were you expecting?
Not to get a console error

### What steps did you take, to get the error?
Right-click any slide

**Comment by rstoenescu** [comment] 2018-01-25 15:59
I'm sorry but I just can't reproduce. What version of Chrome are you using?

**Comment by olegvakulenko** [comment] 2018-01-25 16:21
No. On last Chrome all work without error.

**Comment by rstoenescu** [comment] 2018-01-25 17:54
Could not reproduce, but this issue made me think a little on the touch directives regarding mouse support. Have improved them in the sense that only left click is the trigger now (when on desktop).

@Frondor can you clone Quasar main repo then do a "npm run dev" and tell me if you get any error on the Carousel page pls?

Will close this as the new code guards in place will definitely avoid any such weird browser issues.

**Closed by rstoenescu** 2018-01-25 17:54 UTC

**Comment by Frondor** [comment] 2018-01-25 20:40
I'm so sorry, it looks like its vue-devtools fault actually (or there's a conflict with it). 
It happens on latest chrome version (v63) with vue devtools (v4.1.0) activated. If I disable it or open incognito mode, no error is being thrown.
