### ISSUE TITLE
[Vue warn]: Component emitted event "row-click" but it is neither declared in the emits option nor as an "onRow-click" prop.

### ISSUE THREAD

**Issue by giovannymf** [quasarframework/quasar#9259] opened 2021-05-12 22:51 UTC
**Describe the bug**
"row-click" emit event not declared in QTable, so Vue shows on console: "[Vue warn]: Component emitted event "row-click" but it is neither declared in the emits option nor as an "onRow-click" prop."

**Codepen/jsFiddle/Codesandbox (required)**
The warning does not show up in Codepen

**To Reproduce**

1. Use QTable with @row-click event (eg: "@row-click='onRowClickFn'").
2. Click on any row.
3. See warning in console.

**Expected behavior**
There should be no event related console warnings.

**Platform (please complete the following information):**
Quasar Version:
@quasar/app Version:
Quasar mode:
  - [ x ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

Tested on:
  - [ x ] SPA
  - [ ] SSR
  - [ ] PWA
  - [ ] Electron
  - [ ] Cordova
  - [ ] Capacitor
  - [ ] BEX

OS: Windows 10
Node: v.14.16
NPM: v6.14.11
Yarn: v1.22.10
Browsers: Edge v90.0.818.56 and Chrome v90.0.4430.93

**Comment by rstoenescu** [comment] 2021-05-12 23:13
Duplicate of #9132
Vue issue. Will try to report it.

**Closed by rstoenescu** 2021-05-12 23:13 UTC
Labels: :beetle: bug, 🔝 Qv2
