### ISSUE TITLE
Ripple effect lagging (on drawer) when changing routes and loading new page

### ISSUE THREAD

**Issue by matheus-rossi** [quasarframework/quasar#803] opened 2017-08-14 19:33 UTC
### Software version

Quasar: 0.14 dev
OS: Manjaro Linux
Node: 8.2.1
NPM: 5.3.0
Browsers: Chrome and Vivaldi

### What did you get as the error?

The ripple effect is lagging in the Drawer component, when changing routes

### What were you expecting?

Not to lag on new render page

### What steps did you take, to get the error?

https://matheus-rossi.github.io/#/

Access the page above, and change the routes between skills and home, for example. When the page skills is loading, the ripple effect lags.

It happens on chrome, vivaldi and firefox.

**Comment by rstoenescu** [comment] 2017-09-13 14:58
What exactly do you mean? Does it starts with a delay or it starts then lags? (**An answer to this is very important**)

When changing routes Vue comes into action and starts rendering the page which is a blocking action (fortunately in 99% cases this is really fast so user takes no notice of this).

Cannot reproduce the issue, so can you do another test with latest edge pls? I've done some updates and was wondering if this can still be reproduced. Thanks!

**Comment by rstoenescu** [comment] 2018-02-24 23:50
Obsolete for v0.15, so closing.

**Closed by rstoenescu** 2018-02-24 23:50 UTC
