### ISSUE TITLE
[V1 - 0.16] QSelect Autocomplete

### ISSUE THREAD

**Issue by sn0rcha** [quasarframework/quasar#3874] opened 2019-04-11 20:25 UTC
### What did you get as the error?
Once you stop typing, what you have typed gets highlighted.

### What were you expecting?
To behave as it used to and not highlight when you stop typing

### What steps did you take, to get the error?
Typed in a Qselect auto complete (docs are producing error as well)

0.16 has introduced a bug with Qselect and auto-complete where once you stop typing it's highlighting what you've typed, so if you hit another key once you've stopped typing, it clears what you've typed. It's doing it on the doc page as well - https://v1.quasar-framework.org/vue-components/select

Cheers,
Ben

**Comment by rstoenescu** [comment] 2019-04-11 21:46
This is the 2nd duplicate of https://github.com/quasarframework/quasar/issues/3850
It's been reported, fixed, and will get into beta.17.

**Closed by rstoenescu** 2019-04-11 21:46 UTC

**Comment by sn0rcha** [comment] 2019-04-11 21:48
Thanks sorry didn't see the first issue raised.
