### ISSUE TITLE
q-btn label not updated when array initialized as empty

### ISSUE THREAD

**Issue by flygare** [quasarframework/quasar#2579] opened 2018-09-18 07:38 UTC
### Software version

Quasar: 0.17
OS: MacOS High Sierra
Browsers: Firefox

### JsFiddle (for Quasar v0.15+ only)
https://jsfiddle.net/d2m6Lxas/

### What did you get as the error?
q-tree not updated when initialized as empty

### What were you expecting?
q-tree to be updated, like in the working jsfiddle example

### What steps did you take, to get the error?
initialized array as empty

**Comment by nothingismagick** [comment] 2018-09-18 10:42
Hmm. I updated your fiddle to latest quasar 0.17.15 and nothing changed in the behaviour.

I changed your return statement to this:       

```
return this.selected.toString() || 'Init value'
```
https://jsfiddle.net/d2m6Lxas/11/

And the behaviour became what was expected. I suspect the problem is that an empty array is actually injecting an "undefined". 
 
After looking deeper, I suspected that your call was too deep, and I just changed the label to this:
  <q-btn :label="selected">

And got the expected behavior.
https://jsfiddle.net/d2m6Lxas/30/

**Comment by nothingismagick** [comment] 2018-09-18 10:43
If this resolves your problem, please consider closing the issue.

**Comment by nothingismagick** [comment] 2018-09-18 10:45
Also, Q-Tree is being updated - your :ref in the label is not.

**Comment by rstoenescu** [comment] 2018-09-18 10:48
1. This has to do with Vue entirely, not with Quasar.
2. Please read about Vue reactivity with arrays.

You are using a computed property on the reference of the `selected` array which never changes on push/pop etc.

**Closed by rstoenescu** 2018-09-18 10:48 UTC

**Comment by flygare** [comment] 2018-09-18 10:50
Yes, if only using 'selected' it works but the issue is still occurring when a computed property is used

**Comment by nothingismagick** [comment] 2018-09-18 10:59
@flygare - did you read what @rstoenescu said?

**Comment by flygare** [comment] 2018-09-18 11:09
@nothingismagick i might have misunderstood how vue works, but it re-renders correctly in the example at {{selectedString}}, thought it should also work in quasar then
