### ISSUE TITLE
Fix for mobile Safari 100vh problem

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar#2274] opened 2018-07-17 13:05 UTC
The standard installation of Quasar doesn't have the correct height because of `100vh` on mobile safari

This is a bug that Safari decided not to ever fix:
https://bugs.webkit.org/show_bug.cgi?id=141832

In such cases it's required to change the `100vh` occurrences with `window.innerHeight` after Vue is mounted. I would like to request a polypill for the `100vh` situation on Mobile Safari where Quasar uses `window.innerHeight` instead when it detects it's on Mobile Safari. This could perhaps be done through a Quasar plugin.

Screenshot of my Quasar app on Safari:
![img_0054](https://user-images.githubusercontent.com/3253920/42818846-e2d64242-8a0c-11e8-8819-14422016b36b.jpg)

**Comment by rstoenescu** [comment] 2018-07-20 00:35
Duplicate of #1917

**Closed by rstoenescu** 2018-07-20 00:35 UTC
