### ISSUE TITLE
q-tabs not working as expected in RTL mode

### ISSUE THREAD

**Issue by AlaaDq** [quasarframework/quasar#10915] opened 2021-10-06 19:39 UTC
**Describe the bug**
When using QTabs in RTL mode the sliding arrows are not working…
this code :
**Codepen/jsFiddle/Codesandbox (required)**
Fork a Codepen (https://codepen.io/rstoenescu/pen/VgQbdx) or a jsFiddle (https://jsfiddle.net/rstoenescu/rmaodk0f) or a Codesandbox (https://codesandbox.io/s/github/quasarframework/quasar-codesandbox/tree/legacy-v1) and hit save then copy-paste link here.
https://codepen.io/Alaa-Dq/pen/qBjexYz

**To Reproduce**
change quasar to rtl mode ,or visit this link forked from docs:
https://codepen.io/Alaa-Dq/pen/qBjexYz

**Expected behavior**
When click on right arrow, should slide to right.
When click on left arrow, should slide to left.

**Screenshots**
![image](https://user-images.githubusercontent.com/45366622/136271674-a694985b-4b3f-4e07-8be5-c9af7ca43ad5.png)
# left arrow not working.

**Platform (please complete the following information):**
Quasar Version: both 1 and 2,

Quasar mode:
  - [ ] SPA

Tested on:
  - [ ] SPA

**Comment by AlaaDq** [comment] 2021-10-06 19:41
i have managed to solve it by editting this global  class in src\css\app.scss file .
`[dir='rtl'] .q-tabs.q-tabs--scrollable{
  direction: ltr !important;
}`

**Comment by saifobeidat** [comment] 2021-10-08 09:04
@AlaaDq This will fix the issue in case you have the tabs labels in English so their direction is LTR, but what if  labels are in Arabic (where the tabs should start from right to left) in this case it won't work.

Check the below codepen, if you see 'الاول', 'الثاني', and so on it's started from left, and you need to click the right arrow to slide.. I need the opposite 

https://codepen.io/saifobiedat/pen/QWMLqyE

**Comment by AlaaDq** [comment] 2021-10-08 09:15
yes that is right , but at least it is usable in this way 
and the direction will only be like that when it will need scroll only, otherwise everything is right.
so you can use it in this way until quasar fix it completely.

**Comment by pdanpdan** [comment] 2021-10-08 11:47
duplicate of #8578

**Closed as completed by pdanpdan** 2021-10-08 11:47 UTC
Labels: Qv1
